import streamlit as st
from streamlit_option_menu import option_menu
import requests
from PIL import Image, ImageOps
from io import BytesIO

st.markdown("""<style>.centered-title {text-align: center;}</style>""",unsafe_allow_html=True)
st.markdown("<h1 class='centered-title'>BUKU KATING</h1>", unsafe_allow_html=True)

# bagian sini jangan diubah
def streamlit_menu():
    selected = option_menu(
        menu_title=None,
        options=[
            "Kesekjenan",
            "Baleg",
            "Senator",
            "Departemen PSDA",
            "Departemen MEDKRAF",
            "Departemen MIKFES",
            "Departemen Eksternal",
            "Departemen Internal",
            "Departemen SSD",
        ],
        icons=[
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
        ],
        default_index=0,
        orientation="horizontal",
        styles={
            "container": {"padding": "0!important", "background-color": "#fafafa"},
            "icon": {"color": "black", "font-size": "19px"},
            "nav-link": {
                "font-size": "15px",
                "text-align": "left",
                "margin": "0px",
                "--hover-color": "#eee",
            },
            "nav-link-selected": {"background-color": "#3FBAD8"},
        },
    )
    return selected

@st.cache_data
def load_image(url):
    response = requests.get(url)
    if response.status_code != 200:
        st.error(
            f"Failed to fetch image from {url}, status code: {response.status_code}"
        )
        return None
    try:
        img = Image.open(BytesIO(response.content))
        img = ImageOps.exif_transpose(img)
        img = img.resize((300, 400))
        return img
    except Exception as e:
        st.error(f"Error loading image: {e}")
        return None
    
@st.cache_data
def display_images_with_data(gambar_urls, data_list):
    images = []
    for i, url in enumerate(gambar_urls):
        with st.spinner(f"Memuat gambar {i + 1} dari {len(gambar_urls)}"):
            img = load_image(url)
            if img is not None:
                images.append(img)

    for i, img in enumerate(images):
        # Menggunakan Streamlit untuk menampilkan gambar di tengah kolom
        col1, col2, col3 = st.columns([1, 2, 1])
        with col2:
            st.image(img, use_column_width=True)

        if i < len(data_list):
            st.write(f"Nama: {data_list[i]['nama']}")
            st.write(f"NIM: {data_list[i]['nim']}")
            st.write(f"Umur: {data_list[i]['umur']}")
            st.write(f"Asal: {data_list[i]['asal']}")
            st.write(f"Alamat: {data_list[i]['alamat']}")
            st.write(f"Hobbi: {data_list[i]['hobbi']}")
            st.write(f"Sosial Media: {data_list[i]['sosmed']}")
            st.write(f"Kesan: {data_list[i]['kesan']}")
            st.write(f"Pesan: {data_list[i]['pesan']}")
            st.write("  ")
    st.write("Semua gambar telah dimuat!")
menu = streamlit_menu()

# BAGIAN SINI YANG HANYA BOLEH DIUABAH
if menu == "Kesekjenan":
    def kesekjenan():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1_u-IKsluakgB0pT6x8w8_-ZdmLosCqYw",
            "https://drive.google.com/uc?export=view&id=1I6bGV0pG7Xq4bpM0_1ll26fY-KedU5V4",
            "https://drive.google.com/uc?export=view&id=1iU4ZuyVV3aqoge15vG7Jnayp9oVBrNNA",
            "https://drive.google.com/uc?export=view&id=1I65lwz6BRweI9H4sjxOgE_x6FDg1XQsT",
            "https://drive.google.com/uc?export=view&id=1iTKlTZFbEQCk5x98Ri5vTXt6SpVsKBae",
            "https://drive.google.com/uc?export=view&id=1I4B1hMrN_jFf3fb5qocDVl83cIlVMKiW",
        ]
        data_list = [
            {
                "nama": "Kharisma Gumilang",
                "nim": "121450042",
                "umur": "21",
                "asal": "Palembang",
                "alamat": "Jl.Pulau Damar",
                "hobbi": "Dengerin Musik",
                "sosmed": "@gumilangkharisma",
                "kesan": "Cakep dan Berkarisma",
                "pesan":"Semangat buat TA nya, sukses selalu!"# 1
            },
            {   
                "nama": "Pandra Insani Putra Anwar",
                "nim": "121450147",
                "umur": "21",
                "asal":"Lampung Utara",
                "alamat": "Sukarame",
                "hobbi": "Main Gitar",
                "sosmed": "@pandrainsani27",
                "kesan": "Keren banget dan Insight full",  
                "pesan":"Tetap semangat dan sukses selalu bang!"# 1
            },
            {   
                "nama": "Meliza Wulandari",
                "nim": "121450065",
                "umur": "20",
                "asal":"Sumatera Selatan",
                "alamat": "Jl.Pagar Alam",
                "hobbi": "Nonton Drakor",
                "sosmed": "@wulandarimeliza",
                "kesan": "keren, pendengar yang baik",  
                "pesan":"semangat terus kakak!!!"# 1
            },
        
            {
                "nama": "Putri Maulida Chairani",
                "nim": "121450050",
                "umur": "21",
                "asal":"Sumatera Barat",
                "alamat": "Gg. Nangka 4",
                "hobbi": "Dengerin Bg Pandra Main Gitar",
                "sosmed": "@ptrimaulidaaa_",
                "kesan": "Cantik, pendengar yang baik ",  
                "pesan":"Semangat untuk ngurus TA dan sukses selalu!! "# 1
            },
        
            {   
                "nama": "Hartiti Fadilah",
                "nim": "121450031",
                "umur": "21",
                "asal":"Palembang",
                "alamat": "Pemda",
                "hobbi": "Nyanyi",
                "sosmed": "@htrpdla",
                "kesan": "cantik",  
                "pesan":"Semangat ngurus cuan dan persiapan TA nya!!"# 1
            },
        
            {
                "nama": "Nadilla Andhara Putri",
                "nim": "121450003",
                "umur": "21",
                "asal":"Lampung",
                "alamat": "Metro",
                "hobbi": "Mainn Bola, Belajar",
                "sosmed": "@nadilaandr26",
                "kesan": "vibes bendahara bgt",  
                "pesan":"Semangat ngasprak dan persiapan TA nya!!"# 1
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    kesekjenan()

elif menu == "Baleg":
    def baleg():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=17prCtGIbHo_LG33l3GKK69_MA_NxQsho",
            "https://drive.google.com/uc?export=view&id=17EZ-6JYKOCd5KCjKEezsIPVlIvMEB4kX",
            "https://drive.google.com/uc?export=view&id=17EK7qtBL56-xJzOoDnM9VbNp3bHCMz4A",
            "https://drive.google.com/uc?export=view&id=17QVO3UFaUFClE9XdkK13mN9B2y5Y3iTt",
            "https://drive.google.com/uc?export=view&id=17x5VXHFw7H56MUzRVPpTR_C1cxKo8VXX",
            "https://drive.google.com/uc?export=view&id=17nuKp4XMIA9vbNnqR1GzhTLke5SN5JLd",
            "https://drive.google.com/uc?export=view&id=17X8juYfbPFloccQPtcGHe0-jX90ehLbR",
            "https://drive.google.com/uc?export=view&id=17sNXRcKnWVQKwNdv3ne8jSYy-_Jgxxit",
            "https://drive.google.com/uc?export=view&id=1I3Eh-fKNLM_dVoSQB8dk4Nq6tP-34Qcs",
            "https://drive.google.com/uc?export=view&id=17xx99e76NqBNM5AJoAXaMc0eHeOav157",
            "https://drive.google.com/uc?export=view&id=17IrUjO9IDyo-CVgxped3CtCIlaNItBgZ",
        ]
        data_list = [
            {
                "nama": "Tri Murniya Ningsih",
                "nim": "1214500038",
                "umur": "21",
                "asal":"Bogor",
                "alamat": "Raden Saleh",
                "hobbi": "Nanya ke Gpt",
                "sosmed": "@trimurniaa_",
                "kesan": "Asik, murah senyum, pendengar yang baik",  
                "pesan":"semangat untuk menjalani hari hari dan persiapan TA nya!!"
            },
            {
                "nama": "Annisa Cahyani Surya",
                "nim": "121450114",
                "umur": "21",
                "asal":"Tangerang Selatan",
                "alamat": "Way Huwi",
                "hobbi": "Membaca dan Menonton",
                "sosmed": "@annisacahyanisurya",
                "kesan": "Asik, murah senyum",  
                "pesan":"Semangat menjalani hari-hari dan persiapan TA nya!!"# 1
            },
            {
                "nama": "Wulan Sabina",
                "nim": "121450150",
                "umur": "21",
                "asal":"Medan",
                "alamat": "Raden Saleh",
                "hobbi": "Belajar, Nonton film, Tidur",
                "sosmed": "@wlsbn0",
                "kesan": "asik saat mengobrol",  
                "pesan":"semangat menjalani hari-hari dan persiapan TA nya!!"# 1
            },
             {
                "nama": "Anisa Dini Amalia",
                "nim": "121450081",
                "umur": "20",
                "asal":"Tangerang",
                "alamat": "Jati Agung",
                "hobbi": "Nonton Drama China",
                "sosmed": "@anisadini10",
                "kesan": "seru dan asik ",  
                "pesan":"semangat menjalani hari-hari dan pesiapan TA nya!!"# 1
            },
             {
                "nama": "Feriyadi Yulius",
                "nim": "122450087",
                "umur": "20",
                "asal":"Sumatera Selatan",
                "alamat": "Way Kandis",
                "hobbi": "Baca Buku",
                "sosmed": "@fer-yulius",
                "kesan": "asik dan baik",  
                "pesan":"semangat terus menjalani hari-harinya dan kuliahnya!!"# 1
            },
             {
                "nama": "Renisha Putri Giani",
                "nim": "122450079",
                "umur": "21",
                "asal":"Bandar Lampung",
                "alamat": "Teluk Betung",
                "hobbi": "Jualan Pancing",
                "sosmed": "@pleurnsh",
                "kesan": "asik dan baik",  
                "pesan":"semangat terus menjalani hari-hari dan kuliahnya !!"# 1
            },
             {
                "nama": "Claudhia Angeliani",
                "nim": "121450124",
                "umur": "21",
                "asal":"Lampung Timur",
                "alamat": "Lampung Timur",
                "hobbi": "Tidur",
                "sosmed": "@dylldbee",
                "kesan": "asik dan baik",  
                "pesan":"semangat terus menjalani hari-harinya dan persiapan TA nya !!"# 1
            },
             {
                "nama": "Mirzan Yusuf Rabbani",
                "nim": "122450110",
                "umur": "20",
                "asal":"Jakarta",
                "alamat": "Korpri",
                "hobbi": "Tidur yang lama dan main kucing",
                "sosmed": "@myrrinn",
                "kesan": "asik dan baik",  
                "pesan":"semangat terus menjalani hari-harinya dan kuliahnya !!"# 1
            },
             {
                "nama": "Muhammad Fahrul Aditya",
                "nim": "121450156",
                "umur": "22",
                "asal":"Surakarta,Jawa Tengah",
                "alamat": "Sukarame",
                "hobbi": "Melukis dan Olahraga",
                "sosmed": "@fhrul.pdf",
                "kesan": "asik dan baik",  
                "pesan":"semangat terus menjalani hari-harinya dan persiapan TA nya !!"# 1
            },
             {
                "nama": "Jeremi Susanto",
                "nim": "122450022",
                "umur": "20",
                "asal":"Bandar Lampung",
                "alamat": "Bandar Lampung",
                "hobbi": "Bengong",
                "sosmed": "@jeremi_s_",
                "kesan": "keren banget kak!!",  
                "pesan":"semangat terus menjelani hari-hari dan kuliahnya kakak !!"# 1
            },
             {
                "nama": "Berlinda Enda Putri",
                "nim": "122450065",
                "umur": "20",
                "asal":"Sumatera Barat",
                "alamat": "Way Huwi",
                "hobbi": "MDuduk di tepi pantai dambil galauin bintang yang tinggal satu",
                "sosmed": "@berlyynda",
                "kesan": "asik,lucu dan seru",  
                "pesan":"semangat terus menjalani hari-hari dan kuliahnya kakak !!"# 1
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    baleg()

elif menu == "Senator":
    def senator():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1GuhpEc8X8INrIoYKSS81N55q4_i0LwIQ",
            "https://drive.google.com/uc?export=view&id=18dYYhU18i3Axl5VVLz6Y3TQnznnrKXq4",
        ]
        data_list = [
            {
                "nama": "Anissa Luthfi Alifia",
                "nim": "121450093",
                "umur": "22",
                "asal": "Lampung Tengah",
                "alamat": "Kost Putri Rahayu",
                "hobbi": "Dengerin bintang nyanyi",
                "sosmed": "@anissalutfi_",
                "kesan": "kakaknya keren banget",
                "pesan": "Semangat menjakani hari hari dan persiapan TA nya kak", 
            },
            {
                "nama": "Rian Bintang Wijaya",
                "nim": "122450094",
                "umur": "20",
                "asal": "Palembang",
                "alamat": "Kota Baru",
                "hobbi": "Nyanyi",
                "sosmed": "@bintangtwinkle",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat menjalani hari hari dan kuliahnya bang!!",
            }
        ]
        display_images_with_data(gambar_urls, data_list)
    senator()

elif menu == "Departemen PSDA":
    def Psda():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
        ]
        data_list = [
                    {
                "nama": "Ericson Chandra Sihombing",
                "nim": "121450026",
                "umur": "21",
                "asal": "Bekasi",
                "alamat": "Khobam",
                "hobbi": "Travelling",
                "sosmed": "@ericsonchandr99",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari", 
            },
            {
                "nama": "Elisabeth Claudia Simanjuntak",
                "nim": "122450123",
                "umur": "20",
                "asal": "Tanggerang",
                "alamat": "Owen Kost",
                "hobbi": "Bernafas",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
            {
                "nama": "Nisrina Nur Afifah",
                "nim": "122450123",
                "umur": "19",
                "asal": "Bekasi",
                "alamat": "Sukarame",
                "hobbi": "Menonton",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
            {
                "nama": "",
                "nim": "122450123",
                "umur": "20",
                "asal": "Tanggerang",
                "alamat": "Owen Kost",
                "hobbi": "Bernafas",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
            {
                "nama": "",
                "nim": "122450123",
                "umur": "20",
                "asal": "Tanggerang",
                "alamat": "Owen Kost",
                "hobbi": "Bernafas",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
            {
                "nama": "",
                "nim": "122450123",
                "umur": "20",
                "asal": "Tanggerang",
                "alamat": "Owen Kost",
                "hobbi": "Bernafas",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
            {
                "nama": "",
                "nim": "122450123",
                "umur": "20",
                "asal": "Tanggerang",
                "alamat": "Owen Kost",
                "hobbi": "Bernafas",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
            {
                "nama": "",
                "nim": "122450123",
                "umur": "20",
                "asal": "Tanggerang",
                "alamat": "Owen Kost",
                "hobbi": "Bernafas",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
            {
                "nama": "",
                "nim": "122450123",
                "umur": "20",
                "asal": "Tanggerang",
                "alamat": "Owen Kost",
                "hobbi": "Bernafas",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Psda()

elif menu == "Departemen MEDKRAF":

    def Medkraf():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
        ]
        data_list = [
            {
                "nama": "Wahyudiyanto",
                "nim": "121450040",
                "umur": "22",
                "asal": "Makassar",
                "alamat": "Sukarame",
                "hobbi": "Nonton",
                "sosmed": "@wayylaja",
                "kesan": "Abangnya kece banget!!",
                "pesan": "semangat menjalani hari-hari dan persiapan TA nya bang!!",
            },
            {
                "nama": "Elok Fiola",
                "nim": "122450051",
                "umur": "19",
                "asal": "Bandar Lampung",
                "alamat": "Bandar Lampung",
                "hobbi": "Editing",
                "sosmed": "@elokfiola",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliah nya kak!!", 
            },
            {
                "nama": "Arsyiah Azahra",
                "nim": "121450035",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Tanjung Senang",
                "hobbi": "Nugas",
                "sosmed": "@arsyiah._",
                "kesan": "kakaknya keren banget!!",
                "pesan": "semangat menjalani hari-hari dan persiapan TA nya kak!!", 
            },
            {
                "nama": "Muhammad Kaisar Firdaus ",
                "nim": " 121450135",
                "umur": "21",
                "asal": "Pesawaran",
                "alamat": "Pulau Damar",
                "hobbi": "Lagi Nyari",
                "sosmed": " @dino_kiper",
                "kesan": "Abangnya kece banget!!",
                "pesan": "semangat menjalani hari-hari dan persiapan TA nya bang!!", 
            },
            {
                "nama": "Muhammad Arsal Ranjana Putra",
                "nim": "121450111",
                "umur": "21",
                "asal": "Depok",
                "alamat": "Nangka 4",
                "hobbi": "Ngoding",
                "sosmed": "@arsal.utama",
                "kesan": "Abnagnya keren banget!!",
                "pesan": "semangat menjalani hari-hari dan persiapan TA nya bang!!", 
            },
            {
                "nama": "Cintya  Bella",
                "nim": "122450066",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Teluk",
                "hobbi": "Ngegym",
                "sosmed": "@cintyabella28",
                "kesan": "Kakaknya keren banget!!",
                "pesan": "semangat menjalani hari-hari dan kuliahnya kak!!", 
            },
            {
                "nama": "Eka Fidiya Putri",
                "nim": " 122450045",
                "umur": "20",
                "asal": "Natar, Lampung Selatan",
                "alamat": "Natar, Lampung Selatan",
                "hobbi": "Menyibukkan Diri",
                "sosmed": "@ekafdyaptri",
                "kesan": "kakaknya keren banget!!",
                "pesan": "semangat menjalani hari-hari dan kuliahnya kak!!", 
            },
            {
                "nama": "Najla Juwairia",
                "nim": "122450037",
                "umur": "19",
                "asal": "Sumatra Utara",
                "alamat": "Airan",
                "hobbi": "Menulis, Membaca, fangirling",
                "sosmed": "@nanana_minjoo",
                "kesan": "kakaknya keren banget!!",
                "pesan": "semangat menjalani hari-hari dan kuliahnya kak!!", 
            },
            {
                "nama": "Patricia Leondra Diajeng Putri ",
                "nim": "122450050",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Jatimulyo",
                "hobbi": "Nonton Film",
                "sosmed": "@patriciadiajeng",
                "kesan": "kakaknya keren banget!!",
                "pesan": "semangat menjalani hari-hari dan kuliahnya kak@@", 
            },
            {
                "nama": "Rahma Neliyana",
                "nim": "122450036",
                "umur": "20",
                "asal": "Lampung",
                "alamat": "Sukarame",
                "hobbi": "Baca Coding",
                "sosmed": "@rahmanellyana",
                "kesan": "kakaknya keren banget!!",
                "pesan": "semangat menjalani hari-hari dan kuliahnya kak!!", 
            },
            {
                "nama": "Try Yani Rizki Nur Rohmah ",
                "nim": "122450020",
                "umur": "20",
                "asal": "Lampung Barat",
                "alamat": "Korpri",
                "hobbi": "Bernyanyi dan Menonton",
                "sosmed": "@tryyaniciaaa",
                "kesan": "kakaknya keren banget!!",
                "pesan": "semangat menjalani hari-hari dan kuliahnya kak!!", 
            },
            {
                "nama": "Gymnastiar Al Khoarizmy",
                "nim": "122450096",
                "umur": "20",
                "asal": "Serang",
                "alamat": "Lapangan Golf UIN",
                "hobbi": "Baca Komik",
                "sosmed": "@jimnn.as",
                "kesan": "kakaknya keren banget!!",
                "pesan": "semangat menjalani hari-hari dan kuliah nya kak!!", 
            },
            {
                "nama": "Nasywa Nur Afifah ",
                "nim": "122450125",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Jalan Durian 1 Pemda",
                "hobbi": "Nonton Drakor",
                "sosmed": "@nsywanaf",
                "kesan": "kakaknya keren banget!!",
                "pesan": "semangat menjalani hari-hari dan kuliahnya kak!!", 
            },
            {
                "nama": "Abit Ahmad Oktarian",
                "nim": "122450042",
                "umur": "19",
                "asal": "Bandar Lampung",
                "alamat": "Rajabasa, Labuhan Dalam",
                "hobbi": "Ngoding, Gaming",
                "sosmed": "@abitahmad",
                "kesan": "Abangnya kece banget!!",
                "pesan": "semangat menjalani hari-hari dan kuliahnya bang!!", 
            },
             {
                "nama": "Akmal Faiz Abdillah",
                "nim": "122450114",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Perumahan Griya Sukarame",
                "hobbi": "Main HP",
                "sosmed": "@_akmal.faiz",
                "kesan": "Abangnya kece banget!!",
                "pesan": "semangat menjalani hari-hari dan kuliahnya bang!!", 
            },
             {
                "nama": "Hermawan Manurung ",
                "nim": "122450069",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Dekat Jalan Tol (Wisma Hana Hani) ",
                "hobbi": "Bengong/Membaca Buku",
                "sosmed": "@hermawan.mnrng",
                "kesan": "Abangnya kece banget",
                "pesan": "semangat menjalani hari-hari dan kuliahnya bang!!", 
            },
             {
                "nama": "Khusnun Nisa",
                "nim": "122450078",
                "umur": "20",
                "asal": "Lampung Selatan",
                "alamat": "",
                "hobbi": "Mengerjakan Tugas",
                "sosmed": "@khusnun_nisa335",
                "kesan": "kakaknya keren banget!!",
                "pesan": "semangat menjalani hari-hari dan kuliahnya kak!!", 
            },
             {
                "nama": "Priska Silvia Ferantiana",
                "nim": "122450053",
                "umur": "20",
                "asal": "Palembang",
                "alamat": "Jalan Nangka 2",
                "hobbi": "Baca Novel yang Bikin Nangis",
                "sosmed": "@prskslv",
                "kesan": "kakaknya keren banget",
                "pesan": "semangat menjalani hari-hari dan kuliahnya kak!!", 
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Medkraf()

elif menu == "Departemen MIKFES":

    def Mikfes():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1iT7w4VzecLKH780gi06s_1tXME24Oefv",
            "https://drive.google.com/uc?export=view&id=1hvklUjpYRu1L1QmfmAxTTnE1_g8bZxhm",
            "https://drive.google.com/uc?export=view&id=1hE1uJohpj7v6uNnCff4_YvYCUPFYELfW",
            "https://drive.google.com/uc?export=view&id=1i2QWx6-EfazB5s2ck1q0pi8fX6Fp_cqQ",
            "https://drive.google.com/uc?export=view&id=1hM4tpCGs15QbVGYWUluh4TRi5ay4s-hR",
            "https://drive.google.com/uc?export=view&id=1hkwHV9bAW2cCaGca7ZOwC5H3jdPBjs1t",
            "https://drive.google.com/uc?export=view&id=1iRAretU-if3SdolQjTC8dRWh1Nx7lW8c",
            "https://drive.google.com/uc?export=view&id=1hO57SrGK4V7gwpKOLzjyU4r-Zuh6B7o7",
            "https://drive.google.com/uc?export=view&id=1hXoT5RVPkwLk-sQ_JY1HniV1lbiWVHvb",
            "https://drive.google.com/uc?export=view&id=1hxcfY-gL9GPx2P0YZC24Z5w4CfwHwTLQ",
            "https://drive.google.com/uc?export=view&id=1hOMhnVaypPGgZ6NaHZKI3aCKTTK4G-gj",
            "https://drive.google.com/uc?export=view&id=1hnmZJXZGIhFbzJ_B8yI6D5Ok8MmbVZXA",
            "https://drive.google.com/uc?export=view&id=1hcpjNXksJNz3PvKfTloOjeYjCBSJYMB6",
            "https://drive.google.com/uc?export=view&id=1i26rTUGwaCgdtP8764QnyhRcnt6N5gEj",
            "https://drive.google.com/uc?export=view&id=1i9XmX_5MvG6oMtUpnD2Bawz1ChHm2Ulg",
            "https://drive.google.com/uc?export=view&id=1iJK1YdbxuSHB1Hsy060xOT98J74WisEM",
            "https://drive.google.com/uc?export=view&id=1hxtkgrALzvay6F3Q70O5D7vblUii6buR",
            "https://drive.google.com/uc?export=view&id=1iJax8E04zePFdUnAZN-NAuyLpPrT60Z3",
            "https://drive.google.com/uc?export=view&id=1i3OP0NpOv2iBa1vq-7UXfE9Svs8FHPIq",
        ] 
        data_list = [
            {
                "nama": "Rafi Fadhlillah",
                "nim": "121450143",
                "umur": "21 Tahun",
                "asal": "Lubuk Linggau",
                "alamat": "Jl. Nangka 4",
                "hobbi": "Olahraga",
                "sosmed": "@rafadhilillahh13",
                "kesan": "Abangnya kece banget!!",
                "pesan": "semangat menjalani hari-hari dan persiapan TA nya bang!!",
            },
            {
                "nama": "Annisa Novantika",
                "nim": "121450005",
                "umur": "21 Tahun",
                "asal": "Lampung Utara",
                "alamat": "Jl. Pulau Sebesi, Sukarame",
                "hobbi": " Memasak",
                "sosmed": "@anovavona",
                "kesan": "kakaknya keren banget!!",
                "pesan": "semangat menjalani hari-hari dan persiapan TA nya kak!!",
            },
            {
                "nama": " Ahmad Sahidin Akbar",
                "nim": "122450044",
                "umur": " 20",
                "asal": "Tulang Bawang",
                "alamat": " Sukarame",
                "hobbi": "Olahraga",
                "sosmed": "@sahid22__",
                "kesan": "Abangnya kece banget!!",
                "pesan": "semangat menjalani hari-hari dan kuliahnya bang!!",
            },
            {
                "nama": "Fadhil Fitra Wijaya",
                "nim": "122450082",
                "umur": "20 Tahun",
                "asal": "Bekasi",
                "alamat": "Teluk Betung ",
                "hobbi": "Main Game",
                "sosmed": "@fadhilfwee",
                "kesan": "Abangnya kece banget!!",
                "pesan": "semangat menjalani hari-hari dan kuliahnya bang!!",
            },
            {
                "nama": "Muhammad Regi Abdi Putra Amanta",
                "nim": " 122450031",
                "umur": "19 Tahun",
                "asal": "Palembang",
                "alamat": "Jl. Permadi Sukarame  ",
                "hobbi": "Main Game",
                "sosmed": "@mregiiii_",
                "kesan": "Abangnya kece banget!!!",
                "pesan": "semangat menjalani hari-hari dan kuliahnya bang!!!",
            },
            {
                "nama": "Syalaisha Andina Putriansyah",
                "nim": "122450121",
                "umur": "21 Tahun",
                "asal": "Tangerang",
                "alamat": "Gg Yudhistira ",
                "hobbi": "Baca Novel",
                "sosmed": "@dkselsd_31",
                "kesan": "kakaknya keren banget!!",
                "pesan": "semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Natanael Oktavianus Partahan Sihombing ",
                "nim": "121450107",
                "umur": "20 Tahun",
                "asal": "Jakarta",
                "alamat": "Kemiling ",
                "hobbi": "Membuka Wisata HMSD",
                "sosmed": "@natanaeloks",
                "kesan": "Abangnya kece banget!!!",
                "pesan": "semangat menjalani hari-hari dan persiapan TA nya bang!!!",
            },
            {
                "nama": "Anwar Muslim",
                "nim": "122450117",
                "umur": "21 Tahun",
                "asal": "Bukittinggi",
                "alamat": "Korpri ",
                "hobbi": " ML (Machine Learning)",
                "sosmed": "@here.am.ai",
                "kesan": "Abangnya kece banget!!",
                "pesan": "semangat menjalani hari-hari dan kuliahnya bang!!",
            },
            {
                "nama": "Deva Anjani Khayyuninafsyah",
                "nim": "122450014",
                "umur": "21 Tahun",
                "asal": " Bandar Lampung",
                "alamat": "Kemiling",
                "hobbi": "Menonton Film",
                "sosmed": "@anjaniiidev",
                "kesan": "kakakknya keren banget!!",
                "pesan": "semangat menjalani hari-hari dan kuliah nya kak!!",
            },
            {
                "nama": "Dinda Nababan",
                "nim": "122450120",
                "umur": "20 Tahun",
                "asal": "Medan",
                "alamat": "Jl. Lapas",
                "hobbi": "Main Game",
                "sosmed": "@dindanababan_",
                "kesan": "kakaknya keren banget!!",
                "pesan": "semangat menjalankan hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Marleta Cornelia Leander",
                "nim": "122450092",
                "umur": "20 Tahun",
                "asal": "Depok, Jawa Barat",
                "alamat": "Gg. Nangka 3",
                "hobbi": "Liatin Jurnal",
                "sosmed": "@marletacornelia",
                "kesan": "kakaknya keren banget!!",
                "pesan": "semangat menjalankan hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Rut Junita Sari Siburian",
                "nim": "122450103",
                "umur": "20 Tahun",
                "asal": "Batam, Kep.Riau",
                "alamat": "Gg. Nangka 3",
                "hobbi": "Resume Jurnal",
                "sosmed": "@junitaa_0406",
                "kesan": "kakaknya keren banget!!",
                "pesan": "semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Syadza Puspadari Azhar",
                "nim": " 122450072",
                "umur": "20 Tahun",
                "asal": "Palembang",
                "alamat": "Belwis ",
                "hobbi": "Membaca",
                "sosmed": "@puspadrr",
                "kesan": "pendengar yang baik",
                "pesan": "semangat terus ya kak dan jangan bosen dengerin aku cerita:)",
            },
            {
                "nama": " Abdurrahman Al-atsary",
                "nim": "121450128",
                "umur": "23 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "Perumnas Way Kandis",
                "hobbi": " Membaca",
                "sosmed": "@rahmn_abdr",
                "kesan": "Abangnya kece banget!!",
                "pesan": "semangat menjalankan hari-hari dan persiapan TA nya bang!!",
            },
            {
                "nama": "Aditya Rahman",
                "nim": "122450113",
                "umur": "20 Tahun",
                "asal": " Lampung Timur",
                "alamat": "Korpri",
                "hobbi": "Ngoding WISATA",
                "sosmed": "@rahm_adityaa",
                "kesan": "Abangnya kece banget!!",
                "pesan": "semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Eggi Satria",
                "nim": "122450032",
                "umur": "20 Tahun",
                "asal": "Sukabumi",
                "alamat": "Korpri",
                "hobbi": "Ngoding dan buat konten WISATA",
                "sosmed": "@egistr ",
                "kesan": "Abangnya kece banget!!!",
                "pesan": "semangat menjalani hari-hari dan kuliahnya bang!!!",
            },
            {
                "nama": "Febiya Jomy Pratiwi",
                "nim": "122450074",
                "umur": "20 Tahun",
                "asal": "Tulang Bawang",
                "alamat": "Jl Kelengkeng Raya",
                "hobbi": "Nonton K-Drama ",
                "sosmed": "@pratiwifebiya",
                "kesan": "kakaknya keren banget!!",
                "pesan": "semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Happy Syahrul Ramadhan",
                "nim": "122450013",
                "umur": "20 Tahun",
                "asal": "Lampung",
                "alamat": "Karang Anyar ",
                "hobbi": " Main Game",
                "sosmed": "@sudo.syahrulramadhannn",
                "kesan": "Abanganya kece banget!!",
                "pesan": "semangat menjalankan hari-hari dan kuliahnya bang!!",
            },
            {
                "nama": "Randa Andriana Putra",
                "nim": "122450083",
                "umur": "21 Tahun",
                "asal": "Banten",
                "alamat": " Sukarame",
                "hobbi": " Tidur dan Berkembang",
                "sosmed": "@randaandriana_",
                "kesan": "Abangnya kece banget!!!",
                "pesan": "semangat menjalani hari-hari dan kuliahnya bang!!!",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Mikfes()

elif menu == "Departemen Eksternal":
    def Eksternal():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1XT4J7ES0Qe9tZfamfDPAT9cRzEAxVuK4",
            "https://drive.google.com/uc?export=view&id=1Y6HKTMrQemYdOMrURu0GZ1dbv85KtecZ",
            "https://drive.google.com/uc?export=view&id=1Y4RXsw3qsVk7S2-CdDZ7WUCbjrM8qz2b",
            "https://drive.google.com/uc?export=view&id=1XQfznit1sgxjJ2UfB7HRAeH05SGIe9t5",
            "https://drive.google.com/uc?export=view&id=1XLRNx_EMSbl6huXFAmrFIKxR94iPBY4f",
            "https://drive.google.com/uc?export=view&id=1XNhJydns8jwoZ97kjPorfo7DL7KjwhM6",
            "https://drive.google.com/uc?export=view&id=1XUqppAFQljMv5U8DzYz7nxaafiGJ4qcD",
            "https://drive.google.com/uc?export=view&id=1Xc1fpc-VzwE2oAIsm3Tb6ZK5umblIBFN",
            "https://drive.google.com/uc?export=view&id=1XhHLxjKfCYw7MJSrZBTXPCanB5POcued",
            "https://drive.google.com/uc?export=view&id=1Y1XL_LJeOqhGLZtL0gdrv5eT3MnLfPJK",
            "https://drive.google.com/uc?export=view&id=1XyH5SwHftbEypxsVp4LhpXXVFamfAGkQ",
            "https://drive.google.com/uc?export=view&id=1XXBmidi8Fg1DI2s-732hAMWWUqFSqrXu",
            "https://drive.google.com/uc?export=view&id=1Y4Sh3DzWSZ-wMaWoqTTsOKPncWGAviz9",
            "https://drive.google.com/uc?export=view&id=1XtvXHZQM4npc6B4r62PKGQeWzUYMQL-o",
            "https://drive.google.com/uc?export=view&id=1XccHH55bKm14xGCefcj1eGssWpvWmfRS",
            "https://drive.google.com/uc?export=view&id=1Xx_PeGIUpIm0FgbCL04WBFnMpVx1f4t8",
        ]
        data_list = [
            {
                "nama": "Yogy Sea Tama",
                "nim": "121450041",
                "umur": "21",
                "asal": "Tangerang",
                "alamat": "Jatimulyo",
                "hobbi": "Ngisi Bensin",
                "sosmed": "@yogyyyyyyy",
                "kesan": "Abangnya kece bangett",
                "pesan": "Semangat menjalani hari-hari dan Persiapan TA nya ya bang!!", 
            },
            {
                "nama": "Ramadhita Asifa Hendri",
                "nim": "121450131",
                "umur": "21",
                "asal": "Rajabasa",
                "alamat": "Rajabasa",
                "hobbi": "Belajar",
                "sosmed": "@Ramadhitaasifa",
                "kesan": "kakanya keren banget!!",
                "pesan": "Semangat menjalani ahri-hari dan Persiapan TA nya kak!!",
            },
            {
                "nama": "Nazwa Nabilla",
                "nim": "121450112",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Way Kandis",
                "hobbi": "Belajar dengan Rajin",
                "sosmed": "@nazwanbilla",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan Persiapan TA nya kak!!",
            },
            {
                "nama": "Dea Mutia Risani",
                "nim": "122450099",
                "umur": "20",
                "asal": "Sumatera Barat",
                "alamat": "Korpri",
                "hobbi": "Bikin Surat",
                "sosmed": "@deaa.rsn",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Novelia Adinda",
                "nim": "122450104",
                "umur": "21",
                "asal": "Jakarta",
                "alamat": "Belwis",
                "hobbi": "Tidur",
                "sosmed": "@nvliadinda",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Ratu Keisha Jasmin Deonova",
                "nim": "122450106",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Way Kandis",
                "hobbi": "Ngerjain ADW",
                "sosmed": "@jasminednva",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Tobias David Monogari",
                "nim": "121450081",
                "umur": "20",
                "asal": "Jakarta Barat",
                "alamat": "Pemda",
                "hobbi": "Bikin Puisi",
                "sosmed": "@tobiassiagian",
                "kesan": "abangnya kece banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya bang!!",
            },
            {
                "nama": "Rizki Adrian Bennovry",
                "nim": "121450073",
                "umur": "21",
                "asal": "Bekasi",
                "alamat": "TVRI",
                "hobbi": "Buat Portopolio",
                "sosmed": "@rzkdrnnn",
                "kesan": "Abangnya kece banget",
                "pesan": "Semangat menjalani hari-hari dan persiapan TA nya bang!!",
            },
            {
                "nama": "Arafi Ramadhan Maulana",
                "nim": "12245022",
                "umur": "20",
                "asal": "Jogja, Depok",
                "alamat": "Way Huwi",
                "hobbi": "menghafal al-quran",
                "sosmed": "@arafiramadhanmaulana",
                "kesan": "Abangnya kece banget",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya bang!!",
            },
            {
                "nama": "Asa Do'a Uyi",
                "nim": "122450005",
                "umur": "20",
                "asal": "Muara",
                "alamat": "Korpri",
                "hobbi": "cuci baju",
                "sosmed": "@u_yippy",
                "kesan": "kakaknya keren banget",
                "pesan": "semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Chalifia Wananda",
                "nim": "122450076",
                "umur": "20",
                "asal": "Padang",
                "alamat": "sukarame",
                "hobbi": "Quality Time",
                "sosmed": "@chipawww",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Irvan Alfaritzi",
                "nim": "122450093",
                "umur": "21",
                "asal": "Sumatera Barat",
                "alamat": "Jakarta",
                "hobbi": "Nonton Youtube dan main ML",
                "sosmed": "@Alfaritziirfan",
                "kesan": "Abangnya kece banget",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya bang",
            },
            {
                "nama": "Izza Lutfia",
                "nim": "122450090",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Teluk",
                "hobbi": "main vollly",
                "sosmed": "@izzalutfiaa",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Khaalishah Zuhrah ALyaa Valefi",
                "nim": "122450034",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Rajabasa",
                "hobbi": "Nyanyi",
                "sosmed": "@alyaavalefi",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Raid Muhammad Naufal",
                "nim": "122450027",
                "umur": "20",
                "asal": "Lampung Tengah",
                "alamat": "Sukarame",
                "hobbi": "Ngeresume Seminar",
                "sosmed": "@rayHis_",
                "kesan": "Abangnya kece banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya bang!!",
            },
            {
                "nama": "Tria Yunanni",
                "nim": "122450062",
                "umur": "20",
                "asal": "Way Kanan",
                "alamat": "Jakarta",
                "hobbi": "Baca",
                "sosmed": "@tria_y062",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Eksternal()
elif menu == "Departemen Internal":
    def Internal():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1IuI8XJGQRK1pzryB-EmQwsBKty07kvRm",
            "https://drive.google.com/uc?export=view&id=1b0pgeTG6jySyZMgiK0so3Fj4EEISzwnb",
            "https://drive.google.com/uc?export=view&id=1bEM756lWXJgnfn4-Dv1tDqvp7toB3vLs",
            "https://drive.google.com/uc?export=view&id=1b3Rvth1Uetwpcyhdh9SVFQY9A_Bnleur",
            "https://drive.google.com/uc?export=view&id=1bTr--yB1Wfyv0O20m5dnt0JHQRvpa0t4",
            "https://drive.google.com/uc?export=view&id=1b92JwzvwQuVEavH11dv8LqmAuenEbeUA",
            "https://drive.google.com/uc?export=view&id=1bdKpyuv8-LUwhXvnGe11rF75sNxcDHFg",
            "https://drive.google.com/uc?export=view&id=1bHPySJB3-Ewl150Ig0mM8z2Ai_FRd8Vy",
            "https://drive.google.com/uc?export=view&id=1bJkF9eFUlqbSY91u5UGbs3gC0KbVId0G",
            "https://drive.google.com/uc?export=view&id=1bOImJS3WVoNSMOs7ba3Zbq4Xf0Jr2Sfl",
            "https://drive.google.com/uc?export=view&id=1beiF_B72iF6Ufi_O72mfeEbu6IOms2KU",
            "https://drive.google.com/uc?export=view&id=1b2ZVwSG8Cx3G9Pi8s0TtWJcLgn23b_5U",
            "https://drive.google.com/uc?export=view&id=1bUOYKRuW1pN2FEtKaUII6Wfps9B_L4ra",
        ]
        data_list = [
            {
                "nama": "Dimas rizky ramadhani",
                "nim": "121450027",
                "umur": "20",
                "asal": "Pamulang",
                "alamat": "Way kandis",
                "hobbi": "Manjat tower sutet",
                "sosmed": "@dimzrky",
                "kesan": "Abangnya kece banget!!",
                "pesan": "Semangat menjalani hari-hari dan persiapan TA nya bang dim!!", 
            },
            {
                "nama": "Catherine firdhasari maulina sinaga",
                "nim": "121450072",
                "umur": "20",
                "asal": "Sumatera Utara",
                "alamat": "Airan",
                "hobbi": "Baca novel",
                "sosmed": "@chatherine.sinaga",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan persiapan TA nya kak cath",
            },    
            {
                "nama": "M. Akbar resdika",
                "nim": "121450066",
                "umur": "20",
                "asal": "Lampung Barat",
                "alamat": "Labuhan dalam",
                "hobbi": "Memelihara dino",
                "sosmed": "@akbar_resdika",
                "kesan": "Abangnya kece banget!!",
                "pesan": "Semangat menjalani hari-hari dan persiapan TA nya bang!!",
            },
            {
                "nama": "Rani puspita sari",
                "nim": "122450030",
                "umur": "20",
                "asal": "Metro",
                "alamat": "Rajabasa",
                "hobbi": "Mengaji",
                "sosmed": "@ranipu",
                "kesan": "Kakaknya keren banget!!",
                "pesan": "Semangat menjalankan hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Rendra eka prayoga",
                "nim": "122450112",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Jalan lapas raya",
                "hobbi": "nulis lagu",
                "sosmed": "@rendraepr",
                "kesan": "Abangnya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya bang ren!!",
            },
            {
                "nama": "Salwa farhanatussaidah",
                "nim": "122450055",
                "umur": "20",
                "asal": "Pesawaran",
                "alamat": "Airan raya",
                "hobbi": "ngeliat cogan",
                "sosmed": "@slwfhn_694",
                "kesan": "kakaknya keren banget!!",
                "pesan": "semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Ari sigit",
                "nim": "121450069",
                "umur": "23",
                "asal": "Lampung barat",
                "alamat": "Labuhan ratu",
                "hobbi": "Main futsal",
                "sosmed": "@ari_sigit17",
                "kesan": "Abangnya kece banget!!",
                "pesan": "semangat menjalankan hari-hari dan persiapan TA nya bang!!",
            },
            {
                "nama": "Azizah kusumah putri",
                "nim": "122450068",
                "umur": "21",
                "asal": "Lampung Selatan",
                "alamat": "Natar",
                "hobbi": "berkebun",
                "sosmed": "@azizahksmh15",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalankan hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Meira listyaningrum",
                "nim": "122450011",
                "umur": "20",
                "asal": "Pesawaran",
                "alamat": "Airan raya",
                "hobbi": "Menghalu",
                "sosmed": "@meiraln",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalankan hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Rendi alexander hutagalung",
                "nim": "122450057",
                "umur": "20",
                "asal": "Tangerang",
                "alamat": "Kost gunawan",
                "hobbi": "Menyanyi",
                "sosmed": "@alexanderr",
                "kesan": "Abangnya kece banget!!",
                "pesan": "semangat menjalankan hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Renta siahaan",
                "nim": "122450070",
                "umur": "21",
                "asal": "Sumatera utara",
                "alamat": "Gerbang barat",
                "hobbi": "Memancing",
                "sosmed": "@renta.shn",
                "kesan": "Kakaknya keren banget!!",
                "pesan": "semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Yosia lehare banurea",
                "nim": "121450149",
                "umur": "20",
                "asal": "Dairi, Sumatera utara",
                "alamat": "Perum griya indah",
                "hobbi": "Bawa motor pakai kaki",
                "sosmed": "@yosiabanurea",
                "kesan": "kakaknya kece banget!!",
                "pesan": "semangat menjalani hari-hari dan persiapan TA nya kak!!",
            },
            {
                "nama": "Josua panggabean",
                "nim": "121450061",
                "umur": "21",
                "asal": "Pematang siantar",
                "alamat": "Gya kost",
                "hobbi": "Ngawinin cupang",
                "sosmed": "@josuapanggabean16_",
                "kesan": "Abangnya kece banget!!",
                "pesan": "semangat menjalankan hari-hari dan Persiapan TA nya bang!!",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Internal()
elif menu == "Departemen SSD":
    def Ssd():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=t",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
        ]
        data_list = [
            {
                "nama": "Andrian Agustinus Lumban Gaol",
                "nim": "121450090",
                "umur": "17 +",
                "asal": "Sidikalang",
                "alamat": "Lapas",
                "hobbi": "Nyari Hobi",
                "sosmed": "@andrialgaol",
                "kesan": "abangnya kece banget!!",
                "pesan": "Semangat menjalani hari-hari dan persiapan TA nya bang!!", 
            },
            {
                "nama": "Adisty Syawaida Ariyanto",
                "nim": "121450136",
                "umur": "21",
                "asal": "Metro",
                "alamat": "Metro",
                "hobbi": "Nonton film",
                "sosmed": "@adistisa_",
                "kesan": "Kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan persiapan TA nya kak!!",
            },
            {
                "nama": "Nabila Azhari",
                "nim": "121450029",
                "umur": "21",
                "asal": "Simalungun",
                "alamat": "Airan",
                "hobbi": "Menghitung",
                "sosmed": "@zhjung",
                "kesan": "Kakaknya keren banget!!",
                "pesan": "semangat menjalani hari-hari adn persiapan TA nya kak!!",
            },
            {
                "nama": "Danang Hilal Kurniawan",
                "nim": "122450085",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "TB 3 Asrama",
                "hobbi": "Belajar",
                "sosmed": "@dananghk_",
                "kesan": "Abangnya kece kali",
                "pesan": "semangat menjalani hari-hari dan kuliahnya bang!!",
            },
            {
                "nama": "Farel Julio Akbar",
                "nim": "122450110",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Jalan Lapas",
                "hobbi": "Bebas",
                "sosmed": "@farel__julio",
                "kesan": "abangnya kece banget!!",
                "pesan": "semangat menjalani hari-hari dan kuliahnya bbang!!",
            },
            {
                "nama": "Nabilah Andika Fitriani",
                "nim": "121450129",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Kedaton",
                "hobbi": "Tidur",
                "sosmed": "@nabilaafrn",
                "kesan": "kakanya keren banget!!",
                "pesan": "semangat menjalani hari-hari dan persiapan TA nya kak!!",
            },
            {
                "nama": "Alvia Asrinda Br.Ginting",
                "nim": "122450077",
                "umur": "20",
                "asal": "Binjai",
                "alamat": "Korpri",
                "hobbi": "Nonton Windah",
                "sosmed": "@alviaginting",
                "kesan": "Kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya",
            },
            {
                "nama": "Dhafin Razaka Luthfia",
                "nim": "122450133",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Jalan nangka 1",
                "hobbi": "Olahraga",
                "sosmed": "@dhafinrzqri3",
                "kesan": "kakanya kerern banget!!",
                "pesan": "semnagat menjalani hari-hari dan kuliahnya kak!!",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Ssd()

# Tambahkan menu lainnya sesuai kebutuhan
