import streamlit as st
from streamlit_option_menu import option_menu
import requests
from PIL import Image, ImageOps
from io import BytesIO

st.markdown("""<style>.centered-title {text-align: center;}</style>""",unsafe_allow_html=True)
st.markdown("<h1 class='centered-title'>BUKU KATING</h1>", unsafe_allow_html=True)

# bagian sini jangan diubah
def streamlit_menu():
    selected = option_menu(
        menu_title=None,
        options=[
            "Kesekjenan",
            "Baleg",
            "Senator",
            "Departemen PSDA",
            "Departemen MEDKRAF",
            "Departemen MIKFES",
            "Departemen Eksternal",
            "Departemen Internal",
            "Departemen SSD",
        ],
        icons=[
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
        ],
        default_index=0,
        orientation="horizontal",
        styles={
            "container": {"padding": "0!important", "background-color": "#fafafa"},
            "icon": {"color": "black", "font-size": "19px"},
            "nav-link": {
                "font-size": "15px",
                "text-align": "left",
                "margin": "0px",
                "--hover-color": "#eee",
            },
            "nav-link-selected": {"background-color": "#3FBAD8"},
        },
    )
    return selected

@st.cache_data
def load_image(url):
    response = requests.get(url)
    if response.status_code != 200:
        st.error(
            f"Failed to fetch image from {url}, status code: {response.status_code}"
        )
        return None
    try:
        img = Image.open(BytesIO(response.content))
        img = ImageOps.exif_transpose(img)
        img = img.resize((300, 400))
        return img
    except Exception as e:
        st.error(f"Error loading image: {e}")
        return None
    
@st.cache_data
def display_images_with_data(gambar_urls, data_list):
    images = []
    for i, url in enumerate(gambar_urls):
        with st.spinner(f"Memuat gambar {i + 1} dari {len(gambar_urls)}"):
            img = load_image(url)
            if img is not None:
                images.append(img)

    for i, img in enumerate(images):
        # Menggunakan Streamlit untuk menampilkan gambar di tengah kolom
        col1, col2, col3 = st.columns([1, 2, 1])
        with col2:
            st.image(img, use_column_width=True)

        if i < len(data_list):
            st.write(f"Nama: {data_list[i]['nama']}")
            st.write(f"NIM: {data_list[i]['nim']}")
            st.write(f"Umur: {data_list[i]['umur']}")
            st.write(f"Asal: {data_list[i]['asal']}")
            st.write(f"Alamat: {data_list[i]['alamat']}")
            st.write(f"Hobbi: {data_list[i]['hobbi']}")
            st.write(f"Sosial Media: {data_list[i]['sosmed']}")
            st.write(f"Kesan: {data_list[i]['kesan']}")
            st.write(f"Pesan: {data_list[i]['pesan']}")
            st.write("  ")
    st.write("Semua gambar telah dimuat!")
menu = streamlit_menu()

# BAGIAN SINI YANG HANYA BOLEH DIUABAH
if menu == "Kesekjenan":
    def kesekjenan():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1nJNzJ4_GnFKh-f09CLh_VfvTn0_rryV-",
            "https://drive.google.com/uc?export=view&id=1_aFB_x-ut6-CObYMTcPQ9k8veEE1gDS2",
            "https://drive.google.com/uc?export=view&id=1xZ1E67k3eMQEynERjYg0W9RkFZiYBZ_y",
            "https://drive.google.com/uc?export=view&id=1Oc5-DLSDOJiuWDHRiezyRBUk7GoUrkyR",
            "https://drive.google.com/uc?export=view&id=18zzttrggsfHBAYENQC_So7LTwpQSuReU",
            "https://drive.google.com/uc?export=view&id=1S4f4xnM-VRHVF0gJ96ohCjp5v8cg7GII",
        ]
        data_list = [
            {
                "nama": "Kharisma Gumilang",
                "nim": "121450042",
                "umur": "21",
                "asal": "Palembang",
                "alamat": "Jl.Pulau Damar",
                "hobbi": "Dengerin Musik",
                "sosmed": "@gumilangkharisma",
                "kesan": "awesome",  
                "pesan":"semoga semua mimpinya bisa terwujud bang!"
            },
            {  
                "nama": "Pandra Insani Putra Anwar",
                "nim": "121450147",
                "umur": "21",
                "asal":"Lampung Utara",
                "alamat": "Sukarame",
                "hobbi": "Main Gitar",
                "sosmed": "@pandrainsani27",
                "kesan": "Keren dan teladan",  
                "pesan":"Jangan lupa istirahat bang!"
            },
            {   

                "nama": "Meliza Wulandari",
                "nim": "121450065",
                "umur": "20",
                "asal":"Sumatera Selatan",
                "alamat": "Jl.Pagar Alam",
                "hobbi": "Nonton Drakor",
                "sosmed": "@wulandarimeliza",
                "kesan": "Asyik diajak diskusi",  
                "pesan":"semangat ngasprak strukdatnya kak !!!"# 1
            },

            {  

                "nama": "Putri Maulida Chairani",
                "nim": "121450050",
                "umur": "21",
                "asal":"Sumatera Barat",
                "alamat": "Gg. Nangka 4",
                "hobbi": "Dengerin Bg Pandra Main Gitar",
                "sosmed": "@ptrimaulidaaa_",
                "kesan": "Keliatan care sama kita",  
                "pesan":"Terimakasih kak udah support kami"# 1
            },
        
            {   
               
                "nama": "Hartiti Fadilah",
                "nim": "121450031",
                "umur": "21",
                "asal":"Palembang",
                "alamat": "Pemda",
                "hobbi": "Nyanyi",
                "sosmed": "@htrpdla",
                "kesan": "Banyak ilmu dari kakak",  
                "pesan":"Semangat ngurus cuannya kak"# 1
            },
        
            {

                "nama": "Nadilla Andhara Putri",
                "nim": "121450003",
                "umur": "21",
                "asal":"Lampung",
                "alamat": "Metro",
                "hobbi": "Membaca",
                "sosmed": "@nadilaandr26",
                "kesan": "Publick speakingnya bagus",  
                "pesan":"Keep shining, Kak!"# 1
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    kesekjenan()

elif menu == "Baleg":
    def baleg():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1cL7f55Y1_mpzYFYqq4QUUkFGo3B2b91C",
            "https://drive.google.com/uc?export=view&id=1WfZZYzJCWBKmR2j0ZeNYWV2Cv7Rm0Urj",
            "https://drive.google.com/uc?export=view&id=1jOKb6GNNiBINL630Ez1_Sm4KCZ4cGygj",
            "https://drive.google.com/uc?export=view&id=1Lvwy1euenQlOBd5cmpi2EiDEbHLVeZIL",
            "https://drive.google.com/uc?export=view&id=1uj9aGRXq2PvR7x5wgUvfCesc1nm50JMr",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
            "https://drive.google.com/uc?export=view&id=1uj-IYjN0eGDigoYiirJVpL3ibxrKP7V2",
            "https://drive.google.com/uc?export=view&id=1D41SHxei-b0WfC1iibFLdf0WDuc9RCwD",
            "https://drive.google.com/uc?export=view&id=1HuSDiShE4HKvQQJDw7GL07PaLtqDre4z",
            "https://drive.google.com/uc?export=view&id=1AbtZGCJznjghZTF5WDBdJpDUHY0llCvN",
            "https://drive.google.com/uc?export=view&id=1eM9b3Dcyz-KFUHvWABw90ITgTvbuZhQu",
        ]
        data_list = [
            {
               "nama": "Tri Murniya Ningsih",
                "nim": "121450038",
                "umur": "21",
                "asal":"Bogor",
                "alamat": "Raden Saleh",
                "hobbi": "Nanya ke gpt",
                "sosmed": "@trimurniaa_",
                "kesan": "Seru diajak sharing",  
                "pesan":"semoga selalu diberi keberuntungan kak"
            },
            {
                 "nama": "Annisa Cahyani Surya",
                "nim": "121450114",
                "umur": "21",
                "asal":"Tanggerang Selatan",
                "alamat": "Way Hui",
                "hobbi": "Membaca, menonton",
                "sosmed": "@annisacahyanisurya",
                "kesan": "Selalu kasih solusi.",  
                "pesan":"semangat kuliahnya kak!"# 1
            },
            {
                "nama": "Wulan Sabina",
                "nim": "121450150",
                "umur": "21",
                "asal":"Medan",
                "alamat": "Raden Saleh",
                "hobbi": "Belajar, nonton film, tidur",
                "sosmed": "@wlsbn0",
                "kesan": "ga ekspect kakanya pembisnis",  
                "pesan":"Lancar terus usahanya kak"# 1
            },
             {
                "nama": "Anisa Dini Amalia",
                "nim": "121450081",
                "umur": "20",
                "asal":"Tanggerang",
                "alamat": "Jati Agung",
                "hobbi": "Nonton Drachin",
                "sosmed": "@anisadini10",
                "kesan": "lucuu",  
                "pesan":"semangat kuliahnya kak"# 1
            },
            {
                "nama": "Claudhia Angeliani",
                "nim": "121450124",
                "umur": "21",
                "asal":"Lampung Timur",
                "alamat": "Lampung Timur",
                "hobbi": "Tidur",
                "sosmed": "@dylebee",
                "kesan": "baik banget",  
                "pesan":"Tetap rendah hati, Kak!"# 1
            },
            {
               "nama": "Muhammad fahrul Aditya",
                "nim": "121450156",
                "umur": "22",
                "asal":"Surakarta",
                "alamat": "Sukarame",
                "hobbi": "Melukis, olahraga",
                "sosmed": "@fhrul.pdf",
                "kesan": "kece abis",  
                "pesan":"Semangat buat semua impiannya bang!"# 1
            },
             {
                "nama": "Feriyadi Yulius",
                "nim": "122450087",
                "umur": "20",
                "asal":"Sumatera Selatan",
                "alamat": "Way Kandis",
                "hobbi": "Baca buku",
                "sosmed": "@fer_yulius",
                "kesan": "Ngajar alpronya asik!",  
                "pesan":"Semoga semakin sukses terus bang!"
            },
             {
                "nama": "Renisha Putri Giani",
                "nim": "122450079",
                "umur": "21",
                "asal":"Bandar Lampung",
                "alamat": "Teluk Betung",
                "hobbi": "Jualan pancing",
                "sosmed": "@fleurnsh",
                "kesan": "Banyak ilmu dari kakak.",  
                "pesan":"Jaga kesehatan, ya kak!"# 1
            },

             {
                "nama": "Mirzan Yusuf Rabbani",
                "nim": "122450118",
                "umur": "20",
                "asal":"Jakarta",
                "alamat": "Korpri",
                "hobbi": "Tidur yang lama, main kucing",
                "sosmed": "@myrrinn",
                "kesan": "orangnya easy going",  
                "pesan":"Makasih banyak ilmunya bang!"
            },

            {
                "nama": "Jeremia Susanto",
                "nim": "122450022",
                "umur": "20",
                "asal":"Bandar Lampung",
                "alamat": "Bandar Lampung",
                "hobbi": "Bengong",
                "sosmed": "@jeremia_s_",
                "kesan": "baik, mau ngajarin codingan saya hehe",  
                "pesan":"kece terus kak, semangat aspraknya!"# 1
            },
            {
                "nama": "Berliana Enda Putri",
                "nim": "122450065",
                "umur": "20",
                "asal":"Sumatera Barat",
                "alamat": "Way Huwi",
                "hobbi": "Duduk di tepi pantai sambil galauin bintang ynag tinggal satu",
                "sosmed": "@berlyyanda",
                "kesan": "seru ga ngebosenin",  
                "pesan":"Semoga makin sukses!"
            },

        ]
        display_images_with_data(gambar_urls, data_list)
    baleg()

elif menu == "Senator":
    def senator():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=18uKYtQCwwbnWeBOxWAu1Ns1S_m7Fmg3T",
            "https://drive.google.com/uc?export=view&id=1GzwKsjYbArlBYVL4TnJGa5TK-sZ8_H-R",
        ]
        data_list = [
            {
                "nama": "Anissa Luthfi Alifia",
                "nim": "121450093",
                "umur": "22",
                "asal": "Lampung Tengah",
                "alamat": "Kost Putri Rahayu",
                "hobbi": "Dengerin bintang nyanyi",
                "sosmed": "@anissalutfi_",
                "kesan": "Suka vibes positif dari kakak.",
                "pesan": "Harapan terbaik untuk masa depan kakak!", 
            },
            {
                "nama": "Rian Bintang Wijaya",
                "nim": "122450094",
                "umur": "20",
                "asal": "Palembang",
                "alamat": "Kota Baru",
                "hobbi": "Nyanyi",
                "sosmed": "@bintangtwinkle",
                "kesan": "Bikin kita lebih percaya diri.",
                "pesan": "Terus berkarya dan berprestasi!",
            }
        ]
        display_images_with_data(gambar_urls, data_list)
    senator()

elif menu == "Departemen PSDA":
    def Psda():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1xLmnxL0O7BZhJQkFRXZPd6L4iPiPXKED",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
            "https://drive.google.com/uc?export=view&id=1yc3gf3KuGo1JsTA6VvEEJLM0inv02OgF",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
            "https://drive.google.com/uc?export=view&id=1inAFG1H3Ih0frkUQCgmyM5D5Taz5i6ZK",
            "https://drive.google.com/uc?export=view&id=1yuDWlq3GXZ91xq2Baxfz1RAhYaIb8LCP",
            "https://drive.google.com/uc?export=view&id=194FfO8XdhBGmixV3LETcZjL764er4oGX",
            "https://drive.google.com/uc?export=view&id=1B2r5JEmKz6aFT23Da1UFa_D6AjwSbs6n",
            "https://drive.google.com/uc?export=view&id=1r7wQb3Um5yc1nLQllxmwBRFIXlBhEhaC",
            "https://drive.google.com/uc?export=view&id=1rZ2X04itKRlm0-5w3IWAD0jCfYkI5QpH",
            "https://drive.google.com/uc?export=view&id=1iXlYnPwnxydyRDzP5cXgN5l3jnsIXhfm",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
            "https://drive.google.com/uc?export=view&id=1RdMi_tNJ6MWMddhquyOFsob9zrgdokX8",
            "https://drive.google.com/uc?export=view&id=1JUzxa_3ttI3c96c2iMRNUgVX5Cm2_3c8",
            "https://drive.google.com/uc?export=view&id=1vYCyuWiKBpWuffgf0LJGYNnCnzUr4eez",
            "https://drive.google.com/uc?export=view&id=1X1ETgFqKqHhVA0BSOiGFT0L9IMdZqDWx",
            "https://drive.google.com/uc?export=view&id=1r2S-ASClRDaC1nWPmOHbSRoUqhycAfYW",
            "https://drive.google.com/uc?export=view&id=1nLFOdduF8v3I-Xi5G3s6pACT4F5LFS24",
            "https://drive.google.com/uc?export=view&id=1CwduJEtKASCf8bq7LnmhZoU9zYl1llor",
            "https://drive.google.com/uc?export=view&id=1EL8Prskn37rupiofpBXoWp3jy4dzmGvA",
            
        ]
        data_list = [
                        {
                "nama": "Ericson Chandra Sihombing",
                "nim": "121450026",
                "umur": "21",
                "asal":"Bekasi",
                "alamat": "Khobam",
                "hobbi": "Travelling",
                "sosmed": "@ericsonchandra99",
                "kesan": "keren, tegas, public speakingnya baguss",  
                "pesan":"selamat menjalani hari harinya bang",
            },
            {
                "nama": "Elisabeth Claudia Simanjuntak",
                "nim": "122450123",
                "umur": "20",
                "asal":"Tangerang",
                "alamat": "Kemiling",
                "hobbi": "Bernafas",
                "sosmed": "@celisabethh_",
                "kesan": "lucu dan asikk",  
                "pesan":"ceria terus kakk",
            },
            {
                "nama": "Nisrina Nur Afifah",
                "nim": "122450052",
                "umur": "19",
                "asal":"Jawa Barat",
                "alamat": "Sukarame",
                "hobbi": "Muter-muter",
                "sosmed": "@afifahhnsrn",
                "kesan": "multitalent",  
                "pesan":"semoga selalu diberi keberuntungan kak!",
            },
            { 
                "nama": " Deyvan Loxefal", 
                "nim": " 121450148 ", 
                "umur":  "21", 
                "asal":" Duri Riau  ", 
                "alamat": "Khobam Pulau Damar", 
                "hobbi": "Belajar", 
                "sosmed": "@depanlo", 
                "kesan": "ramah asik baik pinter juga",   
                "pesan":"semangat ta banggg",
            },
            {
                "nama": "M. Farhan Athaulloh",
                "nim": "121450117",
                "umur": "21",
                "asal":"Lampung",
                "alamat": "Kota Baru",
                "hobbi": "Menolong",
                "sosmed": "@mfarhan.ath",
                "kesan": "Abangnya baik dan ramah juga ",  
                "pesan":"sukses terus",
            },
            {
                "nama": "Allya Nurul Islami Pasha",
                "nim": "122450033",
                "umur": "20",
                "asal":"Sumatera Barat",
                "alamat": "Belwis",
                "hobbi": "Nongs",
                "sosmed": "@allyaislami",
                "kesan": "baik banget, asik jugaa",  
                "pesan":"sukses terus di pilihannya kakk",
            },
            {
                "nama": "Eksanty Febriana Sukma Islamiaty",
                "nim": "122450001",
                "umur": "20",
                "asal":"Lubuk Linggau",
                "alamat": "Rajabasa",
                "hobbi": "Nyari sinyal di gedung F",
                "sosmed": "@eksantyfebriana",
                "kesan": "pinter banget",  
                "pesan": "sehat sehat kak!",
            },
            {
                "nama": "Farahanum Afifah Ardiansyah",
                "nim": "122450056",
                "umur": "20",
                "asal":"Padang",
                "alamat": "Sukarame",
                "hobbi": "Minum Kopi",
                "sosmed": "@farahanumafifahh",
                "kesan": "kakanyanya cantik, baik jugaa",  
                "pesan":"semoga dipermudah semua urusannya kak",
            },
            {
                "nama": "Ferdy Kevin Naibaho",
                "nim": "122450107",
                "umur": "20",
                "asal":"Medan",
                "alamat": "Senopati Raya",
                "hobbi": "Dengerin Musik",
                "sosmed": "@ferdy_kevin",
                "kesan": "Abangnya baik",  
                "pesan":"semangat semester 5 bangg!",
            },
            {
                "nama": "M. Deriansyah Okutra",
                "nim": "122450101",
                "umur": "19",
                "asal":"Kayu Agung",
                "alamat": "Jl. Pagar Alam Kedaton",
                "hobbi": "Nongki-nongki",
                "sosmed": "@dransyh_",
                "kesan": "abangnya kerenn",  
                "pesan":"Sukses selalu bang",
            },
            {
                "nama": "Oktavia Nurwenda Puspita Sari",
                "nim": "122450041",
                "umur": "20",
                "asal":"Lampung Timur",
                "alamat": "Way Huwi",
                "hobbi": "Scroll tik-tok",
                "sosmed": "@oktavianrwnda",
                "kesan": "baik dan manis",  
                "pesan":"panjang umur dan sehat selalu kak!",
            },
            
            { 
                "nama": " Ibnu Farhan Al-Ghifari", 
                "nim": " 121450121 ", 
                "umur":  "21", 
                "asal":" Kerinci Jambi  ", 
                "alamat": "Khobam", 
                "hobbi": "game online", 
                "sosmed": "@al_ghifari032", 
                "kesan": "asik diajak ngobrol",   
                "pesan":"Semangat menjalani hari hari bang",
            },
            { 
                "nama": "Johannes Krisjon Silitonga", 
                "nim": "122450043", 
                "umur": "19", 
                "asal":"Tangerang", 
                "alamat": "Jl. Lapas", 
                "hobbi": "Ngasprak", 
                "sosmed": "@johanneskrisjon", 
                "kesan": "profesional",   
                "pesan":"makasih udh bimbing kami bang", 
            },
            { 
                "nama": "Kemas Veriandra Ramadhan", 
                "nim": "122450016", 
                "umur": "19", 
                "asal":"Bekasi", 
                "alamat": "Kojo Golf UIN", 
                "hobbi": "Main game", 
                "sosmed": "@kemasverii", 
                "kesan": "jagoo codingg",   
                "pesan":"makasih bang udah ngajarin kami coding", 
            },
            { 
                "nama": "Leonard Andreas Napitupulu", 
                "nim": "121450153", 
                "umur": "21", 
                "asal":"Medan", 
                "alamat": "Khobam", 
                "hobbi": "belajar", 
                "sosmed": "@lndr.__", 
                "kesan": "Abangnya baik",   
                "pesan":"semoga selalu dijauhkan dari masalah bang", 
            },
            { 
                "nama": "Presilia", 
                "nim": "122450081", 
                "umur": "20", 
                "asal":"Bekasi", 
                "alamat": "Kota Baru", 
                "hobbi": "Dengerin lomba sihir", 
                "sosmed": "@presiliamy", 
                "kesan": "Kakaknya cantik, murah senyum",   
                "pesan":"keep shining!", 
            },
            { 
                "nama": "Sahid Maulana", 
                "nim": "122450109", 
                "umur": "21", 
                "asal":"Depok, Jabar", 
                "alamat": "Jl. Airan Raya", 
                "hobbi": "Dengerin musik", 
                "sosmed": "@sahid_maul19", 
                "kesan": "baik polll, soft spoken, punya lifestylenya sendiri, very good vibes",   
                "pesan":"terus jadi orang baik ya bang, terimakasih sekali lagi..", 
            },
        
            {
                "nama": "Gede Moana",
                "nim": "121450014",
                "umur": "21",
                "asal":"Bekasi",
                "alamat": "Korpri Raya",
                "hobbi": "Belajar, game, baca komik",
                "sosmed": "@gedemoenaa",
                "kesan": "seruu, kalem tapi asik juga",  
                "pesan":"bahagia terus bang",
            },
            {
                "nama": "Jaclin Alcavella",
                "nim": "122450015",
                "umur": "19",
                "asal":"Sumatera Selatan",
                "alamat": "Korpri",
                "hobbi": "Berenang",
                "sosmed": "@jaclinalcv_",
                "kesan": "energinya positif",  
                "pesan":"Semangat kuliahnya ya kak",
            },
            {
                "nama": "Syalaisha Andini Putriansyah",
                "nim": "122450111",
                "umur": "21",
                "asal":"Tangerang",
                "alamat": "Sukarame",
                "hobbi": "Baca",
                "sosmed": "@syalaisha.i__",
                "kesan": "awalnya gabisa bedain sama kak dina",  
                "pesan":"ayoo sdm lagi kak tahun depann",
            },
           
        ]
        display_images_with_data(gambar_urls, data_list)
    Psda()

elif menu == "Departemen MEDKRAF":

    def Medkraf():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1GDdCSYZhy4uhFPRDIAGpNBZH_-J0QXm0",
            "https://drive.google.com/uc?export=view&id=1G9rSMVCcfNxeUbCGis8smTNNtb1NZB13",
            "https://drive.google.com/uc?export=view&id=1GnW7Sj7syeyp6b-Qlh3QYTOXMgTaWPUg",
            "https://drive.google.com/uc?export=view&id=1GM7Ao-eXNwqnpHtDh9Osi3CN-0k5wFrX",
            "https://drive.google.com/uc?export=view&id=1GC1Jy9kgcQUvW0sgtebbeJDOaOgzhkv7",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
            "https://drive.google.com/uc?export=view&id=1Ggd6YxbevVx0ghgcWVSi_714a6FwMSdO",
            "https://drive.google.com/uc?export=view&id=1GqJ1bB5h_0owgsrg1OA6nyHg-4tTrInm",
            "https://drive.google.com/uc?export=view&id=1GOiKy6vysquRmW8jcoAqYgq3mbXbC6-l",
            "https://drive.google.com/uc?export=view&id=1GoWvpPOItmyqzs7UJLwGw-jd1elydarZ",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
            "https://drive.google.com/uc?export=view&id=1GFyuQwrO7OSMObJeBroo8qgf7HDnDzhk",
            "https://drive.google.com/uc?export=view&id=1GO6jXESXoXY2yxCMrJ3N0r-sQXJtQF4u",
            "https://drive.google.com/uc?export=view&id=1GEtS0Du3x5BVhh6fSwSsa0o0XlUg3IN4",
            "https://drive.google.com/uc?export=view&id=1GCSbsiHdEcfGd8b3wDBq0HQOti_GTxjm",
            "https://drive.google.com/uc?export=view&id=1GanTtXCKwhlo1PLN18BTRd84_lV4UX3J",


        ]
        data_list = [
            {
                "nama": "Wahyudiyanto",
                "nim": "121450040",
                "umur": "22",
                "asal": "Makassar",
                "alamat": "Sukarame",
                "hobbi": "Nonton",
                "sosmed": "",
                "kesan": "penuh semangat",
                "pesan": "semoga apa yang diimpikan tercapai bangg",
            },
            {
                "nama": "Elok Fiola",
                "nim": "122450051",
                "umur": "19",
                "asal": "Bandar Lampung",
                "alamat": "Bandar Lampung",
                "hobbi": "Editing",
                "sosmed": "@elokfiola",
                "kesan": "cakep bangett kakk",
                "pesan": "terima kasih sudah membagikan ilmu!", 
            },
            
            {
                "nama": "Muhammad Kaisar Firdaus ",
                "nim": " 121450135",
                "umur": "21",
                "asal": "Pesawaran",
                "alamat": "Pulau Damar",
                "hobbi": "Lagi Nyari",
                "sosmed": " @dino_kiper",
                "kesan": "vibes orang pinter",
                "pesan": "semangat untuk TAnya", 
            },
            {
                "nama": "Muhammad Arsal Ranjana Putra",
                "nim": "121450111",
                "umur": "21",
                "asal": "Depok",
                "alamat": "Nangka 4",
                "hobbi": "Ngoding",
                "sosmed": "@arsal.utama",
                "kesan": "ramah",
                "pesan": "semangat menjalani hari hari di semester2 akhir bang", 
            },
            {
                "nama": "Cintya  Bella",
                "nim": "122450066",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Teluk",
                "hobbi": "Ngegym",
                "sosmed": "@cintyabella28",
                "kesan": "vibesnya cocok banget di divisi media & konten",
                "pesan": "semangat ngonten kak", 
            },
            
            {
                "nama": "Najla Juwairia",
                "nim": "122450037",
                "umur": "19",
                "asal": "Sumatra Utara",
                "alamat": "Airan",
                "hobbi": "Menulis, Membaca, fangirling",
                "sosmed": "@nanana_minjoo",
                "kesan": "ga pelit ilmu",
                "pesan": "keep going", 
            },
            {
                "nama": "Patricia Leondra Diajeng Putri ",
                "nim": "122450050",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Jatimulyo",
                "hobbi": "Nonton Film",
                "sosmed": "@patriciadiajeng",
                "kesan": "Kakak bikin topik serius jadi fun.",
                "pesan": "ayo kita ngajar anak kelas 4 lagi", 
            },
            {
                "nama": "Rahma Neliyana",
                "nim": "122450036",
                "umur": "20",
                "asal": "Lampung",
                "alamat": "Sukarame",
                "hobbi": "Baca Coding",
                "sosmed": "@rahmanellyana",
                "kesan": "asikk orangnyaa ternyata asik beneran",
                "pesan": "maaf sempet salah nyebut nama kak hehe", 
            },
            {
                "nama": "Tri Yani Rizki Nur Rohmah ",
                "nim": "122450020",
                "umur": "20",
                "asal": "Lampung Barat",
                "alamat": "Korpri",
                "hobbi": "Bernyanyi dan Menonton",
                "sosmed": "@tryyaniciaaa",
                "kesan": "easy going!",
                "pesan": "keep spirit", 
            },
            {
                "nama": "Gymnastiar Al Khoarizmy",
                "nim": "122450096",
                "umur": "20",
                "asal": "Serang",
                "alamat": "Lapangan Golf UIN",
                "hobbi": "Baca Komik",
                "sosmed": "@jimnn.as",
                "kesan": "gaya fotonya keren",
                "pesan": "keep sharing your experiences ", 
            },
            {
                "nama": "Nasywa Nur Afifah ",
                "nim": "122450125",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Jalan Durian 1 Pemda",
                "hobbi": "Nonton Drakor",
                "sosmed": "@nsywanaf",
                "kesan": "ramah dan menyenangkan",
                "pesan": "semoga impian nya segera tercapai", 
            },
            {
                "nama": "Abit Ahmad Oktarian",
                "nim": "122450042",
                "umur": "19",
                "asal": "Bandar Lampung",
                "alamat": "Rajabasa, Labuhan Dalam",
                "hobbi": "Ngoding, Gaming",
                "sosmed": "@abitahmad",
                "kesan": "approachable!",
                "pesan": "terus berbagi ilmu dan inspirasi!", 
            },
             {
                "nama": "Akmal Faiz Abdillah",
                "nim": "122450114",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Perumahan Griya Sukarame",
                "hobbi": "Main HP",
                "sosmed": "@_akmal.faiz",
                "kesan": " enak diajak diskusi",
                "pesan": " keep being awesome", 
            },
             {
                "nama": "Hermawan Manurung ",
                "nim": "122450069",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Dekat Jalan Tol (Wisma Hana Hani) ",
                "hobbi": "Bengong/Membaca Buku",
                "sosmed": "@hermawan.mnrng",
                "kesan": "fresh dan energik",
                "pesan": "semangat menjadi pdd bang", 
            },
             {
                "nama": "Khusnun Nisa",
                "nim": "122450078",
                "umur": "20",
                "asal": "Lampung Selatan",
                "alamat": "",
                "hobbi": "Mengerjakan Tugas",
                "sosmed": "@khusnun_nisa335",
                "kesan": "kreatif dalam menjelaskan.",
                "pesan": "makasi materi tentang Rnya kakk", 
            },
             {
                "nama": "Priska Silvia Ferantiana",
                "nim": "122450053",
                "umur": "20",
                "asal": "Palembang",
                "alamat": "Jalan Nangka 2",
                "hobbi": "Baca Novel yang Bikin Nangis",
                "sosmed": "@prskslv",
                "kesan": "kak baca novel tereliye gaa",
                "pesan": "jaga kesehatan kak!", 
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Medkraf()

elif menu == "Departemen MIKFES":

    def Mikfes():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1lWdu9PD3xm8spfuTto6x1yOaskkY1tLH",
            "https://drive.google.com/uc?export=view&id=1436EDcyIy1neMMGiS2i_CwSVcOb2c4b5",
            "https://drive.google.com/uc?export=view&id=1mLBLjztG03vFGRnLO0VGxFJs5mzwz2Rx",
            "https://drive.google.com/uc?export=view&id=1wBGl4p4zGn1jh4N66PLqaRB99u1g1vCb",
            "https://drive.google.com/uc?export=view&id=12svBq_2H8kuFFoTRMT8evNpudd8WJlx4",
            "https://drive.google.com/uc?export=view&id=14eRGQSZOsw8z3h_3f9vLJs2c7g7OsL8v",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
            "https://drive.google.com/uc?export=view&id=10JKTN1r3e4h81eYwukQU3mbrA9VuvFH0",
            "https://drive.google.com/uc?export=view&id=1f2f1CZA4Ui8oEsgn1pb05yDNyb8vDsGu",
            "https://drive.google.com/uc?export=view&id=1XT3d755N6mHdcEy4oAaCaUIJWeXnSXyL",
            "https://drive.google.com/uc?export=view&id=1BHxhT3DncbE6IvhbUoXBrYsXH3phFUlw",
            "https://drive.google.com/uc?export=view&id=1ZVhhLE6CQNUKaNsRILottaElvNXrJjt_",
            "https://drive.google.com/uc?export=view&id=1YGtvvDBP8s1LIMpUlUFeVrehZIrAfzCw",
            "https://drive.google.com/uc?export=view&id=1tWbVuoUWRHwx07rVb8ZdTfDM7hRGZ_Qc",
            "https://drive.google.com/uc?export=view&id=1EU1eKosOx9XR2yT8UtFBv0nvoVRzMR0H",
            "https://drive.google.com/uc?export=view&id=1ABClOGf9ehcxOLj5w41vV0i1vQ6kJ4ns",
            "https://drive.google.com/uc?export=view&id=168N19tWhf7CduhQ4f9iPz0ZjeNy0Fy3-",
            "https://drive.google.com/uc?export=view&id=1fMam-OVQwYMMUcwPtKyWuGuqmmm9Yuj5",
            "https://drive.google.com/uc?export=view&id=1ZOwOb4BCU456TyWmb0minpk3iuhGLUE_",

        ] 
        data_list = [
            {
                "nama": "Rafi Fadhlillah",
                "nim": "121450143",
                "umur": "21 Tahun",
                "asal": "Lubuk Linggau",
                "alamat": "Jl. Nangka 4",
                "hobbi": "Olahraga",
                "sosmed": "@rafadhilillahh13",
                "kesan": "bang keren betull, multitalent",
                "pesan": "mangat terus bang",
            },
            {
                "nama": "Annisa Novantika",
                "nim": "121450005",
                "umur": "21 Tahun",
                "asal": "Lampung Utara",
                "alamat": "Jl. Pulau Sebesi, Sukarame",
                "hobbi": " Memasak",
                "sosmed": "@anovavona",
                "kesan": "nama kakaknya sama kaya kelompok kita",
                "pesan": "bahagia dan sehat sehat kakk",
            },
            {
                "nama": "Natanael Oktavianus Partahan Sihombing ",
                "nim": "121450107",
                "umur": "20 Tahun",
                "asal": "Jakarta",
                "alamat": "Kemiling ",
                "hobbi": "Membuka Wisata HMSD",
                "sosmed": "@natanaeloks",
                "kesan": "stylenya keren bang",
                "pesan": "semangat buat abangnya",
            },
            {
                "nama": " Abdurrahman Al-atsary",
                "nim": "121450128",
                "umur": "23 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "Perumnas Way Kandis",
                "hobbi": " Membaca",
                "sosmed": "@rahmn_abdr",
                "kesan": "bang, pinter banget dan ramah juga, mau ngajarin adik adiknya",
                "pesan": "semoga semua impiannya tercapai bangg, sukses terus",
            },
            {
                "nama": " Ahmad Sahidin Akbar",
                "nim": "122450044",
                "umur": " 20",
                "asal": "Tulang Bawang",
                "alamat": " Sukarame",
                "hobbi": "Olahraga",
                "sosmed": "@sahid22__",
                "kesan": "positif vibes",
                "pesan": "keep going bang",
            },
            {
                "nama": "Fadhil Fitra Wijaya",
                "nim": "122450082",
                "umur": "20 Tahun",
                "asal": "Bekasi",
                "alamat": "Teluk Betung ",
                "hobbi": "Main Game",
                "sosmed": "@fadhilfwee",
                "kesan": "tiggi betul bang",
                "pesan": "sukses untuk semuanya bang",
            },
            {
                "nama": "Muhammad Regi Abdi Putra Amanta",
                "nim": " 122450031",
                "umur": "19 Tahun",
                "asal": "Palembang",
                "alamat": "Jl. Permadi Sukarame  ",
                "hobbi": "Main Game",
                "sosmed": "@mregiiii_",
                "kesan": " very multitalented",
                "pesan": "keep shinning bang",
            },
            {
                "nama": "Syalaisha Andina Putriansyah",
                "nim": "122450121",
                "umur": "21 Tahun",
                "asal": "Tangerang",
                "alamat": "Gg Yudhistira ",
                "hobbi": "Baca Novel",
                "sosmed": "@dkselsd_31",
                "kesan": "suka ketuker sama kak dini",
                "pesan": "kak, ayoo sdm lagiii",
            },

            {
                "nama": "Anwar Muslim",
                "nim": "122450117",
                "umur": "21 Tahun",
                "asal": "Bukittinggi",
                "alamat": "Korpri ",
                "hobbi": " ML (Machine Learning)",
                "sosmed": "@here.am.ai",
                "kesan": "pinter betull",
                "pesan": "makasi bang udah ngajarin codingannya",
            },
            {
                "nama": "Deva Anjani Khayyuninafsyah",
                "nim": "122450014",
                "umur": "21 Tahun",
                "asal": " Bandar Lampung",
                "alamat": "Kemiling",
                "hobbi": "Menonton Film",
                "sosmed": "@anjaniiidev",
                "kesan": "kakaknya cantikk",
                "pesan": "sehat sehat terus kak",
            },
            {
                "nama": "Dinda Nababan",
                "nim": "122450120",
                "umur": "20 Tahun",
                "asal": "Medan",
                "alamat": "Jl. Lapas",
                "hobbi": "Main Game",
                "sosmed": "@dindanababan_",
                "kesan": "vibesnya orang pinter bgt",
                "pesan": "semangat menjalani hari harinya kak",
            },
            {
                "nama": "Marleta Cornelia Leander",
                "nim": "122450092",
                "umur": "20 Tahun",
                "asal": "Depok, Jawa Barat",
                "alamat": "Gg. Nangka 3",
                "hobbi": "Liatin Jurnal",
                "sosmed": "@marletacornelia",
                "kesan": "kakaknya cantik dan multitalent jugaa",
                "pesan": "mangats terus kak",
            },
            {
                "nama": "Rut Junita Sari Siburian",
                "nim": "122450103",
                "umur": "20 Tahun",
                "asal": "Batam, Kep.Riau",
                "alamat": "Gg. Nangka 3",
                "hobbi": "Resume Jurnal",
                "sosmed": "@junitaa_0406",
                "kesan": "asikk dan seruu",
                "pesan": "sukses selalu kak rutt",
            },
            {
                "nama": "Syadza Puspadari Azhar",
                "nim": " 122450072",
                "umur": "20 Tahun",
                "asal": "Palembang",
                "alamat": "Belwis ",
                "hobbi": "Membaca",
                "sosmed": "@puspadrr",
                "kesan": "baik pollll(terutama sama anak anaknyaaa), pendengar yang baik, very positif vibes,",
                "pesan": "makasih banyak kak puspaaaa, semoga selalu diberi keberuntungan dan dipermudah jalannya",
            },

            {
                "nama": "Aditya Rahman",
                "nim": "122450113",
                "umur": "20 Tahun",
                "asal": " Lampung Timur",
                "alamat": "Korpri",
                "hobbi": "Ngoding WISATA",
                "sosmed": "@rahm_adityaa",
                "kesan": "kerenn dan asikk",
                "pesan": "semangat kuliahnya bang",
            },
            {
                "nama": "Eggi Satria",
                "nim": "122450032",
                "umur": "20 Tahun",
                "asal": "Sukabumi",
                "alamat": "Korpri",
                "hobbi": "Ngoding dan buat konten WISATA",
                "sosmed": "@egistr ",
                "kesan": "sejagooo itu codinganyaa",
                "pesan": "dipermudah selalu bang urusanyaa",
            },
            {
                "nama": "Febiya Jomy Pratiwi",
                "nim": "122450074",
                "umur": "20 Tahun",
                "asal": "Tulang Bawang",
                "alamat": "Jl Kelengkeng Raya",
                "hobbi": "Nonton K-Drama ",
                "sosmed": "@pratiwifebiya",
                "kesan": "kakaknya maniss dan ramah",
                "pesan": "sehat sehat kakk",
            },
            {
                "nama": "Happy Syahrul Ramadhan",
                "nim": "122450013",
                "umur": "20 Tahun",
                "asal": "Lampung",
                "alamat": "Karang Anyar ",
                "hobbi": " Main Game",
                "sosmed": "@sudo.syahrulramadhannn",
                "kesan": "bangg pinter bangett, inisiatif",
                "pesan": "semoga selalu diberikan kemudahan bang ",
            },
            {
                "nama": "Randa Andriana Putra",
                "nim": "122450083",
                "umur": "21 Tahun",
                "asal": "Banten",
                "alamat": " Sukarame",
                "hobbi": " Tidur dan Berkembang",
                "sosmed": "@randaandriana_",
                "kesan": "full of ambition and passion",
                "pesan": "semoga apa yang diinginkan tercapai bang",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Mikfes()

elif menu == "Departemen Eksternal":
    def Eksternal():
        gambar_urls = [

            "https://drive.google.com/uc?export=view&id=1guLMBUcjFlpRQ5c57flJqi5YjAeRx67z",
            "https://drive.google.com/uc?export=view&id=1goKHPUDKVyUAxPZ06hohNcid7x0mxMvG",
            "https://drive.google.com/uc?export=view&id=1hUOfa-mAWrpQduWSetnhaK2cLIg-5zsf",
            "https://drive.google.com/uc?export=view&id=1gk5z_PipXUpCS24NHdBSFBzTp_waU-3v",
            "https://drive.google.com/uc?export=view&id=1gz1zMliFShHQNga62X-lisHBgfmnCFIa",
            "https://drive.google.com/uc?export=view&id=1h7b_8B02DHUoQi9Hxj208B4UdZl0VgWy",
            "https://drive.google.com/uc?export=view&id=1h9MHd5HdSAjevSNGJHydElIwMDRLqbkm",
            "https://drive.google.com/uc?export=view&id=1hXJ7bQLn_AqSRBlnM2jNA1h0mVDhH_3U",
            "https://drive.google.com/uc?export=view&id=1gZmdaL_0YPU4EPJZsN8C_xFejsWpSbmy",
            "https://drive.google.com/uc?export=view&id=1g6o0sQEXVLa50ssll2HVyinIZRWH8a6u",
            "https://drive.google.com/uc?export=view&id=1g7szAbwHTkZsn7hclrYwSM1tktmIvg_9",
            "https://drive.google.com/uc?export=view&id=1gkvg3tEJLQz0WXNlpY4A0pObLgi_qbfe",
            "https://drive.google.com/uc?export=view&id=1gjTbxn5vD8fCOAiSNQXSdD5EolXKlTh4",
            "https://drive.google.com/uc?export=view&id=1gGIKLOUu43MqRzOhrlHLN1qw_RN7msZu",
            "https://drive.google.com/uc?export=view&id=1gfdjZHwHt0DlHE8cd_BHbxiD6VPWc8Fw",
            "https://drive.google.com/uc?export=view&id=1g8QyUHprx91NesD_4HnDhEJnO1HEUMhg",

        ]
        data_list = [
            {
                "nama": "Yogy Sea Tama",
                "nim": "121450041",
                "umur": "21",
                "asal": "Tangerang",
                "alamat": "Jatimulyo",
                "hobbi": "Ngisi Bensin",
                "sosmed": "@yogyyyyyyy",
                "kesan": "keren bang style nya",
                "pesan": "semangat semester 5!!", 
            },
            {
                "nama": "Ramadhita Asifa Hendri",
                "nim": "121450131",
                "umur": "21",
                "asal": "Rajabasa",
                "alamat": "Rajabasa",
                "hobbi": "Belajar",
                "sosmed": "@Ramadhitaasifa",
                "kesan": "kakanya cantik",
                "pesan": "sehat sehat kak",
            },
            {
                "nama": "Nazwa Nabilla",
                "nim": "121450112",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Way Kandis",
                "hobbi": "Belajar dengan Rajin",
                "sosmed": "@nazwanbilla",
                "kesan": "ramahh",
                "pesan": "dipermudah jalannya kakk",
            },
            {
                "nama": "Rizki Adrian Bennovry",
                "nim": "121450073",
                "umur": "21",
                "asal": "Bekasi",
                "alamat": "TVRI",
                "hobbi": "Buat Portopolio",
                "sosmed": "@rzkdrnnn",
                "kesan": "stylenya keren bangg",
                "pesan": "semangat untuk ta nya",
            },
            {
                "nama": "Dea Mutia Risani",
                "nim": "122450099",
                "umur": "20",
                "asal": "Sumatera Barat",
                "alamat": "Korpri",
                "hobbi": "Bikin Surat",
                "sosmed": "@deaa.rsn",
                "kesan": "kakanya asikk dan baik juga",
                "pesan": "semangat menjalani hari kak",
            },
            {
                "nama": "Novelia Adinda",
                "nim": "122450104",
                "umur": "21",
                "asal": "Jakarta",
                "alamat": "Belwis",
                "hobbi": "Tidur",
                "sosmed": "@nvliadinda",
                "kesan": "kakaknya cantik dan baikk",
                "pesan": "selalu diberi keberuntungan kak",
            },
            {
                "nama": "Ratu Keisha Jasmin Deonova",
                "nim": "122450106",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Way Kandis",
                "hobbi": "Ngerjain ADW",
                "sosmed": "@jasminednva",
                "kesan": "baik poll, asik juga",
                "pesan": "keep shining kak!",
            },
            {
                "nama": "Tobias David Monogari",
                "nim": "122450081",
                "umur": "20",
                "asal": "Jakarta Barat",
                "alamat": "Pemda",
                "hobbi": "Bikin Puisi",
                "sosmed": "@tobiassiagian",
                "kesan": "ga ekspek seasik dan sebaik ituu",
                "pesan": "semoga selalu diberikan keberuntugan bang!",
            },
        
            {
                "nama": "Arafi Ramadhan Maulana",
                "nim": "12245022",
                "umur": "20",
                "asal": "Jogja, Depok",
                "alamat": "Way Huwi",
                "hobbi": "menghafal al-quran",
                "sosmed": "@arafiramadhanmaulana",
                "kesan": "asikk seruu juga",
                "pesan": "sehat dan bahagia terus bang",
            },
            {
                "nama": "Asa Do'a Uyi",
                "nim": "122450005",
                "umur": "20",
                "asal": "Muara",
                "alamat": "Korpri",
                "hobbi": "cuci baju",
                "sosmed": "@u_yippy",
                "kesan": "inspiratif & very positif vibes +++",
                "pesan": "selalu ceria dan bahagia kak uyii",
            },
            {
                "nama": "Chalifia Wananda",
                "nim": "122450076",
                "umur": "20",
                "asal": "Padang",
                "alamat": "sukarame",
                "hobbi": "Quality Time",
                "sosmed": "@chipawww",
                "kesan": "kakaknya baik dan cantik jugaaa",
                "pesan": "semangat terus kakk",
            },
            {
                "nama": "Irvan Alfaritzi",
                "nim": "122450093",
                "umur": "21",
                "asal": "Sumatera Barat",
                "alamat": "Jakarta",
                "hobbi": "Nonton Youtube dan main ML",
                "sosmed": "@Alfaritziirfan",
                "kesan": "baik dan ramah pol",
                "pesan": "semoga semua impiannya tercapai bang",

            },
            {
                "nama": "Izza Lutfia",
                "nim": "122450090",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Teluk",
                "hobbi": "main vollly",
                "sosmed": "@izzalutfiaa",
                "kesan": "sangat amat ramah dan ekstrovert serta multitalented+++",
                "pesan": "selalu diberi kesehatan dan kebahagiaan kakkk",
            },
            {
                "nama": "Khaalishah Zuhrah ALyaa Valefi",
                "nim": "122450034",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Rajabasa",
                "hobbi": "Nyanyi",
                "sosmed": "@alyaavalefi",
                "kesan": "kakaknya cantik, asik, dan maniss",
                "pesan": "keep being a positive vibes kakk",
            },
            {
                "nama": "Raid Muhammad Naufal",
                "nim": "122450027",
                "umur": "20",
                "asal": "Lampung Tengah",
                "alamat": "Sukarame",
                "hobbi": "Ngeresume Seminar",
                "sosmed": "@rayHis_",
                "kesan": "keren dan asik",
                "pesan": "samangat menjalani kuliah bang",
            },
            {
                "nama": "Tria Yunanni",
                "nim": "122450062",
                "umur": "20",
                "asal": "Way Kanan",
                "alamat": "Jakarta",
                "hobbi": "Baca",
                "sosmed": "@tria_y062",
                "kesan": "ga ekspek ig nya itu nimnya",
                "pesan": "kak, ayo buat jj bareng bang randa",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Eksternal()

elif menu == "Departemen Internal":
    def Internal():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1gRGpQUC6BVXgHXEF-oqG6Q-YkrNdeElD",
            "https://drive.google.com/uc?export=view&id=1do7sx7Io8q6X5lVnRcwKelO5ojTD_3LI",
            "https://drive.google.com/uc?export=view&id=1wwwK_35EDPQmCu6LVfajh47rYxFW00mD",
            "https://drive.google.com/uc?export=view&id=1YfL3BU7Fc9gpaFvGqa59BdqCNSxNBH_R",
            "https://drive.google.com/uc?export=view&id=1aYB860RkSxK6Il9c5Jpi-jCjiOaUV8eE",
            "https://drive.google.com/uc?export=view&id=13vsI4Z4SNUuo1Rqtgrdrq7A-o3QV1sEY",
            "https://drive.google.com/uc?export=view&id=1ItXrCRNuRPzK2PVS3Z-JohnmG2il4IgN",
            "https://drive.google.com/uc?export=view&id=13Xhly909R3bJLVjCbnFRlXd-4PjTUa57",
            "https://drive.google.com/uc?export=view&id=1_VipCe4_sHe8OFKXfaXIK5n0NMGBZVtV",
            "https://drive.google.com/uc?export=view&id=1cLsSpsz1XsB0P4UwmWTUnVrsfRt1uX2X",
            "https://drive.google.com/uc?export=view&id=150k7KErPM3WUnk50nRkvm9MbZcHdYuYU",
            "https://drive.google.com/uc?export=view&id=1DE008oEeCmiJjIVmWRBnGlxJyI9dcfLw",
            "https://drive.google.com/uc?export=view&id=1uIEkHyIf5OSCKKVFRpSAAWK12uf5A8Bk",
        ]
        data_list = [
            {
                "nama": "Dimas rizky ramadhani",
                "nim": "121450027",
                "umur": "20",
                "asal": "Pamulang",
                "alamat": "Way kandis",
                "hobbi": "Manjat tower sutet",
                "sosmed": "@dimzrky",
                "kesan": "ga ekspek sama hobinya",
                "pesan": "Semangat nyusun TA nya bangg", 
            },
            {
                "nama": "Catherine firdhasari maulina sinaga",
                "nim": "121450072",
                "umur": "20",
                "asal": "Sumatera Utara",
                "alamat": "Airan",
                "hobbi": "Baca novel",
                "sosmed": "@chatherine.sinaga",
                "kesan": "kakanya soft spoken",
                "pesan": "Semoga selalu diberi kemudahan kakk",
            },    
            {
                "nama": "M. Akbar resdika",
                "nim": "121450066",
                "umur": "20",
                "asal": "Lampung Barat",
                "alamat": "Labuhan dalam",
                "hobbi": "Memelihara dino",
                "sosmed": "@akbar_resdika",
                "kesan": "baikk ",
                "pesan": "mau liay peliharaannya bangg",
            },
            {
                "nama": "Ari sigit",
                "nim": "121450069",
                "umur": "23",
                "asal": "Lampung barat",
                "alamat": "Labuhan ratu",
                "hobbi": "Main futsal",
                "sosmed": "@ari_sigit17",
                "kesan": "keren banget abangnya",
                "pesan": "semangat kuliahnya bang arii",
            },
            {
                "nama": "Rani puspita sari",
                "nim": "122450030",
                "umur": "20",
                "asal": "Metro",
                "alamat": "Rajabasa",
                "hobbi": "Mengaji",
                "sosmed": "@ranipu",
                "kesan": "positive vibes",
                "pesan": "Selalu bermanfaat untuk orang sekitar ya kak",
            },
            {
                "nama": "Rendra eka prayoga",
                "nim": "122450112",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Jalan lapas raya",
                "hobbi": "nulis lagu",
                "sosmed": "@rendraepr",
                "kesan": "asik dan seru abis",
                "pesan": "keep being awesome bang",
            },
            {
                "nama": "Salwa farhanatussaidah",
                "nim": "122450055",
                "umur": "20",
                "asal": "Pesawaran",
                "alamat": "Airan raya",
                "hobbi": "ngeliat cogan",
                "sosmed": "@slwfhn_694",
                "kesan": "kakaknya cantik",
                "pesan": "semangat kuliahnya kak",
            },
    
            {
                "nama": "Azizah kusumah putri",
                "nim": "122450068",
                "umur": "21",
                "asal": "Lampung Selatan",
                "alamat": "Natar",
                "hobbi": "berkebun",
                "sosmed": "@azizahksmh15",
                "kesan": "Ramah dan baikk",
                "pesan": "kak, mau ke kebunnya",
            },
            {
                "nama": "Meira listyaningrum",
                "nim": "122450011",
                "umur": "20",
                "asal": "Pesawaran",
                "alamat": "Airan raya",
                "hobbi": "Menghalu",
                "sosmed": "@meiraln",
                "kesan": "Baik bangett",
                "pesan": "Semangat kakk!!!",
            },
            {
                "nama": "Rendi alexander hutagalung",
                "nim": "122450057",
                "umur": "20",
                "asal": "Tangerang",
                "alamat": "Kost gunawan",
                "hobbi": "Menyanyi",
                "sosmed": "@alexanderr",
                "kesan": "asik dan ramah",
                "pesan": "semangat untuk kedepannya bang",
            },
            {
                "nama": "Renta siahaan",
                "nim": "122450070",
                "umur": "21",
                "asal": "Sumatera utara",
                "alamat": "Gerbang barat",
                "hobbi": "Memancing",
                "sosmed": "@renta.shn",
                "kesan": "positif vibes jugaa",
                "pesan": "selalu semangat kakak ",
            },
            {
                "nama": "Yosia lehare banurea",
                "nim": "121450149",
                "umur": "20",
                "asal": "Dairi, Sumatera utara",
                "alamat": "Perum griya indah",
                "hobbi": "Bawa motor pakai kaki",
                "sosmed": "@yosiabanurea",
                "kesan": "Baik bangett",
                "pesan": "mau liat abangnya bawa motor pls",
            },
            {
                "nama": "Josua panggabean",
                "nim": "121450061",
                "umur": "21",
                "asal": "Pematang siantar",
                "alamat": "Gya kost",
                "hobbi": "Ngawinin cupang",
                "sosmed": "@josuapanggabean16_",
                "kesan": "sangat amat soft spoken",
                "pesan": "semangat kuliah bang",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Internal()
elif menu == "Departemen SSD":
    def Ssd():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1ANHY6hLMUPfUcfJ1M6oydG2dF1I7jjRy",
            "https://drive.google.com/uc?export=view&id=1AGWcIDjrlQ_fW5_RRAs9NwMbUdm2dwEM",
            "https://drive.google.com/uc?export=view&id=1AGDZrjdcFGBlfiOcW4LSE4iP3Mr_kLt8",
            "https://drive.google.com/uc?export=view&id=1ARMqKYVc2PUOi2yvkV3WJde4y1Rs2fO4",
            "https://drive.google.com/uc?export=view&id=1AW-033s43hiSZEUM_vO62XAJs_NV9n4O",
            "https://drive.google.com/uc?export=view&id=1AMlm2tZjlIWX10vh3SmmM5KUUlJ0a8lj",
            "https://drive.google.com/uc?export=view&id=1AHjLITb2PgNd5W8H-tnjIKqZLndtoIyJ",
            "https://drive.google.com/uc?export=view&id=1AMASVu3dK62KxiVmir0f9qqS2xgMKBR_",
            "https://drive.google.com/uc?export=view&id=1AMYKKb5VRor8DIuGu18jRRg9xzMsxQpc",
        ]
        data_list = [
            {
                "nama": "Andrian Agustinus Lumban Gaol",
                "nim": "121450090",
                "umur": "17 +",
                "asal": "Sidikalang",
                "alamat": "Lapas",
                "hobbi": "Nyari Hobi",
                "sosmed": "@andrialgaol",
                "kesan": "berwibawa",
                "pesan": "mangats terus bangg", 
            },
            {

                "nama": "Adisty Syawaida Ariyanto",
                "nim": "121450136",
                "umur": "21",
                "asal": "Metro",
                "alamat": "Metro",
                "hobbi": "Nonton film",
                "sosmed": "@adistisa_",
                "kesan": "kakaknya asik",
                "pesan": "sehat sehat kak",
            },
            {
                "nama": "Nabila Azhari",
                "nim": "121450029",
                "umur": "21",
                "asal": "Simalungun",
                "alamat": "Airan",
                "hobbi": "Menghitung",
                "sosmed": "@zhjung",
                "kesan": "kakaknya ramah dan baik ",
                "pesan": "semangat menghitungnya kak",
            },
            {
                "nama": "Nabilah Andika Fitriani",
                "nim": "121450129",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Kedaton",
                "hobbi": "Tidur",
                "sosmed": "@nabilaafrn",
                "kesan": "kakaknya baik dan manis",
                "pesan": "keep going kakk",
            },
            {
                "nama": "Danang Hilal Kurniawan",
                "nim": "122450085",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "TB 3 Asrama",
                "hobbi": "Belajar",
                "sosmed": "@dananghk_",
                "kesan": "multitalented dan soft spoken",
                "pesan": "semangat untuk semua mimpinya bang",
            },
            {
                "nama": "Farel Julio Akbar",
                "nim": "122450110",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Jalan Lapas",
                "hobbi": "Bebas",
                "sosmed": "@farel__julio",
                "kesan": "seru, asik, mau ngajarin kamii",
                "pesan": "makaih buat ilmunya bang",
            },
        
            {
                "nama": "Alvia Asrinda Br.Ginting",
                "nim": "122450077",
                "umur": "20",
                "asal": "Binjai",
                "alamat": "Korpri",
                "hobbi": "Nonton Windah",
                "sosmed": "@alviaginting",
                "kesan": "soft spoken dan positive vibes",
                "pesan": "semangat menjalani hari hari di smt 5 kak",
            },
            {
                "nama": "Dhafin Razaka Luthfia",
                "nim": "122450133",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Jalan nangka 1",
                "hobbi": "Olahraga",
                "sosmed": "@dhafinrzqri3",
                "kesan": "pendiem kelihatannya",
                "pesan": "semangat menjalani harinya bangg",
            },
            {
                "nama": "Elia meylani Simanjuntak",
                "nim": "122450026",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Korpri",
                "hobbi": "Main Batminton",
                "sosmed": "@meylanielia",
                "kesan": "asik,ramah,cantik,baik pol bintang 5/5",
                "pesan": "keep being awesome and positive vibes kakk mey",
            },

        ]
        display_images_with_data(gambar_urls, data_list)
    Ssd()

# Tambahkan menu lainnya sesuai kebutuhan
