import streamlit as st
from streamlit_option_menu import option_menu
import requests
from PIL import Image, ImageOps
from io import BytesIO

st.markdown("""<style>.centered-title {text-align: center;}</style>""",unsafe_allow_html=True)
st.markdown("<h1 class='centered-title'>BUKU KATING</h1>", unsafe_allow_html=True)

# bagian sini jangan diubah
def streamlit_menu():
    selected = option_menu(
        menu_title=None,
        options=[
            "Kesekjenan",
            "Baleg",
            "Senator",
            "Departemen PSDA",
            "Departemen MEDKRAF",
            "Departemen MIKFES",
            "Departemen Eksternal",
            "Departemen Internal",
            "Departemen SSD",
        ],
        icons=[
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
        ],
        default_index=0,
        orientation="horizontal",
        styles={
            "container": {"padding": "0!important", "background-color": "#fafafa"},
            "icon": {"color": "black", "font-size": "19px"},
            "nav-link": {
                "font-size": "15px",
                "text-align": "left",
                "margin": "0px",
                "--hover-color": "#eee",
            },
            "nav-link-selected": {"background-color": "#3FBAD8"},
        },
    )
    return selected

@st.cache_data
def load_image(url):
    response = requests.get(url)
    if response.status_code != 200:
        st.error(
            f"Failed to fetch image from {url}, status code: {response.status_code}"
        )
        return None
    try:
        img = Image.open(BytesIO(response.content))
        img = ImageOps.exif_transpose(img)
        img = img.resize((300, 400))
        return img
    except Exception as e:
        st.error(f"Error loading image: {e}")
        return None
    
@st.cache_data
def display_images_with_data(gambar_urls, data_list):
    images = []
    for i, url in enumerate(gambar_urls):
        with st.spinner(f"Memuat gambar {i + 1} dari {len(gambar_urls)}"):
            img = load_image(url)
            if img is not None:
                images.append(img)

    for i, img in enumerate(images):
        # Menggunakan Streamlit untuk menampilkan gambar di tengah kolom
        col1, col2, col3 = st.columns([1, 2, 1])
        with col2:
            st.image(img, use_column_width=True)

        if i < len(data_list):
            st.write(f"Nama: {data_list[i]['nama']}")
            st.write(f"NIM: {data_list[i]['nim']}")
            st.write(f"Umur: {data_list[i]['umur']}")
            st.write(f"Asal: {data_list[i]['asal']}")
            st.write(f"Alamat: {data_list[i]['alamat']}")
            st.write(f"Hobbi: {data_list[i]['hobbi']}")
            st.write(f"Sosial Media: {data_list[i]['sosmed']}")
            st.write(f"Kesan: {data_list[i]['kesan']}")
            st.write(f"Pesan: {data_list[i]['pesan']}")
            st.write("  ")
    st.write("Semua gambar telah dimuat!")
menu = streamlit_menu()

# BAGIAN SINI YANG HANYA BOLEH DIUBAH
if menu == "Kesekjenan":
    def kesekjenan():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1tDrYAHi-AO-kk3DlC3gobKEPCo_Gs6V8",
            "https://drive.google.com/uc?export=view&id=1LO3fr4cWDn433X0MIJwKHO795E0zMeLF",
            "https://drive.google.com/uc?export=view&id=1uuzrRrTMXAwxJHTJpP9Cz7PXDyOtKyZ7",
            "https://drive.google.com/uc?export=view&id=19eBqZ6McnDO9MEqvlqRlLjegc00Et3Zd",
            "https://drive.google.com/uc?export=view&id=169yDgQkr0eK9uPVaYQQdfOK2ofyet3km",
            "https://drive.google.com/uc?export=view&id=170-DKxBRl5vW1NGghFitHiS95weOp0lP",
        ]
        data_list = [
            {
                "nama": "Kharisma Gumilang",
                "nim": "121450142",
                "umur": "21",
                "asal": "Palembang",
                "alamat": "Jl.Pulau Damar",
                "hobbi": "Dengerin Musik",
                "sosmed": "@gumilangkharisma",
                "kesan": "Pembawaan Bang Gumilang sangat dewasa",  
                "pesan":"Semangat ya Bang dalam memajukan HMSD Adyatama!",
            },
            {   
                "nama": "Pandra Insani Putra Anwar",
                "nim": "121450137",
                "umur": "21",
                "asal":"Lampung Utara",
                "alamat": "Sukarame",
                "hobbi": "Main Gitar",
                "sosmed": "@pndrinsni27",
                "kesan": "Penuh dengan cerita unik dan menyenangkan",  
                "pesan":"Semoga hari-harinya bahagia selalu, Bang Pandra!",
            },
            {   
                "nama": "Meliza Wulandari",
                "nim": "121450065",
                "umur": "20",
                "asal":"Pagar Alam, Sumatera Selatan",
                "alamat": "Kota Baru",
                "hobbi": "Nonton Drakor",
                "sosmed": "@wulandarimeliza",
                "kesan": "Kakak yang baik, pintar, dan juga pembawaannya santai",  
                "pesan":"Semangat ya Kak Meliza dalam menjalani harinya",
            },      
            {
                "nama": "Putri Maulida Chairani",
                "nim": "121450050",
                "umur": "21",
                "asal":"Payakumbuh, Sumatera Barat",
                "alamat": "Gg. Nangka 4",
                "hobbi": "Dengerin Bang Pandra Main Gitar",
                "sosmed": "@ptrimaulidaaa_",
                "kesan": "Baik sekali, sangat menghargai orang yang sedang berbicara",  
                "pesan":"Semoga hal-hal baik selalu mengelilingi Kak Putri!",
            },       
            {   
                "nama": "Hartiti Fadilah",
                "nim": "121450031",
                "umur": "21",
                "asal":"Palembang",
                "alamat": "Pemda",
                "hobbi": "Nyanyi",
                "sosmed": "@htrpdla",
                "kesan": "Kakak yang lucu dan juga cantik",  
                "pesan":"Semoga banyak hal menyenangkan hadir dalam kehidupan Kakak!",
            },    
            {
                "nama": "Nadilla Andhara Putri",
                "nim": "121450003",
                "umur": "21",
                "asal":"Metro, Lampung",
                "alamat": "Kota Baru",
                "hobbi": "Main Bola, Belajar",
                "sosmed": "@nadilaandr26",
                "kesan": "Kakak yang tegas namun asyik saat berbincang",  
                "pesan":"Terima kasih Kak Nadilla sudah berbagi tips jadi bendahara yang baik!",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    kesekjenan()


elif menu == "Baleg":
    def Baleg():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1S3lh7hMqXJojczBWUcQWTX4Dfi8jK1OV",
            "https://drive.google.com/uc?export=view&id=1Rp1Zfrtrmh_1lCvJAZm10hpp23z9lbYO",
            "https://drive.google.com/uc?export=view&id=1RjQrnIomGYsUfyzoHJp89fZADIddhni1",
            "https://drive.google.com/uc?export=view&id=1Ru4-0Bp_bqmnA20GJr67BWlGgtRRIXRQ",
            "https://drive.google.com/uc?export=view&id=1RvO_X4WPLIFAfuI8c5DLBp9d8MawJeMu",
            "https://drive.google.com/uc?export=view&id=1S7N5e_ytYj_-eVT5l6f7XqmRP_PO0BV6",
            "https://drive.google.com/uc?export=view&id=1S6Q1oPCSaYt5gigTFKI96SooA4Oj7rcr",
            "https://drive.google.com/uc?export=view&id=1RxA8BsofUjOtBcN9zWw_Z_6JWAv316il",
            "https://drive.google.com/uc?export=view&id=1S6Hkmph-XUU3H2QbkofP_69yn33-_1e1",   
            "https://drive.google.com/uc?export=view&id=1S6VtFamkRdyK6Ayo0JlltfJ9GvMZtl6W",
            "https://drive.google.com/uc?export=view&id=1RqEn0HTpF92YWZBfqvr48KXYruWP7fIi",
        ] 
        data_list = [
            {
                "nama": "Tri Murniya Ningsih",
                "nim": "121450038",
                "umur": "21",
                "asal": "Bogor",
                "alamat": "Raden Saleh",
                "hobbi": "Tanya sama GPT",
                "sosmed": "@trimurniaa",
                "kesan": "Sangat seru dalam berbincang dan ramah sekali",
                "pesan": "Suka sekali dengan keramahan Kak Niya, Semoga bisa akrab dengan Kak Niya",
            },
            {
                "nama": "Annisa Cahyani Surya",
                "nim": "121450114",
                "umur": "21",
                "asal": "Tangerang Selatan",
                "alamat": "Way Huwi",
                "hobbi": "Puasa Senin Kamis",
                "sosmed": "@annisacahyanisurya",
                "kesan": "Kakak yang berbicara dengan nada lembut dan sangat baik",
                "pesan": "Semangat ya kak dalam menjalani harinya, aura kakak positif sekali!", 
            },
            {
                "nama": "Wulan Sabina",
                "nim": "121450150",
                "umur": "21",
                "asal": "Medan",
                "alamat": "Raden Saleh",
                "hobbi": "Menonton film",
                "sosmed": "wlsbn0",
                "kesan": "Paras kakak cantik sekali dan kosakatanya sangat baik dalam berbicara",
                "pesan": "Semoga saya bisa juga jadi keren dan cantik seperti Kak Wulan", 
            },
            {
                "nama": "Anisa Dini Amalia",
                "nim": "121450021",
                "umur": "20",
                "asal": "Tangerang",
                "alamat": "Jati Agung",
                "hobbi": "Baca Webtoon",
                "sosmed": " @anisadini10",
                "kesan": "Kakak yang pendiam namun ketika berbicara sangat seru",
                "pesan": "Wah, saya lupa minta rekomendasi webtoon dari kakak! Semangat terus, Kak!", 
            },
            {
                "nama": "Claudhia Angeliani",
                "nim": "121450124",
                "umur": "21",
                "asal": "Lampung Timur",
                "alamat": "Lampung Timur",
                "hobbi": "Baca Jurnal",
                "sosmed": " @dylebee",
                "kesan": "Kakak yang sangat baik, ramah, dan juga cantik",
                "pesan": "Wah, semangat baca jurnalnya Kak!", 
            },
            {
                "nama": "Muhammad Fachrul Aditya",
                "nim": "121450156",
                "umur": "22",
                "asal": "Surakarta",
                "alamat": "Sukarame",
                "hobbi": "Sholat Malam",
                "sosmed": "@fhrul.pdf",
                "kesan": "Terlihat sangat baik dan tidak sombong",
                "pesan": "Sedih sekali tidak sempat berwawancara dengan Abang karena waktu itu Abang pulang duluan", 
            },
            {
                "nama": "Feryadi Yulius ",
                "nim": "122450087",
                "umur": "20",
                "asal": "Padang",
                "alamat": "Belwis",
                "hobbi": "Sholat Dhuha",
                "sosmed": "@fer_yulius",
                "kesan": "Seperti sering melihat Bang Fery, Baik, Sangat jelas ketika menyampaikan pendapat",
                "pesan": "Semoga bisa terus Sholat Dhuha setiap hari ya Bang", 
            },
            {
                "nama": "Renisha Putri Giani",
                "nim": "122450079",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Teluk Betung",
                "hobbi": "Baca Al-Qur'an",
                "sosmed": "@fleurnsh",
                "kesan": "Cantik sekali dan terlihat sangat anggun",
                "pesan": "Kak Renisha semangat ya dalam menjalani perkuliahannya! Semoga hobinya bisa nular ke saya, Masyaallah.",
            },
            {
                "nama": "Mirzan Yusuf Rabbani",
                "nim": "122450118",
                "umur": "20",
                "asal": "Jakarta",
                "alamat": "Korpri",
                "hobbi": "Main Kucing",
                "sosmed": "@myrrinn",
                "kesan": "Bang Mirzan lucu ketika berbicara dan terlihat baik",
                "pesan": "Semangat, Bang Mirzan! Semoga harinya selalu cerah", 
            },
            {
                "nama": "Jeremia Susanto",
                "nim": "122450022",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Bilabong",
                "hobbi": "Cerita",
                "sosmed": "@jeremia_s_",
                "kesan": "Sangat seru, menggembirakan saat berbicara",
                "pesan": "Terima kasih, Bang Jeremia sudah buat wawancaranya seru sekali", 
            }, 
            {
                "nama": " Berliana Enda Putri",
                "nim": "122450065",
                "umur": "20",
                "asal": "Sumatera Barat",
                "alamat": "Way Huwi",
                "hobbi": "Baca Buku, Ngoding, Ibadah",
                "sosmed": "@berlyyanda",
                "kesan": "Kakak yang lucu dan sangat menggembirakan ketika berbicara",
                "pesan": "Semoga banyak hal menggembirakan hadir dalam hari Kakak!", 
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Baleg()

elif menu == "Senator":
    def senator():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=194WIXQjHxMb8j-XQNpURCOcHZW4rHcv5",
            "https://drive.google.com/uc?export=view&id=1S7tuvpHtbj3pYzyWH__LYkM3rVgyp39I",
        ]
        data_list = [
            {
                "nama": "Anissa Luthfi Alifia",
                "nim": "121450093",
                "umur": "22",
                "asal": "Lampung Tengah",
                "alamat": "Kost Putri Rahayu",
                "hobbi": "Dengerin bintang nyanyi",
                "sosmed": "@anissalutfi_",
                "kesan": "Kak Upi asyik sekali dan penyampaiannya sangat jelas serta cerdas",
                "pesan": "Senang sekali, ternyata Kakak ingat saya! Semoga kita bisa semakin akrab ya Kak", 
            },
            {
                "nama": "Rian Bintang Wijaya",
                "nim": "122450094",
                "umur": "20",
                "asal": "Palembang",
                "alamat": "Kota Baru",
                "hobbi": "Nyanyi",
                "sosmed": "@bintangtwinkle",
                "kesan": "Bang Bintang sangat cerdas dalam menyampaikan pendapat, asyik dalam berbicara",
                "pesan": "Semangat dalam menggapai cita-citanya ya Bang Bintang",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    senator()

elif menu == "Departemen PSDA":
    def Psda():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1V5HNXfrs6zI83NNPJG2hLhr-ZDGPWRIR", 
            "https://drive.google.com/uc?export=view&id=1DyPltr-UF37vGm3CrsaS6qvjsmLppoVS", 
            "https://drive.google.com/uc?export=view&id=1aNRs3bAjixwiUs02otyDvqVkKrQU44BG",
            "https://drive.google.com/uc?export=view&id=1aaSB76pIH5GQrL6H4goW2_do7V---Dr9",
            "https://drive.google.com/uc?export=view&id=1SWLwG6t0s8In3a-LDYgC6YnG2ZF5SyYB",
            "https://drive.google.com/uc?export=view&id=1dF9CPCf5msMg5Z-HMqTTbS_7LbeV34uV",
            "https://drive.google.com/uc?export=view&id=1hr4_xKcAJvHlCFsTBb0XFG8Cr9AshQd1",
            "https://drive.google.com/uc?export=view&id=129kNKW3AUSZP7swvgM_mR4CRtWZspfir",
            "https://drive.google.com/uc?export=view&id=10udp3IjSKHGcF7ZT3ZoajG1XepZcrXp-",
            "https://drive.google.com/uc?export=view&id=1GuTULGfEImlS850_Q1bwPhYEXORgPacu",
            "https://drive.google.com/uc?export=view&id=1MOAXUxXir15ZEzc-hbj5Fx_Q7jYlyiZB",
            "https://drive.google.com/uc?export=view&id=1nQon_NOicM5ACM0FZmKeogkIklo3GKRq",
            "https://drive.google.com/uc?export=view&id=1OFnXyHP3QkLWRhR1kB9OB0YtFFpvHRYA",
            "https://drive.google.com/uc?export=view&id=15aSLm4NXgJHeIGkqVGwmbTfb7492NG1u",
            "https://drive.google.com/uc?export=view&id=1eaLxxrfaATMdiaJrbSvIAXHqI6Gb_yki",
            "https://drive.google.com/uc?export=view&id=1KCYceP4ANuofHvu4_61b2N82blRIJSNB",
            "https://drive.google.com/uc?export=view&id=1YCcuNlov9ME2o7xbQin3rVfMNnor5YU-",
            "https://drive.google.com/uc?export=view&id=1C0EzbZ_FAbIUXcstV_lNxJS_XaKlIOs8",
            "https://drive.google.com/uc?export=view&id=1ZkItUE5pUXtR_DHM2yXPX5xl5X7PVPAG",
            "https://drive.google.com/uc?export=view&id=1PbH8VwC1oqDdlgshog7T0U4Q85Zj8Zy4",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
        ] 
        data_list = [
            {
                "nama": "Ericson Chandra Sihombing",
                "nim": "121450026",
                "umur": "21",
                "asal": "Bekasi",
                "alamat": "Khobam",
                "hobbi": "Travelling",
                "sosmed": "@ericsonchandra99",
                "kesan": "Kalimat-kalimat yang disampaikan Bang Ericson sangat berbobot dan bermanfaat bagi saya",
                "pesan": "Keren sekali, Bang Ericson! Semangat dalam menjalani kehidupan sehari-harinya!", 
            },
            {
                "nama": "Elisabeth Claudia Simanjuntak",
                "nim": "122450123",
                "umur": "20",
                "asal": "Tangerang",
                "alamat": "Owen Kost",
                "hobbi": "Bernapas",
                "sosmed": "@celisabethh_",
                "kesan": "Super baik dan tidak sombong, senang bercanda gurau",
                "pesan": "Kak Elisabeth, saya harap kita bisa akrab kedepannya.. Semangat terus, Kakak!",
            },
            {
                "nama": "Nisrina Nur Afifah",
                "nim": "122450052",
                "umur": "19",
                "asal": "Bekasi",
                "alamat": "Sukarame",
                "hobbi": "Menonton",
                "sosmed": "@afifahhnsrn",
                "kesan": "Cantik sekali dan berpakaian sangat rapih",
                "pesan": "Kak Fifah, Semangat dalam menjalani berbagai tugasnya! Semoga dipermudah dalam mengejar cita-cita.",
            },
            { 
                "nama": "Deyvan Loxefal", 
                "nim": " 121450148 ", 
                "umur":  "21", 
                "asal":"Pekanbaru", 
                "alamat": "Jl. Pulau Damar", 
                "hobbi": "Belajar", 
                "sosmed": "@depanloo", 
                "kesan": "Bang Deyvan sungguh menyenangkan dan mampu melelehkan suasana",   
                "pesan":"Semoga senyuman selalu terpancar dalam Bang Deyvan setiap harinya. Semangat, Bang Devyan!",
            },
            {
                "nama": "M. Farhan Athaulloh",
                "nim": "121450117",
                "umur": "21",
                "asal":"Lampung",
                "alamat": "Kota Baru",
                "hobbi": "Menolong",
                "sosmed": "@mfarhan.ath",
                "kesan": "Sangat seru saat berbincang dan tidak sombong",  
                "pesan":"Maju terus, Bang! Semoga makin sukses dalam kehidupannya.",
            },
            {
                "nama": "Allya Nurul Islami Pasha",
                "nim": "122450033",
                "umur": "20",
                "asal":"Sumatera Barat",
                "alamat": "Gang Perwira, Belwis",
                "hobbi": "Keliling Lampung",
                "sosmed": "@allyaislami_",
                "kesan": "Kakak yang cantik dan sangat asyik saat berbincang bersama",  
                "pesan":"Semoga hari-hari Kak Allya selalu beruntung dan dikeliling orang baik!",
            },
            {
                "nama": "Eksanty Febriana Sukma Islamiaty",
                "nim": "122450001",
                "umur": "20",
                "asal":"Bekasi",
                "alamat": "Rajabasa",
                "hobbi": "Nunggu Ngumpulin Tugas Kurang dari 55 detik",
                "sosmed": "@eksantyfebriana",
                "kesan": "Ramah sekali dan  dan sering bersenda gurau sehingga mencairkan suasana",  
                "pesan": "Semangat ya Kak Eksanty dalam menjalani kehidupannya! Saya sering menyapa Kakak di ruang asprak fisika, Semoga bisa akrab dengan Kakak",
            },
            {
                "nama": "Farahanum Afifah Ardiansyah",
                "nim": "122450056",
                "umur": "20",
                "asal":"Padang",
                "alamat": "Gya Kost",
                "hobbi": "Tidur",
                "sosmed": "@farahanumafifahh",
                "kesan": "Sangat baik dan juga asyik saat berbincang",  
                "pesan":"Semangat selalu untuk Kak Hanum! Terima kasih sudah membantu saya saat genting waktu itu",
            },
            {
                "nama": "Ferdy Kevin Naibaho",
                "nim": "122450107",
                "umur": "19",
                "asal":"Medan",
                "alamat": "Jl. Pangeran Senopati Raya",
                "hobbi": "Review Journal",
                "sosmed": "@ferdy_kevin",
                "kesan": "Terlihat sedikit serius namun ternyata asyik dan senang bersenda gurau",  
                "pesan":"Wah, Semangat ya Bang Ferdy! Sukses selalu untuk kedepannya",
            },
            {
                "nama": "M. Deriansyah Okutra",
                "nim": "122450101",
                "umur": "19",
                "asal":"Kayu Agung",
                "alamat": "Jl. Pagar Alam Kedaton",
                "hobbi": "Main-main",
                "sosmed": "@dransyh_",
                "kesan": "Abang yang baik dan juga lucu",  
                "pesan":"Jangan lupa istirahat yang cukup, Bang Deri!",
            },
            {
                "nama": "Oktavia Nurwenda Puspita Sari",
                "nim": "122450041",
                "umur": "20",
                "asal":"Lampung Timur",
                "alamat": "Way Huwi",
                "hobbi": "Memasak",
                "sosmed": "@_oktavianrwnda_",
                "kesan": "Kakak yang lucu dan berparas manis",  
                "pesan":"Semoga Kakak selalu dikelilingi hal baik!",
            },
            { 
                "nama": "Ibnu Farhan Al-Ghifari", 
                "nim": " 121450121 ", 
                "umur":  "21", 
                "asal":" Kerinci, Jambi  ", 
                "alamat": "Khobam", 
                "hobbi": "Game Online", 
                "sosmed": "@al_ghifari032", 
                "kesan": "Abang yang tinggi dan juga baik",   
                "pesan":"K",
            },
            { 
                "nama": "Johannes Krisjon Silitonga", 
                "nim": "122450043", 
                "umur": "19", 
                "asal":"Tangerang", 
                "alamat": "Jl. Lapas Raya", 
                "hobbi": "Pacaran sama Abeth", 
                "sosmed": "@johanneskrisjnnn", 
                "kesan": "Abang yang sangat ramah, baik, dan sangat bisa mencairkan suasana",   
                "pesan":"Bang Johannes, semoga bisa selalu bahagia dalam hidupnya dan dijauhi dari hal-hal buruk!", 
            },
            { 
                "nama": "Kemas Veriandra Ramadhan", 
                "nim": "122450016", 
                "umur": "19", 
                "asal":"Bekasi", 
                "alamat": "Kojo Golf UIN", 
                "hobbi": "Gitar dan Game", 
                "sosmed": "@kemasverii", 
                "kesan": "Bang Kemas sangat pintar",   
                "pesan":"Wah, Saya sering kagum dengan kepintaran Bang Kemas! Sukses selalu, Bang!", 
            },
            { 
                "nama": "Leonard Andreas Napitupulu", 
                "nim": "121450153", 
                "umur": "21", 
                "asal":"Medan", 
                "alamat": "Khobam", 
                "hobbi": "Belajar", 
                "sosmed": "@lndr.__", 
                "kesan": "Abang yang sangat lembut saat berbicara",   
                "pesan":"Semoga hari-hari Abang bisa selalu menyenangkan!", 
            },
            { 
                "nama": "Presilia", 
                "nim": "122450081", 
                "umur": "20", 
                "asal":"Bekasi", 
                "alamat": "Kota Baru", 
                "hobbi": "Dengerin Frank Ocean", 
                "sosmed": "@presiliamy", 
                "kesan": "Kak Presilia sangat cantik",   
                "pesan":"Semangat, Kak! Semoga bisa menggapai cita-citanya.", 
            },
            { 
                "nama": "Sahid Maulana", 
                "nim": "122450109", 
                "umur": "21", 
                "asal":"Depok, Jawa Barat", 
                "alamat": "Jl. Airan Raya, Kost Shofa Marwah", 
                "hobbi": "Denger musik dan main game", 
                "sosmed": "@sahid_maul19", 
                "kesan": "Bang Sahid sangat berbakat dan baik sekali juga super ramah",   
                "pesan":"Semoga Bang Sahid bisa selalu jadi pribadi yang baik hati dan ramah. Semangat terus ya Bang Sahid!", 
            },
            {
                "nama": "Gede Moena",
                "nim": "121450014",
                "umur": "21",
                "asal":"Bekasi",
                "alamat": "Korpri Raya, Jl. Sakura",
                "hobbi": "Ngejar Nilai A",
                "sosmed": "@gedemoenaa",
                "kesan": "Abang yang sedikit pendiam namun asyik saat berbincang",  
                "pesan":"Sukses terus untuk Bang Gede! ",
            },
            {
                "nama": "Jaclin Alcavella",
                "nim": "122450015",
                "umur": "19",
                "asal":"Sumatera Selatan",
                "alamat": "Korpri",
                "hobbi": "Berenang",
                "sosmed": "@jaclinalcv_",
                "kesan": "Kak Jaclin sangat ramah dan tidak sombong",  
                "pesan":"Wah, Saya harap bisa berenang bareng dengan Kak Jaclin!",
            },
            {
                "nama": "Syalaisha Andini Putriansyah",
                "nim": "122450111",
                "umur": "21",
                "asal":"Tangerang",
                "alamat": "Sukarame",
                "hobbi": "Baca",
                "sosmed": "@syalaisha.i__",
                "kesan": "Kak Dini super baik dan juga lemah lembut",  
                "pesan":"Terima kasih, Kak Dini sering bantu saya saat Praktikum ADS!",
            },
            { 
                "nama": "Rafa Aqilla Jungjunan", 
                "nim": "122450142", 
                "umur": "20", 
                "asal":"Pekanbaru", 
                "alamat": "Belwis", 
                "hobbi": "Baca Webtoon", 
                "sosmed": "@rafaaqilla", 
                "kesan": "Abang yang berbicara lembut",   
                "pesan":"Sayang sekali tidak sempat berbincang dan berfoto dengan Abang karena Abang izin pulang duluan", 
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Psda()

elif menu == "Departemen MEDKRAF":
    def Medkraf():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1EL-_93l8ULYXPbHmLgI4u2DN0fwMbWEh", 
            "https://drive.google.com/uc?export=view&id=1DydoYPXYG12-TrJ8lySdNQC-YirViPVv", 
            "https://drive.google.com/uc?export=view&id=1FEeu2yB9uX2DfBfr368bOaw69lYIy0oq", 
            "https://drive.google.com/uc?export=view&id=1EgBUuI54QiIicfVQddNC0r9rTLciH6ND", 
            "https://drive.google.com/uc?export=view&id=1E9o7tc0-_nnC2BySv4YDNIy8zq0AuWCC", 
            "https://drive.google.com/uc?export=view&id=1_h-3z9q-enSW5El0xPfAZglBwWEcTm5Q",
            "https://drive.google.com/uc?export=view&id=1FV0EZE2m8rmdNK_RfuaEfzwpMl3DOa8k",
            "https://drive.google.com/uc?export=view&id=1F1EXEo35QEk4gZN70RSkhqz_1A1Yrs5J",
            "https://drive.google.com/uc?export=view&id=1FSTMs1n3WnO-O8hnhxkThzMgUK0C5Qwq",
            "https://drive.google.com/uc?export=view&id=1EoRxtDwdFCCpwsrfvbXwCWa3WaPHnJJR",
            "https://drive.google.com/uc?export=view&id=1EVOT14NbKuHKHIa8W8ICGGLvoAEL1fJL",
            "https://drive.google.com/uc?export=view&id=1Ed6ZERe-xfgu70xXd3LnW5jOmxvMuWNa",
            "https://drive.google.com/uc?export=view&id=1ETkIlkvpOHtY3P0U0Uk0QYKCT7qvXjgk",
            "https://drive.google.com/uc?export=view&id=1EFdd3O8TCFO8F0HOzWLR6alVNOenL_Bq",
            "https://drive.google.com/uc?export=view&id=1EzAiiB3NgMN61qCSK_k-25MDXELh155u",          
        ] 
        data_list = [
            {
                "nama": "Wahyudiyanto",
                "nim": "121450040",
                "umur": "22",
                "asal": "Makassar",
                "alamat": "Sukarame",
                "hobbi": "Nonton",
                "sosmed": "-",
                "kesan": "Sangat pintar dan cerdas dalam menjelaskan jawaban",
                "pesan": "Semangat terus Bang Tao!",
            },
            {
                "nama": "Elok Fiola",
                "nim": "122450051",
                "umur": "19",
                "asal": "Bandar Lampung",
                "alamat": "Bandar Lampung",
                "hobbi": "Editing",
                "sosmed": "@elokfiola",
                "kesan": "Cantik sekali dan ramah",
                "pesan": "Semoga hari-hari Kak Elok juga seelok Kakak!", 
            },
            {
                "nama": "Muhammad Kaisar Firdaus ",
                "nim": " 121450135",
                "umur": "21",
                "asal": "Pesawaran",
                "alamat": "Pulau Damar",
                "hobbi": "Lagi Nyari",
                "sosmed": " @dino_kiper",
                "kesan": "Abang yang sangat tinggi dan juga cerdas",
                "pesan": "Semangat selalu ya Bang Kaisar!", 
            },
            {
                "nama": "Muhammad Arsal Ranjana Putra",
                "nim": "121450111",
                "umur": "21",
                "asal": "Depok",
                "alamat": "Nangka 4",
                "hobbi": "Ngoding",
                "sosmed": "@arsal.utama",
                "kesan": "Abang yang tampan dan tidak sombong",
                "pesan": "Sukses terus ya Bang Arsal!", 
            },
            {
                "nama": "Cintya  Bella",
                "nim": "122450066",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Teluk",
                "hobbi": "Ngegym",
                "sosmed": "@cintyabella28",
                "kesan": "Cantik sekali dan berpakaian sangat rapih juga trendy",
                "pesan": "Semoga Kak Cibel selalu sehat dan bahagia! Semangat Kakak!", 
            },
            {
                "nama": "Patricia Leondra Diajeng Putri ",
                "nim": "122450050",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Jatimulyo",
                "hobbi": "Nonton Film",
                "sosmed": "@patriciadiajeng",
                "kesan": "Sangat ramah dan cantik sekali",
                "pesan": "Terima kasih, Kak Cia selalu banyak membantu saat Praktikum ADS! Sukses selalu", 
            },
            {
                "nama": "Rahma Neliyana",
                "nim": "122450036",
                "umur": "20",
                "asal": "Lampung",
                "alamat": "Sukarame",
                "hobbi": "Baca Coding",
                "sosmed": "@rahmanellyana",
                "kesan": "Sangat seru dan bisa mencairkan suasana",
                "pesan": "Semangat teru ya Kak Neli!", 
            },
            {
                "nama": "Try Yani Rizki Nur Rohmah ",
                "nim": "122450020",
                "umur": "20",
                "asal": "Lampung Barat",
                "alamat": "Korpri",
                "hobbi": "Bernyanyi dan Menonton",
                "sosmed": "@tryyaniciaaa",
                "kesan": "Cantik sekali dan juga asyik",
                "pesan": "Kak Try, Terima kasih ya sudah ajak saya bikin konten bareng!", 
            },
            {
                "nama": "Gymnastiar Al Khoarizmy",
                "nim": "122450096",
                "umur": "20",
                "asal": "Serang",
                "alamat": "Lapangan Golf UIN",
                "hobbi": "Baca Komik",
                "sosmed": "@jimnn.as",
                "kesan": "Sangat lucu dan juga baik",
                "pesan": "Semangat ya untuk Bang Gym!", 
            },
            {
                "nama": "Nasywa Nur Afifah ",
                "nim": "122450125",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Jalan Durian 1 Pemda",
                "hobbi": "Nonton Drakor",
                "sosmed": "@nsywanaf",
                "kesan": "Kakak yang cantiknya terlihat sangat adem",
                "pesan": "Semoga hari kakak selalu menggembirakan!", 
            },
            {
                "nama": "Abit Ahmad Oktarian",
                "nim": "122450042",
                "umur": "19",
                "asal": "Bandar Lampung",
                "alamat": "Rajabasa, Labuhan Dalam",
                "hobbi": "Ngoding, Gaming",
                "sosmed": "@abitahmad",
                "kesan": "Sangat lucu dan cerdas sekali",
                "pesan": "Semangat dalam menggapai cita ya Bang Abit", 
            },
            {
                "nama": "Akmal Faiz Abdillah",
                "nim": "122450114",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Perumahan Griya Sukarame",
                "hobbi": "Main HP",
                "sosmed": "@_akmal.faiz",
                "kesan": "Bang Akmal sangat ramah",
                "pesan": "Semoga sukses selalu ya Bang Akmal!", 
            },
            {
                "nama": "Hermawan Manurung ",
                "nim": "122450069",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Dekat Jalan Tol (Wisma Hana Hani) ",
                "hobbi": "Bengong/Membaca Buku",
                "sosmed": "@hermawan.mnrng",
                "kesan": "Sangat lucu dan mmapu mencairkan suasana",
                "pesan": "Semangat ya Bang Hermawan dalam kuliahnya!", 
            },
            {
                "nama": "Khusnun Nisa",
                "nim": "122450078",
                "umur": "20",
                "asal": "Lampung Selatan",
                "alamat": "Muara Piluk",
                "hobbi": "Mengerjakan Tugas",
                "sosmed": "@khusnun_nisa335",
                "kesan": "Kakak yang sangat lemah lembut",
                "pesan": "Semangat selalu untuk Kak Khusnun!", 
            },
            {
                "nama": "Priska Silvia Ferantiana",
                "nim": "122450053",
                "umur": "20",
                "asal": "Palembang",
                "alamat": "Jalan Nangka 2",
                "hobbi": "Baca Novel yang Bikin Nangis",
                "sosmed": "@prskslv",
                "kesan": "Kakak sangat lucu dan ramah",
                "pesan": "Semoga hari Kakak selalu banyak hal baik!", 
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Medkraf()

elif menu == "Departemen MIKFES":
    def Mikfes():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1yIbabgRvAxQjYfQARS6GuzbV7LtS_jJT",
            "https://drive.google.com/uc?export=view&id=1z04e4NllfS_moqxQgv2q_n6-qYovy9uP",
            "https://drive.google.com/uc?export=view&id=1pVSL1dDyzdxD9r9MDYZHAV4iA-CSzg56",
            "https://drive.google.com/uc?export=view&id=1UTCgYMdQlICYxaZU26qYMDoibwtv1F2e",
            "https://drive.google.com/uc?export=view&id=1DY8qV7tV0u8dNNgbH4KaSfozgDxrpZxw",
            "https://drive.google.com/uc?export=view&id=1xan2YSABjmXdlfzutnsgJ6vmHCH531vt",
            "https://drive.google.com/uc?export=view&id=1PKn6Mmgf9_zRn13wvN4-_wgf9JyK5KBX",
            "https://drive.google.com/uc?export=view&id=1jUVcK6WMnV3V-P7YgLe0gJw_YAdlPO1g",
            "https://drive.google.com/uc?export=view&id=16s7opqy9uhvarMn9Oi380D6OS-RbsS1g",
            "https://drive.google.com/uc?export=view&id=1LGheDP_h-O6kWHZ2io7Wpa51UI2tgdZz",
            "https://drive.google.com/uc?export=view&id=12HBknVEG-f3J4iKNfMX0dqD0x236iBxx",
            "https://drive.google.com/uc?export=view&id=1G7Cf41oOiJmUkWM7UYo_h8yjugCBaGV1",
            "https://drive.google.com/uc?export=view&id=1EoSuPSH3XWvr0N6JT-JcgXFezWoxVaOE",
            "https://drive.google.com/uc?export=view&id=1fnWcA1hNVyJRlUI_cv3uKPFQJku2IBm6",
            "https://drive.google.com/uc?export=view&id=1aedMvtmgOf7kwD-Yk0FqrBoqdXphEn9-",
            "https://drive.google.com/uc?export=view&id=1t8lVr_NFqeQNvw8OmAhHlBOp2TUxgCQA",
            "https://drive.google.com/uc?export=view&id=1-Yi-E2j8j8XSVrFvqwT-QjtvSZ3BsWB3",
            "https://drive.google.com/uc?export=view&id=12LruYNhd-1aj1qV8RbKZUCczmjVh3yqB",
            "https://drive.google.com/uc?export=view&id=1jGyCuyGj7xwWZFZHGk3Rxo0J9qrcLx91",
        ] 
        data_list = [
            {
                "nama": "Rafi Fadhlillah",
                "nim": "121450143",
                "umur": "21 Tahun",
                "asal": "Lubuk Linggau",
                "alamat": "Jl. Nangka 4",
                "hobbi": "Olahraga",
                "sosmed": "@rafadhilillahh13",
                "kesan": "Sangat cerdas dan tampan",
                "pesan": "Sukses selalu untuk Bang Rafi!",
            },
            {
                "nama": "Annisa Novantika",
                "nim": "121450005",
                "umur": "21 Tahun",
                "asal": "Lampung Utara",
                "alamat": "Jl. Pulau Sebesi, Sukarame",
                "hobbi": " Memasak",
                "sosmed": "@anovavona",
                "kesan": "Cantik sekali, murah senyum, ramah, dan juga wangi",
                "pesan": "Semoga hari Kakak selalu menyenangkan!",
            },
            {
                "nama": "Natanael Oktavianus Partahan Sihombing ",
                "nim": "121450107",
                "umur": "20 Tahun",
                "asal": "Jakarta",
                "alamat": "Kemiling ",
                "hobbi": "Membuka Wisata HMSD",
                "sosmed": "@natanaeloks",
                "kesan": "Abang yang baik dan murah senyum",
                "pesan": "Bahagia selalu untuk Bang Natan!",
            },
            {
                "nama": "Abdurrahman Al-Atsary",
                "nim": "121450128",
                "umur": "23 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "Perumnas Way Kandis",
                "hobbi": " Membaca",
                "sosmed": "@rahmn_abdr",
                "kesan": "Sangat pintar dan baik",
                "pesan": "Sukses selalu, Bang!",
            },
            {
                "nama": "Ahmad Sahidin Akbar",
                "nim": "122450044",
                "umur": " 20",
                "asal": "Tulang Bawang",
                "alamat": " Sukarame",
                "hobbi": "Olahraga",
                "sosmed": "@sahid22__",
                "kesan": "Abang yang murah senyum dan baik",
                "pesan": "Maju terus, Bang Sahidin!",
            },
            {
                "nama": "Fadhil Fitra Wijaya",
                "nim": "122450082",
                "umur": "20 Tahun",
                "asal": "Bekasi",
                "alamat": "Teluk Betung ",
                "hobbi": "Main Game",
                "sosmed": "@fadhilfwee",
                "kesan": "Abang yang sangat keren dan berpakaian rapih",
                "pesan": "Wah, saya sangat kagum dengan outfit Bang Fadhil!",
            },
            {
                "nama": "Muhammad Regi Abdi Putra Amanta",
                "nim": " 122450031",
                "umur": "19 Tahun",
                "asal": "Palembang",
                "alamat": "Jl. Permadi Sukarame  ",
                "hobbi": "Main Game",
                "sosmed": "@mregiiii_",
                "kesan": "Abang yang sangat ramah dan murah senyum",
                "pesan": "Semoga Bang Regi bahagia selalu",
            },
            {
                "nama": "Syalaisha Andina Putriansyah",
                "nim": "122450121",
                "umur": "21 Tahun",
                "asal": "Tangerang",
                "alamat": "Gg Yudhistira ",
                "hobbi": "Baca Novel",
                "sosmed": "@dkselsd_31",
                "kesan": "Kakak yang anggun",
                "pesan": "Semangat kakak! Semoga dikelilingi hal-hal baik!",
            },
            {
                "nama": "Anwar Muslim",
                "nim": "122450117",
                "umur": "21 Tahun",
                "asal": "Bukittinggi",
                "alamat": "Korpri ",
                "hobbi": " ML (Machine Learning)",
                "sosmed": "@here.am.ai",
                "kesan": "Baik dan sangat ramah",
                "pesan": "Sukses selalu untuk Bang Anwar",
            },
            {
                "nama": "Deva Anjani Khayyuninafsyah",
                "nim": "122450014",
                "umur": "21 Tahun",
                "asal": " Bandar Lampung",
                "alamat": "Kemiling",
                "hobbi": "Menonton Film",
                "sosmed": "@anjaniiidev",
                "kesan": "Kakak sangat cantik dan wangi",
                "pesan": "Semoga lancar terus kak untuk perkuliahannya",
            },
            {
                "nama": "Dinda Nababan",
                "nim": "122450120",
                "umur": "20 Tahun",
                "asal": "Medan",
                "alamat": "Jl. Lapas",
                "hobbi": "Main Game",
                "sosmed": "@dindanababan_",
                "kesan": "Sangat ramah dan super baik hati",
                "pesan": "Semangat selalu untuk Kak Dinda",
            },
            {
                "nama": "Marleta Cornelia Leander",
                "nim": "122450092",
                "umur": "20 Tahun",
                "asal": "Depok, Jawa Barat",
                "alamat": "Gg. Nangka 3",
                "hobbi": "Liatin Jurnal",
                "sosmed": "@marletacornelia",
                "kesan": "Cantik dan tidak sombong",
                "pesan": "Sehat selalu ya untuk Kak Marleta",
            },
            {
                "nama": "Rut Junita Sari Siburian",
                "nim": "122450103",
                "umur": "20 Tahun",
                "asal": "Batam, Kep.Riau",
                "alamat": "Gg. Nangka 3",
                "hobbi": "Resume Jurnal",
                "sosmed": "@junitaa_0406",
                "kesan": "Baik hati dan tidak sombong",
                "pesan": "Sukses ya untuk Kakak!",
            },
            {
                "nama": "Syadza Puspadari Azhar",
                "nim": " 122450072",
                "umur": "20 Tahun",
                "asal": "Palembang",
                "alamat": "Belwis ",
                "hobbi": "Membaca",
                "sosmed": "@puspadrr",
                "kesan": "Kak Puspa sangat baik dan pintar juga super ramah dan asyik",
                "pesan": "Terima kasih, Kak Puspa sudah banyak menyemangati saya! Semangat selalu untuk Kak Puspa!",
            },
            {
                "nama": "Aditya Rahman",
                "nim": "122450113",
                "umur": "20 Tahun",
                "asal": " Lampung Timur",
                "alamat": "Korpri",
                "hobbi": "Ngoding WISATA",
                "sosmed": "@rahm_adityaa",
                "kesan": "Sangat pintar dan juga tampan",
                "pesan": "Sukses selalu untuk Bang Adit!",
            },
            {
                "nama": "Eggi Satria",
                "nim": "122450032",
                "umur": "20 Tahun",
                "asal": "Sukabumi",
                "alamat": "Korpri",
                "hobbi": "Ngoding dan buat konten WISATA",
                "sosmed": "@egistr ",
                "kesan": "Sangat baik dan juga ramah sekali",
                "pesan": "Bang Eggi, semoga kita bisa semakin akrab!",
            },
            {
                "nama": "Febiya Jomy Pratiwi",
                "nim": "122450074",
                "umur": "20 Tahun",
                "asal": "Tulang Bawang",
                "alamat": "Jl Kelengkeng Raya",
                "hobbi": "Nonton K-Drama ",
                "sosmed": "@pratiwifebiya",
                "kesan": "Kakak yang baik dan ramah",
                "pesan": "Sukses terus ya Kakak!",
            },
            {
                "nama": "Happy Syahrul Ramadhan",
                "nim": "122450013",
                "umur": "20 Tahun",
                "asal": "Lampung",
                "alamat": "Karang Anyar ",
                "hobbi": " Main Game",
                "sosmed": "@sudo.syahrulramadhannn",
                "kesan": "Abang yang baik dan tidak sombong",
                "pesan": "Semangat selalu Bang Syahrul!",
            },
            {
                "nama": "Randa Andriana Putra",
                "nim": "122450083",
                "umur": "21 Tahun",
                "asal": "Banten",
                "alamat": " Sukarame",
                "hobbi": " Tidur dan Berkembang",
                "sosmed": "@randaandriana_",
                "kesan": "Sangat pintar dan baik hati",
                "pesan": "Wah, semoga saya bisa ketularan pintar seperti Bang Randa!",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Mikfes()

elif menu == "Departemen Eksternal":
    def Eksternal():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1nH0VJn31cLetsrtbOfAbZxbtwBHIE90O",
            "https://drive.google.com/uc?export=view&id=16DVBXXKuxoajH7W7_w8imEL2wtSFtowP",
            "https://drive.google.com/uc?export=view&id=1Ptut-Mt4dXsTH8Vgqlvw0OCL7gQoe0ap",
            "https://drive.google.com/uc?export=view&id=11wpLfWcnNfyq3PgsYJpIbmUrOy2l-eaF",
            "https://drive.google.com/uc?export=view&id=1mocd0vzSi9rGdkKbSlFLNt4liqv1Lp-w",
            "https://drive.google.com/uc?export=view&id=1pa0c-kI-vZM3KVfwyKz3mCdig1llD08z",
            "https://drive.google.com/uc?export=view&id=1sxa4WuGbdSk0RAJqiBhr3dEfIt5zVdW9",
            "https://drive.google.com/uc?export=view&id=19d2W7dy2muqjl4MSAycX72QQVi00d8Xx",
            "https://drive.google.com/uc?export=view&id=1zxsm0VuEtUt9306kZZJ-zl_8-56SILnm",
            "https://drive.google.com/uc?export=view&id=1a5ljtz9jgaU_VVx7_29KI6G4HUGReCFh",
            "https://drive.google.com/uc?export=view&id=1utkmPIKZqAEMYuJltNQdbVmt-C0VHCkE",
            "https://drive.google.com/uc?export=view&id=1TwcdP-Xxva-SOT-2yRpnJaDAiVzBCqQt",
            "https://drive.google.com/uc?export=view&id=12xjG-YKQ7dcPKsPns0uGCInVJe97f-Fz",
            "https://drive.google.com/uc?export=view&id=1NgX0o6JSwvzKPjRSaeO1ED0JsXzKjhfA",
            "https://drive.google.com/uc?export=view&id=1YSKSJRvWFl36oOuU2SDD7H3XC17Tcqt3",
            "https://drive.google.com/uc?export=view&id=1WjPSHPAB6H57j5_PbNqEfJmp5yhULZUM",
        ] 
        data_list = [
            {
                "nama": "Yogy Sea Tama",
                "nim": "121450041",
                "umur": "21",
                "asal": "Tangerang",
                "alamat": "Jatimulyo",
                "hobbi": "Ngisi Bensin",
                "sosmed": "@yogyyyyyyy",
                "kesan": "Bang Yogy sangat ramah dan asyik sekali",
                "pesan": "Sukses selalu untuk Bang Yogy!", 
            },
            {
                "nama": "Ramadhita Asifa Hendri",
                "nim": "121450131",
                "umur": "21",
                "asal": "Rajabasa",
                "alamat": "Rajabasa",
                "hobbi": "Belajar",
                "sosmed": "@Ramadhitaasifa",
                "kesan": "Kakak yang cantik",
                "pesan": "Semoga harinya selalu cerah, Kak!",
            },
            {
                "nama": "Nazwa Nabilla",
                "nim": "121450112",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Way Kandis",
                "hobbi": "Belajar dengan Rajin",
                "sosmed": "@nazwanbilla",
                "kesan": "Kak Nazwa super ramah",
                "pesan": "Semangat selalu untuk Kak Nazwa!",
            },
            {
                "nama": "Rizki Adrian Bennovry",
                "nim": "121450073",
                "umur": "21",
                "asal": "Bekasi",
                "alamat": "TVRI",
                "hobbi": "Buat Portopolio",
                "sosmed": "@rzkdrnnn",
                "kesan": "Bang Rizki sangat asyik dan tidak sombong",
                "pesan": "Wah, senang sekali kenal dengan Bang Rizki yang ramah dari Bekasi juga!",
            },
            {
                "nama": "Dea Mutia Risani",
                "nim": "122450099",
                "umur": "20",
                "asal": "Sumatera Barat",
                "alamat": "Korpri",
                "hobbi": "Bikin Surat",
                "sosmed": "@deaa.rsn",
                "kesan": "Kakak yang baik dan lucu",
                "pesan": "Semoga lancar selalu dalam kehidupannya kak!",
            },
            {
                "nama": "Novelia Adinda",
                "nim": "122450104",
                "umur": "21",
                "asal": "Jakarta",
                "alamat": "Belwis",
                "hobbi": "Tidur",
                "sosmed": "@nvliadinda",
                "kesan": "Cantik sekali dan namanya sangat indah",
                "pesan": "Semangat selalu untuk Kak Novelia!",
            },
            {
                "nama": "Ratu Keisha Jasmin Deonova",
                "nim": "122450106",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Way Kandis",
                "hobbi": "Ngerjain ADW",
                "sosmed": "@jasminednva",
                "kesan": "Kakak yang anggun",
                "pesan": "Semoga Kakak bahagia selalu!",
            },
            {
                "nama": "Tobias David Monogari",
                "nim": "121450081",
                "umur": "20",
                "asal": "Jakarta Barat",
                "alamat": "Pemda",
                "hobbi": "Bikin Puisi",
                "sosmed": "@tobiassiagian",
                "kesan": "Abang yang sangat jelas ketika menjawab pertanyaan",
                "pesan": "Semangat terus untuk Bang Tobias dalam menjalani harinya!",
            },
            {
                "nama": "Arafi Ramadhan Maulana",
                "nim": "12245022",
                "umur": "20",
                "asal": "Jogja, Depok",
                "alamat": "Way Huwi",
                "hobbi": "menghafal al-quran",
                "sosmed": "@arafiramadhanmaulana",
                "kesan": "Bang Arafi super asyik",
                "pesan": "Semoga hari-hari Abang sama asyiknya dengan Abang!",
            },
            {
                "nama": "Asa Do'a Uyi",
                "nim": "122450005",
                "umur": "20",
                "asal": "Muara",
                "alamat": "Korpri",
                "hobbi": "cuci baju",
                "sosmed": "@u_yippy",
                "kesan": "Sangat sholehah dan baik hati",
                "pesan": "Sukses selalu ya Kak Asa!",
            },
            {
                "nama": "Chalifia Wananda",
                "nim": "122450076",
                "umur": "20",
                "asal": "Padang",
                "alamat": "sukarame",
                "hobbi": "Quality Time",
                "sosmed": "@chipawww",
                "kesan": "Kakak yang cantik sekali dan ramah",
                "pesan": "Wah, Semangat ya Kak Chalifia! Kita sering bertemu di ruang Asprak Fisika",
            },
            {
                "nama": "Irvan Alfaritzi",
                "nim": "122450093",
                "umur": "21",
                "asal": "Sumatera Barat",
                "alamat": "Jakarta",
                "hobbi": "Nonton Youtube dan main ML",
                "sosmed": "@Alfaritziirfan",
                "kesan": "Sangat baik",
                "pesan": "Sukses selalu untuk Bang Irvan",
            },
            {
                "nama": "Izza Lutfia",
                "nim": "122450090",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Teluk",
                "hobbi": "main vollly",
                "sosmed": "@izzalutfiaa",
                "kesan": "Sangat asyik dan juga cantik",
                "pesan": "Semangat terus ya Kak Izza!",
            },
            {
                "nama": "Khaalishah Zuhrah Alyaa Valefi",
                "nim": "122450034",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Rajabasa",
                "hobbi": "Nyanyi",
                "sosmed": "@alyaavalefi",
                "kesan": "Kakak yang anggun",
                "pesan": "Semangat selalu ya untuk Kakak!",
            },
            {
                "nama": "Raid Muhammad Naufal",
                "nim": "122450027",
                "umur": "20",
                "asal": "Lampung Tengah",
                "alamat": "Sukarame",
                "hobbi": "Ngeresume Seminar",
                "sosmed": "@rayHis_",
                "kesan": "Bang Raid sangat keren",
                "pesan": "Semoga hari Bang Raid selalu membahagiakan!",
            },
            {
                "nama": "Tria Yunanni",
                "nim": "122450062",
                "umur": "20",
                "asal": "Way Kanan",
                "alamat": "Jakarta",
                "hobbi": "Baca",
                "sosmed": "@tria_y062",
                "kesan": "Kakak sangat asyik dan cantik sekali",
                "pesan": "Semangat dalam perkuliahannya Kak Yuna!",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Eksternal()

elif menu == "Departemen Internal":
    def Internal():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1DQJ2phi626azsbEA9sLaMYOgLpdj3mXr",
            "https://drive.google.com/uc?export=view&id=1CvephZ1oyDIsWiIIhGobYv1-_IeRpnvr",
            "https://drive.google.com/uc?export=view&id=1DI-zaLeJf5fATv-8hwDMRkciUFM5EH1X",
            "https://drive.google.com/uc?export=view&id=1DejAJISohLmUJATpozugCQLgMkur1KI5",
            "https://drive.google.com/uc?export=view&id=1CyGRLDLChK4EHki5EgaYFKIQVGAArYFX",
            "https://drive.google.com/uc?export=view&id=1D9d9EZQBSEG-zKfZbmgLHvu1uVLCnyXr",
            "https://drive.google.com/uc?export=view&id=1D-Lz21fDcOxvzZWRPibNKc9LdVRsrbS9",
            "https://drive.google.com/uc?export=view&id=1DIukB2n3uFb8Bx5Opk5dWJ3wWEtiFOoU",
            "https://drive.google.com/uc?export=view&id=1DKUVmRsADVzz0YClE4i_GESX0sFVe1gu",
            "https://drive.google.com/uc?export=view&id=1DfuJLQPMcXGJ5NyQMTn2EmRKSWut1wcl",
            "https://drive.google.com/uc?export=view&id=1D2TYethe8ocBsxwgwmjzb0jVgIO1hkML",
            "https://drive.google.com/uc?export=view&id=1CxG4oJPoWHrM9c5oNRXRJuIYD5LGaX1Q",
            "https://drive.google.com/uc?export=view&id=1DoiFFy2GFfPP1FXS3_3Dy7sVtdKaghZM",
        ] 
        data_list = [
            {
                "nama": "Dimas Rizky Ramadhani",
                "nim": "121450027",
                "umur": "20",
                "asal": "Pamulang",
                "alamat": "Way kandis",
                "hobbi": "Manjat tower sutet",
                "sosmed": "@dimzrky",
                "kesan": "Sangat asyik juga berbobot saat menyampaikan pesan dan juga ramah",
                "pesan": "Sukses selalu ya Bang Dimas! Semoga bahagia terus", 
            },
            {
                "nama": "Catherine Firdhasari Maulina Sinaga",
                "nim": "121450072",
                "umur": "20",
                "asal": "Sumatera Utara",
                "alamat": "Airan",
                "hobbi": "Baca novel",
                "sosmed": "@chatherine.sinaga",
                "kesan": "Kakak yang cantik dan anggun",
                "pesan": "Semangat terus ya untuk Kak Catherine",
            },    
            {
                "nama": "M. Akbar Resdika",
                "nim": "121450066",
                "umur": "20",
                "asal": "Lampung Barat",
                "alamat": "Labuhan dalam",
                "hobbi": "Memelihara dino",
                "sosmed": "@akbar_resdika",
                "kesan": "Abang yang baik dan ramah",
                "pesan": "Semoga dipermudah dalam segala urusannya, Bang!",
            },
            {
                "nama": "Ari Sigit",
                "nim": "121450069",
                "umur": "23",
                "asal": "Lampung barat",
                "alamat": "Labuhan ratu",
                "hobbi": "Main futsal",
                "sosmed": "@ari_sigit17",
                "kesan": "Sangat baik dan ramah juga sholeh",
                "pesan": "Semangat dalam perkuliahannya, Bang!",
            },
            {
                "nama": "Rani Puspita Sari",
                "nim": "122450030",
                "umur": "20",
                "asal": "Metro",
                "alamat": "Rajabasa",
                "hobbi": "Mengaji",
                "sosmed": "@ranipu",
                "kesan": "Kakak yang cantik",
                "pesan": "Sukses selalu utnuk Kak Rani!",
            },
            {
                "nama": "Rendra Eka Prayoga",
                "nim": "122450112",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Jalan lapas raya",
                "hobbi": "nulis lagu",
                "sosmed": "@rendraepr",
                "kesan": "Ramah sekali dan juga pintar",
                "pesan": "Maju terus ya Bang Rendra!",
            },
            {
                "nama": "Salwa Farhanatussaidah",
                "nim": "122450055",
                "umur": "20",
                "asal": "Pesawaran",
                "alamat": "Airan raya",
                "hobbi": "ngeliat cogan",
                "sosmed": "@slwfhn_694",
                "kesan": "Kakak yang manis dan baik",
                "pesan": "Semoga hari-hari Kakak selalu indah!",
            },
            {
                "nama": "Azizah Kusumah Putri",
                "nim": "122450068",
                "umur": "21",
                "asal": "Lampung Selatan",
                "alamat": "Natar",
                "hobbi": "berkebun",
                "sosmed": "@azizahksmh15",
                "kesan": "Kakak yang baik dan juga ramah",
                "pesan": "Sukses selalu ya Kakak!",
            },
            {
                "nama": "Meira Listyaningrum",
                "nim": "122450011",
                "umur": "20",
                "asal": "Pesawaran",
                "alamat": "Airan raya",
                "hobbi": "Menghalu",
                "sosmed": "@meiraln",
                "kesan": "Kakak yang cantik dan baik",
                "pesan": "Semoga harinya selalu baik seperti Kakak!",
            },
            {
                "nama": "Rendi Alexander Hutagalung",
                "nim": "122450057",
                "umur": "20",
                "asal": "Tangerang",
                "alamat": "Kost gunawan",
                "hobbi": "Menyanyi",
                "sosmed": "@alexanderr",
                "kesan": "Abang yang murah senyum",
                "pesan": "Semangat terus ya Bang Rendi!",
            },
            {
                "nama": "Renta Siahaan",
                "nim": "122450070",
                "umur": "21",
                "asal": "Sumatera utara",
                "alamat": "Gerbang barat",
                "hobbi": "Memancing",
                "sosmed": "@renta.shn",
                "kesan": "Kakak cantik sekali",
                "pesan": "Sukses selalu ya Kak Renta!",
            },
            {
                "nama": "Yosia Lehare Banurea",
                "nim": "121450149",
                "umur": "20",
                "asal": "Dairi, Sumatera utara",
                "alamat": "Perum griya indah",
                "hobbi": "Bawa motor pakai kaki",
                "sosmed": "@yosiabanurea",
                "kesan": "Abang yang baik dan ramah juga murah senyum",
                "pesan": "Semangat ya Bang Yosia!",
            },
            {
                "nama": "Josua Panggabean",
                "nim": "121450061",
                "umur": "21",
                "asal": "Pematang siantar",
                "alamat": "Gya kost",
                "hobbi": "Ngawinin cupang",
                "sosmed": "@josuapanggabean16_",
                "kesan": "Abang yang ramah",
                "pesan": "Sukses selalu ya Bang Josua",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Internal()

elif menu == "Departemen SSD":
    def Ssd():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1ATu4V1cwPI7tureHMg4YmQbgUobLYY5L",
            "https://drive.google.com/uc?export=view&id=1AexR-ZGgs03Emd1YrHHxCgiqAclv0El9",
            "https://drive.google.com/uc?export=view&id=1AekCrithr7PoOv5_yxFYWHk-PfBgPAbM",
            "https://drive.google.com/uc?export=view&id=1AcSxzqi2KVjf-rQ80Dgudpr2943-n01d",
            "https://drive.google.com/uc?export=view&id=1AUIiTxfuM7slR6zdyzUk2FsEkU3wep5p",
            "https://drive.google.com/uc?export=view&id=1Af4HSlb8USP6aQgPAT7o2LHnJcHrhUK8",
            "https://drive.google.com/uc?export=view&id=1Af1MxQzAtIfwi5SzJJVv-ZxLHEy_ZqQ_",
            "https://drive.google.com/uc?export=view&id=1ATaBhaGj48tmRuJuv0BQlmY8SaREOWnH",
            "https://drive.google.com/uc?export=view&id=1AQu2cNF9gJOGM9GD62-CjpjegZqBJL7u",
        ] 
        data_list = [
            {
                "nama": "Andrian Agustinus Lumban Gaol",
                "nim": "121450090",
                "umur": "17 +",
                "asal": "Sidikalang",
                "alamat": "Lapas",
                "hobbi": "Nyari Hobi",
                "sosmed": "@andrialgaol",
                "kesan": "Pembawaannya sangat dewasa dan pintar serta berbobot sekali saat berbicara",
                "pesan": "Sukses selalu ya untuk Bang Andrian!", 
            },
            {
                "nama": "Adisty Syawaida Ariyanto",
                "nim": "121450136",
                "umur": "21",
                "asal": "Metro",
                "alamat": "Metro",
                "hobbi": "Nonton film",
                "sosmed": "@adistysa_",
                "kesan": "Cantik dan juga baik",
                "pesan": "Semangat terus ya Kak Adisty!",
            },
            {
                "nama": "Nabila Azhari",
                "nim": "121450029",
                "umur": "21",
                "asal": "Simalungun",
                "alamat": "Airan",
                "hobbi": "Menghitung",
                "sosmed": "@zhjung",
                "kesan": "Ramah dan juga baik",
                "pesan": "Semoga hari-hari Kakak selalu berbunga!",
            },
            {
                "nama": "Nabilah Andika Fitriani",
                "nim": "121450129",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Kedaton",
                "hobbi": "Tidur",
                "sosmed": "@nabilaafrn",
                "kesan": "Kakak yang cantik dan ramah",
                "pesan": "Semangat Kakak dalam perkuliahannya!",
            },
            {
                "nama": "Danang Hilal Kurniawan",
                "nim": "122450085",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "TB 3 Asrama",
                "hobbi": "Belajar",
                "sosmed": "@dananghk_",
                "kesan": "Bang Danang sangat pintar",
                "pesan": "Sukses selalu untuk Bang Danang!",
            },
            {
                "nama": "Farrel Julio Akbar",
                "nim": "122450110",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Jalan Lapas",
                "hobbi": "Bebas",
                "sosmed": "@farel__julio",
                "kesan": "Bang Farrel sangat murah senyum dan pintar",
                "pesan": "Semangat selalu untuk Bang Farrel!",
            },
            {
                "nama": "Alvia Asrinda Br.Ginting",
                "nim": "122450077",
                "umur": "20",
                "asal": "Binjai",
                "alamat": "Korpri",
                "hobbi": "Nonton Windah",
                "sosmed": "@alviagnting",
                "kesan": "Cantik dan ramah juga",
                "pesan": "Sukses terus ya untuk Kakak!",
            },
            {
                "nama": "Dhafin Razaka Luthfia",
                "nim": "122450133",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Jalan nangka 1",
                "hobbi": "Olahraga",
                "sosmed": "@dhafinrzqra3",
                "kesan": "Abang yang ramah",
                "pesan": "Semoga hari-hari Bang Dhafin selalu cerah!",
            },
            {
                "nama": "Ellia Meylani Simanjuntak",
                "nim": "-",
                "umur": "-",
                "asal": "-",
                "alamat": "-",
                "hobbi": "-",
                "sosmed": "-",
                "kesan": "-",
                "pesan": "-",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Ssd()

# Tambahkan menu lainnya sesuai kebutuhan
