import streamlit as st
from streamlit_option_menu import option_menu
import requests
from PIL import Image, ImageOps
from io import BytesIO

st.markdown("""<style>.centered-title {text-align: center;}</style>""",unsafe_allow_html=True)
st.markdown("<h1 class='centered-title'>BUKU KATING</h1>", unsafe_allow_html=True)

# bagian sini jangan diubah
def streamlit_menu():
    selected = option_menu(
        menu_title=None,
        options=[
            "Kesekjenan",
            "Baleg",
            "Senator",
            "Departemen PSDA",
            "Departemen MEDCRAF",
            "Departemen MIKFES",
            "Departemen Eksternal",
            "Departemen Internal",
            "Departemen SSD",
        ],
        icons=[
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
        ],
        default_index=0,
        orientation="horizontal",
        styles={
            "container": {"padding": "0!important", "background-color": "#fafafa"},
            "icon": {"color": "black", "font-size": "19px"},
            "nav-link": {
                "font-size": "15px",
                "text-align": "left",
                "margin": "0px",
                "--hover-color": "#eee",
            },
            "nav-link-selected": {"background-color": "#3FBAD8"},
        },
    )
    return selected

@st.cache_data
def load_image(url):
    response = requests.get(url)
    if response.status_code != 200:
        st.error(
            f"Failed to fetch image from {url}, status code: {response.status_code}"
        )
        return None
    try:
        img = Image.open(BytesIO(response.content))
        img = ImageOps.exif_transpose(img)
        img = img.resize((300, 400))
        return img
    except Exception as e:
        st.error(f"Error loading image: {e}")
        return None
    
@st.cache_data
def display_images_with_data(gambar_urls, data_list):
    images = []
    for i, url in enumerate(gambar_urls):
        with st.spinner(f"Memuat gambar {i + 1} dari {len(gambar_urls)}"):
            img = load_image(url)
            if img is not None:
                images.append(img)

    for i, img in enumerate(images):
        # Menggunakan Streamlit untuk menampilkan gambar di tengah kolom
        col1, col2, col3 = st.columns([1, 2, 1])
        with col2:
            st.image(img, use_column_width=True)

        if i < len(data_list):
            st.write(f"Nama: {data_list[i]['nama']}")
            st.write(f"NIM: {data_list[i]['nim']}")
            st.write(f"Umur: {data_list[i]['umur']}")
            st.write(f"Asal: {data_list[i]['asal']}")
            st.write(f"Alamat: {data_list[i]['alamat']}")
            st.write(f"Hobbi: {data_list[i]['hobbi']}")
            st.write(f"Sosial Media: {data_list[i]['sosmed']}")
            st.write(f"Kesan: {data_list[i]['kesan']}")
            st.write(f"Pesan: {data_list[i]['pesan']}")
            st.write("  ")
    st.write("Semua gambar telah dimuat!")
menu = streamlit_menu()

# BAGIAN SINI YANG HANYA BOLEH DIUBAH
if menu == "Kesekjenan":
    def kesekjenan():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1tDrYAHi-AO-kk3DlC3gobKEPCo_Gs6V8",
            "https://drive.google.com/uc?export=view&id=1LO3fr4cWDn433X0MIJwKHO795E0zMeLF",
            "https://drive.google.com/uc?export=view&id=1uuzrRrTMXAwxJHTJpP9Cz7PXDyOtKyZ7",
            "https://drive.google.com/uc?export=view&id=19eBqZ6McnDO9MEqvlqRlLjegc00Et3Zd",
            "https://drive.google.com/uc?export=view&id=169yDgQkr0eK9uPVaYQQdfOK2ofyet3km",
            "https://drive.google.com/uc?export=view&id=170-DKxBRl5vW1NGghFitHiS95weOp0lP",
        ]
        data_list = [
            {
                "nama": "Kharisma Gumilang",
                "nim": "121450042",
                "umur": "21",
                "asal": "Palembang",
                "alamat": "Jl.Pulau Damar",
                "hobbi": "Dengerin Musik",
                "sosmed": "@gumilangkharisma",
                "kesan": "Berkharisma dan Menginspirasi",  
                "pesan":"Semangat buat TA nya, sehat selalu!"# 1
            },
            {   
                "nama": "Pandra Insani Putra Anwar",
                "nim": "121450147",
                "umur": "21",
                "asal":"Lampung Utara",
                "alamat": "Sukarame",
                "hobbi": "Main Gitar",
                "sosmed": "@pandrainsani27",
                "kesan": "Keren banget dan Insight full",  
                "pesan":"Semangat bang !!!, tetap ganteng -juesi"# 1
            },
            {   
                "nama": "Meliza Wulandari",
                "nim": "121450065",
                "umur": "20",
                "asal":"Sumatera Selatan",
                "alamat": "Jl.Pagar Alam",
                "hobbi": "Nonton Drakor",
                "sosmed": "@wulandarimeliza",
                "kesan": "keren banget kak",  
                "pesan":"semangat ngaspraknya kak !!!"# 1
            },
        
            {
                "nama": "Putri Maulida Chairani",
                "nim": "121450050",
                "umur": "21",
                "asal":"Sumatera Barat",
                "alamat": "Gg. Nangka 4",
                "hobbi": "Dengerin Bg Pandra Main Gitar",
                "sosmed": "@ptrimaulidaaa_",
                "kesan": "Cantik, pendengar yang baik ",  
                "pesan":"Terimakasih udah support kami"# 1
            },
        
            {   
                "nama": "Hartiti Fadilah",
                "nim": "121450031",
                "umur": "21",
                "asal":"Palembang",
                "alamat": "Pemda",
                "hobbi": "Nyanyi",
                "sosmed": "@htrpdla",
                "kesan": "cantik",  
                "pesan":"Semangat ngurus cuannya"# 1
            },
        
            {
                "nama": "Nadilla Andhara Putri",
                "nim": "121450003",
                "umur": "21",
                "asal":"Lampung",
                "alamat": "Metro",
                "hobbi": "Mainn Bola, Belajar",
                "sosmed": "@nadilaandr26",
                "kesan": "vibes bendaharanya kerasa bgt",  
                "pesan":"Semangat ngasprak strukdatnya!"# 1
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    kesekjenan()


elif menu == "Baleg":
    def Baleg():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1S3lh7hMqXJojczBWUcQWTX4Dfi8jK1OV",
            "https://drive.google.com/uc?export=view&id=1Rp1Zfrtrmh_1lCvJAZm10hpp23z9lbYO",
            "https://drive.google.com/uc?export=view&id=1RjQrnIomGYsUfyzoHJp89fZADIddhni1",
            "https://drive.google.com/uc?export=view&id=1Ru4-0Bp_bqmnA20GJr67BWlGgtRRIXRQ",
            "https://drive.google.com/uc?export=view&id=1S6Q1oPCSaYt5gigTFKI96SooA4Oj7rcr",
            "https://drive.google.com/uc?export=view&id=1RxA8BsofUjOtBcN9zWw_Z_6JWAv316il",
            "https://drive.google.com/uc?export=view&id=1RvO_X4WPLIFAfuI8c5DLBp9d8MawJeMu",
            "https://drive.google.com/uc?export=view&id=1S6Hkmph-XUU3H2QbkofP_69yn33-_1e1",   
            "https://drive.google.com/uc?export=view&id=1S7N5e_ytYj_-eVT5l6f7XqmRP_PO0BV6",
            "https://drive.google.com/uc?export=view&id=1S6VtFamkRdyK6Ayo0JlltfJ9GvMZtl6W",
            "https://drive.google.com/uc?export=view&id=1RqEn0HTpF92YWZBfqvr48KXYruWP7fIi",
        ]
        data_list = [
            {
                "nama": "Tri Murniya Ningsih",
                "nim": "121450038",
                "umur": "21",
                "asal": "Bogor",
                "alamat": "Raden Saleh",
                "hobbi": "Tanya sama GPT",
                "sosmed": "@trimurniaa",
                "kesan": "Kakaknya cantik, ramah, baik",
                "pesan": "semangat kuliahnya kakak, tetap jadi orang baik",
            },
            {
                "nama": "Annisa Cahyani Surya",
                "nim": "121450114",
                "umur": "21",
                "asal": "Tangerang Selatan",
                "alamat": "Way Huwi",
                "hobbi": "Puasa Senin Kamis",
                "sosmed": "@annisacahyanisurya",
                "kesan": "Baik banget kakaknya, sgt humble",
                "pesan": "Semangat kuliahnya kak", 
            },
            {
                "nama": "Wulan Sabina",
                "nim": "121450150",
                "umur": "21",
                "asal": "Medan",
                "alamat": "Raden Saleh",
                "hobbi": "Menonton film",
                "sosmed": "wlsbn0",
                "kesan": "Ramah banget kakanya, baikk pula",
                "pesan": "semangat ya kak, tetap ramahh", 
            },
            {
                "nama": "Anisa Dini Amalia",
                "nim": "121450021",
                "umur": "20",
                "asal": "Tangerang",
                "alamat": "Jati Agung",
                "hobbi": "Baca Webtoon",
                "sosmed": " @anisadini10",
                "kesan": "Kakaknya ramahh, asik,baik",
                "pesan": "semangat terus kuliahnya kakak, jangan mudah menyerah", 
            },
            {
                "nama": "Anisa Fitriyani",
                "nim": "122450019",
                "umur": "20",
                "asal": "Batam",
                "alamat": "Kalianda",
                "hobbi": "Membaca Al waqiah setiap magrib",
                "sosmed": " @ansftynn_",
                "kesan": "Manis banget kakaknya, ramah juga",
                "pesan": "semangat kuliahnya kak, tetap baik hati kak", 
            },
            {
                 "nama": "Feryadi Yulius ",
                "nim": "122450087",
                "umur": "20",
                "asal": "Padang",
                "alamat": "Belwis",
                "hobbi": "Sholat Dhuha",
                "sosmed": "@fer_yulius",
                "kesan": "Abangnya sepertinya famous yah",
                "pesan": "semangat kuliahnya kak, semoga lulus tepat waktu", 
            },
            {
                "nama": "Renisha Putri Giani",
                "nim": "122450079",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Teluk Betung",
                "hobbi": "Baca Al-Qur'an",
                "sosmed": "@fleurnsh",
                "kesan": "MasyaAllah kak pertahankan hobinya",
                "pesan": "Semangat kuliahnya, semoga semakin rajin mengerjakan tugas",
            },
            {
                "nama": "Claudhia Angeliani",
                "nim": "121450124",
                "umur": "21",
                "asal": "Lampung Timur",
                "alamat": "Lampung Timur",
                "hobbi": "Baca Jurnal",
                "sosmed": " @dylebee",
                "kesan": "Bagus sekali kak namanya, orangnya juga cantik",
                "pesan": "semangat ya kuliahnya jangan putus asa kak", 
            },
            {
                "nama": "Mirzan Yusuf Rabbani",
                "nim": "122450118",
                "umur": "20",
                "asal": "Jakarta",
                "alamat": "Korpri",
                "hobbi": "Main Kucing",
                "sosmed": "@myrrinn",
                "kesan": "Abangnya baik, kalem, dan ramah",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari", 
            },
            {
                "nama": "Dhea Amelia Putri",
                "nim": "122450004",
                "umur": "20 tahun",
                "asal": "Ogan Ilir",
                "alamat": "Natar",
                "hobbi": "Nyari Sinyal di Gedung F",
                "sosmed": " @_.dheamelia",
                "kesan": "Kakaknya kelihatan aktif organisasi bangettt",
                "pesan": "Ramahh banget kak Dheaa", 
            },
            {
                "nama": "Muhammad Fachrul Aditya",
                "nim": "121450156",
                "umur": "22",
                "asal": "Surakarta",
                "alamat": "Sukarame",
                "hobbi": "Sholat Malam",
                "sosmed": "@fhrul.pdf",
                "kesan": "Abangnya keliatan soleh ya rajin sholat malam",
                "pesan": "semangat kuliahnya kak, tetap pertahankan rajin sholat malamnya", 
            },
             {
                "nama": "Jeremia Susanto",
                "nim": "122450022",
                "umur": "21",
                "asal": "Palembang",
                "alamat": "Bilabong",
                "hobbi": "Cerita",
                "sosmed": "@jeremia_s_",
                "kesan": "Abangnya keren banget",
                "pesan": "semangat kuliahnya bang, jangan lupa belajar tiap hari", 
            }, 
            {
                "nama": " Berliana Enda Putri",
                "nim": "122450065",
                "umur": "20",
                "asal": "Sumatera Barat",
                "alamat": "Way Huwi",
                "hobbi": "Baca Buku, Ngoding, Ibadah",
                "sosmed": "@berlyyanda",
                "kesan": "Abangnya keliatan soleh ya rajin sholat malam",
                "pesan": "semangat kuliahnya kak, tetap pertahankan rajin sholat malamnya", 
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Baleg()

elif menu == "Senator":
    def senator():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=194WIXQjHxMb8j-XQNpURCOcHZW4rHcv5",
            "https://drive.google.com/uc?export=view&id=1S7tuvpHtbj3pYzyWH__LYkM3rVgyp39I",
        ]
        data_list = [
            {
                "nama": "Anissa Luthfi Alifia",
                "nim": "121450093",
                "umur": "22",
                "asal": "Lampung Tengah",
                "alamat": "Kost Putri Rahayu",
                "hobbi": "Dengerin bintang nyanyi",
                "sosmed": "@anissalutfi_",
                "kesan": "kakaknya keren banget",
                "pesan": "Semangat kuliahnya kak, jangan lupa belajar tiap hari", 
            },
            {
                "nama": "Rian Bintang Wijaya",
                "nim": "122450094",
                "umur": "20",
                "asal": "Palembang",
                "alamat": "Kota Baru",
                "hobbi": "Nyanyi",
                "sosmed": "@bintangtwinkle",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            }
        ]
        display_images_with_data(gambar_urls, data_list)
    senator()

elif menu == "Departemen PSDA":
    def Psda():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
        ]
        data_list = [
            {
                "nama": "Ericson Chandra Sihombing",
                "nim": "121450026",
                "umur": "21",
                "asal": "Bekasi",
                "alamat": "Khobam",
                "hobbi": "Travelling",
                "sosmed": "@ericsonchandr99",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari", 
            },
            {
                "nama": "Elisabeth Claudia Simanjuntak",
                "nim": "122450123",
                "umur": "20",
                "asal": "Tanggerang",
                "alamat": "Owen Kost",
                "hobbi": "Bernafas",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
            {
                "nama": "Nisrina Nur Afifah",
                "nim": "122450123",
                "umur": "19",
                "asal": "Bekasi",
                "alamat": "Sukarame",
                "hobbi": "Menonton",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
            {
                "nama": "",
                "nim": "122450123",
                "umur": "20",
                "asal": "Tanggerang",
                "alamat": "Owen Kost",
                "hobbi": "Bernafas",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
            {
                "nama": "",
                "nim": "122450123",
                "umur": "20",
                "asal": "Tanggerang",
                "alamat": "Owen Kost",
                "hobbi": "Bernafas",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
            {
                "nama": "",
                "nim": "122450123",
                "umur": "20",
                "asal": "Tanggerang",
                "alamat": "Owen Kost",
                "hobbi": "Bernafas",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
            {
                "nama": "",
                "nim": "122450123",
                "umur": "20",
                "asal": "Tanggerang",
                "alamat": "Owen Kost",
                "hobbi": "Bernafas",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
            {
                "nama": "",
                "nim": "122450123",
                "umur": "20",
                "asal": "Tanggerang",
                "alamat": "Owen Kost",
                "hobbi": "Bernafas",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
            {
                "nama": "",
                "nim": "122450123",
                "umur": "20",
                "asal": "Tanggerang",
                "alamat": "Owen Kost",
                "hobbi": "Bernafas",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Psda()

elif menu == "Departemen MEDCRAF":
    def Medkraf():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1EL-_93l8ULYXPbHmLgI4u2DN0fwMbWEh",
            "https://drive.google.com/uc?export=view&id=1DydoYPXYG12-TrJ8lySdNQC-YirViPVv",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
            "https://drive.google.com/uc?export=view&id=1FEeu2yB9uX2DfBfr368bOaw69lYIy0oq",
            "https://drive.google.com/uc?export=view&id=1EgBUuI54QiIicfVQddNC0r9rTLciH6ND",
            "https://drive.google.com/uc?export=view&id=1E9o7tc0-_nnC2BySv4YDNIy8zq0AuWCC",
            "https://drive.google.com/uc?export=view&id=1EyCkwBbD-FzwpUfpjaz5boD9_pgiLC0P",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
            "https://drive.google.com/uc?export=view&id=1F8ibL_vkAhbDZeQXyyzS1bnC1yvksDeV",
            "https://drive.google.com/uc?export=view&id=1FV0EZE2m8rmdNK_RfuaEfzwpMl3DOa8k",
            "https://drive.google.com/uc?export=view&id=1EoRxtDwdFCCpwsrfvbXwCWa3WaPHnJJR",
            "https://drive.google.com/uc?export=view&id=1FSTMs1n3WnO-O8hnhxkThzMgUK0C5Qwq",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
            "https://drive.google.com/uc?export=view&id=1EVOT14NbKuHKHIa8W8ICGGLvoAEL1fJL",
            "https://drive.google.com/uc?export=view&id=1Ed6ZERe-xfgu70xXd3LnW5jOmxvMuWNa",
            "https://drive.google.com/uc?export=view&id=1ETkIlkvpOHtY3P0U0Uk0QYKCT7qvXjgk",
            "https://drive.google.com/uc?export=view&id=1EFdd3O8TCFO8F0HOzWLR6alVNOenL_Bq",
            "https://drive.google.com/uc?export=view&id=1EzAiiB3NgMN61qCSK_k-25MDXELh155u",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
        ]
        data_list = [
            {
                "nama": "Wahyudiyanto",
                "nim": "121450040",
                "umur": "22",
                "asal": "Makassar",
                "alamat": "Sukarame",
                "hobbi": "Nonton",
                "sosmed": "",
                "kesan": "",
                "pesan": "",
            },
            {
                "nama": "Elok Fiola",
                "nim": "122450051",
                "umur": "19",
                "asal": "Bandar Lampung",
                "alamat": "Bandar Lampung",
                "hobbi": "Editing",
                "sosmed": "@elokfiola",
                "kesan": "Manis bangett kakk, NIM nya sama kayak aku hihi",
                "pesan": "Semangat ya kak, tetap ramah", 
            },
            {
                "nama": "Arsyiah Azahra",
                "nim": "121450035",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Tanjung Senang",
                "hobbi": "Nugas",
                "sosmed": "@arsyiah._",
                "kesan": "",
                "pesan": "", 
            },
            {
                "nama": "Muhammad Kaisar Firdaus ",
                "nim": " 121450135",
                "umur": "21",
                "asal": "Pesawaran",
                "alamat": "Pulau Damar",
                "hobbi": "Lagi Nyari",
                "sosmed": " @dino_kiper",
                "kesan": "",
                "pesan": "", 
            },
            {
                "nama": "Muhammad Arsal Ranjana Putra",
                "nim": "121450111",
                "umur": "21",
                "asal": "Depok",
                "alamat": "Nangka 4",
                "hobbi": "Ngoding",
                "sosmed": "@arsal.utama",
                "kesan": "",
                "pesan": "", 
            },
            {
                "nama": "Cintya  Bella",
                "nim": "122450066",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Teluk",
                "hobbi": "Ngegym",
                "sosmed": "@cintyabella28",
                "kesan": "Suka banget sama outfit kakak, cocok banget di divisi media & konten",
                "pesan": "", 
            },
            {
                "nama": "Eka Fidiya Putri",
                "nim": " 122450045",
                "umur": "20",
                "asal": "Natar, Lampung Selatan",
                "alamat": "Natar, Lampung Selatan",
                "hobbi": "Menyibukkan Diri",
                "sosmed": "@ekafdyaptri",
                "kesan": "",
                "pesan": "", 
            },
            {
                "nama": "Najla Juwairia",
                "nim": "122450037",
                "umur": "19",
                "asal": "Sumatra Utara",
                "alamat": "Airan",
                "hobbi": "Menulis, Membaca, fangirling",
                "sosmed": "@nanana_minjoo",
                "kesan": "",
                "pesan": "", 
            },
            {
                "nama": "Patricia Leondra Diajeng Putri ",
                "nim": "122450050",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Jatimulyo",
                "hobbi": "Nonton Film",
                "sosmed": "@patriciadiajeng",
                "kesan": "",
                "pesan": "", 
            },
            {
                "nama": "Rahma Neliyana",
                "nim": "122450036",
                "umur": "20",
                "asal": "Lampung",
                "alamat": "Sukarame",
                "hobbi": "Baca Coding",
                "sosmed": "@rahmanellyana",
                "kesan": "",
                "pesan": "", 
            },
            {
                "nama": "Try Yani Rizki Nur Rohmah ",
                "nim": "122450020",
                "umur": "20",
                "asal": "Lampung Barat",
                "alamat": "Korpri",
                "hobbi": "Bernyanyi dan Menonton",
                "sosmed": "@tryyaniciaaa",
                "kesan": "",
                "pesan": "", 
            },
            {
                "nama": "Gymnastiar Al Khoarizmy",
                "nim": "122450096",
                "umur": "20",
                "asal": "Serang",
                "alamat": "Lapangan Golf UIN",
                "hobbi": "Baca Komik",
                "sosmed": "@jimnn.as",
                "kesan": "",
                "pesan": "Ramahh banget kak Dheaa", 
            },
            {
                "nama": "Nasywa Nur Afifah ",
                "nim": "122450125",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Jalan Durian 1 Pemda",
                "hobbi": "Nonton Drakor",
                "sosmed": "@nsywanaf",
                "kesan": "Abangnya keliatan soleh ya rajin sholat malam",
                "pesan": "semangat kuliahnya kak, tetap pertahankan rajin sholat malamnya", 
            },
            {
                "nama": "Abit Ahmad Oktarian",
                "nim": "122450042",
                "umur": "19",
                "asal": "Bandar Lampung",
                "alamat": "Rajabasa, Labuhan Dalam",
                "hobbi": "Ngoding, Gaming",
                "sosmed": "@abitahmad",
                "kesan": "",
                "pesan": "", 
            },
             {
                "nama": "Akmal Faiz Abdillah",
                "nim": "122450114",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Perumahan Griya Sukarame",
                "hobbi": "Main HP",
                "sosmed": "@_akmal.faiz",
                "kesan": "",
                "pesan": "", 
            },
             {
                "nama": "Hermawan Manurung ",
                "nim": "122450069",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Dekat Jalan Tol (Wisma Hana Hani) ",
                "hobbi": "Bengong/Membaca Buku",
                "sosmed": "@hermawan.mnrng",
                "kesan": "",
                "pesan": "", 
            },
             {
                "nama": "Khusnun Nisa",
                "nim": "122450078",
                "umur": "20",
                "asal": "Lampung Selatan",
                "alamat": "",
                "hobbi": "Mengerjakan Tugas",
                "sosmed": "@khusnun_nisa335",
                "kesan": "",
                "pesan": "", 
            },
             {
                "nama": "Priska Silvia Ferantiana",
                "nim": "122450053",
                "umur": "20",
                "asal": "Palembang",
                "alamat": "Jalan Nangka 2",
                "hobbi": "Baca Novel yang Bikin Nangis",
                "sosmed": "@prskslv",
                "kesan": "",
                "pesan": "", 
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Medkraf()

elif menu == "Departemen MIKFES":
    def Mikfes():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1yIbabgRvAxQjYfQARS6GuzbV7LtS_jJT",
            "https://drive.google.com/uc?export=view&id=1z04e4NllfS_moqxQgv2q_n6-qYovy9uP",
            "https://drive.google.com/uc?export=view&id=1DY8qV7tV0u8dNNgbH4KaSfozgDxrpZxw",
            "https://drive.google.com/uc?export=view&id=1xan2YSABjmXdlfzutnsgJ6vmHCH531vt",
            "https://drive.google.com/uc?export=view&id=1PKn6Mmgf9_zRn13wvN4-_wgf9JyK5KBX",
            "https://drive.google.com/uc?export=view&id=1jUVcK6WMnV3V-P7YgLe0gJw_YAdlPO1g",
            "https://drive.google.com/uc?export=view&id=1pVSL1dDyzdxD9r9MDYZHAV4iA-CSzg56",
            "https://drive.google.com/uc?export=view&id=16s7opqy9uhvarMn9Oi380D6OS-RbsS1g",
            "https://drive.google.com/uc?export=view&id=1LGheDP_h-O6kWHZ2io7Wpa51UI2tgdZz",
            "https://drive.google.com/uc?export=view&id=12HBknVEG-f3J4iKNfMX0dqD0x236iBxx",
            "https://drive.google.com/uc?export=view&id=1G7Cf41oOiJmUkWM7UYo_h8yjugCBaGV1",
            "https://drive.google.com/uc?export=view&id=1EoSuPSH3XWvr0N6JT-JcgXFezWoxVaOE",
            "https://drive.google.com/uc?export=view&id=1fnWcA1hNVyJRlUI_cv3uKPFQJku2IBm6",
            "https://drive.google.com/uc?export=view&id=1UTCgYMdQlICYxaZU26qYMDoibwtv1F2e",
            "https://drive.google.com/uc?export=view&id=1aedMvtmgOf7kwD-Yk0FqrBoqdXphEn9-",
            "https://drive.google.com/uc?export=view&id=1t8lVr_NFqeQNvw8OmAhHlBOp2TUxgCQA",
            "https://drive.google.com/uc?export=view&id=1-Yi-E2j8j8XSVrFvqwT-QjtvSZ3BsWB3",
            "https://drive.google.com/uc?export=view&id=12LruYNhd-1aj1qV8RbKZUCczmjVh3yqB",
            "https://drive.google.com/uc?export=view&id=1jGyCuyGj7xwWZFZHGk3Rxo0J9qrcLx91",
        ] 
        data_list = [
            {
                "nama": "Rafi Fadhlillah",
                "nim": "121450143",
                "umur": "21 Tahun",
                "asal": "Lubuk Linggau",
                "alamat": "Jl. Nangka 4",
                "hobbi": "Olahraga",
                "sosmed": "@rafadhilillahh13",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Annisa Novantika",
                "nim": "121450005",
                "umur": "21 Tahun",
                "asal": "Lampung Utara",
                "alamat": "Jl. Pulau Sebesi, Sukarame",
                "hobbi": " Memasak",
                "sosmed": "@anovavona",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": " Ahmad Sahidin Akbar",
                "nim": "122450044",
                "umur": " 20",
                "asal": "Tulang Bawang",
                "alamat": " Sukarame",
                "hobbi": "Olahraga",
                "sosmed": "@sahid22__",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Fadhil Fitra Wijaya",
                "nim": "122450082",
                "umur": "20 Tahun",
                "asal": "Bekasi",
                "alamat": "Teluk Betung ",
                "hobbi": "Main Game",
                "sosmed": "@fadhilfwee",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Muhammad Regi Abdi Putra Amanta",
                "nim": " 122450031",
                "umur": "19 Tahun",
                "asal": "Palembang",
                "alamat": "Jl. Permadi Sukarame  ",
                "hobbi": "Main Game",
                "sosmed": "@mregiiii_",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Syalaisha Andina Putriansyah",
                "nim": "122450121",
                "umur": "21 Tahun",
                "asal": "Tangerang",
                "alamat": "Gg Yudhistira ",
                "hobbi": "Baca Novel",
                "sosmed": "@dkselsd_31",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Natanael Oktavianus Partahan Sihombing ",
                "nim": "121450107",
                "umur": "20 Tahun",
                "asal": "Jakarta",
                "alamat": "Kemiling ",
                "hobbi": "Membuka Wisata HMSD",
                "sosmed": "@natanaeloks",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Anwar Muslim",
                "nim": "122450117",
                "umur": "21 Tahun",
                "asal": "Bukittinggi",
                "alamat": "Korpri ",
                "hobbi": " ML (Machine Learning)",
                "sosmed": "@here.am.ai",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Deva Anjani Khayyuninafsyah",
                "nim": "122450014",
                "umur": "21 Tahun",
                "asal": " Bandar Lampung",
                "alamat": "Kemiling",
                "hobbi": "Menonton Film",
                "sosmed": "@anjaniiidev",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Dinda Nababan",
                "nim": "122450120",
                "umur": "20 Tahun",
                "asal": "Medan",
                "alamat": "Jl. Lapas",
                "hobbi": "Main Game",
                "sosmed": "@dindanababan_",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Marleta Cornelia Leander",
                "nim": "122450092",
                "umur": "20 Tahun",
                "asal": "Depok, Jawa Barat",
                "alamat": "Gg. Nangka 3",
                "hobbi": "Liatin Jurnal",
                "sosmed": "@marletacornelia",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Rut Junita Sari Siburian",
                "nim": "122450103",
                "umur": "20 Tahun",
                "asal": "Batam, Kep.Riau",
                "alamat": "Gg. Nangka 3",
                "hobbi": "Resume Jurnal",
                "sosmed": "@junitaa_0406",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Syadza Puspadari Azhar",
                "nim": " 122450072",
                "umur": "20 Tahun",
                "asal": "Palembang",
                "alamat": "Belwis ",
                "hobbi": "Membaca",
                "sosmed": "@puspadrr",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": " Abdurrahman Al-atsary",
                "nim": "121450128",
                "umur": "23 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "Perumnas Way Kandis",
                "hobbi": " Membaca",
                "sosmed": "@rahmn_abdr",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Aditya Rahman",
                "nim": "122450113",
                "umur": "20 Tahun",
                "asal": " Lampung Timur",
                "alamat": "Korpri",
                "hobbi": "Ngoding WISATA",
                "sosmed": "@rahm_adityaa",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Eggi Satria",
                "nim": "122450032",
                "umur": "20 Tahun",
                "asal": "Sukabumi",
                "alamat": "Korpri",
                "hobbi": "Ngoding dan buat konten WISATA",
                "sosmed": "@egistr ",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Febiya Jomy Pratiwi",
                "nim": "122450074",
                "umur": "20 Tahun",
                "asal": "Tulang Bawang",
                "alamat": "Jl Kelengkeng Raya",
                "hobbi": "Nonton K-Drama ",
                "sosmed": "@pratiwifebiya",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Happy Syahrul Ramadhan",
                "nim": "122450013",
                "umur": "20 Tahun",
                "asal": "Lampung",
                "alamat": "Karang Anyar ",
                "hobbi": " Main Game",
                "sosmed": "@sudo.syahrulramadhannn",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Randa Andriana Putra",
                "nim": "122450083",
                "umur": "21 Tahun",
                "asal": "Banten",
                "alamat": " Sukarame",
                "hobbi": " Tidur dan Berkembang",
                "sosmed": "@randaandriana_",
                "kesan": "-",
                "pesan": "-",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Mikfes()

elif menu == "Departemen Eksternal":
    def Eksternal():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1nH0VJn31cLetsrtbOfAbZxbtwBHIE90O",
            "https://drive.google.com/uc?export=view&id=16DVBXXKuxoajH7W7_w8imEL2wtSFtowP",
            "https://drive.google.com/uc?export=view&id=1Ptut-Mt4dXsTH8Vgqlvw0OCL7gQoe0ap",
            "https://drive.google.com/uc?export=view&id=1mocd0vzSi9rGdkKbSlFLNt4liqv1Lp-w",
            "https://drive.google.com/uc?export=view&id=1pa0c-kI-vZM3KVfwyKz3mCdig1llD08z",
            "https://drive.google.com/uc?export=view&id=1sxa4WuGbdSk0RAJqiBhr3dEfIt5zVdW9",
            "https://drive.google.com/uc?export=view&id=19d2W7dy2muqjl4MSAycX72QQVi00d8Xx",
            "https://drive.google.com/uc?export=view&id=11wpLfWcnNfyq3PgsYJpIbmUrOy2l-eaF",
            "https://drive.google.com/uc?export=view&id=1zxsm0VuEtUt9306kZZJ-zl_8-56SILnm",
            "https://drive.google.com/uc?export=view&id=1a5ljtz9jgaU_VVx7_29KI6G4HUGReCFh",
            "https://drive.google.com/uc?export=view&id=1utkmPIKZqAEMYuJltNQdbVmt-C0VHCkE",
            "https://drive.google.com/uc?export=view&id=1TwcdP-Xxva-SOT-2yRpnJaDAiVzBCqQt",
            "https://drive.google.com/uc?export=view&id=12xjG-YKQ7dcPKsPns0uGCInVJe97f-Fz",
            "https://drive.google.com/uc?export=view&id=1NgX0o6JSwvzKPjRSaeO1ED0JsXzKjhfA",
            "https://drive.google.com/uc?export=view&id=1YSKSJRvWFl36oOuU2SDD7H3XC17Tcqt3",
            "https://drive.google.com/uc?export=view&id=1WjPSHPAB6H57j5_PbNqEfJmp5yhULZUM",
        ] 
        data_list = [
            {
                "nama": "Yogy Sea Tama",
                "nim": "121450041",
                "umur": "21",
                "asal": "Tangerang",
                "alamat": "Jatimulyo",
                "hobbi": "Ngisi Bensin",
                "sosmed": "@yogyyyyyyy",
                "kesan": "Abangnya kece bangett",
                "pesan": "Semangat menjalani hari-hari dan Persiapan TA nya ya bang!!", 
            },
            {
                "nama": "Ramadhita Asifa Hendri",
                "nim": "121450131",
                "umur": "21",
                "asal": "Rajabasa",
                "alamat": "Rajabasa",
                "hobbi": "Belajar",
                "sosmed": "@Ramadhitaasifa",
                "kesan": "kakanya keren banget!!",
                "pesan": "Semangat menjalani ahri-hari dan Persiapan TA nya kak!!",
            },
            {
                "nama": "Nazwa Nabilla",
                "nim": "121450112",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Way Kandis",
                "hobbi": "Belajar dengan Rajin",
                "sosmed": "@nazwanbilla",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan Persiapan TA nya kak!!",
            },
            {
                "nama": "Dea Mutia Risani",
                "nim": "122450099",
                "umur": "20",
                "asal": "Sumatera Barat",
                "alamat": "Korpri",
                "hobbi": "Bikin Surat",
                "sosmed": "@deaa.rsn",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Novelia Adinda",
                "nim": "122450104",
                "umur": "21",
                "asal": "Jakarta",
                "alamat": "Belwis",
                "hobbi": "Tidur",
                "sosmed": "@nvliadinda",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Ratu Keisha Jasmin Deonova",
                "nim": "122450106",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Way Kandis",
                "hobbi": "Ngerjain ADW",
                "sosmed": "@jasminednva",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Tobias David Monogari",
                "nim": "121450081",
                "umur": "20",
                "asal": "Jakarta Barat",
                "alamat": "Pemda",
                "hobbi": "Bikin Puisi",
                "sosmed": "@tobiassiagian",
                "kesan": "abangnya kece banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya bang!!",
            },
            {
                "nama": "Rizki Adrian Bennovry",
                "nim": "121450073",
                "umur": "21",
                "asal": "Bekasi",
                "alamat": "TVRI",
                "hobbi": "Buat Portopolio",
                "sosmed": "@rzkdrnnn",
                "kesan": "Abangnya kece banget",
                "pesan": "Semangat menjalani hari-hari dan persiapan TA nya bang!!",
            },
            {
                "nama": "Arafi Ramadhan Maulana",
                "nim": "12245022",
                "umur": "20",
                "asal": "Jogja, Depok",
                "alamat": "Way Huwi",
                "hobbi": "menghafal al-quran",
                "sosmed": "@arafiramadhanmaulana",
                "kesan": "Abangnya kece banget",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya bang!!",
            },
            {
                "nama": "Asa Do'a Uyi",
                "nim": "122450005",
                "umur": "20",
                "asal": "Muara",
                "alamat": "Korpri",
                "hobbi": "cuci baju",
                "sosmed": "@u_yippy",
                "kesan": "kakaknya keren banget",
                "pesan": "semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Chalifia Wananda",
                "nim": "122450076",
                "umur": "20",
                "asal": "Padang",
                "alamat": "sukarame",
                "hobbi": "Quality Time",
                "sosmed": "@chipawww",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Irvan Alfaritzi",
                "nim": "122450093",
                "umur": "21",
                "asal": "Sumatera Barat",
                "alamat": "Jakarta",
                "hobbi": "Nonton Youtube dan main ML",
                "sosmed": "@Alfaritziirfan",
                "kesan": "Abangnya kece banget",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya bang",
            },
            {
                "nama": "Izza Lutfia",
                "nim": "122450090",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Teluk",
                "hobbi": "main vollly",
                "sosmed": "@izzalutfiaa",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Khaalishah Zuhrah ALyaa Valefi",
                "nim": "122450034",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Rajabasa",
                "hobbi": "Nyanyi",
                "sosmed": "@alyaavalefi",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Raid Muhammad Naufal",
                "nim": "122450027",
                "umur": "20",
                "asal": "Lampung Tengah",
                "alamat": "Sukarame",
                "hobbi": "Ngeresume Seminar",
                "sosmed": "@rayHis_",
                "kesan": "Abangnya kece banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya bang!!",
            },
            {
                "nama": "Tria Yunanni",
                "nim": "122450062",
                "umur": "20",
                "asal": "Way Kanan",
                "alamat": "Jakarta",
                "hobbi": "Baca",
                "sosmed": "@tria_y062",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Eksternal()

elif menu == "Departemen Internal":
    def Internal():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1DQJ2phi626azsbEA9sLaMYOgLpdj3mXr",
            "https://drive.google.com/uc?export=view&id=1CvephZ1oyDIsWiIIhGobYv1-_IeRpnvr",
            "https://drive.google.com/uc?export=view&id=1DI-zaLeJf5fATv-8hwDMRkciUFM5EH1X",
            "https://drive.google.com/uc?export=view&id=1CyGRLDLChK4EHki5EgaYFKIQVGAArYFX",
            "https://drive.google.com/uc?export=view&id=1D9d9EZQBSEG-zKfZbmgLHvu1uVLCnyXr",
            "https://drive.google.com/uc?export=view&id=1D-Lz21fDcOxvzZWRPibNKc9LdVRsrbS9",
            "https://drive.google.com/uc?export=view&id=1DejAJISohLmUJATpozugCQLgMkur1KI5",
            "https://drive.google.com/uc?export=view&id=1DIukB2n3uFb8Bx5Opk5dWJ3wWEtiFOoU",
            "https://drive.google.com/uc?export=view&id=1DKUVmRsADVzz0YClE4i_GESX0sFVe1gu",
            "https://drive.google.com/uc?export=view&id=1DfuJLQPMcXGJ5NyQMTn2EmRKSWut1wcl",
            "https://drive.google.com/uc?export=view&id=1D2TYethe8ocBsxwgwmjzb0jVgIO1hkML",
            "https://drive.google.com/uc?export=view&id=1CxG4oJPoWHrM9c5oNRXRJuIYD5LGaX1Q",
            "https://drive.google.com/uc?export=view&id=1DoiFFy2GFfPP1FXS3_3Dy7sVtdKaghZM",
        ]
        data_list = [
            {
                "nama": "Dimas rizky ramadhani",
                "nim": "121450027",
                "umur": "20",
                "asal": "Pamulang",
                "alamat": "Way kandis",
                "hobbi": "Manjat tower sutet",
                "sosmed": "@dimzrky",
                "kesan": "Berkharisma banget",
                "pesan": "Semangat nyusun TA nya bang dimas", 
            },
            {
                "nama": "Catherine firdhasari maulina sinaga",
                "nim": "121450072",
                "umur": "20",
                "asal": "Sumatera Utara",
                "alamat": "Airan",
                "hobbi": "Baca novel",
                "sosmed": "@chatherine.sinaga",
                "kesan": "kakanya ramah bintang 100",
                "pesan": "Semangat berproses kak",
            },    
            {
                "nama": "M. Akbar resdika",
                "nim": "121450066",
                "umur": "20",
                "asal": "Lampung Barat",
                "alamat": "Labuhan dalam",
                "hobbi": "Memelihara dino",
                "sosmed": "@akbar_resdika",
                "kesan": "Kelihatannya baik (emot senyum)",
                "pesan": "Semangat nyusun TA bang",
            },
            {
                "nama": "Rani puspita sari",
                "nim": "122450030",
                "umur": "20",
                "asal": "Metro",
                "alamat": "Rajabasa",
                "hobbi": "Mengaji",
                "sosmed": "@ranipu",
                "kesan": "Kakak baik",
                "pesan": "Selalu bermanfaat untuk orang sekitar ya kak",
            },
            {
                "nama": "Rendra eka prayoga",
                "nim": "122450112",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Jalan lapas raya",
                "hobbi": "nulis lagu",
                "sosmed": "@rendraepr",
                "kesan": "Ramah bintang 1000",
                "pesan": "Semoga jadi pribadi yang lebih baik lagi ",
            },
            {
                "nama": "Salwa farhanatussaidah",
                "nim": "122450055",
                "umur": "20",
                "asal": "Pesawaran",
                "alamat": "Airan raya",
                "hobbi": "ngeliat cogan",
                "sosmed": "@slwfhn_694",
                "kesan": "Cantik bangett",
                "pesan": "semangat kuliahnya kak",
            },
            {
                "nama": "Ari sigit",
                "nim": "121450069",
                "umur": "23",
                "asal": "Lampung barat",
                "alamat": "Labuhan ratu",
                "hobbi": "Main futsal",
                "sosmed": "@ari_sigit17",
                "kesan": "keren banget abangnya",
                "pesan": "semangat kuliahnya bang ari",
            },
            {
                "nama": "Azizah kusumah putri",
                "nim": "122450068",
                "umur": "21",
                "asal": "Lampung Selatan",
                "alamat": "Natar",
                "hobbi": "berkebun",
                "sosmed": "@azizahksmh15",
                "kesan": "Ramah bangett",
                "pesan": "Semangkaaa semangat kakak!!!",
            },
            {
                "nama": "Meira listyaningrum",
                "nim": "122450011",
                "umur": "20",
                "asal": "Pesawaran",
                "alamat": "Airan raya",
                "hobbi": "Menghalu",
                "sosmed": "@meiraln",
                "kesan": "Baik bangett",
                "pesan": "Semangat kakk!!!",
            },
            {
                "nama": "Rendi alexander hutagalung",
                "nim": "122450057",
                "umur": "20",
                "asal": "Tangerang",
                "alamat": "Kost gunawan",
                "hobbi": "Menyanyi",
                "sosmed": "@alexanderr",
                "kesan": "Baik bangett",
                "pesan": "jangan pentang menyerah,selalu berusaha",
            },
            {
                "nama": "Renta siahaan",
                "nim": "122450070",
                "umur": "21",
                "asal": "Sumatera utara",
                "alamat": "Gerbang barat",
                "hobbi": "Memancing",
                "sosmed": "@renta.shn",
                "kesan": "Keren banget",
                "pesan": "selalu semangat kakak ",
            },
            {
                "nama": "Yosia lehare banurea",
                "nim": "121450149",
                "umur": "20",
                "asal": "Dairi, Sumatera utara",
                "alamat": "Perum griya indah",
                "hobbi": "Bawa motor pakai kaki",
                "sosmed": "@yosiabanurea",
                "kesan": "Baik bangett",
                "pesan": "semangat kakak!!!",
            },
            {
                "nama": "Josua panggabean",
                "nim": "121450061",
                "umur": "21",
                "asal": "Pematang siantar",
                "alamat": "Gya kost",
                "hobbi": "Ngawinin cupang",
                "sosmed": "@josuapanggabean16_",
                "kesan": "sangat soft spoken",
                "pesan": "semangat kuliah bang",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Internal()

elif menu == "Departemen SSD":
    def Ssd():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1ATu4V1cwPI7tureHMg4YmQbgUobLYY5L",
            "https://drive.google.com/uc?export=view&id=1AexR-ZGgs03Emd1YrHHxCgiqAclv0El9",
            "https://drive.google.com/uc?export=view&id=1AekCrithr7PoOv5_yxFYWHk-PfBgPAbM",
            "https://drive.google.com/uc?export=view&id=1AUIiTxfuM7slR6zdyzUk2FsEkU3wep5p",
            "https://drive.google.com/uc?export=view&id=1Af4HSlb8USP6aQgPAT7o2LHnJcHrhUK8",
            "https://drive.google.com/uc?export=view&id=1AcSxzqi2KVjf-rQ80Dgudpr2943-n01d",
            "https://drive.google.com/uc?export=view&id=1Af1MxQzAtIfwi5SzJJVv-ZxLHEy_ZqQ_",
            "https://drive.google.com/uc?export=view&id=1ATaBhaGj48tmRuJuv0BQlmY8SaREOWnH",
        ] 
        data_list = [
            {
                "nama": "Andrian Agustinus Lumban Gaol",
                "nim": "121450090",
                "umur": "17 +",
                "asal": "Sidikalang",
                "alamat": "Lapas",
                "hobbi": "Nyari Hobi",
                "sosmed": "@andrialgaol",
                "kesan": "Public speakingnya bagus bangett",
                "pesan": "Semangat cari duitnya bang", 
            },
            {
                "nama": "Adisty Syawaida Ariyanto",
                "nim": "121450136",
                "umur": "21",
                "asal": "Metro",
                "alamat": "Metro",
                "hobbi": "Nonton film",
                "sosmed": "@adistysa_",
                "kesan": "Keren banget kak",
                "pesan": "Semangat kuliahnya kak",
            },
            {
                "nama": "Nabila Azhari",
                "nim": "121450029",
                "umur": "21",
                "asal": "Simalungun",
                "alamat": "Airan",
                "hobbi": "Menghitung",
                "sosmed": "@zhjung",
                "kesan": "",
                "pesan": "",
            },
            {
                "nama": "Danang Hilal Kurniawan",
                "nim": "122450085",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "TB 3 Asrama",
                "hobbi": "Belajar",
                "sosmed": "@dananghk_",
                "kesan": "",
                "pesan": "",
            },
            {
                "nama": "Farrel Julio Akbar",
                "nim": "122450110",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Jalan Lapas",
                "hobbi": "Bebas",
                "sosmed": "@farel__julio",
                "kesan": "",
                "pesan": "",
            },
            {
                "nama": "Nabilah Andika Fitriani",
                "nim": "121450129",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Kedaton",
                "hobbi": "Tidur",
                "sosmed": "@nabilaafrn",
                "kesan": "",
                "pesan": "",
            },
            {
                "nama": "Alvia Asrinda Br.Ginting",
                "nim": "122450077",
                "umur": "20",
                "asal": "Binjai",
                "alamat": "Korpri",
                "hobbi": "Nonton Windah",
                "sosmed": "@alviagnting",
                "kesan": "",
                "pesan": "",
            },
            {
                "nama": "Dhafin Razaka Luthfia",
                "nim": "122450133",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Jalan nangka 1",
                "hobbi": "Olahraga",
                "sosmed": "@dhafinrzqra3",
                "kesan": "",
                "pesan": "",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Ssd()

# Tambahkan menu lainnya sesuai kebutuhan
