import streamlit as st
from streamlit_option_menu import option_menu
import requests
from PIL import Image, ImageOps
from io import BytesIO

st.markdown("""<style>.centered-title {text-align: center;}</style>""",unsafe_allow_html=True)
st.markdown("<h1 class='centered-title'>BUKU KATING</h1>", unsafe_allow_html=True)

# bagian sini jangan diubah
def streamlit_menu():
    selected = option_menu(
        menu_title=None,
        options=[
            "Kesekjenan",
            "Baleg",
            "Senator",
            "Departemen PSDA",
            "Departemen MEDKRAF",
            "Departemen MIKFES",
            "Departemen Eksternal",
            "Departemen Internal",
            "Departemen SSD",
        ],
        icons=[
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
        ],
        default_index=0,
        orientation="horizontal",
        styles={
            "container": {"padding": "0!important", "background-color": "#fafafa"},
            "icon": {"color": "black", "font-size": "19px"},
            "nav-link": {
                "font-size": "15px",
                "text-align": "left",
                "margin": "0px",
                "--hover-color": "#eee",
            },
            "nav-link-selected": {"background-color": "#3FBAD8"},
        },
    )
    return selected

@st.cache_data
def load_image(url):
    response = requests.get(url)
    if response.status_code != 200:
        st.error(
            f"Failed to fetch image from {url}, status code: {response.status_code}"
        )
        return None
    try:
        img = Image.open(BytesIO(response.content))
        img = ImageOps.exif_transpose(img)
        img = img.resize((300, 400))
        return img
    except Exception as e:
        st.error(f"Error loading image: {e}")
        return None
    
@st.cache_data
def display_images_with_data(gambar_urls, data_list):
    images = []
    for i, url in enumerate(gambar_urls):
        with st.spinner(f"Memuat gambar {i + 1} dari {len(gambar_urls)}"):
            img = load_image(url)
            if img is not None:
                images.append(img)

    for i, img in enumerate(images):
        # Menggunakan Streamlit untuk menampilkan gambar di tengah kolom
        col1, col2, col3 = st.columns([1, 2, 1])
        with col2:
            st.image(img, use_column_width=True)

        if i < len(data_list):
            st.write(f"Nama: {data_list[i]['nama']}")
            st.write(f"NIM: {data_list[i]['nim']}")
            st.write(f"Umur: {data_list[i]['umur']}")
            st.write(f"Asal: {data_list[i]['asal']}")
            st.write(f"Alamat: {data_list[i]['alamat']}")
            st.write(f"Hobbi: {data_list[i]['hobbi']}")
            st.write(f"Sosial Media: {data_list[i]['sosmed']}")
            st.write(f"Kesan: {data_list[i]['kesan']}")
            st.write(f"Pesan: {data_list[i]['pesan']}")
            st.write("  ")
    st.write("Semua gambar telah dimuat!")
menu = streamlit_menu()

# BAGIAN SINI YANG HANYA BOLEH DIUABAH
if menu == "Kesekjenan":
    def kesekjenan():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1KaVC9QuVfyvtaPNSoGrG19BlFjZCf2ff",
            "https://drive.google.com/uc?export=view&id=1KYsZsZvUfAY588YYhooWT3ZwWC7t-rOk",
            "https://drive.google.com/uc?export=view&id=1K4GadUDULQUp1yP8OpxSiMgobVOA_3WG",
            "https://drive.google.com/uc?export=view&id=1KXpeujwgQbVIwp6-AyUMcfi4oGv6qSii",
            "https://drive.google.com/uc?export=view&id=1KDp3BF5ygMAx6XY8Y1ELQFrGsh2Y4gO8",
            "https://drive.google.com/uc?export=view&id=1KMf2LZ6bTvrtx8H2fvlyzp2h-T_bT7hL",
        ]
        data_list = [
            {
                "nama": "Kharisma Gumilang",
                "nim": "121450142",
                "umur": "21",
                "asal": "Palembang",
                "alamat": "Jl.Pulau Damar",
                "hobbi": "Dengerin Musik",
                "sosmed": "@gumilangkharisma",
                "kesan": "Berkharisma dan Menginspirasi",  
                "pesan":"Semangat buat TA nya, sehat selalu!"# 1
            },
            {   
                "nama": "Pandra Insani Putra Anwar",
                "nim": "121450147",
                "umur": "21",
                "asal":"Lampung Utara",
                "alamat": "Sukarame",
                "hobbi": "Main Gitar",
                "sosmed": "@pandrainsani27",
                "kesan": "Keren banget dan Insight full",  
                "pesan":"Semangat bang !!!, tetap ganteng -juesi"# 1
            },
            {   
                "nama": "Meliza Wulandari",
                "nim": "121450065",
                "umur": "20",
                "asal":"Sumatera Selatan",
                "alamat": "Jl.Pagar Alam",
                "hobbi": "Nonton Drakor",
                "sosmed": "@wulandarimeliza",
                "kesan": "keren banget kak",  
                "pesan":"semangat ngaspraknya kak !!!"# 1
            },
        
            {
                "nama": "Putri Maulida Chairani",
                "nim": "121450050",
                "umur": "21",
                "asal":"Sumatera Barat",
                "alamat": "Gg. Nangka 4",
                "hobbi": "Dengerin Bg Pandra Main Gitar",
                "sosmed": "@ptrimaulidaaa_",
                "kesan": "Cantik, pendengar yang baik ",  
                "pesan":"Terimakasih udah support kami"# 1
            },
        
            {   
                "nama": "Hartiti Fadilah",
                "nim": "121450031",
                "umur": "21",
                "asal":"Palembang",
                "alamat": "Pemda",
                "hobbi": "Nyanyi",
                "sosmed": "@htrpdla",
                "kesan": "cantik",  
                "pesan":"Semangat ngurus cuannya"# 1
            },
        
            {
                "nama": "Nadilla Andhara Putri",
                "nim": "121450003",
                "umur": "21",
                "asal":"Lampung",
                "alamat": "Metro",
                "hobbi": "Mainn Bola, Belajar",
                "sosmed": "@nadilaandr26",
                "kesan": "vibes bendaharanya kerasa bgt",  
                "pesan":"Semangat ngasprak strukdatnya!"# 1
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    kesekjenan()

elif menu == "Baleg":
    def baleg():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1P4z6MT-y-eJwKRUTenuTee-pO0er3jXn",
            "https://drive.google.com/uc?export=view&id=1PWPFbfuRA7dlP6aouo0KL6fxf7F1KZS6",
            "https://drive.google.com/uc?export=view&id=1PpVVepegQ9-DZeWBqAfbf6OsYMNeFV0f",
            "https://drive.google.com/uc?export=view&id=1PRAwMW5swMpXvMVbESTG3Fcw6E3I9P8G",
            "https://drive.google.com/uc?export=view&id=1OyqQcdq62GWD9AcxvzESL0fUbTd6FybK",
            "https://drive.google.com/uc?export=view&id=1PDEO3RyItAtib5NX_qgZHXIQK659u59n",
            "https://drive.google.com/uc?export=view&id=1PI-VpSelYlw0OGmhov00jGyD8jINhyEe",
            "https://drive.google.com/uc?export=view&id=1P0OSys_xyA-VsgbPUC1Bmrwgz98OjghL",
            "https://drive.google.com/uc?export=view&id=1PsDPuYyc5qdyrKtPYCL-QtDh1AEpbWjB",
            "https://drive.google.com/uc?export=view&id=1Ov7RoO9jul3WxOMsC2da76V_GLO8mHMa",
            "https://drive.google.com/uc?export=view&id=1PVkwyIDeUhNUFSXj_WRey9q-ovnjkrNn",
        ]
        data_list = [
             {
                "nama": "Tri murniya Ningsih",
                "nim": "121450038",
                "umur": "21",
                "asal":"Bogor",
                "alamat": "Raden saleh",
                "hobbi": "Nanya ke gpt",
                "sosmed": "@trimurniaa_",
                "kesan": "Kakak cantik asprak alpro RA",  
                "pesan":"semangat ngaspraknya kakak !!!"
            },
            {
                "nama": "Annisa cahyani surya",
                "nim": "121450114",
                "umur": "21",
                "asal":"Tangsel",
                "alamat": "Way huwi",
                "hobbi": "Membaca, nonton",
                "sosmed": "@anisacahyanisurya",
                "kesan": "Kakak nya cantik banget",  
                "pesan":"semoga TA nya lancar kakkk !!!"# 1
            },
            {
                "nama": "Wulan sabina",
                "nim": "121450150",
                "umur": "21",
                "asal":"Medan",
                "alamat": "Raden saleh",
                "hobbi": "Belajar, nonton film, tidur",
                "sosmed": "@wlsbn0",
                "kesan": "Kakak pasti orang baik kannn",  
                "pesan":"semoga dilancarkan dan dimudahkan segala urusannya ya kak!!!"# 1
            },
            {
                "nama": "Anisa dini amalia",
                "nim": "121450081",
                "umur": "20",
                "asal":"Tanggerang",
                "alamat": "Jati agung",
                "hobbi": "Nonton drachin",
                "sosmed": "@anisadini10",
                "kesan": "Waktu ngomongin hobinya, kakaknya keliatan seneng bgt",  
                "pesan":"semangat maraton drachinnya kak !!!"# 1
            },
            {
                "nama": "Feriyadi yulius",
                "nim": "122450087",
                "umur": "20",
                "asal":"Sumatera selatan",
                "alamat": "Way kandis",
                "hobbi": "Baca buku",
                "sosmed": "@fer_yulius",
                "kesan": "Abangnya keren",  
                "pesan":"semangat menjalani semester 5 bang!!!"# 1
            },
            {
                "nama": "Renisha Putri Giani",
                "nim": "122450079",
                "umur": "21",
                "asal":"Bandar Lampung",
                "alamat": "Teluk Betung",
                "hobbi": "Jualan pancing",
                "sosmed": "@fleurnsh",
                "kesan": "Kakaknya lucu",  
                "pesan":" Semangat kuliahnya kakak !!!"# 1
            },
            {
                "nama": "Claudhia Angeliani",
                "nim": "121450124",
                "umur": "21",
                "asal":"Lampung Timur",
                "alamat": "Lampung Timur",
                "hobbi": "Tidur",
                "sosmed": "@dylebee",
                "kesan": "Seru bgt ngobrol sama kakak",  
                "pesan":" Semangat berproses kak!!!"# 1
            },
            {
                "nama": "Mirzan Yusuf Rabbani",
                "nim": "122450110",
                "umur": "20",
                "asal":"Jakarta",
                "alamat": "Korpri",
                "hobbi": "Tidur yang lama, main kucing",
                "sosmed": "@myrrinn",
                "kesan": "ucul kakaknya,tinngi lagi",  
                "pesan":"semangat berhibernasinya kak !!!"# 1
            },
            {
                "nama": "Muhammad fahrul Aditya",
                "nim": "121450156",
                "umur": "22",
                "asal":"Surakarta",
                "alamat": "Sukarame",
                "hobbi": "Melukis, olahraga",
                "sosmed": "@fhrul.pdf",
                "kesan": "Kakaknya keren banget",  
                "pesan":"Terus semangat bangg"# 1
            },
            {
                "nama": "Jeremia susanto",
                "nim": "122450022",
                "umur": "20",
                "asal":"Bandar Lampung",
                "alamat": "Bandar Lampung",
                "hobbi": "Bengong",
                "sosmed": "@jeremia_s_",
                "kesan": "Bang jere ramah bgt orangnya",  
                "pesan":"semangat kuliahnya bang !!!"# 1
            },
            {
                "nama": "Berliana enda putri",
                "nim": "122450065",
                "umur": "20",
                "asal":"Sumatera barat",
                "alamat": "Way huwi",
                "hobbi": "Duduk di tepi pantai sambil galauin bintang yang tinggal satu",
                "sosmed": "@berlyyanda",
                "kesan": " kakaknya lucuu dan seruu",  
                "pesan":"Tetap semangat, jangan menyerah!!!"# 1
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    baleg()

elif menu == "Senator":
    def senator():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1K_iWKcWEALDAhqtdZQorDcjzFZwQbxsk",
            "https://drive.google.com/uc?export=view&id=1Os-txXjA5rWUz3g_V7n0ZoBiKLc6xwdt",
        ]
        data_list = [
            {
                "nama": "Anissa Luthfi Alifia",
                "nim": "121450093",
                "umur": "22",
                "asal": "Lampung Tengah",
                "alamat": "Kost Putri Rahayu",
                "hobbi": "Dengerin bintang nyanyi",
                "sosmed": "@anissalutfi_",
                "kesan": "kakaknya keren banget",
                "pesan": "Semangat kuliahnya kak, jangan lupa belajar tiap hari", 
            },
            {
                "nama": "Rian Bintang Wijaya",
                "nim": "122450094",
                "umur": "20",
                "asal": "Palembang",
                "alamat": "Kota Baru",
                "hobbi": "Nyanyi",
                "sosmed": "@bintangtwinkle",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            }
        ]
        display_images_with_data(gambar_urls, data_list)
    senator()

elif menu == "Departemen PSDA":
    def Psda():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1JYU9PnJN2OEDMpcLMiEvR74X_AjXXicu",
            "https://drive.google.com/uc?export=view&id=1JYTyS4I_gvVboPGK0RVyw4lqXoLFydRQ",
            "https://drive.google.com/uc?export=view&id=1Ij1jXu_4Amd_gzrKO07Exk_YiloVk3oI",
            "https://drive.google.com/uc?export=view&id1JCKD-J1tkSML8kIymviOIq1NEW3ITJA1",
            "https://drive.google.com/uc?export=view&id=1JbT7L2rcEZD9oX8Yt9S-recxYjH1nE9G",
            "https://drive.google.com/uc?export=view&id=1J4JQcYEKaNbtas0LuGKA0V7pZG5h7BZ_",
            "https://drive.google.com/uc?export=view&id=1IgM8qjj87nZ1B50ZKUUAKABC7RnJK9Tm",
            "https://drive.google.com/uc?export=view&id=1IgYvyO7sKnkLgTBpStN8DFP-NGC9oA0z",
            "https://drive.google.com/uc?export=view&id=1IqeVNrUgSajAeLoQjZJzDxCIL26U56NS",
            "https://drive.google.com/uc?export=view&id=1IZyV5soW_FwbQLI0Wn9ukHXzealz7wjf",
            "https://drive.google.com/uc?export=view&id=1IfJs3qGaEffN4L0xhNr61U-Z7DkeZtIw",
            "https://drive.google.com/uc?export=view&id=1JGe2bg9x74T1d6PYDzFmcQQs9-DwhXOh",
            "https://drive.google.com/uc?export=view&id=1JKnWV5KMJ1tbxJ_Sz3iUU2Av-RlJENFu",
            "https://drive.google.com/uc?export=view&id=1JH-2FHgqVF1lWGBMoDFcsalE4KKajJcH",
            "https://drive.google.com/uc?export=view&id=1J5zEmmwy9SXKMrZtjsV1uA9mAblEubY1",
            "https://drive.google.com/uc?export=view&id=1JRcd98W-2JmjDXaHiaoUsQ-ee6RBMpmk",
            "https://drive.google.com/uc?export=view&id=1J577559uBKdSY1r4SnSFJcYI7w6Te53Y",
            "https://drive.google.com/uc?export=view&id=1JiqUNtXySsu4vFaL7cDlZWj7mraam6Iu",
            "https://drive.google.com/uc?export=view&id=1JnY99VTF6gjIncmPJg2SOepA6Qb0TqMu",
            "https://drive.google.com/uc?export=view&id=1JuE2X_YLlMPRr8iws7BWX9h6NcQN4XnF",
        ]
        data_list = [
             {
                "nama": "Ericson Chandra Sihombing",
                "nim": "121450026",
                "umur": "21",
                "asal":"Bekasi",
                "alamat": "Khobam",
                "hobbi": "Travelling",
                "sosmed": "@ericsonchandra99",
                "kesan": "makasih insightnya bang, keren bangett",  
                "pesan":"Sehat selalu bang, semangat terus",
            },
            {
                "nama": "Elisabeth Claudia Simanjuntak",
                "nim": "122450123",
                "umur": "18",
                "asal":"Tangerang",
                "alamat": "Kemiling",
                "hobbi": "Bernafas",
                "sosmed": "@celisabethh_",
                "kesan": "Kakaknya cantik bangettt",  
                "pesan":"Terus semangat kuliahnya Kak",
            },
            {
                "nama": "Nisrina Nur Afifah",
                "nim": "122450052",
                "umur": "19",
                "asal":"Jawa Barat",
                "alamat": "Sukarame",
                "hobbi": "Muter-muter",
                "sosmed": "@afifahhnsrn",
                "kesan": "Kakak cantik banget dan mengispirasi",  
                "pesan":"Semangat terus kak, terus menginspirasi ya kak",
            },
            { 
                "nama": " Deyvan Loxefal", 
                "nim": " 121450148 ", 
                "umur":  "21", 
                "asal":" Duri Riau  ", 
                "alamat": "Khobam Pulau Damar", 
                "hobbi": "Belajar", 
                "sosmed": "@depanlo", 
                "kesan": "Abangnya keren asik dan seruu",   
                "pesan":"Sukses terus bang",
            },
              {
                "nama": "M. Farhan Athaulloh",
                "nim": "121450117",
                "umur": "21",
                "asal":"Lampung",
                "alamat": "Kota Baru",
                "hobbi": "Menolong",
                "sosmed": "@mfarhan.ath",
                "kesan": "Abangnya baik dan ramah juga kereen",  
                "pesan":"Suksek terus bang, semangatt",
            },
            {
                "nama": "Allya Nurul Islami Pasha",
                "nim": "122450033",
                "umur": "20",
                "asal":"Sumatera Barat",
                "alamat": "Belwis",
                "hobbi": "Nongs",
                "sosmed": "@allyaislami",
                "kesan": "kakak keren banget dan berwibawa sekali",  
                "pesan":"sukses selalu kak",
            },
            {
                "nama": "Eksanty Febriana Sukma Islamiaty",
                "nim": "122450001",
                "umur": "20",
                "asal":"Lubuk Linggau",
                "alamat": "Rajabasa",
                "hobbi": "Nyari sinyal di gedung F",
                "sosmed": "@eksantyfebriana",
                "kesan": "kakak alpha girl nya sangat terpancar, kece parahh",  
                "pesan": "semangat terus kuliahnya kak",
            },
            {
                "nama": "Farahanum Afifah Ardiansyah",
                "nim": "122450056",
                "umur": "20",
                "asal":"Padang",
                "alamat": "Sukarame",
                "hobbi": "Minum Kopi",
                "sosmed": "@farahanumafifahh",
                "kesan": "kakanyanya cantik dan ramah",  
                "pesan":"sehat sehat terus kak dan semangatt",
            },
            {
                "nama": "Ferdy Kevin Naibaho",
                "nim": "122450107",
                "umur": "20",
                "asal":"Medan",
                "alamat": "Senopati Raya",
                "hobbi": "Dengerin Musik",
                "sosmed": "@ferdy_kevin",
                "kesan": "Abangnya kece dan ramah",  
                "pesan":"sukses selalu bang",
            },
            {
                "nama": "M. Deriansyah Okutra",
                "nim": "122450101",
                "umur": "19",
                "asal":"Kayu Agung",
                "alamat": "Jl. Pagar Alam Kedaton",
                "hobbi": "Nongki-nongki",
                "sosmed": "@dransyh_",
                "kesan": "Abangnya baik dan asik",  
                "pesan":"Semangat terus kuliahnya bang",
            },
            {
                "nama": "Oktavia Nurwenda Puspita Sari",
                "nim": "122450041",
                "umur": "20",
                "asal":"Lampung Timur",
                "alamat": "Way Huwi",
                "hobbi": "Scroll tik-tok",
                "sosmed": "@oktavianrwnda",
                "kesan": "Kakaknya anggun banget",  
                "pesan":"Sukses selalu kak",
            },
            { 
                "nama": " Ibnu Farhan Al-Ghifari", 
                "nim": " 121450121 ", 
                "umur":  "21", 
                "asal":" Kerinci Jambi  ", 
                "alamat": "Khobam", 
                "hobbi": "game online", 
                "sosmed": "@al_ghifari032", 
                "kesan": "Abangnya ramah",   
                "pesan":"Semangat kuliahnya bangg sukses terus",
            },
            { 
                "nama": "Johannes Krisjon Silitonga", 
                "nim": "122450043", 
                "umur": "19", 
                "asal":"Tangerang", 
                "alamat": "Jl. Lapas", 
                "hobbi": "Ngasprak", 
                "sosmed": "@johanneskrisjon", 
                "kesan": "Abangnya keren bangett",   
                "pesan":"Keren terus bang, sukses selalu", 
            },
            { 
                "nama": "Kemas Veriandra Ramadhan", 
                "nim": "122450016", 
                "umur": "19", 
                "asal":"Bekasi", 
                "alamat": "Kojo Golf UIN", 
                "hobbi": "Main game", 
                "sosmed": "@kemasverii", 
                "kesan": "pinter banget dan jago ngoding",   
                "pesan":" Sukses selalu bang", 
            },
            { 
                "nama": "Leonard Andreas Napitupulu", 
                "nim": "121450153", 
                "umur": "21", 
                "asal":"Medan", 
                "alamat": "Khobam", 
                "hobbi": "belajar", 
                "sosmed": "@lndr.__", 
                "kesan": "Abangnya baik",   
                "pesan":"semangat kuliahnya bang", 
            },
            { 
                "nama": "Presilia", 
                "nim": "122450081", 
                "umur": "20", 
                "asal":"Bekasi", 
                "alamat": "Kota Baru", 
                "hobbi": "Dengerin lomba sihir", 
                "sosmed": "@presiliamy", 
                "kesan": "Kakaknya cantik",   
                "pesan":"Semangat ngaspraknya bang", 
            },
            { 
                "nama": "Sahid Maulana", 
                "nim": "122450109", 
                "umur": "21", 
                "asal":"Depok, Jabar", 
                "alamat": "Jl. Airan Raya", 
                "hobbi": "Dengerin musik", 
                "sosmed": "@sahid_maul19", 
                "kesan": "Bang Sahid best daplok, pengertian banget, full word affirmation, dan care bgtt",   
                "pesan": "Sehat selalu bang, makasih udah jadi daplok yang terbaik untuk anova, dan terimakasih untuk long text yang selalu menghagatkan hati", 
            },
            {
                "nama": "Gede Moana",
                "nim": "121450014",
                "umur": "21",
                "asal":"Bekasi",
                "alamat": "Korpri Raya",
                "hobbi": "Belajar, game, baca komik",
                "sosmed": "@gedemoenaa",
                "kesan": "abangnya asik dan seru.",  
                "pesan":"Sukses terus bang",
            },
            {
                "nama": "Jaclin Alcavella",
                "nim": "122450015",
                "umur": "19",
                "asal":"Sumatera Selatan",
                "alamat": "Korpri",
                "hobbi": "Berenang",
                "sosmed": "@jaclinalcv_",
                "kesan": "kakak asik, manis dan baik banget ",  
                "pesan":"Semangat kuliahnya kak",
            },
            {
                "nama": "Syalaisha Andini Putriansyah",
                "nim": "122450111",
                "umur": "21",
                "asal":"Tangerang",
                "alamat": "Sukarame",
                "hobbi": "Baca",
                "sosmed": "@syalaisha.i__",
                "kesan": "kakaknya manis banget",  
                "pesan":"Semangat terus kuliahnya kak",
            }
        ]
        display_images_with_data(gambar_urls, data_list)
    Psda()

elif menu == "Departemen MEDKRAF":

    def Medkraf():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1C8b0zTwOYJjwlBEnGMJ5tNVehfNOdDmS",
            "https://drive.google.com/uc?export=view&id=1Bh5EKkvhP7nqdxD_gkGqMx_yinUNZPws",
            "https://drive.google.com/uc?export=view&id=1Cm9s5vPL93OcHdug3odwW0Hju1yZWwbV",
            "https://drive.google.com/uc?export=view&id=1CJp6azbQrBxs8_CVfqdRU1q5zOH0r5Q3",
            "https://drive.google.com/uc?export=view&id=1BlgCsfgIEgPatb-eEk8bd3_5iSj73X_P",
            "https://drive.google.com/uc?export=view&id=1Ca1FIDxl6WNtdAJth49lS6524HGyG9RT",
            "https://drive.google.com/uc?export=view&id=1CfL-KWkL1Y4ZqVsfDvoQVNDEezOXzpDK",
            "https://drive.google.com/uc?export=view&id=1CtChTqbnuAgGUVNlFuCDaZtLwST_2oEa",
            "https://drive.google.com/uc?export=view&id=1Cd7tv8lCA3B7iU2ycgf8ZT1uajlr3yi2",
            "https://drive.google.com/uc?export=view&id=1CgZOAbinDdgF7Tl8yXu5N64-jJdkkrGH",
            "https://drive.google.com/uc?export=view&id=1CUTFWfBj2SOdjjsK97dVKdUsELqV2zv0",
            "https://drive.google.com/uc?export=view&id=1CBS9U8r5MlTmJG13YYQ5PHp9Z9Psma4v",
            "https://drive.google.com/uc?export=view&id=1CDNdCi1PxQH_ydpl5sx74lGdKA2wiQw6",
            "https://drive.google.com/uc?export=view&id=1C7BVo7tIWZdoWZlF58dIpQ_0mA3RwYdg",
            "https://drive.google.com/uc?export=view&id=1Bsb703i0-k5XpSXD2-bAcgnIX-g_dwHw",
            "https://drive.google.com/uc?export=view&id=1Ca5PRh3j-McJY30SFdyugPuLqNd18V5H",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
            
        ]
        data_list = [
            {
                "nama": "Wahyudiyanto",
                "nim": "121450040",
                "umur": "22",
                "asal": "Makassar",
                "alamat": "Sukarame",
                "hobbi": "Nonton",
                "sosmed": "wayylaja",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang",
            },
            {
                "nama": "Elok Fiola",
                "nim": "122450051",
                "umur": "19",
                "asal": "Bandar Lampung",
                "alamat": "Bandar Lampung",
                "hobbi": "Editing",
                "sosmed": "@elokfiola",
                "kesan": "Manis bangett kakk",
                "pesan": "Semangat ya kak, tetap ramah", 
            },
            {
                "nama": "Muhammad Kaisar Firdaus ",
                "nim": " 121450135",
                "umur": "21",
                "asal": "Pesawaran",
                "alamat": "Pulau Damar",
                "hobbi": "Lagi Nyari",
                "sosmed": " @dino_kiper",
                "kesan": "Sangat menyenangkan dan bermanfaat",
                "pesan": "Semangat fotonya bang", 
            },
            {
                "nama": "Muhammad Arsal Ranjana Putra",
                "nim": "121450111",
                "umur": "21",
                "asal": "Depok",
                "alamat": "Nangka 4",
                "hobbi": "Ngoding",
                "sosmed": "@arsal.utama",
                "kesan": "terimakasih atas insightnya bang",
                "pesan": "Semangat desainnya bang", 
            },
            {
                "nama": "Cintya  Bella",
                "nim": "122450066",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Teluk",
                "hobbi": "Ngegym",
                "sosmed": "@cintyabella28",
                "kesan": "Suka banget sama outfit kakak, cocok banget di divisi media & konten",
                "pesan": "semangat kuliahnya kakk", 
            },
            {
                "nama": "Eka Fidiya Putri",
                "nim": " 122450045",
                "umur": "20",
                "asal": "Natar, Lampung Selatan",
                "alamat": "Natar, Lampung Selatan",
                "hobbi": "Menyibukkan Diri",
                "sosmed": "@ekafdyaptri",
                "kesan": "senang bisa belajar dari kakak",
                "pesan": "Sampai ketemu lagi di kampus ya,kak", 
            },
            {
                "nama": "Patricia Leondra Diajeng Putri ",
                "nim": "122450050",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Jatimulyo",
                "hobbi": "Nonton Film",
                "sosmed": "@patriciadiajeng",
                "kesan": "kakaknya cantik banget",
                "pesan": "Makasih ya kak, sudah mau berbagi ilmu", 
            },
            {
                "nama": "Rahma Neliyana",
                "nim": "122450036",
                "umur": "20",
                "asal": "Lampung",
                "alamat": "Sukarame",
                "hobbi": "Baca Coding",
                "sosmed": "@rahmanellyana",
                "kesan": "Terimakasih sharing ilmunya kak",
                "pesan": "Semangat kuliahnya kak", 
            },
            {
                "nama": "Try Yani Rizki Nur Rohmah ",
                "nim": "122450020",
                "umur": "20",
                "asal": "Lampung Barat",
                "alamat": "Korpri",
                "hobbi": "Bernyanyi dan Menonton",
                "sosmed": "@tryyaniciaaa",
                "kesan": "Terimakasih atas insightnya kak",
                "pesan": "semangat kuliahnya kak", 
            },
            {
                "nama": "Gymnastiar Al Khoarizmy",
                "nim": "122450096",
                "umur": "20",
                "asal": "Serang",
                "alamat": "Lapangan Golf UIN",
                "hobbi": "Baca Komik",
                "sosmed": "@jimnn.as",
                "kesan": "Senang bisa belajar dari abang",
                "pesan": "Semangat kuliahnya bang", 
            },
            {
                "nama": "Nasywa Nur Afifah ",
                "nim": "122450125",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Jalan Durian 1 Pemda",
                "hobbi": "Nonton Drakor",
                "sosmed": "@nsywanaf",
                "kesan": "Wawancaranya sangat menginspirasi",
                "pesan": "semangat kuliahnya kak", 
            },
            {
                "nama": "Abit Ahmad Oktarian",
                "nim": "122450042",
                "umur": "19",
                "asal": "Bandar Lampung",
                "alamat": "Rajabasa, Labuhan Dalam",
                "hobbi": "Ngoding, Gaming",
                "sosmed": "@abitahmad",
                "kesan": "Terimakasih bang, saya belajar banyak",
                "pesan": "semangat kuliahnya bang", 
            },
             {
                "nama": "Akmal Faiz Abdillah",
                "nim": "122450114",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Perumahan Griya Sukarame",
                "hobbi": "Main HP",
                "sosmed": "@_akmal.faiz",
                "kesan": "abangnya ramah banget",
                "pesan": "semangat ngaspraknya bang", 
            },
             {
                "nama": "Hermawan Manurung ",
                "nim": "122450069",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Dekat Jalan Tol (Wisma Hana Hani) ",
                "hobbi": "Bengong/Membaca Buku",
                "sosmed": "@hermawan.mnrng",
                "kesan": "Lucu banget bang",
                "pesan": "semangat kuliahnya bang", 
            },
             {
                "nama": "Khusnun Nisa",
                "nim": "122450078",
                "umur": "20",
                "asal": "Lampung Selatan",
                "alamat": "Jati Agung",
                "hobbi": "Mengerjakan Tugas",
                "sosmed": "@khusnun_nisa335",
                "kesan": "Sharing ilmunya keren banget kak",
                "pesan": "Semangat kuliahnya kak", 
            },
             {
                "nama": "Priska Silvia Ferantiana",
                "nim": "122450053",
                "umur": "20",
                "asal": "Palembang",
                "alamat": "Jalan Nangka 2",
                "hobbi": "Baca Novel yang Bikin Nangis",
                "sosmed": "@prskslv",
                "kesan": "kakaknya ramah banget",
                "pesan": "Semangat kuliahnya kak", 
            },
            {
                "nama": "Arsyiah Azahra",
                "nim": "121450035",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Tanjung Senang",
                "hobbi": "Nugas",
                "sosmed": "@arsyiah._",
                "kesan": "Senang bisa belajar dari kakak",
                "pesan": "Semangat kuliahnya kak", 
            },
             {
                "nama": "Najla Juwairia",
                "nim": "122450037",
                "umur": "19",
                "asal": "Sumatra Utara",
                "alamat": "Airan",
                "hobbi": "Menulis, Membaca, fangirling",
                "sosmed": "@nanana_minjoo",
                "kesan": "kakak keren banget",
                "pesan": "terimakasih atas sharing nya", 
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Medkraf()

elif menu == "Departemen MIKFES":

    def Mikfes():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1L83ddTKLOkpG1fKdb3wk45-vS0pEODt7",
            "https://drive.google.com/uc?export=view&id=1LoUlIUviXGoEnnV47K5WDUZj_bQ2Nkc0",
            "https://drive.google.com/uc?export=view&id=1LE_a-uZa-CR08i4Llhjnbr9O5s_YHeKs",
            "https://drive.google.com/uc?export=view&id=1Lim8CYoKRrUHX6jQqERkQ1z52uS7DljC",
            "https://drive.google.com/uc?export=view&id=1LXFOPPONHpmiVEVo7cDYBCGhA_lcAs-M",
            "https://drive.google.com/uc?export=view&id=1L2pjK7kIkARCFoJU9YIcnn3mb_wtsE5n",
            "https://drive.google.com/uc?export=view&id=1KziYaJpqY6Poo-agqaJtX-lILAUFFIhi",
            "https://drive.google.com/uc?export=view&id=1LeQa16ReSDVb5qI-xWhQvI-ybEcNLuw1",
            "https://drive.google.com/uc?export=view&id=1LZB09yyV1doy32QKo6yB0UW5OrOGc1IV",
            "https://drive.google.com/uc?export=view&id=1KregWnEoR44iVj5FzzI7TEUJ9InHFjAU",
            "https://drive.google.com/uc?export=view&id=1LZkKDzrYOxXghUH5hz2WYGWe1nsiS1G9",
            "https://drive.google.com/uc?export=view&id=1L_ZSBVgl0tWTf6V-iGkx84cTjg9bDWss",
            "https://drive.google.com/uc?export=view&id=1LOTriGPrCWeT6S4FBBXfvx12rnpq55tv",
            "https://drive.google.com/uc?export=view&id=1L1Zg5OkA_CKSy70EIq1ryOqLN4Lw9wNM",
            "https://drive.google.com/uc?export=view&id=1LDa4cEsoK3CNCYN_BvK_L1Lt7bWFr6oM",
            "https://drive.google.com/uc?export=view&id=1LQFmAxjfPLmUMyiw2pN_Fx1tt6CYVHTw",
            "https://drive.google.com/uc?export=view&id=1L-OXf5EyKTufvBgzAbGgd0BQ22nQatdz",
            "https://drive.google.com/uc?export=view&id=1LLfAVeGq3LWTvbspya38v90AuVrkCUTP",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
        ] 
        data_list = [
            {
                "nama": "Rafi Fadhlillah",
                "nim": "121450143",
                "umur": "21 Tahun",
                "asal": "Lubuk Linggau",
                "alamat": "Jl. Nangka 4",
                "hobbi": "Olahraga",
                "sosmed": "@rafadhilillahh13",
                "kesan": " Abangnya ramah banget",
                "pesan": "Sehat selalu bang",
            },
            {
                "nama": " Ahmad Sahidin Akbar",
                "nim": "122450044",
                "umur": " 20",
                "asal": "Tulang Bawang",
                "alamat": " Sukarame",
                "hobbi": "Olahraga",
                "sosmed": "@sahid22__",
                "kesan": "Gagah banget bang",
                "pesan": " Semangat olahraganya bang :D",
            },
            {
                "nama": "Fadhil Fitra Wijaya",
                "nim": "122450082",
                "umur": "20 Tahun",
                "asal": "Bekasi",
                "alamat": "Teluk Betung ",
                "hobbi": "Main Game",
                "sosmed": "@fadhilfwee",
                "kesan": "Abang tinggi banget",
                "pesan": "kapan kapan main game bereng ya bang",
            },
            {
                "nama": "Muhammad Regi Abdi Putra Amanta",
                "nim": " 122450031",
                "umur": "19 Tahun",
                "asal": "Palembang",
                "alamat": "Jl. Permadi Sukarame  ",
                "hobbi": "Main Game",
                "sosmed": "@mregiiii_",
                "kesan": "Publik Speakingnya bagus banget bang",
                "pesan": "Semangat kuliahnya bang ",
            },
            {
                "nama": "Syalaisha Andina Putriansyah",
                "nim": "122450121",
                "umur": "21 Tahun",
                "asal": "Tangerang",
                "alamat": "Gg Yudhistira ",
                "hobbi": "Baca Novel",
                "sosmed": "@dkselsd_31",
                "kesan": "Kakaknya ramah",
                "pesan": "Sehat selalu kak",
            },
            {
                "nama": "Natanael Oktavianus Partahan Sihombing ",
                "nim": "121450107",
                "umur": "20 Tahun",
                "asal": "Jakarta",
                "alamat": "Kemiling ",
                "hobbi": "Membuka Wisata HMSD",
                "sosmed": "@natanaeloks",
                "kesan": " Abangnya baik",
                "pesan": "Semangat kuliahnya bang",
            },
            {
                "nama": "Anwar Muslim",
                "nim": "122450117",
                "umur": "21 Tahun",
                "asal": "Bukittinggi",
                "alamat": "Korpri ",
                "hobbi": " ML (Machine Learning)",
                "sosmed": "@here.am.ai",
                "kesan": "Abangnya lucu",
                "pesan": "Semangat ngaspraknya bang :D",
            },
            {
                "nama": "Deva Anjani Khayyuninafsyah",
                "nim": "122450014",
                "umur": "21 Tahun",
                "asal": " Bandar Lampung",
                "alamat": "Kemiling",
                "hobbi": "Menonton Film",
                "sosmed": "@anjaniiidev",
                "kesan": "Kakak cantik banget",
                "pesan": "Semanagat kuliahnya kak",
            },
            {
                "nama": "Dinda Nababan",
                "nim": "122450120",
                "umur": "20 Tahun",
                "asal": "Medan",
                "alamat": "Jl. Lapas",
                "hobbi": "Main Game",
                "sosmed": "@dindanababan_",
                "kesan": "Kakak baik bangettt",
                "pesan": "Semangat ngaspraknya kak :D",
            },
            {
                "nama": "Marleta Cornelia Leander",
                "nim": "122450092",
                "umur": "20 Tahun",
                "asal": "Depok, Jawa Barat",
                "alamat": "Gg. Nangka 3",
                "hobbi": "Liatin Jurnal",
                "sosmed": "@marletacornelia",
                "kesan": "Kakak cantik banget",
                "pesan": "Semangat baca jurnalnya kak",
            },
            {
                "nama": "Rut Junita Sari Siburian",
                "nim": "122450103",
                "umur": "20 Tahun",
                "asal": "Batam, Kep.Riau",
                "alamat": "Gg. Nangka 3",
                "hobbi": "Resume Jurnal",
                "sosmed": "@junitaa_0406",
                "kesan": "Kakaknya berwibawa",
                "pesan": "Semangat kuliahnya kak",
            },
            {
                "nama": "Syadza Puspadari Azhar",
                "nim": " 122450072",
                "umur": "20 Tahun",
                "asal": "Palembang",
                "alamat": "Belwis ",
                "hobbi": "Membaca",
                "sosmed": "@puspadrr",
                "kesan": "Sangat baik hati dan tidak sombong",
                "pesan": "Sehat selalu kak",
            },
            {
                "nama": " Abdurrahman Al-atsary",
                "nim": "121450128",
                "umur": "23 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "Perumnas Way Kandis",
                "hobbi": " Membaca",
                "sosmed": "@rahmn_abdr",
                "kesan": "Keren banget abangnya",
                "pesan": "Semanagat bacanya bang",
            },
            {
                "nama": "Aditya Rahman",
                "nim": "122450113",
                "umur": "20 Tahun",
                "asal": " Lampung Timur",
                "alamat": "Korpri",
                "hobbi": "Ngoding WISATA",
                "sosmed": "@rahm_adityaa",
                "kesan": "Ramah banget ",
                "pesan": "Semangat kuliahnya bang",
            },
            {
                "nama": "Eggi Satria",
                "nim": "122450032",
                "umur": "20 Tahun",
                "asal": "Sukabumi",
                "alamat": "Korpri",
                "hobbi": "Ngoding dan buat konten WISATA",
                "sosmed": "@egistr ",
                "kesan": "Baik bangett",
                "pesan": "WISATA keren banget bang ",
            },
            {
                "nama": "Febiya Jomy Pratiwi",
                "nim": "122450074",
                "umur": "20 Tahun",
                "asal": "Tulang Bawang",
                "alamat": "Jl Kelengkeng Raya",
                "hobbi": "Nonton K-Drama ",
                "sosmed": "@pratiwifebiya",
                "kesan": "Cantik kakaknya",
                "pesan": "Selamat menonton kak",
            },
            {
                "nama": "Happy Syahrul Ramadhan",
                "nim": "122450013",
                "umur": "20 Tahun",
                "asal": "Lampung",
                "alamat": "Karang Anyar ",
                "hobbi": " Main Game",
                "sosmed": "@sudo.syahrulramadhannn",
                "kesan": "baik banget",
                "pesan": "Semangat kuliahnya bang",
            },
            {
                "nama": "Randa Andriana Putra",
                "nim": "122450083",
                "umur": "21 Tahun",
                "asal": "Banten",
                "alamat": " Sukarame",
                "hobbi": " Tidur dan Berkembang",
                "sosmed": "@randaandriana_",
                "kesan": "PJ tugas paling kece :D",
                "pesan": "Semangat kuliahnya bang",
            },
            {
                "nama": "Annisa Novantika",
                "nim": "121450005",
                "umur": "21 Tahun",
                "asal": "Lampung Utara",
                "alamat": "Jl. Pulau Sebesi, Sukarame",
                "hobbi": " Memasak",
                "sosmed": "@anovavona",
                "kesan": "kakaknya baik",
                "pesan": "semangat kuliahnya kak",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Mikfes()

elif menu == "Departemen Eksternal":
    def Eksternal():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1QOwjGz_K1qeKlPRGldnKr4F19QGFpK-i",
            "https://drive.google.com/uc?export=view&id=1QNw1DXQq6eoZgy-rYD4574pvvIYQG4W5",
            "https://drive.google.com/uc?export=view&id=1QLliY5qEAJFbhRU3oN6qmTVmNaBUdY5Z",
            "https://drive.google.com/uc?export=view&id=1QZgdBMY1Szywx9k_ByXH-7qkgVkvTzTZ",
            "https://drive.google.com/uc?export=view&id=1QXBGqymQFPr3R2OEK09c8KQtPGjrd3dS",
            "https://drive.google.com/uc?export=view&id=1QV8_cBM80CiUf1HaD9pb-VqGMUtmsf3E",
            "https://drive.google.com/uc?export=view&id=1QI6vYMI956BIwxXpq_RWdChtna4bDWvx",
            "https://drive.google.com/uc?export=view&id=1QEDf3vJcrgGa8obgylydDjY53bkQGodY",
            "https://drive.google.com/uc?export=view&id=1Q0blZintMqrNiOvh2JMmEKvrOREB3WpB",
            "https://drive.google.com/uc?export=view&id=1PuhE62rrW8-ZMQT_EZtURcisr9xE6qwU",
            "https://drive.google.com/uc?export=view&id=1PtrVqYdgfunJvvEkHBiFxU7iVt7Lpxi6",
            "https://drive.google.com/uc?export=view&id=1Q1Y2dngk8ErLaW1f6bsq5jW15wKz8SkA",
            "https://drive.google.com/uc?export=view&id=1QFVRGm7GUeU7Z98z5a6zNB3NvBHXQVAH",
            "https://drive.google.com/uc?export=view&id=1PzWuQ8_z3R07Q8l1G0tew6GsftQJMXpo",
            "https://drive.google.com/uc?export=view&id=1Q8H1om-CvsQtO-QZ1__bWKfi2w_cGYFN",
            "https://drive.google.com/uc?export=view&id=1PvnvrsrVu-p6MapOwNuwYwS-SyrT53sj",

        ]
        data_list = [
            {
                "nama": "Yogy Sea Tama",
                "nim": "121450041",
                "umur": "21",
                "asal": "Tangerang",
                "alamat": "Jatimulyo",
                "hobbi": "Ngisi Bensin",
                "sosmed": "@yogyyyyyyy",
                "kesan": "Abangnya kece bangett",
                "pesan": "Semangat menjalani hari-hari dan Persiapan TA nya ya bang!!", 
            },
            {
                "nama": "Ramadhita Asifa Hendri",
                "nim": "121450131",
                "umur": "21",
                "asal": "Rajabasa",
                "alamat": "Rajabasa",
                "hobbi": "Belajar",
                "sosmed": "@Ramadhitaasifa",
                "kesan": "kakanya keren banget!!",
                "pesan": "Semangat menjalani ahri-hari dan Persiapan TA nya kak!!",
            },
            {
                "nama": "Nazwa Nabilla",
                "nim": "121450112",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Way Kandis",
                "hobbi": "Belajar dengan Rajin",
                "sosmed": "@nazwanbilla",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan Persiapan TA nya kak!!",
            },
            {
                "nama": "Dea Mutia Risani",
                "nim": "122450099",
                "umur": "20",
                "asal": "Sumatera Barat",
                "alamat": "Korpri",
                "hobbi": "Bikin Surat",
                "sosmed": "@deaa.rsn",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Novelia Adinda",
                "nim": "122450104",
                "umur": "21",
                "asal": "Jakarta",
                "alamat": "Belwis",
                "hobbi": "Tidur",
                "sosmed": "@nvliadinda",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Ratu Keisha Jasmin Deonova",
                "nim": "122450106",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Way Kandis",
                "hobbi": "Ngerjain ADW",
                "sosmed": "@jasminednva",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Tobias David Monogari",
                "nim": "121450081",
                "umur": "20",
                "asal": "Jakarta Barat",
                "alamat": "Pemda",
                "hobbi": "Bikin Puisi",
                "sosmed": "@tobiassiagian",
                "kesan": "abangnya kece banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya bang!!",
            },
            {
                "nama": "Rizki Adrian Bennovry",
                "nim": "121450073",
                "umur": "21",
                "asal": "Bekasi",
                "alamat": "TVRI",
                "hobbi": "Buat Portopolio",
                "sosmed": "@rzkdrnnn",
                "kesan": "Abangnya kece banget",
                "pesan": "Semangat menjalani hari-hari dan persiapan TA nya bang!!",
            },
            {
                "nama": "Arafi Ramadhan Maulana",
                "nim": "12245022",
                "umur": "20",
                "asal": "Jogja, Depok",
                "alamat": "Way Huwi",
                "hobbi": "menghafal al-quran",
                "sosmed": "@arafiramadhanmaulana",
                "kesan": "Abangnya kece banget",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya bang!!",
            },
            {
                "nama": "Asa Do'a Uyi",
                "nim": "122450005",
                "umur": "20",
                "asal": "Muara",
                "alamat": "Korpri",
                "hobbi": "cuci baju",
                "sosmed": "@u_yippy",
                "kesan": "kakaknya keren banget",
                "pesan": "semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Chalifia Wananda",
                "nim": "122450076",
                "umur": "20",
                "asal": "Padang",
                "alamat": "sukarame",
                "hobbi": "Quality Time",
                "sosmed": "@chipawww",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Irvan Alfaritzi",
                "nim": "122450093",
                "umur": "21",
                "asal": "Sumatera Barat",
                "alamat": "Jakarta",
                "hobbi": "Nonton Youtube dan main ML",
                "sosmed": "@Alfaritziirfan",
                "kesan": "Abangnya kece banget",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya bang",
            },
            {
                "nama": "Izza Lutfia",
                "nim": "122450090",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Teluk",
                "hobbi": "main vollly",
                "sosmed": "@izzalutfiaa",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Khaalishah Zuhrah ALyaa Valefi",
                "nim": "122450034",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Rajabasa",
                "hobbi": "Nyanyi",
                "sosmed": "@alyaavalefi",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Raid Muhammad Naufal",
                "nim": "122450027",
                "umur": "20",
                "asal": "Lampung Tengah",
                "alamat": "Sukarame",
                "hobbi": "Ngeresume Seminar",
                "sosmed": "@rayHis_",
                "kesan": "Abangnya kece banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya bang!!",
            },
            {
                "nama": "Tria Yunanni",
                "nim": "122450062",
                "umur": "20",
                "asal": "Way Kanan",
                "alamat": "Jakarta",
                "hobbi": "Baca",
                "sosmed": "@tria_y062",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Eksternal()
elif menu == "Departemen Internal":
    def Internal():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1ArM1w1voGx7t7h2EBj0FBzjLk13MvlCF",
            "https://drive.google.com/uc?export=view&id=19p8250lw9Su0OpXPlhw94cN_RsjjLhNe",
            "https://drive.google.com/uc?export=view&id=1AU2-ypgUv-n6owdpx6-r6g4dn38cRayn",
            "https://drive.google.com/uc?export=view&id=1AFPH03yiWMQBjmKJjkainSLaLbRfe7zV",
            "https://drive.google.com/uc?export=view&id=1AQ3USMnoCpfeuGDWGNQePgSSdswUwpeO",
            "https://drive.google.com/uc?export=view&id=1AtTjXmkd57UH5ozen4BjJM92ouSmA0sM",
            "https://drive.google.com/uc?export=view&id=1Ap_LDvBC361tqSMqbqVv-KIEWVAAPA-y",
            "https://drive.google.com/uc?export=view&id=1AkwKsukVNuSAo27kbDu_9UY8YCPY2HRk",
            "https://drive.google.com/uc?export=view&id=1AbgCz22bQeF9zXMjbuEPc5-sDec5B5h-",
            "https://drive.google.com/uc?export=view&id=1Arj2O3NiiDYXw4Y_0lcs_1GGNH01f0nM",
            "https://drive.google.com/uc?export=view&id=1AKHPM_lDBXIcHGWR05pHXsDvMyF_Vhhf",
            "https://drive.google.com/uc?export=view&id=19xnKqzNnW7jPHL4qUVY6TL-ACWim1CQq",
            "https://drive.google.com/uc?export=view&id=1ArS9FrW2gMiFaLhI7058B9GAWEfo3jUS",
        ]
        data_list = [
             {
                "nama": "Dimas rizky ramadhani",
                "nim": "121450027",
                "umur": "20",
                "asal": "Pamulang",
                "alamat": "Way kandis",
                "hobbi": "Manjat tower sutet",
                "sosmed": "@dimzrky",
                "kesan": "Berkharisma banget",
                "pesan": "Semangat nyusun TA nya bang dimas", 
            },
            {
                "nama": "Catherine firdhasari maulina sinaga",
                "nim": "121450072",
                "umur": "20",
                "asal": "Sumatera Utara",
                "alamat": "Airan",
                "hobbi": "Baca novel",
                "sosmed": "@chatherine.sinaga",
                "kesan": "kakanya ramah bintang 100",
                "pesan": "Semangat berproses kak",
            },    
            {
                "nama": "M. Akbar resdika",
                "nim": "121450066",
                "umur": "20",
                "asal": "Lampung Barat",
                "alamat": "Labuhan dalam",
                "hobbi": "Memelihara dino",
                "sosmed": "@akbar_resdika",
                "kesan": "Kelihatannya baik (emot senyum)",
                "pesan": "Semangat nyusun TA bang",
            },
            {
                "nama": "Rani puspita sari",
                "nim": "122450030",
                "umur": "20",
                "asal": "Metro",
                "alamat": "Rajabasa",
                "hobbi": "Mengaji",
                "sosmed": "@ranipu",
                "kesan": "Kakak baik",
                "pesan": "Selalu bermanfaat untuk orang sekitar ya kak",
            },
            {
                "nama": "Rendra eka prayoga",
                "nim": "122450112",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Jalan lapas raya",
                "hobbi": "nulis lagu",
                "sosmed": "@rendraepr",
                "kesan": "Ramah bintang 1000",
                "pesan": "Semoga jadi pribadi yang lebih baik lagi ",
            },
            {
                "nama": "Salwa farhanatussaidah",
                "nim": "122450055",
                "umur": "20",
                "asal": "Pesawaran",
                "alamat": "Airan raya",
                "hobbi": "ngeliat cogan",
                "sosmed": "@slwfhn_694",
                "kesan": "Cantik bangett",
                "pesan": "semangat kuliahnya kak",
            },
            {
                "nama": "Ari sigit",
                "nim": "121450069",
                "umur": "23",
                "asal": "Lampung barat",
                "alamat": "Labuhan ratu",
                "hobbi": "Main futsal",
                "sosmed": "@ari_sigit17",
                "kesan": "keren banget abangnya",
                "pesan": "semangat kuliahnya bang ari",
            },
            {
                "nama": "Azizah kusumah putri",
                "nim": "122450068",
                "umur": "21",
                "asal": "Lampung Selatan",
                "alamat": "Natar",
                "hobbi": "berkebun",
                "sosmed": "@azizahksmh15",
                "kesan": "Ramah bangett",
                "pesan": "Semangkaaa semangat kakak!!!",
            },
            {
                "nama": "Meira listyaningrum",
                "nim": "122450011",
                "umur": "20",
                "asal": "Pesawaran",
                "alamat": "Airan raya",
                "hobbi": "Menghalu",
                "sosmed": "@meiraln",
                "kesan": "Baik bangett",
                "pesan": "Semangat kakk!!!",
            },
            {
                "nama": "Rendi alexander hutagalung",
                "nim": "122450057",
                "umur": "20",
                "asal": "Tangerang",
                "alamat": "Kost gunawan",
                "hobbi": "Menyanyi",
                "sosmed": "@alexanderr",
                "kesan": "Baik bangett",
                "pesan": "jangan pentang menyerah,selalu berusaha",
            },
            {
                "nama": "Renta siahaan",
                "nim": "122450070",
                "umur": "21",
                "asal": "Sumatera utara",
                "alamat": "Gerbang barat",
                "hobbi": "Memancing",
                "sosmed": "@renta.shn",
                "kesan": "Keren banget",
                "pesan": "selalu semangat kakak ",
            },
            {
                "nama": "Yosia lehare banurea",
                "nim": "121450149",
                "umur": "20",
                "asal": "Dairi, Sumatera utara",
                "alamat": "Perum griya indah",
                "hobbi": "Bawa motor pakai kaki",
                "sosmed": "@yosiabanurea",
                "kesan": "Baik bangett",
                "pesan": "semangat kakak!!!",
            },
            {
                "nama": "Josua panggabean",
                "nim": "121450061",
                "umur": "21",
                "asal": "Pematang siantar",
                "alamat": "Gya kost",
                "hobbi": "Ngawinin cupang",
                "sosmed": "@josuapanggabean16_",
                "kesan": "sangat soft spoken",
                "pesan": "semangat kuliah bang",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Internal()
elif menu == "Departemen SSD":
    def Ssd():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1BZM6qsE06Ht7r0WrTJfvTcIDk_fRhlhc",
            "https://drive.google.com/uc?export=view&id=1BTnMdpqaOpRvmc26r0bhycGj8fyxHrIm",
            "https://drive.google.com/uc?export=view&id=1BRm9fHDrApt7FU8wIeFgyKy7n0MQlnNz",
            "https://drive.google.com/uc?export=view&id=1BVNXctSvEFcv7QCgM6AFEzCRKgojGdJp",
            "https://drive.google.com/uc?export=view&id=1Az4wlRvJYSSP6BC0cyVNYqL_TZgdEH1k",
            "https://drive.google.com/uc?export=view&id=1BZg5Dd5uHdGdtDAC4QMN2GpJS85DW107",
            "https://drive.google.com/uc?export=view&id=1BRgXjp3o16XcO1NW5oZlDiag8jRGBo8Y",
            "https://drive.google.com/uc?export=view&id=1BKFs50f_7hvWkp1gfU59yo3EDeLNl1Fu",
            "https://drive.google.com/uc?export=view&id=1Az744NsaGKrF37PqpBHi8ArIVKhdJLmx",
            
        ]
        data_list = [
            {
                "nama": "Andrian Agustinus Lumban Gaol",
                "nim": "121450090",
                "umur": "17 +",
                "asal": "Sidikalang",
                "alamat": "Lapas",
                "hobbi": "Nyari Hobi",
                "sosmed": "@andrialgaol",
                "kesan": "Public speakingnya bagus bangett",
                "pesan": "Semangat cari duitnya bang", 
            },
            {
                "nama": "Adisty Syawaida Ariyanto",
                "nim": "121450136",
                "umur": "21",
                "asal": "Metro",
                "alamat": "Metro",
                "hobbi": "Nonton film",
                "sosmed": "@adistisa_",
                "kesan": "Keren banget kak",
                "pesan": "Semangat kuliahnya kak",
            },
            {
                "nama": "Nabila Azhari",
                "nim": "121450029",
                "umur": "21",
                "asal": "Simalungun",
                "alamat": "Airan",
                "hobbi": "Menghitung",
                "sosmed": "@zhjung",
                "kesan": "seru banget kakaknya",
                "pesan": "Menjadi pribadi yang lebih baik kedepannya",
            },
            {
                "nama": "Danang Hilal Kurniawan",
                "nim": "122450085",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "TB 3 Asrama",
                "hobbi": "Belajar",
                "sosmed": "@dananghk_",
                "kesan": "abangnya keren banget menginsprirasi",
                "pesan": "Semangat ngaspraknya bang",
            },
            {
                "nama": "Farel Julio Akbar",
                "nim": "122450110",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Jalan Lapas",
                "hobbi": "Bebas",
                "sosmed": "@farel__julio",
                "kesan": "Abangnya ramah banget",
                "pesan": "Semangat abang kapo",
            },
            {
                "nama": "Nabilah Andika Fitriani",
                "nim": "121450129",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Kedaton",
                "hobbi": "Tidur",
                "sosmed": "@nabilaafrn",
                "kesan": "Sharing ilmunya keren banget",
                "pesan": "Semangat kuliahnya kak",
            },
            {
                "nama": "Alvia Asrinda Br.Ginting",
                "nim": "122450077",
                "umur": "20",
                "asal": "Binjai",
                "alamat": "Korpri",
                "hobbi": "Nonton Windah",
                "sosmed": "@alviaginting",
                "kesan": "Terimakasih insightnya kak",
                "pesan": "Semangat kuliahnya kak",
            },
            {
                "nama": "Dhafin Razaka Luthfia",
                "nim": "122450133",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Jalan nangka 1",
                "hobbi": "Olahraga",
                "sosmed": "@dhafinrzqri3",
                "kesan": "Terimakasih ilmunya kak",
                "pesan": "Semangat kuliahnya ya kak",
            },
            {
                "nama": "Elia Meylani Simanjuntak ",
                "nim": "122450026",
                "umur": "20",
                "asal":"Bekasi",
                "alamat": "Korpri",
                "hobbi": "Nyanyi",
                "sosmed": "@meylaniellia",
                "kesan": "kakak cantik banget, manis, terus ramah dan baik, seruu",  
                "pesan":"semangat kuliahnya kak"
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Ssd()

# Tambahkan menu lainnya sesuai kebutuhan
