import streamlit as st
from streamlit_option_menu import option_menu
import requests
from PIL import Image, ImageOps
from io import BytesIO

st.markdown("""<style>.centered-title {text-align: center;}</style>""",unsafe_allow_html=True)
st.markdown("<h1 class='centered-title'>BUKU KATING</h1>", unsafe_allow_html=True)

# bagian sini jangan diubah
def streamlit_menu():
    selected = option_menu(
        menu_title=None,
        options=[
            "Kesekjenan",
            "Baleg",
            "Senator",
            "Departemen PSDA",
            "Departemen MEDCRAF",
            "Departemen MIKFES",
            "Departemen Eksternal",
            "Departemen Internal",
            "Departemen SSD",
        ],
        icons=[
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
        ],
        default_index=0,
        orientation="horizontal",
        styles={
            "container": {"padding": "0!important", "background-color": "#fafafa"},
            "icon": {"color": "black", "font-size": "19px"},
            "nav-link": {
                "font-size": "15px",
                "text-align": "left",
                "margin": "0px",
                "--hover-color": "#eee",
            },
            "nav-link-selected": {"background-color": "#3FBAD8"},
        },
    )
    return selected

@st.cache_data
def load_image(url):
    response = requests.get(url)
    if response.status_code != 200:
        st.error(
            f"Failed to fetch image from {url}, status code: {response.status_code}"
        )
        return None
    try:
        img = Image.open(BytesIO(response.content))
        img = ImageOps.exif_transpose(img)
        img = img.resize((300, 400))
        return img
    except Exception as e:
        st.error(f"Error loading image: {e}")
        return None
    
@st.cache_data
def display_images_with_data(gambar_urls, data_list):
    images = []
    for i, url in enumerate(gambar_urls):
        with st.spinner(f"Memuat gambar {i + 1} dari {len(gambar_urls)}"):
            img = load_image(url)
            if img is not None:
                images.append(img)

    for i, img in enumerate(images):
        # Menggunakan Streamlit untuk menampilkan gambar di tengah kolom
        col1, col2, col3 = st.columns([1, 2, 1])
        with col2:
            st.image(img, use_column_width=True)

        if i < len(data_list):
            st.write(f"Nama: {data_list[i]['nama']}")
            st.write(f"NIM: {data_list[i]['nim']}")
            st.write(f"Umur: {data_list[i]['umur']}")
            st.write(f"Asal: {data_list[i]['asal']}")
            st.write(f"Alamat: {data_list[i]['alamat']}")
            st.write(f"Hobbi: {data_list[i]['hobbi']}")
            st.write(f"Sosial Media: {data_list[i]['sosmed']}")
            st.write(f"Kesan: {data_list[i]['kesan']}")
            st.write(f"Pesan: {data_list[i]['pesan']}")
            st.write("  ")
    st.write("Semua gambar telah dimuat!")
menu = streamlit_menu()

# BAGIAN SINI YANG HANYA BOLEH DIUABAH
if menu == "Kesekjenan":
    def kesekjenan():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1K-Mb7QcEJtdmADdy7bnIKzhGlOA-Rrpb",
            "https://drive.google.com/uc?export=view&id=1MfzFXfPq9zzp09IdOQudezhyy0iAw5LG",
            "https://drive.google.com/uc?export=view&id=1PH9FaszLQyoeiIz4qVk0CJ1vrB5Mf9p-",
            "https://drive.google.com/uc?export=view&id=1mTyqFWwLfoOlWMax2zeB22mS6AX_36vV",
            "https://drive.google.com/uc?export=view&id=13B6154zsrRX419a0nZM3y8P__3tpVfzR",
            "https://drive.google.com/uc?export=view&id=1O49loCksGwswHL9JpiR8rDpHPh1RCHdx",
        ]
        data_list = [
            {
                "nama": "Kharisma Gumilang",
                "nim": "121450042",
                "umur": "21",
                "asal": "Palembang",
                "alamat": "Jl.Pulau Damar",
                "hobbi": "Dengerin Musik",
                "sosmed": "@gumilangkharisma",
                "kesan": "Berkharisma dan Energetic",  
                "pesan":"Semangat buat TA nya, sehat selalu!"# 1
            },
            {   
                "nama": "Pandra Insani Putra Anwar",
                "nim": "121450147",
                "umur": "21",
                "asal":"Lampung Utara",
                "alamat": "Sukarame",
                "hobbi": "Main Gitar",
                "sosmed": "@pandrainsani27",
                "kesan": "Kece abiezzz dan funny",  
                "pesan":"Selalu ganteng bang"# 1
            },
            {   
                "nama": "Meliza Wulandari",
                "nim": "121450065",
                "umur": "20",
                "asal":"Sumatera Selatan",
                "alamat": "Jl.Pagar Alam",
                "hobbi": "Nonton Drakor",
                "sosmed": "@wulandarimeliza",
                "kesan": "Positive energy dan good listener",  
                "pesan":"semangat ngaspraknya kak !!!"# 1
            },
        
            {
                "nama": "Putri Maulida Chairani",
                "nim": "121450050",
                "umur": "21",
                "asal":"Sumatera Barat",
                "alamat": "Gg. Nangka 4",
                "hobbi": "Dengerin Bg Pandra Main Gitar",
                "sosmed": "@ptrimaulidaaa_",
                "kesan": "Cantik dan rendah hati ",  
                "pesan":"Semoga selalu baik hati kak"# 1
            },
        
            {   
                "nama": "Hartiti Fadilah",
                "nim": "121450031",
                "umur": "21",
                "asal":"Palembang",
                "alamat": "Pemda",
                "hobbi": "Nyanyi",
                "sosmed": "@htrpdla",
                "kesan": "lucu, keren",  
                "pesan":"Semangat ngurus duitnya kak"# 1
            },
        
            {
                "nama": "Nadilla Andhara Putri",
                "nim": "121450003",
                "umur": "21",
                "asal":"Lampung",
                "alamat": "Metro",
                "hobbi": "Belajar",
                "sosmed": "@nadilaandr26",
                "kesan": "lucu",  
                "pesan":"Semangat ngasprak strukdatnya!"# 1
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    kesekjenan()

elif menu == "Baleg":

    def Baleg():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
        ]
        data_list = [
            {
                "nama": "Tri Murniya Ningsih",
                "nim": "121450038",
                "umur": "21",
                "asal": "Bogor",
                "alamat": "Raden Saleh",
                "hobbi": "Tanya sama GPT",
                "sosmed": "@trimurniaa",
                "kesan": "Kakaknya humble banget, cantik, baik, adaptif dan inspiratif",
                "pesan": "semangat kuliahnya kakak",
            },
            {
                "nama": "Annisa Cahyani Surya",
                "nim": "121450114",
                "umur": "21",
                "asal": "Tangerang Selatan",
                "alamat": "Way Huwi",
                "hobbi": "Puasa Senin Kamis",
                "sosmed": "@annisacahyanisurya",
                "kesan": "Baik banget kakaknya, humble",
                "pesan": "Semangat kuliahnya kak", 
            },
            {
                "nama": "Wulan Sabina",
                "nim": "121450150",
                "umur": "21",
                "asal": "Medan",
                "alamat": "Raden Saleh",
                "hobbi": "Menonton film",
                "sosmed": "wlsbn0",
                "kesan": "Ramah banget kakanya, baikk ",
                "pesan": "semangat ya kak, tetap ramahh", 
            },
            {
                "nama": "Anisa Dini Amalia",
                "nim": "121450021",
                "umur": "20",
                "asal": "Tangerang",
                "alamat": "Jati Agung",
                "hobbi": "Baca Webtoon",
                "sosmed": " @anisadini10",
                "kesan": "Kakaknya ramahh, asik,baik",
                "pesan": "semangat terus kuliahnya kakak", 
            },
            {
                "nama": "Anisa Fitriyani",
                "nim": "122450019",
                "umur": "20",
                "asal": "Batam",
                "alamat": "Kalianda",
                "hobbi": "Membaca Al waqiah setiap magrib",
                "sosmed": " @ansftynn_",
                "kesan": "Manis banget kakaknya",
                "pesan": "Tetap baik hati kak", 
            },
            {
                 "nama": "Feryadi Yulius ",
                "nim": "122450087",
                "umur": "20",
                "asal": "Padang",
                "alamat": "Belwis",
                "hobbi": "Sholat Dhuha",
                "sosmed": "@fer_yulius",
                "kesan": "Abangnya kece",
                "pesan": "semangat kuliahnya kak, semoga lulus tepat waktu", 
            },
            {
                "nama": "Renisha Putri Giani",
                "nim": "122450079",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Teluk Betung",
                "hobbi": "Baca Al-Qur'an",
                "sosmed": "@fleurnsh",
                "kesan": "pertahankan hobinya kak",
                "pesan": "Semangat kuliahnya",
            },
            {
                "nama": "Claudhia Angeliani",
                "nim": "121450124",
                "umur": "21",
                "asal": "Lampung Timur",
                "alamat": "Lampung Timur",
                "hobbi": "Baca Jurnal",
                "sosmed": " @dylebee",
                "kesan": "Kakanya cantik",
                "pesan": "semangat ya kuliahnya kak", 
            },
            {
                "nama": "Mirzan Yusuf Rabbani",
                "nim": "122450118",
                "umur": "20",
                "asal": "Jakarta",
                "alamat": "Korpri",
                "hobbi": "Main Kucing",
                "sosmed": "@myrrinn",
                "kesan": "Abangnya baik, kalem, cool dan ramah",
                "pesan": "Semangat kuliahnya bang", 
            },
            {
                "nama": "Dhea Amelia Putri",
                "nim": "122450004",
                "umur": "20 tahun",
                "asal": "Ogan Ilir",
                "alamat": "Natar",
                "hobbi": "Nyari Sinyal di Gedung F",
                "sosmed": " @_.dheamelia",
                "kesan": "Kakaknya kelihatan aktif organisasi bangettt",
                "pesan": "Semangat menjalani hari kak", 
            },
            {
                "nama": "Muhammad Fachrul Aditya",
                "nim": "121450156",
                "umur": "22",
                "asal": "Surakarta",
                "alamat": "Sukarame",
                "hobbi": "Sholat Malam",
                "sosmed": "@fhrul.pdf",
                "kesan": "Abangnya keliatan soleh ya rajin sholat malam",
                "pesan": "semangat kuliahnya kak, tetap pertahankan rajin sholat malamnya", 
            },
             {
                "nama": "Jeremia Susanto",
                "nim": "122450022",
                "umur": "21",
                "asal": "Palembang",
                "alamat": "Bilabong",
                "hobbi": "Cerita",
                "sosmed": "@jeremia_s_",
                "kesan": "Abangnya asik banget",
                "pesan": "semangat yang mulia", 
            }, 
            {
                "nama": " Berliana Enda Putri",
                "nim": "122450065",
                "umur": "20",
                "asal": "Sumatera Barat",
                "alamat": "Way Huwi",
                "hobbi": "Baca Buku, Ngoding, Ibadah",
                "sosmed": "@berlyyanda",
                "kesan": "Abangnya keliatan soleh dan rajin sholat ",
                "pesan": "semangat kuliahnya kak, tetap pertahankan rajin sholat malamnya", 
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Baleg()

elif menu == "Senator":
    def senator():
        gambar_urls = [
            "https://drive.google.com/file/d/153XRrsS0UtZIfseYsxt4t_jjJ3orSaLz/view?usp=drive_link_",
            "https://drive.google.com/file/d/11NwTYhM_qrsochiBVPuvWbjPvNS1rcQh/view?usp=drive_link",
            
        ]
        data_list = [
            {
                "nama": "Anissa Luthfi Alifia",
                "nim": "121450093",
                "umur": "22",
                "asal": "Lampung Tengah",
                "alamat": "Kost Putri Rahayu",
                "hobbi": "Dengerin bintang nyanyi",
                "sosmed": "@anissalutfi_",
                "kesan": "kak upii keren banget, public speakingnya good, sangat inspiratif",
                "pesan": "Semangat kak, terimakasih telah menjadi contoh yang baik, sukses selalu", 
            },
            {
                "nama": "Rian Bintang Wijaya",
                "nim": "122450094",
                "umur": "20",
                "asal": "Palembang",
                "alamat": "Kota Baru",
                "hobbi": "Nyanyi",
                "sosmed": "@bintangtwinkle",
                "kesan": "Bang Bintang keren, sangat menginspirasi",
                "pesan": "Terimakasih telah memberikan motivasi",
            }
        ]
        display_images_with_data(gambar_urls, data_list)
    senator()

elif menu == "Departemen PSDA":
    def Psda():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
        ]
        data_list = [
            {
                "nama": "Ericson Chandra Sihombing",
                "nim": "121450026",
                "umur": "21",
                "asal": "Bekasi",
                "alamat": "Khobam",
                "hobbi": "Travelling",
                "sosmed": "@ericsonchandr99",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari", 
            },
            {
                "nama": "Elisabeth Claudia Simanjuntak",
                "nim": "122450123",
                "umur": "20",
                "asal": "Tanggerang",
                "alamat": "Owen Kost",
                "hobbi": "Bernafas",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
            {
                "nama": "Nisrina Nur Afifah",
                "nim": "122450123",
                "umur": "19",
                "asal": "Bekasi",
                "alamat": "Sukarame",
                "hobbi": "Menonton",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
            {
                "nama": "",
                "nim": "122450123",
                "umur": "20",
                "asal": "Tanggerang",
                "alamat": "Owen Kost",
                "hobbi": "Bernafas",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
            {
                "nama": "",
                "nim": "122450123",
                "umur": "20",
                "asal": "Tanggerang",
                "alamat": "Owen Kost",
                "hobbi": "Bernafas",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
            {
                "nama": "",
                "nim": "122450123",
                "umur": "20",
                "asal": "Tanggerang",
                "alamat": "Owen Kost",
                "hobbi": "Bernafas",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
            {
                "nama": "",
                "nim": "122450123",
                "umur": "20",
                "asal": "Tanggerang",
                "alamat": "Owen Kost",
                "hobbi": "Bernafas",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
            {
                "nama": "",
                "nim": "122450123",
                "umur": "20",
                "asal": "Tanggerang",
                "alamat": "Owen Kost",
                "hobbi": "Bernafas",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
            {
                "nama": "",
                "nim": "122450123",
                "umur": "20",
                "asal": "Tanggerang",
                "alamat": "Owen Kost",
                "hobbi": "Bernafas",
                "sosmed": "",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Psda()

elif menu == "Departemen MEDKRAF":

    def Medkraf():
        gambar_urls = ["https://drive.google.com/file/d/1uXSjy19Kpurk-KnVnEYuzcUDXohnne8q/view?usp=drive_link",
"https://drive.google.com/file/d/1m6eqXfbKCDGinrTIk1vNs1YwhOlBRfhR/view?usp=drive_link",
"https://drive.google.com/file/d/1zYToDlpYPPgopnLDMTWNkQC-DBq35qVy/view?usp=drive_link",
"https://drive.google.com/file/d/1e6DAKEVJUABgNf1E03s9gwrVdJ0Bqn7b/view?usp=drive_link",
"https://drive.google.com/file/d/1ix-1qpSmnpgV47aY_FV078KTSxchH0g6/view?usp=drive_link",
"https://drive.google.com/file/d/1VbjnsviH41IZII5vzDvA65PBRABT5qpa/view?usp=drive_link",
"https://drive.google.com/file/d/1GtsOIQU-Hv73w-Ihvzd-tRHbNeaCRkqs/view?usp=drive_link",
"https://drive.google.com/file/d/1TO9zWz9X57LE5RLJV2iwpDrtPnBeZWgO/view?usp=drive_link",
"https://drive.google.com/file/d/1w-E7Sssw6KHfzduvi_aStPB57vgQb5cW/view?usp=drive_link",
"https://drive.google.com/file/d/1ENOYYaF8AAZfDqfXSlLc5eNCosDJmgYY/view?usp=drive_link"
"https://drive.google.com/file/d/1tMZ-ouHj79TOWQcLSwhXggd5Y_UFNgxy/view?usp=drive_link",
"https://drive.google.com/file/d/1BXseMLcwUTwhstzgxNq0ZbO43KtLQfrf/view?usp=drive_link"
"https://drive.google.com/file/d/12k_IyYSjRVM9G_plWWHO3cJ2M5rukv62/view?usp=drive_link",
"https://drive.google.com/file/d/1o1uIt-_QwyjeDGFJoeYZiO_In-0ZZlRL/view?usp=drive_link",
"https://drive.google.com/file/d/1r7M6WEgpCoxfXguXCQiVnUDramTjXYsT/view?usp=drive_link",

         
        ]
        data_list = [
            {
                "nama": "Wahyudiyanto",
                "nim": "121450040",
                "umur": "22",
                "asal": "Makassar",
                "alamat": "Sukarame",
                "hobbi": "Nonton",
                "sosmed": "",
                "kesan": "Abangnya keren",
                "pesan": "Semangat terus Bang",
            },
            {
                "nama": "Elok Fiola",
                "nim": "122450051",
                "umur": "19",
                "asal": "Bandar Lampung",
                "alamat": "Bandar Lampung",
                "hobbi": "Editing",
                "sosmed": "@elokfiola",
                "kesan": "Manis bangett kakk",
                "pesan": "Semangat ya kak ngumpulin sg nya", 
            },
            {
                "nama": "Muhammad Kaisar Firdaus ",
                "nim": " 121450135",
                "umur": "21",
                "asal": "Pesawaran",
                "alamat": "Pulau Damar",
                "hobbi": "Lagi Nyari",
                "sosmed": " @dino_kiper",
                "kesan": "Cool, kece abiezz",
                "pesan": "Semangat terus Bang", 
            },
            {
                "nama": "Muhammad Arsal Ranjana Putra",
                "nim": "121450111",
                "umur": "21",
                "asal": "Depok",
                "alamat": "Nangka 4",
                "hobbi": "Ngoding",
                "sosmed": "@arsal.utama",
                "kesan": "Sepuh koding, keren",
                "pesan": "Semangat ngodingnya Bang", 
            },
            {
                "nama": "Cintya  Bella",
                "nim": "122450066",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Teluk",
                "hobbi": "Ngegym",
                "sosmed": "@cintyabella28",
                "kesan": "Suka banget sama outfit kakak selalu rapi dan on point",
                "pesan": "Selalu ramah dan sukses selalu kak", 
            },       
{
                "nama": "Patricia Leondra Diajeng Putri ",
                "nim": "122450050",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Jatimulyo",
                "hobbi": "Nonton Film",
                "sosmed": "@patriciadiajeng",
                "kesan": "Kak ciaa cantik, girly bangett",
                "pesan": "Menyala terus kak cantiknya", 
            },
            {
                "nama": "Rahma Neliyana",
                "nim": "122450036",
                "umur": "20",
                "asal": "Lampung",
                "alamat": "Sukarame",
                "hobbi": "Baca Coding",
                "sosmed": "@rahmanellyana",
                "kesan": "Kak nya lucu, keren banget pas nge-mc",
                "pesan": "Semangat terus kak", 
            },
            {
                "nama": "Try Yani Rizki Nur Rohmah ",
                "nim": "122450020",
                "umur": "20",
                "asal": "Lampung Barat",
                "alamat": "Korpri",
                "hobbi": "Bernyanyi dan Menonton",
                "sosmed": "@tryyaniciaaa",
                "kesan": "Kakak nya cantik banget, lucuuu, outfitnya kece, on point",
                "pesan": "Semangat terus kak", 
            },
            {
                "nama": "Gymnastiar Al Khoarizmy",
                "nim": "122450096",
                "umur": "20",
                "asal": "Serang",
                "alamat": "Lapangan Golf UIN",
                "hobbi": "Baca Komik",
                "sosmed": "@jimnn.as",
                "kesan": "Abangnya lucu, keren, anak canon bgt",
                "pesan": "Semangat terus menjalan hari hari ini bang", 
            },
            {
                "nama": "Nasywa Nur Afifah ",
                "nim": "122450125",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Jalan Durian 1 Pemda",
                "hobbi": "Nonton Drakor",
                "sosmed": "@nsywanaf",
                "kesan": "Kakaknyakeliatan soleh",
                "pesan": "semangat kuliahnya kak", 
            },
            {
                "nama": "Abit Ahmad Oktarian",
                "nim": "122450042",
                "umur": "19",
                "asal": "Bandar Lampung",
                "alamat": "Rajabasa, Labuhan Dalam",
                "hobbi": "Ngoding, Gaming",
                "sosmed": "@abitahmad",
                "kesan": "Bang abit keen, sepuh koding",
                "pesan": "Semangat kulih dan ngodingnya bang", 
            },
             {
                "nama": "Akmal Faiz Abdillah",
                "nim": "122450114",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Perumahan Griya Sukarame",
                "hobbi": "Main HP",
                "sosmed": "@_akmal.faiz",
                "kesan": "Keren, sepuh koding",
                "pesan": "Semangat terus bang", 
            },
             {
                "nama": "Hermawan Manurung ",
                "nim": "122450069",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Dekat Jalan Tol (Wisma Hana Hani) ",
                "hobbi": "Bengong/Membaca Buku",
                "sosmed": "@hermawan.mnrng",
                "kesan": "Abangnya keren banget, aura pdd banget",
                "pesan": "Semangat terus jepret jepret nya bang", 
            },
             {
                "nama": "Khusnun Nisa",
                "nim": "122450078",
                "umur": "20",
                "asal": "Lampung Selatan",
                "alamat": "",
                "hobbi": "Mengerjakan Tugas",
                "sosmed": "@khusnun_nisa335",
                "kesan": "Kak khusnun lucu, humble",
                "pesan": "Semangat kak, tetap ramah dan baik hati", 
            },
             {
                "nama": "Priska Silvia Ferantiana",
                "nim": "122450053",
                "umur": "20",
                "asal": "Palembang",
                "alamat": "Jalan Nangka 2",
                "hobbi": "Baca Novel yang Bikin Nangis",
                "sosmed": "@prskslv",
                "kesan": "Kak Priska lucu, baik dan humble",
                "pesan": "Next ganti genre novel kak, jangan nangis mulu, semangat kak", 
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Medkraf()

elif menu == "Departemen MIKFES":

    def Mikfes():
        gambar_urls = [
            "https://drive.google.com/file/d/1XvWdYZtsp-gCapdkXuRoI-d7EGfbX6fH/view?usp=drive_link",
            "https://drive.google.com/file/d/15omJKQNiFuDfpUpEETHsgAMTSQTAwScd/view?usp=drive_link",
            "https://drive.google.com/file/d/1gg6yz-675ULyJ39y3nQemArWx-GRbw2K/view?usp=drive_link",
            "https://drive.google.com/file/d/1s2wXl5u53SSnXV-MA_8hpV2ISW4oxx02/view?usp=drive_link",
            "https://drive.google.com/file/d/1EcYOmIQ1pnCn_DYoSgGrljwhGBOHLgSF/view?usp=drive_link",
            "https://drive.google.com/file/d/1Q5pxm0Kslvh6ewmD2bP0mWnFwOmQz7uR/view?usp=drive_link",
            "https://drive.google.com/file/d/1vRA6kRgrX8Xsv-HpDUJhm2ID6MGVVhaK/view?usp=drive_link",
            "https://drive.google.com/file/d/1VV1JDpDdEj4ka4LzdrStrCo_8hlj3JgJ/view?usp=drive_link",
            "https://drive.google.com/file/d/1Cj6Na9XAJVMk66RHuZhHWCbkqx0yBpm9/view?usp=drive_link",
            "https://drive.google.com/file/d/1zYPCRWdwupJ5qypwvIfM7PnxugHkuxXY/view?usp=drive_link",
            "https://drive.google.com/file/d/1SvRLRIXtxIsvpaT7PX2Ds9BMlvgyPZL6/view?usp=drive_link",
            "https://drive.google.com/file/d/1EOml8ZrLKpJSoigiRi9yC1Frn0S3gtOT/view?usp=drive_link",
            "https://drive.google.com/file/d/1hmu5Ek2sQTCgRVLPkK-UBZsMqCIsCZSz/view?usp=drive_link",
            "https://drive.google.com/file/d/1NWSLg89N1pxdGq8dyOKq6Sbqc482LLMc/view?usp=drive_link",
            "https://drive.google.com/file/d/1jJUvVcGeHXvtJefFDmyj-ppU0S2-EfEi/view?usp=drive_link",
            "https://drive.google.com/file/d/12aIzSDImAVUEhot1uctwY6R-mRG_mP06/view?usp=drive_link",
            "https://drive.google.com/file/d/13pCmE4QcFm-HnnbPAzPkFyc9rPuNDEX-/view?usp=drive_link",
            "https://drive.google.com/file/d/1Ffr1-3tmin9lKs3oYAC-9J3_hpYQTIET/view?usp=drive_link",
            "https://drive.google.com/file/d/1Zyh2xX4rH_qLlOzq6frxtoscQphW0XqI/view?usp=drive_link",

        ] 
        data_list = [
            {
                "nama": "Rafi Fadhlillah",
                "nim": "121450143",
                "umur": "21 Tahun",
                "asal": "Lubuk Linggau",
                "alamat": "Jl. Nangka 4",
                "hobbi": "Olahraga",
                "sosmed": "@rafadhilillahh13",
                "kesan": "Abangnya keren, berwibawa",
                "pesan": "Semangat terus Bang",
            },
            {
                "nama": "Annisa Novantika",
                "nim": "121450005",
                "umur": "21 Tahun",
                "asal": "Lampung Utara",
                "alamat": "Jl. Pulau Sebesi, Sukarame",
                "hobbi": " Memasak",
                "sosmed": "@anovavona",
                "kesan": "Kak Anova cantik dan lucuuu",
                "pesan": "Entar kita masak bareng yuk kak, hobi kita sama hehe",
            },
            {
                "nama": " Ahmad Sahidin Akbar",
                "nim": "122450044",
                "umur": " 20",
                "asal": "Tulang Bawang",
                "alamat": " Sukarame",
                "hobbi": "Olahraga",
                "sosmed": "@sahid22__",
                "kesan": "Lucu,murah senyum dan gampang ketawa abangnya",
                "pesan": "Selalu tampilkan senyum terindah bang",
            },
            {
                "nama": "Fadhil Fitra Wijaya",
                "nim": "122450082",
                "umur": "20 Tahun",
                "asal": "Bekasi",
                "alamat": "Teluk Betung ",
                "hobbi": "Main Game",
                "sosmed": "@fadhilfwee",
                "kesan": "Aura wibu kuat bangett, keren banget abang ini",
                "pesan": "Semangat terus Bang",
            },
            {
                "nama": "Muhammad Regi Abdi Putra Amanta",
                "nim": " 122450031",
                "umur": "19 Tahun",
                "asal": "Palembang",
                "alamat": "Jl. Permadi Sukarame  ",
                "hobbi": "Main Game",
                "sosmed": "@mregiiii_",
                "kesan": "Keren banget, berprestasi, inspiratif",
                "pesan": "Terimakasih udah menginspirasi bang, suses selalu",
            },
            {
                "nama": "Syalaisha Andina Putriansyah",
                "nim": "122450121",
                "umur": "21 Tahun",
                "asal": "Tangerang",
                "alamat": "Gg Yudhistira ",
                "hobbi": "Baca Novel",
                "sosmed": "@dkselsd_31",
                "kesan": "Kakak kembar lucuuu",
                "pesan": "Semangat terus kak",
            },
            {
                "nama": "Natanael Oktavianus Partahan Sihombing ",
                "nim": "121450107",
                "umur": "20 Tahun",
                "asal": "Jakarta",
                "alamat": "Kemiling ",
                "hobbi": "Membuka Wisata HMSD",
                "sosmed": "@natanaeloks",
                "kesan": "Bang Nathan keren dan lucu",
                "pesan": "Sukses selalu Bang",
            },
            {
                "nama": "Anwar Muslim",
                "nim": "122450117",
                "umur": "21 Tahun",
                "asal": "Bukittinggi",
                "alamat": "Korpri ",
                "hobbi": " ML (Machine Learning)",
                "sosmed": "@here.am.ai",
                "kesan": "Bang Anwar Kiyowo",
                "pesan": "Semangat terus main ml nya Bang",
            },
            {
                "nama": "Deva Anjani Khayyuninafsyah",
                "nim": "122450014",
                "umur": "21 Tahun",
                "asal": " Bandar Lampung",
                "alamat": "Kemiling",
                "hobbi": "Menonton Film",
                "sosmed": "@anjaniiidev",
                "kesan": "Kakaknya comell dan cantik banget",
                "pesan": "Selalu ramah dan full senyum kak",
            },
            {
                "nama": "Dinda Nababan",
                "nim": "122450120",
                "umur": "20 Tahun",
                "asal": "Medan",
                "alamat": "Jl. Lapas",
                "hobbi": "Main Game",
                "sosmed": "@dindanababan_",
                "kesan": "Kakaknya baik",
                "pesan": "Semangat terus kak",
            },
            {
                "nama": "Marleta Cornelia Leander",
                "nim": "122450092",
                "umur": "20 Tahun",
                "asal": "Depok, Jawa Barat",
                "alamat": "Gg. Nangka 3",
                "hobbi": "Liatin Jurnal",
                "sosmed": "@marletacornelia",
                "kesan": "Kakaknya cantik, suaranya bagus, kece abis",
                "pesan": "Semangat kuliahnya kak, sukses terus",
            },
            {
                "nama": "Rut Junita Sari Siburian",
                "nim": "122450103",
                "umur": "20 Tahun",
                "asal": "Batam, Kep.Riau",
                "alamat": "Gg. Nangka 3",
                "hobbi": "Resume Jurnal",
                "sosmed": "@junitaa_0406",
                "kesan": "Kak nita lucuuu, mudah senyum, ramah",
                "pesan": "Semangat kuliahnya kak, happy terus",
            },
            {
                "nama": "Syadza Puspadari Azhar",
                "nim": " 122450072",
                "umur": "20 Tahun",
                "asal": "Palembang",
                "alamat": "Belwis ",
                "hobbi": "Membaca",
                "sosmed": "@puspadrr",
                "kesan": "Daplok terbaik, pemberi solusi yang baik, ramah, adaptif dan inspiratif",
                "pesan": "Sehat dan sukses selalu kak puspa, terimakasih banyak membantu",
            },
            {
                "nama": " Abdurrahman Al-atsary",
                "nim": "121450128",
                "umur": "23 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "Perumnas Way Kandis",
                "hobbi": " Membaca",
                "sosmed": "@rahmn_abdr",
                "kesan": "Abang ini lucu sekali",
                "pesan": "Semangat terus banggg",
            },
            {
                "nama": "Aditya Rahman",
                "nim": "122450113",
                "umur": "20 Tahun",
                "asal": " Lampung Timur",
                "alamat": "Korpri",
                "hobbi": "Ngoding WISATA",
                "sosmed": "@rahm_adityaa",
                "kesan": "Abang ini kiyowo dan kece abiezzz",
                "pesan": "Semangat ngoding nya Bang",
            },
            {
                "nama": "Eggi Satria",
                "nim": "122450032",
                "umur": "20 Tahun",
                "asal": "Sukabumi",
                "alamat": "Korpri",
                "hobbi": "Ngoding dan buat konten WISATA",
                "sosmed": "@egistr ",
                "kesan": "baik banget abangnya, sepuh koding",
                "pesan": "Terimakasih sudah banyak membantu mencari error bang ",
            },
            {
                "nama": "Febiya Jomy Pratiwi",
                "nim": "122450074",
                "umur": "20 Tahun",
                "asal": "Tulang Bawang",
                "alamat": "Jl Kelengkeng Raya",
                "hobbi": "Nonton K-Drama ",
                "sosmed": "@pratiwifebiya",
                "kesan": "Kak feby baik, lucu, humble,imut banget",
                "pesan": "Semangat kak kuliahnya, sukses selalu",
            },
            {
                "nama": "Happy Syahrul Ramadhan",
                "nim": "122450013",
                "umur": "20 Tahun",
                "asal": "Lampung",
                "alamat": "Karang Anyar ",
                "hobbi": " Main Game",
                "sosmed": "@sudo.syahrulramadhannn",
                "kesan": "Abangnya baik, keren",
                "pesan": "Happy kiyowo terus bang",
            },
            {
                "nama": "Randa Andriana Putra",
                "nim": "122450083",
                "umur": "21 Tahun",
                "asal": "Banten",
                "alamat": " Sukarame",
                "hobbi": " Tidur dan Berkembang",
                "sosmed": "@randaandriana_",
                "kesan": "PJ tugas yang baik, diam diam perhatian",
                "pesan": "Terimakasih Bang sudah banyak membantu, semangat kuliahnya bang",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Mikfes()

elif menu == "Departemen Eksternal ":
    def Eksternal():
        gambar_urls = [
            "https://drive.google.com/file/d/1CACRuG3QeMFrIfvDwvQNcreni4H_58Tu/view?usp=drive_link",
            "https://drive.google.com/file/d/1nY_9_ptnK2_aiBZzl2JA4-GJU2MfHgkw/view?usp=drive_link",
            "https://drive.google.com/file/d/1CV_7-UatDRXz3bLQSxOd-x8GRBkXYbe9/view?usp=drive_link",
            "https://drive.google.com/file/d/1NKtwTr6bIQhydbBFwQeGL-0UEaMDQe9z/view?usp=drive_link",
            "https://drive.google.com/file/d/1zF1ZIZOOKIhE3pobuJNds4tZK2GPzjlO/view?usp=drive_link",
            "https://drive.google.com/file/d/1slCjPK2cqzVMA9uuvwPN4SN5Ligr08SF/view?usp=drive_link",
            "https://drive.google.com/file/d/1iSSmngnS8pk01OvQMW7R0o07Kb3KB8LN/view?usp=drive_link",
            "https://drive.google.com/file/d/1g9CT6avG5nNuzNMWplETvrRcld8OI95a/view?usp=drive_link",
            "https://drive.google.com/file/d/1hK--RbZxn0OovPe4gLYS24uCRFZOfDKO/view?usp=drive_link",
            "https://drive.google.com/file/d/1LZu-LYBFMdUNq_fTTGQZrkpszJLau5bi/view?usp=drive_link",
            "https://drive.google.com/file/d/18qUBJiRScYRQCHvBE32lPFC2yEdq9Cvu/view?usp=drive_link",
            "https://drive.google.com/file/d/1-KMcCsjjIbpgfscO6xfN-36qg04umM1K/view?usp=drive_link",
            "https://drive.google.com/file/d/1n4ZQJnZeJsJNAMjITDu4CDmu6mwmAYaS/view?usp=drive_link",
            "https://drive.google.com/file/d/1DICJUYtmJjR9iJZzI0T6wbs61togg7Vq/view?usp=drive_link",
            "https://drive.google.com/file/d/1gyGKhAzaVUAkMn-LrYKoCu7ViDQChqEN/view?usp=drive_link",
            "https://drive.google.com/file/d/1B6PwDUmyBcA3e52zUKE6BDE0n-mvdlOP/view?usp=drive_link",
         
        ]
        data_list = [
            {
                "nama": "Yogy Sea Tama",
                "nim": "121450041",
                "umur": "21",
                "asal": "Tangerang",
                "alamat": "Jatimulyo",
                "hobbi": "Ngisi Bensin",
                "sosmed": "@yogyyyyyyy",
                "kesan": "Abangnya sangat menginspirasi",
                "pesan": "Semangat menjalani hari-hari dan Persiapan TA nya ya bang!!", 
            },
            {
                "nama": "Ramadhita Asifa Hendri",
                "nim": "121450131",
                "umur": "21",
                "asal": "Rajabasa",
                "alamat": "Rajabasa",
                "hobbi": "Belajar",
                "sosmed": "@Ramadhitaasifa",
                "kesan": "kakanya energik banget yah, jiwa eksternal kuat banget!!",
                "pesan": "Semangat terus ya kak, selalu lucu!!",
            },
            {
                "nama": "Nazwa Nabilla",
                "nim": "121450112",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Way Kandis",
                "hobbi": "Belajar dengan Rajin",
                "sosmed": "@nazwanbilla",
                "kesan": "kakaknya cantik banget loh!!",
                "pesan": "Semangat persiapan TA nya kak!!",
            },
            {
                "nama": "Dea Mutia Risani",
                "nim": "122450099",
                "umur": "20",
                "asal": "Sumatera Barat",
                "alamat": "Korpri",
                "hobbi": "Bikin Surat",
                "sosmed": "@deaa.rsn",
                "kesan": "kakaknya baik banget!!",
                "pesan": "Semangat kuliahnya kak!!",
            },
            {
                "nama": "Novelia Adinda",
                "nim": "122450104",
                "umur": "21",
                "asal": "Jakarta",
                "alamat": "Belwis",
                "hobbi": "Tidur",
                "sosmed": "@nvliadinda",
                "kesan": "kakaknya cantik, baik banget, selalu sabar membantu mencari error!!",
                "pesan": "Terimakasih kak sudah banyak membantu, semangat dan sukses selalu!!",
            },
            {
                "nama": "Ratu Keisha Jasmin Deonova",
                "nim": "122450106",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Way Kandis",
                "hobbi": "Ngerjain ADW",
                "sosmed": "@jasminednva",
                "kesan": "kakaknya keren banget, ramah dan inspiratif!!",
                "pesan": "Semangat terus kak!!",
            },
            {
                "nama": "Tobias David Monogari",
                "nim": "121450081",
                "umur": "20",
                "asal": "Jakarta Barat",
                "alamat": "Pemda",
                "hobbi": "Bikin Puisi",
                "sosmed": "@tobiassiagian",
                "kesan": "Bang Tobias empowering, proaktif dan inspiratif!!",
                "pesan": "Semangat berkarya dan selalu menginspirasi Bang!!",
            },
            {
                "nama": "Rizki Adrian Bennovry",
                "nim": "121450073",
                "umur": "21",
                "asal": "Bekasi",
                "alamat": "TVRI",
                "hobbi": "Buat Portopolio",
                "sosmed": "@rzkdrnnn",
                "kesan": "Abangnya lucu pas salting",
                "pesan": "Semangat terus abang NIM, sukses selalu!!",
            },
            {
                "nama": "Arafi Ramadhan Maulana",
                "nim": "12245022",
                "umur": "20",
                "asal": "Jogja, Depok",
                "alamat": "Way Huwi",
                "hobbi": "menghafal al-quran",
                "sosmed": "@arafiramadhanmaulana",
                "kesan": "Abangnya ramah, pelawak dan energik",
                "pesan": "Semangatdan sukses selalu bang!!",
            },
            {
                "nama": "Asa Do'a Uyi",
                "nim": "122450005",
                "umur": "20",
                "asal": "Muara",
                "alamat": "Korpri",
                "hobbi": "cuci baju",
                "sosmed": "@u_yippy",
                "kesan": "kak uyipi lucuu",
                "pesan": "semangat terus kak uyipii!!",
            },
            {
                "nama": "Chalifia Wananda",
                "nim": "122450076",
                "umur": "20",
                "asal": "Padang",
                "alamat": "sukarame",
                "hobbi": "Quality Time",
                "sosmed": "@chipawww",
                "kesan": "kakaknya baik dan ramah!!",
                "pesan": "Semangat menjalani hari-hari !!",
            },
            {
                "nama": "Irvan Alfaritzi",
                "nim": "122450093",
                "umur": "21",
                "asal": "Sumatera Barat",
                "alamat": "Jakarta",
                "hobbi": "Nonton Youtube dan main ML",
                "sosmed": "@Alfaritziirfan",
                "kesan": "Abangnya kece dan lucu banget",
                "pesan": "Semangat menjalani hari-hari nya Bang, next SDM terima aku ya Bang",
            },
            {
                "nama": "Izza Lutfia",
                "nim": "122450090",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Teluk",
                "hobbi": "main vollly",
                "sosmed": "@izzalutfiaa",
                "kesan": "kak izzah keren banget, enerjik, ramah dan jiwanya eksternal banget!!",
                "pesan": "Semangat terus kak terimakasih udah menginspirasi!!",
            },
            {
                "nama": "Khaalishah Zuhrah ALyaa Valefi",
                "nim": "122450034",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Rajabasa",
                "hobbi": "Nyanyi",
                "sosmed": "@alyaavalefi",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Raid Muhammad Naufal",
                "nim": "122450027",
                "umur": "20",
                "asal": "Lampung Tengah",
                "alamat": "Sukarame",
                "hobbi": "Ngeresume Seminar",
                "sosmed": "@rayHis_",
                "kesan": "Abangnya baik, lucu, pemalu!",
                "pesan": "Semangat ngaspraknya bang, terimakasih selalu sabar membantu mencari error!!",
            },
            {
                "nama": "Tria Yunanni",
                "nim": "122450062",
                "umur": "20",
                "asal": "Way Kanan",
                "alamat": "Jakarta",
                "hobbi": "Baca",
                "sosmed": "@tria_y062",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani kuliahnya kak!!",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Eksternal()
elif menu == "Departemen Internal":
    def Internal():
        gambar_urls = [
            "https://drive.google.com/file/d/1Uw9bqB2HGlalFNIcLfxMepfbTKdgOy7j/view?usp=drive_link",
            "https://drive.google.com/file/d/139SGLg6-xz1Dai9o8NhdL954vCYBqC3k/view?usp=drive_link",
            "https://drive.google.com/file/d/1_ZWXPk_bng-chdTCOtODfi1vMydHRSlr/view?usp=drive_link",
            "https://drive.google.com/file/d/1UWy9MpyLpXuVQKVqOfqBS_-LURvVg0nr/view?usp=drive_link",
            "https://drive.google.com/file/d/13SA49IkgBGf1iZn1vTtCLAbWlJaqx7J9/view?usp=drive_link",
            "https://drive.google.com/file/d/1nKPFtpM1HaG01uuUQieJvrvVk6FbIz8t/view?usp=drive_link",
            "https://drive.google.com/file/d/1tZHupTruTTCugJPpDsDNx2zKJhq8buR6/view?usp=drive_link",
            "https://drive.google.com/file/d/1r3kHSswPWeDlFfzCzgBIdpZEAA6RQ-64/view?usp=drive_link",
            "https://drive.google.com/file/d/17r5txbyhlIxJW6crESIqVyw2x3w-iMpw/view?usp=drive_link",
            "https://drive.google.com/file/d/1aSAAEERoBb4K5XxmyCI8Azd-R-fYmqzJ/view?usp=drive_link",
            "https://drive.google.com/file/d/1_n75ELJM6aNVAE6cK05QHzMLfQhnQWgi/view?usp=drive_link",
            "https://drive.google.com/file/d/1xt1eKyEj2PtH0PoP9hH4vKOYzR6JlZRJ/view?usp=drive_link",
            "https://drive.google.com/file/d/1TrjiCoQlUhCRONn-lI4T1IHkfG5oDGfV/view?usp=drive_link",

        ]
        data_list = [
            {
                "nama": "Dimas rizky ramadhani",
                "nim": "121450027",
                "umur": "20",
                "asal": "Pamulang",
                "alamat": "Way kandis",
                "hobbi": "Manjat tower sutet",
                "sosmed": "@dimzrky",
                "kesan": "Inspiratif",
                "pesan": "Semangat nyusun TA nya bang dimas", 
            },
            {
                "nama": "Catherine Firdhasari Maulina Sinaga",
                "nim": "121450072",
                "umur": "20",
                "asal": "Sumatera Utara",
                "alamat": "Airan",
                "hobbi": "Baca novel",
                "sosmed": "@chatherine.sinaga",
                "kesan": "kakanya cantik dan rohani banget",
                "pesan": "Semangat kuliahnya kak",
            },    
            {
                "nama": "M. Akbar Resdika",
                "nim": "121450066",
                "umur": "20",
                "asal": "Lampung Barat",
                "alamat": "Labuhan dalam",
                "hobbi": "Memelihara dino",
                "sosmed": "@akbar_resdika",
                "kesan": "Abangnya lucu",
                "pesan": "Semangat nyusun TA bang",
            },
            {
                "nama": "Rani Puspita Sari",
                "nim": "122450030",
                "umur": "20",
                "asal": "Metro",
                "alamat": "Rajabasa",
                "hobbi": "Mengaji",
                "sosmed": "@ranipu",
                "kesan": "Pemberani, profesional",
                "pesan": "Sukses selalu kak",
            },
            {
                "nama": "Rendra Eka Prayoga",
                "nim": "122450112",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Jalan lapas raya",
                "hobbi": "nulis lagu",
                "sosmed": "@rendraepr",
                "kesan": "Ramah, empowering, proaktif",
                "pesan": "Tetap Menginspirasi Bang",
            },
            {
                "nama": "Salwa Farhanatussaidah",
                "nim": "122450055",
                "umur": "20",
                "asal": "Pesawaran",
                "alamat": "Airan raya",
                "hobbi": "ngeliat cogan",
                "sosmed": "@slwfhn_694",
                "kesan": "Ra",
                "pesan": "semangat kuliahnya kak",
            },
            {
                "nama": "Ari Sigit",
                "nim": "121450069",
                "umur": "23",
                "asal": "Lampung barat",
                "alamat": "Labuhan ratu",
                "hobbi": "Main futsal",
                "sosmed": "@ari_sigit17",
                "kesan": "keren banget abangnya",
                "pesan": "semangat kuliahnya bang ari",
            },
            {
                "nama": "Azizah Kusumah Putri",
                "nim": "122450068",
                "umur": "21",
                "asal": "Lampung Selatan",
                "alamat": "Natar",
                "hobbi": "berkebun",
                "sosmed": "@azizahksmh15",
                "kesan": "Ramah banget kakaknya",
                "pesan": "Semangat kakak kuliah dan berkebun!!!",
            },
            {
                "nama": "Meira listyaningrum",
                "nim": "122450011",
                "umur": "20",
                "asal": "Pesawaran",
                "alamat": "Airan raya",
                "hobbi": "Menghalu",
                "sosmed": "@meiraln",
                "kesan": "Baik bangett",
                "pesan": "Semangat kakk!!!",
            },
            {
                "nama": "Rendi alexander hutagalung",
                "nim": "122450057",
                "umur": "20",
                "asal": "Tangerang",
                "alamat": "Kost gunawan",
                "hobbi": "Menyanyi",
                "sosmed": "@alexanderr",
                "kesan": "Lucu banget abang ini",
                "pesan": "pantang menyerah,selalu berusaha, tetap semangat bang",
            },
            {
                "nama": "Renta siahaan",
                "nim": "122450070",
                "umur": "21",
                "asal": "Sumatera utara",
                "alamat": "Gerbang barat",
                "hobbi": "Memancing",
                "sosmed": "@renta.shn",
                "kesan": "Kak renta lucu banget logatnya",
                "pesan": "selalu semangat kakak ",
            },
            {
                "nama": "Yosia lehare banurea",
                "nim": "121450149",
                "umur": "20",
                "asal": "Dairi, Sumatera utara",
                "alamat": "Perum griya indah",
                "hobbi": "Bawa motor pakai kaki",
                "sosmed": "@yosiabanurea",
                "kesan": "Abangnya keren banget pas main basket",
                "pesan": "Selalu tampilkan senyum terindah kita itu bang",
            },
            {
                "nama": "Josua panggabean",
                "nim": "121450061",
                "umur": "21",
                "asal": "Pematang siantar",
                "alamat": "Gya kost",
                "hobbi": "Ngawinin cupang",
                "sosmed": "@josuapanggabean16_",
                "kesan": "abang abang soft spoken",
                "pesan": "semangat ngaspraknya Bang",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Internal()
elif menu == "Departemen SSD ":
    def Ssd():
        gambar_urls = [
            "https://drive.google.com/file/d/1YHHgg_vy890Cs8WuNFMTHpMB9r-jaScz/view?usp=drive_link",
            "https://drive.google.com/file/d/1VPeOV9oT9kOVtor5drBl16LRIt0kLzsn/view?usp=drive_link",
            "https://drive.google.com/file/d/1803U5Y9ujNyJiw52mXOCKtCLi4JE_pKU/view?usp=drive_link",
            "https://drive.google.com/file/d/1uKidG6Jn9QJ4Slo_KpkdLLXMHs3nwYmQ/view?usp=drive_link",
            "https://drive.google.com/file/d/1WhDRcPABV-UHjcorsFZYQLqRqmDmhVlV/view?usp=drive_link",
            "https://drive.google.com/file/d/1CpDghlwgsdiliSyaIE4wJqmAJ-0kZQcp/view?usp=drive_link",
            "https://drive.google.com/file/d/19Aw8fQyRdRdCGB59UyB7m4FyVPzEGslP/view?usp=drive_link",
            "https://drive.google.com/file/d/1Psr_7ODH8kaokvIh1biAol53WGixfhB4/view?usp=drive_link",

         
        ]
        data_list = [
            {
                "nama": "Andrian Agustinus Lumban Gaol",
                "nim": "121450090",
                "umur": "17 +",
                "asal": "Sidikalang",
                "alamat": "Lapas",
                "hobbi": "Nyari Hobi",
                "sosmed": "@andrialgaol",
                "kesan": "Public speakingnya bagus bangett, menginspirasi",
                "pesan": "Semangat cari duitnya bang", 
            },
            {
                "nama": "Adisty Syawaida Ariyanto",
                "nim": "121450136",
                "umur": "21",
                "asal": "Metro",
                "alamat": "Metro",
                "hobbi": "Nonton film",
                "sosmed": "@adistysa_",
                "kesan": "Keren banget kak",
                "pesan": "Semangat kuliahnya kak",
            },
            {
                "nama": "Nabila Azhari",
                "nim": "121450029",
                "umur": "21",
                "asal": "Simalungun",
                "alamat": "Airan",
                "hobbi": "Menghitung",
                "sosmed": "@zhjung",
                "kesan": "Kak Lala Lucu banget",
                "pesan": "Semangat kuliahnya kak",
            },
            {
                "nama": "Danang Hilal Kurniawan",
                "nim": "122450085",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "TB 3 Asrama",
                "hobbi": "Belajar",
                "sosmed": "@dananghk_",
                "kesan": "Abangnya pekerja keras banget",
                "pesan": "Semangat cari cuan bang, lancar usaha",
            },
            {
                "nama": "Farrel Julio Akbar",
                "nim": "122450110",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Jalan Lapas",
                "hobbi": "Bebas",
                "sosmed": "@farel__julio",
                "kesan": "Abangnya cool bgt dan enerjik",
                "pesan": "Tetap Humble dan inspiratif",
            },
            {
                "nama": "Nabilah Andika Fitriani",
                "nim": "121450129",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Kedaton",
                "hobbi": "Tidur",
                "sosmed": "@nabilaafrn",
                "kesan": "Inovatif dan komunikatif",
                "pesan": "Semangat menjalani hari hari kak",
            },
            {
                "nama": "Alvia Asrinda Br.Ginting",
                "nim": "122450077",
                "umur": "20",
                "asal": "Binjai",
                "alamat": "Korpri",
                "hobbi": "Nonton Windah",
                "sosmed": "@alviagnting",
                "kesan": "Kakaknya baik",
                "pesan": "Semangat dan sukses terus kak",
            },
            {
                "nama": "Dhafin Razaka Luthfia",
                "nim": "122450133",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Jalan nangka 1",
                "hobbi": "Olahraga",
                "sosmed": "@dhafinrzqra3",
                "kesan": "Abang ini lucu dan cool cool gimana gitu",
                "pesan": "Semangat usaha kost nya bang",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Ssd()

# Tambahkan menu lainnya sesuai kebutuhan
