import streamlit as st
from streamlit_option_menu import option_menu
import requests
from PIL import Image, ImageOps
from io import BytesIO

st.markdown("""<style>.centered-title {text-align: center;}</style>""",unsafe_allow_html=True)
st.markdown("<h1 class='centered-title'>BUKU KATING</h1>", unsafe_allow_html=True)

# bagian sini jangan diubah
def streamlit_menu():
    selected = option_menu(
        menu_title=None,
        options=[
            "Kesekjenan",
            "Baleg",
            "Senator",
            "Departemen PSDA",
            "Departemen MEDKRAF",
            "Departemen MIKFES",
            "Departemen Eksternal",
            "Departemen Internal",
            "Departemen SSD",
        ],
        icons=[
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
        ],
        default_index=0,
        orientation="horizontal",
        styles={
            "container": {"padding": "0!important", "background-color": "#fafafa"},
            "icon": {"color": "black", "font-size": "19px"},
            "nav-link": {
                "font-size": "15px",
                "text-align": "left",
                "margin": "0px",
                "--hover-color": "#eee",
            },
            "nav-link-selected": {"background-color": "#3FBAD8"},
        },
    )
    return selected

@st.cache_data
def load_image(url):
    response = requests.get(url)
    if response.status_code != 200:
        st.error(
            f"Failed to fetch image from {url}, status code: {response.status_code}"
        )
        return None
    try:
        img = Image.open(BytesIO(response.content))
        img = ImageOps.exif_transpose(img)
        img = img.resize((300, 400))
        return img
    except Exception as e:
        st.error(f"Error loading image: {e}")
        return None
    
@st.cache_data
def display_images_with_data(gambar_urls, data_list):
    images = []
    for i, url in enumerate(gambar_urls):
        with st.spinner(f"Memuat gambar {i + 1} dari {len(gambar_urls)}"):
            img = load_image(url)
            if img is not None:
                images.append(img)

    for i, img in enumerate(images):
        # Menggunakan Streamlit untuk menampilkan gambar di tengah kolom
        col1, col2, col3 = st.columns([1, 2, 1])
        with col2:
            st.image(img, use_column_width=True)

        if i < len(data_list):
            st.write(f"Nama: {data_list[i]['nama']}")
            st.write(f"NIM: {data_list[i]['nim']}")
            st.write(f"Umur: {data_list[i]['umur']}")
            st.write(f"Asal: {data_list[i]['asal']}")
            st.write(f"Alamat: {data_list[i]['alamat']}")
            st.write(f"Hobbi: {data_list[i]['hobbi']}")
            st.write(f"Sosial Media: {data_list[i]['sosmed']}")
            st.write(f"Kesan: {data_list[i]['kesan']}")
            st.write(f"Pesan: {data_list[i]['pesan']}")
            st.write("  ")
    st.write("Semua gambar telah dimuat!")
menu = streamlit_menu()

# BAGIAN SINI YANG HANYA BOLEH DIUABAH
if menu == "Kesekjenan":
    def kesekjenan():
        gambar_urls = [

            "https://drive.google.com/uc?export=view&id=1j-xe3ChUkC7re7chFUXvJ4AKOwht1GAD",
            "https://drive.google.com/uc?export=view&id=1iyN5ViLQo6CXuGCnGsCBGPLgGH7Z80rQ",
            "https://drive.google.com/uc?export=view&id=1iyJACnbYfpMeno9naIXODUrfoOSoKTU0",
            "https://drive.google.com/uc?export=view&id=1izdRpOCeiXdQzSprAsZUsMiJphlOqDz0",
            "https://drive.google.com/uc?export=view&id=1j9dILE-yCXWVxpagqXDxJWFotWAcMccy",
            "https://drive.google.com/uc?export=view&id=1j8-bko0mxM_0qJAFCSVe8ZvYCIbRgh2t",
        ]
        data_list = [
            {
                "nama": "Kharisma Gumilang",
                "nim": "121450142",
                "umur": "21 Tahun",
                "asal": "Palembang",
                "alamat": "Jl.Pulau Damar",
                "hobbi": "Dengerin Musik",
                "sosmed": "@gumilangkharisma",
                "kesan": "Bang gumi keren banget dan sangat inspiratif",  
                "pesan":"Semangat dan sukses selalu bang",
            },
            {   
                "nama": "Pandra Insani Putra Azwar",
                "nim": "121450137",
                "umur": "21 Tahun",
                "asal":"Lampung Utara",
                "alamat": "Sukarame",
                "hobbi": "Main Gitar",
                "sosmed": "@pandrainsani27",
                "kesan": "Bang, keren dan kece banget",  
                "pesan":"Semangat kuliahnya ya bang",
            },
            {   
                "nama": "Meliza Wulandari",
                "nim": "121450065",
                "umur": "20 Tahun",
                "asal":"Sumatera Selatan",
                "alamat": "Jl.Pagar Alam",
                "hobbi": "Nonton Drakor",
                "sosmed": "@wulandarimeliza",
                "kesan": "Kakaknya baik dan kalem banget",  
                "pesan": "Teruslah berjuang disetiap langkahmu kak",
            },
            {
                "nama": "Putri Maulida Chairani",
                "nim": "121450050",
                "umur": "21 Tahun",
                "asal": "Sumatera Barat",
                "alamat": "Gg. Nangka 4",
                "hobbi": "Dengerin Bg Pandra Main Gitar",
                "sosmed": "@ptrimaulidaaa_",
                "kesan": "Kakaknya positif vibes bangett",  
                "pesan":"Sukses selalu dan tetap berjuang ya kak",
            },
            {   
                "nama": "Hartiti Fadilah",
                "nim": "121450031",
                "umur": "21 Tahun",
                "asal":"Palembang",
                "alamat": "Pemda",
                "hobbi": "Nyanyi",
                "sosmed": "@htrpdla",
                "kesan": "Kakaknya manis banget",  
                "pesan": "Kak, semangat dan sukses terus yaaw",
            },
            {
                "nama": "Nadilla Andhara Putri",
                "nim": "121450003",
                "umur": "21 Tahun",
                "asal": "Lampung",
                "alamat": "Metro",
                "hobbi": "Membaca",
                "sosmed": "@nadilaandr26",
                "kesan": "Cantik dan keren banget kakaknya",  
                "pesan":"Semangat selalu ya kak",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    kesekjenan()

elif menu == "Baleg":
    def baleg():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=17R7Y8xuPXIvZL1M0tuV-x1rymt4UgiQW",
            "https://drive.google.com/uc?export=view&id=17QmfpRvmf2ezQeVRLbb3KdX3tT6FL9bg",
            "https://drive.google.com/uc?export=view&id=17QoZEkcaB_LNbUQdK23OXyqKmk7eClyj",
            "https://drive.google.com/uc?export=view&id=17OvFyCarssNMX-YUoJGyd6jSnhxC2nK9",
            "https://drive.google.com/uc?export=view&id=17NgLlNuDsEZwvRhlf1Nznis6nhhJk6vC",
            "https://drive.google.com/uc?export=view&id=1oleVWWor9Ak7P1w5DlP02BSKIQmrZrg7",
            "https://drive.google.com/uc?export=view&id=17Tf2C77eapDpz0UwgbhTckgg8ZlpWz8L",
            "https://drive.google.com/uc?export=view&id=17NIQZIPlDhJOzTmJkLlHyw0757Z90G39",
            "https://drive.google.com/uc?export=view&id=17S7VSg8MuqtvwCJVnhXIhoaSLe9Upwvx",
            "https://drive.google.com/uc?export=view&id=17ZUnwXfLY979eBaUA3VBs5F3M4BqrUQT",
            "https://drive.google.com/uc?export=view&id=17QdKekbn7l2EzEIAqgi0l-8C8EaoHPeq",
        ]
        data_list = [
            {
                "nama": "Tri Murniya Ningsih",
                "nim": "121450038",
                "umur": "21 Tahun",
                "asal":"Bogor",
                "alamat": "Raden Saleh",
                "hobbi": "Nanya ke GPT",
                "sosmed": "@trimurniaa_",
                "kesan": "Kakaknya selalu ceria dan ramah bangett",  
                "pesan": "Kak, semangat kuliahnya yaww!",
            },
            {
                "nama": "Annisa Cahyani Surya",
                "nim": "121450114",
                "umur": "21 Tahun",
                "asal": "Tanggerang Selatan",
                "alamat": "Way Huwi",
                "hobbi": "Membaca, menonton",
                "sosmed": "@annisacahyanisurya",
                "kesan": "Kakaknya suka ghibli sama sepertiku hehee",  
                "pesan": "Sukses terus ya kak, jangan lupa nonton ",
            },
            {
                "nama": "Wulan Sabina",
                "nim": "121450150",
                "umur": "21 Tahun",
                "asal": "Medan",
                "alamat": "Raden saleh",
                "hobbi": "Belajar, menonton film, tidur",
                "sosmed": "@wlsbn0",
                "kesan": "Public speakingnya keren banget kakk",  
                "pesan": "Kak, teruslah maju dengan penuh semangatt",
            },
            {
                "nama": "Anisa Dini Amalia",
                "nim": "121450081",
                "umur": "20 Tahun",
                "asal":"Tanggerang",
                "alamat": "Jati agung",
                "hobbi": "Nonton drachin",
                "sosmed": "@anisadini10",
                "kesan": "Kakaknya ramah dan asik bangett",  
                "pesan":"Semangat selalu kuliahnya kak",
            },
            {
                "nama": "Claudhea Angeliani",
                "nim": "121450124",
                "umur": "21 Tahun",
                "asal":"Lampung Timur",
                "alamat": "Lampung Timur",
                "hobbi": "Tidur",
                "sosmed": "@dylebee",
                "kesan": "Kakaknya baik banget",  
                "pesan":"Selalu semangat yaa kak",
            },
            {
                "nama": "Muhammad Fachrul Aditya",
                "nim": "121450156",
                "umur": "22 Tahun",
                "asal": "Surakarta",
                "alamat": "Sukarame",
                "hobbi": "Melukis, olahraga",
                "sosmed": "@fhrul.pdf",
                "kesan": "Abangnya baik dan kece",  
                "pesan": "Selalu semangat kuliahnya bang",
            },
            {
                "nama": "Feriyadi Yulius",
                "nim": "122450087",
                "umur": "20 Tahun",
                "asal": "Sumatera Selatan",
                "alamat": "Way Kandis",
                "hobbi": "Baca Buku",
                "sosmed": "@fer_yulius",
                "kesan": "Abangnya postif vibes bangett",  
                "pesan":"Semoga dilancarkan segala urusannya bang",
            },
            {
                "nama": "Renisha Putri Giani",
                "nim": "122450079",
                "umur": "21 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "Teluk Betung",
                "hobbi": "Jualan pancing",
                "sosmed": "@fleurnsh",
                "kesan": "Kakaknya lucu banget dan suka banget sama kucing",  
                "pesan":" Semangat dan sukses kuliahnya kak",
            },
            {
                "nama": "Mirzan Yusuf Rabbani",
                "nim": "122450118",
                "umur": "20 Tahun",
                "asal": "Jakarta",
                "alamat": "Korpri",
                "hobbi": "Tidur yang lama, main kucing",
                "sosmed": "@myrrinn",
                "kesan": "Abangnya tinggi bangett dan kalem",  
                "pesan": "Semangat terus bang dan selalu ceria",
            },
            {
                "nama": "Jeremia Susanto",
                "nim": "122450022",
                "umur": "21 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "Bandar Lampung",
                "hobbi": "Bengong",
                "sosmed": "@jeremia_s_",
                "kesan": "Bang jere seruu bangett",  
                "pesan": "Sukses dan keren selalu yaa bang",
            },
            {
                "nama": "Berliana Enda Putri",
                "nim": "122450065",
                "umur": "20 Tahun",
                "asal": "Sumatera Barat",
                "alamat": "Way Huwi",
                "hobbi": "Duduk di tepi pantai sambil galauin bintang yang tinggal satu",
                "sosmed": "@berlyyanda",
                "kesan": "Kakaknya seru dan keren banget",  
                "pesan":"Semangat setiap saat yaa kak",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    baleg()

elif menu == "Senator":
    def senator():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1IKppB7EwJfG7yqLLceZ3TkaE5b5rZyfH",
            "https://drive.google.com/uc?export=view&id=18DkHEV3sI9wa2q7FQOJEDqgU26bdaNQe",
        
        ]
        data_list = [
            {
                "nama": "Anissa Luthfi Alifia",
                "nim": "121450093",
                "umur": "22 Tahun",
                "asal": "Lampung Tengah",
                "alamat": "Kost Putri Rahayu",
                "hobbi": "Dengerin bintang nyanyi",
                "sosmed": "@anissalutfi_",
                "kesan": "Kakaknya luar biasa keren bangett",
                "pesan": "Semangat selalu dan tetaplah luar biasa kak", 
            },
            {
                "nama": "Rian Bintang Wijaya",
                "nim": "122450094",
                "umur": "20 Tahun",
                "asal": "Palembang",
                "alamat": "Kota Baru",
                "hobbi": "Nyanyi",
                "sosmed": "@bintangtwinkle",
                "kesan": "Abangnya selalu keren banget",
                "pesan": "Semangat dan sukses dalam kuliahnya yaa bang",
            }
        ]
        display_images_with_data(gambar_urls, data_list)
    senator()

elif menu == "Departemen PSDA":
    def Psda():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1R-4SkCopBfYa0BO9NhRDKTJFGX1wS-Zm",
            "https://drive.google.com/uc?export=view&id=1QYw8VZDHM0QYzMR_Lg05C5S1-c58b19V",
            "https://drive.google.com/uc?export=view&id=1QypkoXZ77FgNNEUM1endqHiPvqSDrWWR",
            "https://drive.google.com/uc?export=view&id=1Q48N5l7b1i7yOeUeELTZA_RzwSI8ni3A",
            "https://drive.google.com/uc?export=view&id=1R7Hps5fPUCsqz3Ga7pw6UQ6oEtbgBk4a",
            "https://drive.google.com/uc?export=view&id=1Qn4BDQxcPlWeGmWhOnGvsy9BVbzahjG6",
            "https://drive.google.com/uc?export=view&id=1Qj1c04qOKluemQ0bYZiRyRT5M4TbwQll",
            "https://drive.google.com/uc?export=view&id=1Qz4rR7YB4siWDDSz6ma2G1y1PoFoOefv",
            "https://drive.google.com/uc?export=view&id=1QgM3LzK4h-XVb0oj1QxycYlMMMJX3cvV",
            "https://drive.google.com/uc?export=view&id=1QxL3z9J-ORkyBA9WM1so8M6uNGpWh0tO",
            "https://drive.google.com/uc?export=view&id=1Qp7mXacVcL8a578-LgBhAOEtWZgeynQR",
            "https://drive.google.com/uc?export=view&id=1QXfWZE7Z0y847N9Fz8i5swEvgdnoHiOs",
            "https://drive.google.com/uc?export=view&id=1Q8B3gG9qzWuYZVI92jD9Y6EgCpwkFM3E",
            "https://drive.google.com/uc?export=view&id=1QHQ0UTthr_xqDIBAq4ENlRu43dKsi_fq",
            "https://drive.google.com/uc?export=view&id=1QNR2ERma3zMDlJh_8T1aLC4mBfLJAjVt",
            "https://drive.google.com/uc?export=view&id=1Q57Dp7edlIRCM6HX_8ruGca_4MYdRJL2",
            "https://drive.google.com/uc?export=view&id=1Q3Wmlbx_WLRPMvFVSutV5i-VwF5HhDKG",
            "https://drive.google.com/uc?export=view&id=1R-qfgdLpm5d1aUxztJnT7GRABcZbSKSa",
            "https://drive.google.com/uc?export=view&id=1R4qLRUicNrKU2pryAcSkI7P2UFiiYI9Y",
            "https://drive.google.com/uc?export=view&id=1R2M0pWN9wEny8UKA0BAccykNafmyR8HL",  
        ]

        data_list = [
            {
                "nama": "Ericson Chandra Sihombing",
                "nim": "121450026",
                "umur": "21 Tahun",
                "asal": "Bekasi",
                "alamat": "Khobam",
                "hobbi": "Travelling",
                "sosmed": "@ericsonchandr99",
                "kesan": "Abangnya baik banget dan tegas",
                "pesan": "Semangat kuliahnya dan selalu sukses yaa bang", 
            },
            {
                "nama": "Elisabeth Claudia Simanjuntak",
                "nim": "122450123",
                "umur": "20 Tahun",
                "asal": "Tanggerang",
                "alamat": "Kemiling",
                "hobbi": "Bernafas",
                "sosmed": "@celisabethh_",
                "kesan": "Kakak manis bangett",
                "pesan": "Semangat belajarnya yaa kak",
            },
            {
                "nama": "Nisrina Nur Afifah",
                "nim": "122450052",
                "umur": "19 Tahun",
                "asal": "Bekasi",
                "alamat": "Sukarame",
                "hobbi": "Menonton",
                "sosmed": "@afifahhnsrn",
                "kesan": "Kakak cantik dan keren bangett",
                "pesan": "Kak, semangat yaa kuliahnya",
            },
            {
                "nama": "Deyvan Loxefal",
                "nim": "121450148",
                "umur": "21 Tahun",
                "asal": "Pekanbaru",
                "alamat": "Jl. Pulau Damar",
                "hobbi": "Belajar",
                "sosmed": "@depanloo",
                "kesan": "Abangnya asik dan seru bangett",  
                "pesan": "Semangat belajarnya ya bang! Semoga impiannya tercapai",
            },
            {
                "nama": "M. Farhan Athaulloh",
                "nim": "121450117",
                "umur": "21 Tahun",
                "asal": "Lampung",
                "alamat": "Kota Baru",
                "hobbi": "Menolong",
                "sosmed": "@mfarhan.ath",
                "kesan": "Abangnya baik, ramah dan keren bangett",  
                "pesan": "Tetap semangat dan terus berbagi kebaikan ya bang",
            },
            {
                "nama": "Allya Nurul Islami Pasha",
                "nim": "122450033",
                "umur": "20 Tahun",
                "asal": "Sumatera Barat",
                "alamat": "Gang Perwira Belwis",
                "hobbi": "keliling Lampung",
                "sosmed": "@allyaislami_",
                "kesan": "Kakaknya tegas dan baik banget",
                "pesan": "Sukses kuliahnya kak dan semangat selalu kak",
            },
            {
                "nama": "Eksanty Febriana Sugma Islamiaty",
                "nim": "122450001",
                "umur": "20 Tahun",
                "asal": "Bekasi",
                "alamat": "Rajabasa",
                "hobbi": "Nyari sinyal di gedung F",
                "sosmed": "@eksantyfebriana",
                "kesan": "Kakaknya ramah dan baik bangett",  
                "pesan": "Semangat kuliah dan belajarnya yaa kak",
            },
            {
                "nama": "Farahanum Afifah Ardiansyah",
                "nim": "122450056",
                "umur": "20 Tahun",
                "asal": "Padang",
                "alamat": "Sukarame",
                "hobbi": "Minum kopi",
                "sosmed": "@farahanumafifahh",
                "kesan": "Kakaknya cantik dan keren bangett",  
                "pesan": "Kak, jangan lelah belajar! Semoga sukses selalu",
            },
            {
                "nama": "Ferdy Kevin Naibaho",
                "nim": "122450107",
                "umur": "20 Tahun",
                "asal": "Medan",
                "alamat": "Jl pangeran senopati raya",
                "hobbi": "Review jurnal",
                "sosmed": "@ferdy_kevin",
                "kesan": "Abangnya baik bangett",  
                "pesan": "Semangat terus kuliahnya bang",
            },
            {
                "nama": "M. Deriansyah Okutra",
                "nim": "122450101",
                "umur": "19 Tahun",
                "asal": "Palembang, Pagar Alam",
                "alamat": "Kedaton",
                "hobbi": "Main-main",
                "sosmed": "@dransyh_",
                "kesan": "Abangnya keren bangett",  
                "pesan": "Tetap semangat ya bang, semoga sukses",
            },
            {
                "nama": "Oktavia Nurwenda Puspitasari",
                "nim": "122450041",
                "umur": "20 Tahun",
                "asal": "Lampung Timur",
                "alamat": "Way Huwi",
                "hobbi": "Memasak",
                "sosmed": "@_oktavianrwnda_",
                "kesan": "Kakaknya baik dan ramah bangett",  
                "pesan": "Semoga kuliahnya lancar yaa kak",
            },
            {
                "nama": "Presilia",
                "nim": "122450081",
                "umur": "20 Tahun",
                "asal": "Bekasi",
                "alamat": "Kota Baru",
                "hobbi": "Dengerin lomba sihir",
                "sosmed": "@presiliamg",
                "kesan": "Kakaknya kalem dan cantik banget",  
                "pesan": "Terus semangat kak, semoga sukses",
            },
            {
                "nama": "Johannes Krisjon Silitonga",
                "nim": "122450043",
                "umur": "19 Tahun",
                "asal": "Tanggerang",
                "alamat": "Jl. Lapas Raya",
                "hobbi": "Ngeasprak",
                "sosmed": "@johanneskrisjonn",
                "kesan": "Abangnya keren dan tegas banget",  
                "pesan": "Semoga sukses selalu bang! Semangat kuliahnya",
            },
            {
                "nama": "Ibnu Farhan Al-Ghifari",
                "nim": "121450121",
                "umur": "21 Tahun",
                "asal": "Kerinci Jambi",
                "alamat": "Khobam",
                "hobbi": "Game online",
                "sosmed": "@al_ghifari032",
                "kesan": "Abangnya baik banget dan ramah",  
                "pesan": "Tetap semangat bang! Semoga sukses selalu menyertai",
            },
            {
                "nama": "Leonard Andreas Napitupulu",
                "nim": "121450153",
                "umur": "21 Tahun",
                "asal": "Medan",
                "alamat": "Khobam",
                "hobbi": "Belajar",
                "sosmed": "@lndr.__ ",
                "kesan": "Abangnya baik dan kalem",  
                "pesan": "Semoga lancar selalu kak, jangan pernah lelah belajar",
            },
            {
                "nama": "Kemas Veriandra Ramadhan",
                "nim": "122450016",
                "umur": "19 Tahun",
                "asal": "Bekasi",
                "alamat": "Kojo",
                "hobbi": "Gitar, ngegame",
                "sosmed": "@kemasverii",
                "kesan": "Abangnya baik dan pinter banget ngodingnyaa",  
                "pesan": "Semoga sukses selalu bang, semangat!",
            },
            {
                "nama": "Sahid Maulana",
                "nim": "122450109",
                "umur": "21 Tahun",
                "asal": "Depok",
                "alamat": "Airan Raya",
                "hobbi": "Dengerin musik",
                "sosmed": "@sahid_maul19",
                "kesan": "Abangnya baik, keren dan long textnya keren banget",  
                "pesan": "Semangat terus bang dan tetap keren yaa bang",
            },
            {
                "nama": "Gede Moana",
                "nim": "121450014",
                "umur": "21 Tahun",
                "asal": "Bekasi",
                "alamat": "Korpri Raya",
                "hobbi": "Belajar, Game, Baca Komik",
                "sosmed": "@gedemoenaa",
                "kesan": "Abangnya baik, keren dan seru",  
                "pesan": "Semoga sukses selalu bang",
            },
            {
                "nama": "Jaclin Alcavella",
                "nim": "122450015",
                "umur": "19 Tahun",
                "asal": "Sumatera Selatan",
                "alamat": "Korpri",
                "hobbi": "Berenang",
                "sosmed": "@jaclinaclcv_",
                "kesan": "Kakaknya keren bangett",  
                "pesan": "Terus maju dan semoga makin sukses kak",
            },
            {
                "nama": "Syalaisha Andini Putriansyah",
                "nim": "122450111",
                "umur": "21 Tahun",
                "asal": "Tangerang",
                "alamat": "Sukarame",
                "hobbi": "Membaca",
                "sosmed": "@syalaisha.i__",
                "kesan": "Kakaknya ramah, dan baik bangett",  
                "pesan": "Semangat kak, semoga sukses selalu yaa kak",
            },
       
        ]
        display_images_with_data(gambar_urls, data_list)
    Psda()

elif menu == "Departemen MEDKRAF":
    def Medkraf():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=183cqgtCRCW2EihXeRx-lbci5sFIovS7y",
            "https://drive.google.com/uc?export=view&id=17waaokT9gk4qg8_BjwysWlvVgs9cgdvn",
            "https://drive.google.com/uc?export=view&id=17g2BV-RMMcrj4Q5flADdEBMsyKTWS99Y",
            "https://drive.google.com/uc?export=view&id=188yNaG2qhNcImdB4OQD2KIHJ6JEFI1xm",
            "https://drive.google.com/uc?export=view&id=17whqsIinhquQykxN6p4Avz8DHmUKXiVT",
            "https://drive.google.com/uc?export=view&id=17nd3HHcadf1HRSUDxFmD-2FB2vuHKkIb",
            "https://drive.google.com/uc?export=view&id=17rrI_Nf6NMMGykb_aJ3HCpTFUDYf8j0w",
            "https://drive.google.com/uc?export=view&id=1OF1bvFLArs8SH8Q9wEOEzbzOpWl8a_sa",
            "https://drive.google.com/uc?export=view&id=17ufV5b-yR5pnRJmtsB2ineW4AGm-ztMK",
            "https://drive.google.com/uc?export=view&id=17gu6llLI_floPgSlZ2s5SoSEiebJXKfy",
            "https://drive.google.com/uc?export=view&id=17q04jQCrVhKcC6vcBuMY_fJQrvxjfNQi",
            "https://drive.google.com/uc?export=view&id=17guAsXeE0NPDduNHvwPKm0DIldJKbmJL",
            "https://drive.google.com/uc?export=view&id=17yxfyAwgqlgfsblTOC4tgnDLthj6Xfew",
            "https://drive.google.com/uc?export=view&id=18CZjJEUrmgodsx7EHbtojg3Fp4NVcDEl",
            "https://drive.google.com/uc?export=view&id=185K8lC-HNOjEg8SN35cPBoNsRpBMSK1f",
            "https://drive.google.com/uc?export=view&id=181qRqrI7qc3lg_ljLClS6bf1hbDCC4J-",
        ]
        data_list = [
            {
                "nama": "Wahyudiyanto",
                "nim": "121450040",
                "umur": "22 Tahun",
                "asal": "Makassar",
                "alamat": "Sukarame",
                "hobbi": "Nonton",
                "sosmed": "@wayyulaja",
                "kesan": "Abangnya ramah dan keren",
                "pesan": "Selalu sukses dan tambah keren bang",
            },
            {
                "nama": "Elok Fiola",
                "nim": "122450051",
                "umur": "19 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "Bandar Lampung",
                "hobbi": "Editing",
                "sosmed": "@elokfiola",
                "kesan": "Kakaknya manis banget kalo senyum",
                "pesan": "Semangat kuliahnya yaa kak dan always happy", 
            },
            {
                "nama": "Muhammad Kaisar Firdaus ",
                "nim": " 121450135",
                "umur": "21 Tahun",
                "asal": "Pesawaran",
                "alamat": "Pulau Damar",
                "hobbi": "Lagi Nyari",
                "sosmed": " @dino_kiper",
                "kesan": "Abangnya seru banget",
                "pesan": "Semangat terus bang, jangan pernah putus asa", 
            },
            {
                "nama": "Muhammad Arsal Ranjana Putra",
                "nim": "121450111",
                "umur": "21 Tahun",
                "asal": "Depok",
                "alamat": "Nangka 4",
                "hobbi": "Ngoding",
                "sosmed": "@arsal.utama",
               "kesan": "Abangnya ramah dan kerenn",
                "pesan": "Semangat ngodingnya yaa bang", 
            },
            {
                "nama": "Cintya Bella",
                "nim": "122450066",
                "umur": "20 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "Teluk",
                "hobbi": "Ngegym",
                "sosmed": "@cintyabella28",
               "kesan": "Kakaknya cantik dan kreatif bangett",
                "pesan": "Semangat ngontennya yaa kak", 
            },
            {
                "nama": "Eka Fidiya Putri",
                "nim": " 122450045",
                "umur": "20 Tahun",
                "asal": "Natar, Lampung Selatan",
                "alamat": "Natar, Lampung Selatan",
                "hobbi": "Menyibukkan Diri",
                "sosmed": "@ekafdyaptri",
                "kesan": "Kakaknya baik, ramah dan keren banget",
                "pesan": "Kak, semangat terus dan tetap keren yaw", 
            },
            {
                "nama": "Patricia Leondra Diajeng Putri ",
                "nim": "122450050",
                "umur": "20 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "Jatimulyo",
                "hobbi": "Nonton Film",
                "sosmed": "@patriciadiajeng",
                "kesan": "Kak ciaa baik dan ramahh bangett",
                "pesan": "Semangat kuliahnya dan ngaspraknya yaa kak", 
            },
            {
                "nama": "Rahma Neliyana",
                "nim": "122450036",
                "umur": "20 Tahun",
                "asal": "Lampung",
                "alamat": "Sukarame",
                "hobbi": "Baca Coding",
                "sosmed": "@rahmanellyana",
                "kesan": "Kakaknya ramah dan keren bangett",
                "pesan": "Semangat dan terus berkarya yaa kak", 
            },
            {
                "nama": "Try Yani Rizki Nur Rohmah ",
                "nim": "122450020",
                "umur": "20 Tahun",
                "asal": "Lampung Barat",
                "alamat": "Korpri",
                "hobbi": "Bernyanyi dan Menonton",
                "sosmed": "@tryyaniciaaa",
               "kesan": "Kakaknya kalem dan cantik banget",
                "pesan": "Kak, semangat dan sukses selalu",  
            },
            {
                "nama": "Gymnastiar Al Khoarizmy",
                "nim": "122450096",
                "umur": "20 Tahun",
                "asal": "Serang",
                "alamat": "Lapangan Golf UIN",
                "hobbi": "Baca Komik",
                "sosmed": "@jimnn.as",
                "kesan": "Abangnya baik dan pinter",
                "pesan": "Semangat terus, sukses selalu bang",  
            },
            {
                "nama": "Nasywa Nur Afifah",
                "nim": "122450125",
                "umur": "20 Tahun",
                "asal": "Bekasi",
                "alamat": "Jalan Durian 1 Pemda",
                "hobbi": "Nonton Drakor",
                "sosmed": "@nsywanaf",
                "kesan": "Kakaknya baik bangett",
                "pesan": "Semangat kuliahnya kak", 
            },
            {
                "nama": "Priska Silvia Ferantiana",
                "nim": "122450053",
                "umur": "20 Tahun",
                "asal": "Palembang",
                "alamat": "Jalan Nangka 2",
                "hobbi": "Baca Novel yang Bikin Nangis",
                "sosmed": "@prskslv",
                "kesan": "Kakaknya baik dan kalem banget",
                "pesan": "Semangat kak dan always happy",  
            },
            {
                "nama": "Abit Ahmad Oktarian",
                "nim": "122450042",
                "umur": "19 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "Rajabasa, Labuhan Dalam",
                "hobbi": "Ngoding, Gaming",
                "sosmed": "@abitahmad",
                "kesan": "Abangnya pinter banget ngoding",
                "pesan": "Semangat ngodingnya bang, dan sukses terus",  
            },
            {
                "nama": "Akmal Faiz Abdillah",
                "nim": "122450114",
                "umur": "20 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "Perumahan Griya Sukarame",
                "hobbi": "Main HP",
                "sosmed": "@_akmal.faiz",
                "kesan": "Abangnya baik, dan keren banget",
                "pesan": "Bang, semangat kuliahnya yaa", 
            },
            {
                "nama": "Hermawan Manurung ",
                "nim": "122450069",
                "umur": "20 Tahun",
                "asal": "Bogor",
                "alamat": "Dekat Jalan Tol (Wisma Hana Hani)",
                "hobbi": "Bengong/Membaca Buku",
                "sosmed": "@hermawan.mnrng",
                "kesan": "Abangnya keren dan baik banget",
                "pesan": "Teruslah semangat, sukses selalu bang",  
            },
            {
                "nama": "Khusnun Nisa",
                "nim": "122450078",
                "umur": "20 Tahun",
                "asal": "Lampung Selatan",
                "alamat": "",
                "hobbi": "Mengerjakan Tugas",
                "sosmed": "@khusnun_nisa335",
                "kesan": "Kakaknya baik dan kerenn",
                "pesan": "Kak, semangat mengerjakan tugasnya yaww", 
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Medkraf()

elif menu == "Departemen MIKFES":
    def Mikfes():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1lzteNlW03KKqSB9PBfvDBejk_EStCXSc",
            "https://drive.google.com/uc?export=view&id=1lssOBZXjK-iJgtktxkHFMwOScJ-tsI6L",
            "https://drive.google.com/uc?export=view&id=1lwE5NJ4EI-r7QjZyM126VI0DWz6ZDdBw",
            "https://drive.google.com/uc?export=view&id=1m-COGJrvizrN7Z6DSjXWiSe-aXUJVXFm",
            "https://drive.google.com/uc?export=view&id=1lF5fgRaOkA113A5EWXBWBCUszPMJwtnS",
            "https://drive.google.com/uc?export=view&id=1m7rUi8ADAKqSAM4bw7ukq5UULyhaPQf7",
            "https://drive.google.com/uc?export=view&id=1lG8-zkBglyKyFhiNsZAXUHA_b7VptDc4",
            "https://drive.google.com/uc?export=view&id=1luJcVW7N2h67PzLceT8PPLhFzXmvXmC_",
            "https://drive.google.com/uc?export=view&id=1lJ9MeQljQVS3Gq4iF86zrwkNz7rT4djD",
            "https://drive.google.com/uc?export=view&id=1lMVIbJL87exTTjYLY3PJkrOMJ8AAEZRo",
            "https://drive.google.com/uc?export=view&id=1lajLKt1BRWEEM7vVdidDyGYfT3oj8nJC",
            "https://drive.google.com/uc?export=view&id=1lMKtmIi3RETm_fiYGB4G6rx7lFtrLhKh",
            "https://drive.google.com/uc?export=view&id=1lNi0XMywqjS_2AxrvpHN9t325fUBRZ9R",
            "https://drive.google.com/uc?export=view&id=1lUskDTkD_KHe5OkhocJ_8pQH5Jp1CVgB",
            "https://drive.google.com/uc?export=view&id=1mE7TM04-PStZhXATXAnQ95mA8-z41rcN",
            "https://drive.google.com/uc?export=view&id=1l7VVbvsscYdinwYU74WP82JqUIprSd1n",
            "https://drive.google.com/uc?export=view&id=1lX31c9SFEx3YCHZhDe6wRFrG4VE_AL1n",
            "https://drive.google.com/uc?export=view&id=1mFsrVglYlG6NfH1GDYMDnvH6hlJWq79K",
            "https://drive.google.com/uc?export=view&id=1mB5MtrxuEKN-GHO6XGsyMZrns75BLwoT",
        ] 
        data_list = [
            {
                "nama": "Rafi Fadhlillah",
                "nim": "121450143",
                "umur": "21 Tahun",
                "asal": "Lubuk Linggau",
                "alamat": "Jl. Nangka 4",
                "hobbi": "Olahraga",
                "sosmed": "@rafadhilillahh13",
                "kesan": "Abangnya baik, ramah dan inspiratif",
                "pesan": "Bang, semoga sukses dan terus menginspirasi", 
            },
            {
                "nama": "Annisa Novantika",
                "nim": "121450005",
                "umur": "21 Tahun",
                "asal": "Lampung Utara",
                "alamat": "Jl. Pulau Sebesi, Sukarame",
                "hobbi": " Memasak",
                "sosmed": "@anovavona",
                "kesan": "Kakaknya kalem dan baik",
                "pesan": "Semangat kuliahnya kak, pengen coba masakan kakak hehe", 
            },
            {
                "nama": "Natanael Oktavianus Partahan Sihombing ",
                "nim": "121450107",
                "umur": "20 Tahun",
                "asal": "Jakarta",
                "alamat": "Kemiling ",
                "hobbi": "Membuka Wisata HMSD",
                "sosmed": "@natanaeloks",
                "kesan": "Abangnya ramah, baik dan kerenn",
                "pesan": "Semangat dan sukses selalu bang, ditunggu wisata HMSDnya yaa bang", 
            },
            {
                "nama": "Abdurrahman Al-atsary",
                "nim": "121450128",
                "umur": "23 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "Perumnas Way Kandis",
                "hobbi": " Membaca",
                "sosmed": "@rahmn_abdr",
               "kesan": "Abangnya keren bangett pokonya",
                "pesan": "Terus berkarya bang, dan sukses selalu", 
            },
            {
                "nama": "Ahmad Sahidin Akbar",
                "nim": "122450044",
                "umur": "20 Tahun",
                "asal": "Tulang Bawang",
                "alamat": " Sukarame",
                "hobbi": "Olahraga",
                "sosmed": "@sahid22__",
               "kesan": "Abangnya baik dan keren banget",
                "pesan": "Bang, semangat dan sukses selalu yaa", 
            },
            {
                "nama": "Fadhil Fitra Wijaya",
                "nim": "122450082",
                "umur": "20 Tahun",
                "asal": "Bekasi",
                "alamat": "Teluk Betung ",
                "hobbi": "Main Game",
                "sosmed": "@fadhilfwee",
                "kesan": "Abangnya kece bangett, keren outfitnya",
                "pesan": "Selalu semangat menjalani perkuliahan ya bang", 
            },
            {
                "nama": "Muhammad Regi Abdi Putra Amanta",
                "nim": " 122450031",
                "umur": "19 Tahun",
                "asal": "Palembang",
                "alamat": "Jl. Permadi Sukarame  ",
                "hobbi": "Main Game",
                "sosmed": "@mregiiii_",
                "kesan": "Abangnya keren bangett dan inspiratif",
                "pesan": "Sukses selalu dan terus berkarya bang", 
            },
            {
                "nama": "Syalaisha Andina Putriansyah",
                "nim": "122450121",
                "umur": "21 Tahun",
                "asal": "Tangerang",
                "alamat": "Gg Yudhistira ",
                "hobbi": "Baca Novel",
                "sosmed": "@dkselsd_31",
               "kesan": "Kakaknya kalem dan baik banget",
                "pesan": "Kak, semangat terus yaw", 
            },
            {
                "nama": "Anwar Muslim",
                "nim": "122450117",
                "umur": "21 Tahun",
                "asal": "Bukittinggi",
                "alamat": "Korpri ",
                "hobbi": " ML (Machine Learning)",
                "sosmed": "@here.am.ai",
               "kesan": "Abangnya baik bangett",
                "pesan": "Sukses terus dan semangat MLnya bang", 
            },
            {
                "nama": "Deva Anjani Khayyuninafsyah",
                "nim": "122450014",
                "umur": "21 Tahun",
                "asal": " Bandar Lampung",
                "alamat": "Kemiling",
                "hobbi": "Menonton Film",
                "sosmed": "@anjaniiidev",
                "kesan": "Kakaknya manis bangett",
                "pesan": "Semangat terus dalam perkuliahannya kak", 
            },
            {
                "nama": "Dinda Nababan",
                "nim": "122450120",
                "umur": "20 Tahun",
                "asal": "Medan",
                "alamat": "Jl. Lapas",
                "hobbi": "Main Game",
                "sosmed": "@dindanababan_",
               "kesan": "Kakaknya baik dan ramah",
                "pesan": "Semangat kuliahnyaa kak", 
            },
            {
                "nama": "Marleta Cornelia Leander",
                "nim": "122450092",
                "umur": "20 Tahun",
                "asal": "Depok, Jawa Barat",
                "alamat": "Gg. Nangka 3",
                "hobbi": "Liatin Jurnal",
                "sosmed": "@marletacornelia",
                "kesan": "Kakaknya baik dan ramah bangett, nim ujungnya sama kak hihi",
                "pesan": "Terus semangat dan sukses selalu kak", 
            },
            {
                "nama": "Rut Junita Sari Siburian",
                "nim": "122450103",
                "umur": "20 Tahun",
                "asal": "Batam, Kep.Riau",
                "alamat": "Gg. Nangka 3",
                "hobbi": "Resume Jurnal",
                "sosmed": "@junitaa_0406",
                "kesan": "Kakaknya baik dan kalem",
                "pesan": "Kak, semangat dan sukses selalu yaw", 
            },
            {
                "nama": "Syadza Puspadari Azhar",
                "nim": " 122450072",
                "umur": "20 Tahun",
                "asal": "Palembang",
                "alamat": "Belwis ",
                "hobbi": "Membaca",
                "sosmed": "@puspadrr",
                "kesan": "Kak puspaa kerenn bangett, perhatian, dan baik banget",
                "pesan": "Kak, semangat kuliah dan belajarnya yaww", 
            },
            {
                "nama": "Aditya Rahman",
                "nim": "122450113",
                "umur": "20 Tahun",
                "asal": " Lampung Timur",
                "alamat": "Korpri",
                "hobbi": "Ngoding WISATA",
                "sosmed": "@rahm_adityaa",
                "kesan": "Abangnya kece dan jago banget ngoding",
                "pesan": "Bang, semangat terus ngodingnya yaa", 
            },
            {
                "nama": "Eggi Satria",
                "nim": "122450032",
                "umur": "20 Tahun",
                "asal": "Sukabumi",
                "alamat": "Korpri",
                "hobbi": "Ngoding dan buat konten WISATA",
                "sosmed": "@egistr ",
                "kesan": "Abangnya jago banget ngoding dan baik jugaa",
                "pesan": "Semangatt ngoding dan buat kontennya yaa bangg", 
            },
            {
                "nama": "Febiya Jomy Pratiwi",
                "nim": "122450074",
                "umur": "20 Tahun",
                "asal": "Tulang Bawang",
                "alamat": "Jl Kelengkeng Raya",
                "hobbi": "Nonton K-Drama ",
                "sosmed": "@pratiwifebiya",
                "kesan": "Kakaknya kalem dan cantik banget",
                "pesan": "Semangat belajarnya kak", 
            },
            {
                "nama": "Happy Syahrul Ramadhan",
                "nim": "122450013",
                "umur": "20 Tahun",
                "asal": "Lampung",
                "alamat": "Karang Anyar ",
                "hobbi": " Main Game",
                "sosmed": "@sudo.syahrulramadhannn",
                "kesan": "Abangnya baik, dan keren banget",
                "pesan": "Semangat dalam perkuliahannya bang dan always happy", 
            },
            {
                "nama": "Randa Andriana Putra",
                "nim": "122450083",
                "umur": "21 Tahun",
                "asal": "Banten",
                "alamat": " Sukarame",
                "hobbi": " Tidur dan Berkembang",
                "sosmed": "@randaandriana_",
                "kesan": "Abangnya baik bangett, ramah dan jago banget ngoding",
                "pesan": "Semangat ngodingnya, dan terus berkembang ya bang", 
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Mikfes()

elif menu == "Departemen EKSTERNAL ":
    def Eksternal():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1ibYoGBP4UElpLLYv7NyWnw-llkXbV1l6",
            "https://drive.google.com/uc?export=view&id=1iVNuB183zMjTxCUMabbHqsXTZLp9sWJZ",
            "https://drive.google.com/uc?export=view&id=1ipUm405AzYjWWRWb5YXQlzDBRITgOZso",
            "https://drive.google.com/uc?export=view&id=1iI_VzQMEa5h_gm8toSOTvbJaxnTaUh85",
            "https://drive.google.com/uc?export=view&id=1ipXGfu3GxkGdP760w8hb31pLxh912F2j",
            "https://drive.google.com/uc?export=view&id=1iuof9_-4VA7dLO_-U6GAt4t0K_p3bBLb",
            "https://drive.google.com/uc?export=view&id=1hjOERUjIkic4ZiBi_0L4Wd7RGYQ4sgRh",
            "https://drive.google.com/uc?export=view&id=1ikuS_XJLmCiH5lSi0Unv_4VJGFQ68Ts_",
            "https://drive.google.com/uc?export=view&id=1i639k5dmb0fWkgXUYS6UAq3a9gF0MLZ-",
            "https://drive.google.com/uc?export=view&id=1hmjOpiqsh9kKyVpgOe3OdJ1jSpCIeYJb",
            "https://drive.google.com/uc?export=view&id=1hxSREJTLRnzxQukmSbQcBjLfYE-Ozina",
            "https://drive.google.com/uc?export=view&id=1iSD8N5UkIO7cjt3S1z5SEyoPPyhxewsO",
            "https://drive.google.com/uc?export=view&id=1iCt_YKCSPVJFoyxVM1yTK9lQIhb1U0Wp",
            "https://drive.google.com/uc?export=view&id=1i5VbSoeF4qkey--0U2IAj-KNdLWgneJM",
            "https://drive.google.com/uc?export=view&id=1i92jnzlfCR0SVy3QDJuNplQUUNdCs93s",
            "https://drive.google.com/uc?export=view&id=1i-5c7GqzkBRujZqrSzTvdpsIRbooUrIG",
         
        ]
        data_list = [
            {
                "nama": "Yogy Sae Tama",
                "nim": "121450041",
                "umur": "21 Tahun",
                "asal": "Tangerang",
                "alamat": "Jatimulyo",
                "hobbi": "Ngisi Bensin",
                "sosmed": "@yogyyyyyyy",
                "kesan": "Abangnya baik dan keren bangett",
                "pesan": "Semangat selalu ya bang", 
            },
            {
                "nama": "Ramadhita Asifa Hendri",
                "nim": "121450131",
                "umur": "21 Tahun",
                "asal": "Rajabasa",
                "alamat": "Rajabasa",
                "hobbi": "Belajar",
                "sosmed": "@Ramadhitaasifa",
                "kesan": "Kakaknya baik bangett",
                "pesan": "Semangat belajarnya yaa kak",
            },
            {
                "nama": "Nazwa Nabilla",
                "nim": "121450112",
                "umur": "21 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "Way Kandis",
                "hobbi": "Belajar dengan Rajin",
                "sosmed": "@nazwanbilla",
                "kesan": "Kakaknya baik bangett",
                "pesan": "Kak, semangat belajarnya yaw",
            },
            {
                "nama": "Rizki Adrian Bennovry",
                "nim": "121450073",
                "umur": "21 Tahun",
                "asal": "Bekasi",
                "alamat": "TVRI",
                "hobbi": "Buat Portopolio",
                "sosmed": "@rzkdrnnn",
                "kesan": "Abangnya baik dan keren bangett",
                "pesan": "Tetap semangat dalam perkuliahannya bang",
            },
            {
                "nama": "Dea Mutia Risani",
                "nim": "122450099",
                "umur": "20 Tahun",
                "asal": "Sumatera Barat",
                "alamat": "Korpri",
                "hobbi": "Bikin Surat",
                "sosmed": "@deaa.rsn",
                "kesan": "Kakaknya keren bangett",
                "pesan": "Semangat kuliahnya dan bikin suratnya kak",
            },
            {
                "nama": "Novelia Adinda",
                "nim": "122450104",
                "umur": "21 Tahun",
                "asal": "Jakarta",
                "alamat": "Belwis",
                "hobbi": "Tidur",
                "sosmed": "@nvliadinda",
                "kesan": "Kakaknya baik banget",
                "pesan": "Semangatt dalam menjalani perkuliahan ya kak",
            },
            {
                "nama": "Ratu Keisha Jasmin Deonova",
                "nim": "122450106",
                "umur": "20 Tahun",
                "asal": "Bogor",
                "alamat": "Way Kandis",
                "hobbi": "Ngerjain ADW",
                "sosmed": "@jasminednva",
                "kesan": "Kakaknya keren dan ramah banget",
                "pesan": "Semangat kak, semoga sukses selalu",
            },
            {
                "nama": "Tobias David Monogari",
                "nim": "121450081",
                "umur": "20 Tahun",
                "asal": "Jakarta Barat",
                "alamat": "Pemda",
                "hobbi": "Bikin Puisi",
                "sosmed": "@tobiassiagian",
                "kesan": "Abangnya kece dan baik bangett",
                "pesan": "Semangat selalu ya bang",
            },
            {
                "nama": "Arafi Ramadhan Maulana",
                "nim": "12245022",
                "umur": "20 Tahun",
                "asal": "Jogja, Depok",
                "alamat": "Way Huwi",
                "hobbi": "Menghafal Al-Quran",
                "sosmed": "@arafiramadhanmaulana",
                "kesan": "Abangnya seruu",
                "pesan": "Semangat dan sehat terus ya bang",
            },
            {
                "nama": "Asa Do'a Uyi",
                "nim": "122450005",
                "umur": "20 Tahun",
                "asal": "Muara",
                "alamat": "Korpri",
                "hobbi": "cuci baju",
                "sosmed": "@u_yippy",
                "kesan": "Kakaknya seru dan asikk",
                "pesan": "Semangat dan selalu bahagia kakk",
            },
            {
                "nama": "Chalifia Wananda",
                "nim": "122450076",
                "umur": "20 Tahun",
                "asal": "Padang",
                "alamat": "sukarame",
                "hobbi": "Quality Time",
                "sosmed": "@chipawww",
                "kesan": "Manis banget kak",
                "pesan": "Semangatt kuliahh dan quality time kak",
            },
            {
                "nama": "Irvan Alfaritzi",
                "nim": "122450093",
                "umur": "21 Tahun",
                "asal": "Sumatera Barat",
                "alamat": "Jakarta",
                "hobbi": "Nonton Youtube dan main ML",
                "sosmed": "@Alfaritziirfan",
                "kesan": "Abangnya baik poll",
                "pesan": "Semoga dipermudah segala urusannya bang",
            },
            {
                "nama": "Izza Lutfia",
                "nim": "122450090",
                "umur": "20 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "Teluk",
                "hobbi": "main volly",
                "sosmed": "@izzalutfiaa",
                "kesan": "Kakaknya ramah, baik dan asik bangett",
                "pesan": "Semoga selalu sehat dan bahagia kak",
            },
            {
                "nama": "Khaalishah Zuhrah ALyaa Valefi",
                "nim": "122450034",
                "umur": "20 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "Rajabasa",
                "hobbi": "Nyanyi",
                "sosmed": "@alyaavalefi",
                "kesan": "Kakaknya manis poll",
                "pesan": "Kak, mangats selalu yaww",
            },
            {
                "nama": "Raid Muhammad Naufal",
                "nim": "122450027",
                "umur": "20 Tahun",
                "asal": "Lampung Tengah",
                "alamat": "Sukarame",
                "hobbi": "Ngeresume Seminar",
                "sosmed": "@rayHis_",
                "kesan": "Abangnya seruu dan baik",
                "pesan": "Sukses dan semangat terus bang",
            },
            {
                "nama": "Tria Yunanni",
                "nim": "122450062",
                "umur": "20 Tahun",
                "asal": "Way Kanan",
                "alamat": "Jakarta",
                "hobbi": "Baca",
                "sosmed": "@tria_y062",
                "kesan": "Kakak daplok waktu pplk hihi",
                "pesan": "Kak, sukses terus dan always happy yaww",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Eksternal()

elif menu == "Departemen INTERNAL ":
    def Internal():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1HWqMwjCl1U9Mz_N-gw0gpg7YkT1LHLy2",
            "https://drive.google.com/uc?export=view&id=1IMlO-AnsWELfLoejcCAqLaGRnhQK5OTt",
            "https://drive.google.com/uc?export=view&id=1IPy2JUwBltNj6RPTGw8_dgiTzhPuAkdL",
            "https://drive.google.com/uc?export=view&id=1Ht6dmMYGb9pJ34hTmox9qs7QAX2zF29H",
            "https://drive.google.com/uc?export=view&id=1I0IrMYJ0uBXLm0rqs1Of0vcADndDL_DR",
            "https://drive.google.com/uc?export=view&id=1I8jT4JFD0F4aav6atH3oULzovO7kCwrx",
            "https://drive.google.com/uc?export=view&id=1I5iH-w2v4ajRFrFVmfidAKEgSCOnrc37",
            "https://drive.google.com/uc?export=view&id=1HuhVs1Gq9HmotGKl7byLK0lXUBM9UUdY",
            "https://drive.google.com/uc?export=view&id=1HVjOIY5bKobykw7xmLjuzJdz1BxvAEls",
            "https://drive.google.com/uc?export=view&id=1HlNpsKbH7bJ4mpMFooQNB9zO21EVGvRC",
            "https://drive.google.com/uc?export=view&id=1HtvEwXSh3OOGOH4qENiHf4Q4oWRfVEU0",
            "https://drive.google.com/uc?export=view&id=1HvcaBVg8e57Yvw5wt8bE_5PYPln4KWkT",
            "https://drive.google.com/uc?export=view&id=1HdzG0bYupOKgqkpNLhOewrN-CXCNvupG",
         
        ]
        data_list = [
            {
                "nama": "Dimas Rizky Ramadhani",
                "nim": "121450027",
                "umur": "20 Tahun",
                "asal": "Pamulang",
                "alamat": "Way kandis",
                "hobbi": "Manjat tower sutet",
                "sosmed": "@dimzrky",
                "kesan": "Hobinya anti mainstream ya bang",
                "pesan": "Sukses selalu bang, semangat nyusun TA nyaa", 
            },
            {
                "nama": "Catherine Firdhasari Maulina Sinaga",
                "nim": "121450072",
                "umur": "20 Tahun",
                "asal": "Sumatera Utara",
                "alamat": "Airan",
                "hobbi": "Baca novel",
                "sosmed": "@chatherine.sinaga",
                "kesan": "Kakaknya kalem bangett dan baik",
                "pesan": "Semangat terus ya kak, sukses teruss", 
            },
            {
                "nama": "M. Akbar Resdika",
                "nim": "121450066",
                "umur": "20 Tahun",
                "asal": "Lampung Barat",
                "alamat": "Labuhan dalam",
                "hobbi": "Memelihara dino",
                "sosmed": "@akbar_resdika",
                "kesan": "Abangnya seru poll",
                "pesan": "Bang, semangat menjalani harinya",
            },
            {
                "nama": "Ari Sigit",
                "nim": "121450069",
                "umur": "23 Tahun",
                "asal": "Lampung barat",
                "alamat": "Labuhan ratu",
                "hobbi": "Main futsal",
                "sosmed": "@ari_sigit17",
                "kesan": "Abangnya baik dan kalem",
                "pesan": "Tetap semangat, dan sukses selalu",
            },    
            {
                "nama": "Rani Puspita Sari",
                "nim": "122450030",
                "umur": "20 Tahun",
                "asal": "Metro",
                "alamat": "Rajabasa",
                "hobbi": "Mengaji",
                "sosmed": "@ranipu",
                "kesan": "Kakaknya baik dan kerenn",
                "pesan": "Selalu semanagat yaww kak",
            },
            {
                "nama": "Rendra Eka Prayoga",
                "nim": "122450112",
                "umur": "20 Tahun",
                "asal": "Bekasi",
                "alamat": "Jalan lapas raya",
                "hobbi": "nulis lagu",
                "sosmed": "@rendraepr",
                "kesan": "Abangnyaa baik, seru poll klo cerita",
                "pesan": "Sukses terus bang, semangat ngasprak strukdat RC ya bang",
            },
            {
                "nama": "Salwa Farhanatussaidah",
                "nim": "122450055",
                "umur": "20 Tahun",
                "asal": "Pesawaran",
                "alamat": "Airan raya",
                "hobbi": "ngeliat cogan",
                "sosmed": "@slwfhn_694",
                "kesan": "Cantik bangett kak",
                "pesan": "Mangats kuliahnya kak",
            },
            {
                "nama": "Azizah Kusumah Putri",
                "nim": "122450068",
                "umur": "21 Tahun",
                "asal": "Lampung Selatan",
                "alamat": "Natar",
                "hobbi": "berkebun",
                "sosmed": "@azizahksmh15",
                "kesan": "Kakaknya baik dan ramahh",
                "pesan": "Semangat menjalani hari dan berkebunnya kak",
            },
            {
                "nama": "Meira Listyaningrum",
                "nim": "122450011",
                "umur": "20 Tahun",
                "asal": "Pesawaran",
                "alamat": "Airan raya",
                "hobbi": "Menghalu",
                "sosmed": "@meiraln",
                "kesan": "Kakaknya baikk",
                "pesan": "Sukses terus kak",
            },
            {
                "nama": "Rendi Alexander Hutagalung",
                "nim": "122450057",
                "umur": "20 Tahun",
                "asal": "Tangerang",
                "alamat": "Kost gunawan",
                "hobbi": "Menyanyi",
                "sosmed": "@alexanderr",
                "kesan": "Abangnya asik, ramah dan baikk",
                "pesan": "Semoga selalu diberi kemudahan ya bang",
            },
            {
                "nama": "Renta Siahaan",
                "nim": "122450070",
                "umur": "21 Tahun",
                "asal": "Sumatera Utara",
                "alamat": "Gerbang barat",
                "hobbi": "Memancing",
                "sosmed": "@renta.shn",
                "kesan": "Kakaknya kalemm",
                "pesan": "Kak, terus semangat yaww",
            },
            {
                "nama": "Yosia Lehare Banurea",
                "nim": "121450149",
                "umur": "20 Tahun",
                "asal": "Dairi, Sumatera utara",
                "alamat": "Perum griya indah",
                "hobbi": "Bawa motor pakai kaki",
                "sosmed": "@yosiabanurea",
                "kesan": "Abangnya baikk banget",
                "pesan": "Bang, ajarin bawa motor dong bang",
            },
            {
                "nama": "Josua Panggabean",
                "nim": "121450061",
                "umur": "21 Tahun",
                "asal": "Pematang Siantar",
                "alamat": "Gya kost",
                "hobbi": "Ngawinin cupang",
                "sosmed": "@josuapanggabean16_",
                "kesan": "Abangnya baik bangett",
                "pesan": "Semangatt kuliah dan sukses selalu ya bangg",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Internal()
    
elif menu == "Departemen SSD ":
    def Ssd():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1AbujEcqxFV9ptyPWhAphNpckcl0H0W6Z",
            "https://drive.google.com/uc?export=view&id=1AXZkHU5Vzjcdtht0Kch6a6uL5qahDTpq",
            "https://drive.google.com/uc?export=view&id=1AX_vYwfaBGbD0eD6zurSQc6yWSazlNpJ",
            "https://drive.google.com/uc?export=view&id=1AcZj795OGNLFB1xUHQOlUvUCkjkNv0Z9",
            "https://drive.google.com/uc?export=view&id=1AfI1ZDq62oJxWq36a4urcjlP06MkB9NY",
            "https://drive.google.com/uc?export=view&id=1AbPJG9WqrkRNNHQ2k854nT96NvZ4HBs4",
            "https://drive.google.com/uc?export=view&id=1AYUNBIGJavbquJvw8G3_pyMo9T5vWFjz",
            "https://drive.google.com/uc?export=view&id=1AZcU3hWul79gnWYUFMDzD8c0v39wvX3u",
            "https://drive.google.com/uc?export=view&id=1A_6O5iRJR75N7QL-nvQlE0yPWz0LQfJu",
        ]
        data_list = [
            {
                "nama": "Andrian Agustinus Lumban Gaol",
                "nim": "121450090",
                "umur": "17 Tahun",
                "asal": "Sidikalang",
                "alamat": "Lapas",
                "hobbi": "Nyari Hobi",
                "sosmed": "@andrialgaol",
                "kesan": "Abangnyaa kerenn dan kece poll",
                "pesan": "Semangat dan tetep keren bang",
            },
            {
                "nama": "Adisty Syawaida Ariyanto",
                "nim": "121450136",
                "umur": "21 Tahun",
                "asal": "Metro",
                "alamat": "Metro",
                "hobbi": "Nonton film",
                "sosmed": "@adistisa_",
                "kesan": "Kakaknya baik bangett",
                "pesan": "Semoga kuliahnya lancar ya kak",
            },
            {
                "nama": "Nabila Azhari",
                "nim": "121450029",
                "umur": "21 Tahun",
                "asal": "Simalungun",
                "alamat": "Airan",
                "hobbi": "Menghitung",
                "sosmed": "@zhjung",
                "kesan": "Kakaknya ramah",
                "pesan": "Kak, semangatt kuliah dan menghitungnya yaw",
            },
            {
                "nama": "Nabilah Andika Fitriani",
                "nim": "121450129",
                "umur": "21 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "Kedaton",
                "hobbi": "Tidur",
                "sosmed": "@nabilaafrn",
                "kesan": "Kakaknya baik dan seruu",
                "pesan": "Kak, semangat dan sukses terus yaw",
            },
            {
                "nama": "Danang Hilal Kurniawan",
                "nim": "122450085",
                "umur": "21 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "TB 3 Asrama",
                "hobbi": "Belajar",
                "sosmed": "@dananghk_",
                "kesan": "Keren poll, public speakingnya mantebb",
                "pesan": "Semangat berinovasi bang",
            },
            {
                "nama": "Farel Julio Akbar",
                "nim": "122450110",
                "umur": "20 Tahun",
                "asal": "Bogor",
                "alamat": "Jalan Lapas",
                "hobbi": "Bebas",
                "sosmed": "@farel__julio",
                "kesan": "Abangnya baik dan seru bangett",
                "pesan": "Semoga lancar kuliahnya bang",
            },
            {
                "nama": "Alvia Asrinda Br.Ginting",
                "nim": "122450077",
                "umur": "20 Tahun",
                "asal": "Binjai",
                "alamat": "Korpri",
                "hobbi": "Nonton Windah",
                "sosmed": "@alviaginting",
                "kesan": "Kakaknya cantik bangett dan soft spoken",
                "pesan": "Semangat perkuliahannya bang",
            },
            {
                "nama": "Dhafin Razaka Luthfia",
                "nim": "122450133",
                "umur": "20 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "Jalan nangka 1",
                "hobbi": "Olahraga",
                "sosmed": "@dhafinrzqri3",
                "kesan": "Abangnya pendiem",
                "pesan": "Bang, selalu semangat menjalani perkuliahannya yaa",
            },
            {
                "nama": "Elia Meylani Simanjuntak",
                "nim": "122450026",
                "umur": "20 Tahun",
                "asal": "Bekasi",
                "alamat": "Korpri",
                "hobbi": "Main Badminton",
                "sosmed": "@meylanielia",
                "kesan": "Kakaknya seru dan asik poll",
                "pesan": "Semangatt kak dan always happy kak",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Ssd()