import streamlit as st
from streamlit_option_menu import option_menu
import requests
from PIL import Image, ImageOps
from io import BytesIO

st.markdown("""<style>.centered-title {text-align: center;}</style>""",unsafe_allow_html=True)
st.markdown("<h1 class='centered-title'>BUKU KATING</h1>", unsafe_allow_html=True)

# bagian sini jangan diubah
def streamlit_menu():
    selected = option_menu(
        menu_title=None,
        options=[
            "Kesekjenan",
            "Baleg",
            "Senator",
            "Departemen PSDA",
            "Departemen MEDCRAF",
            "Departemen MIKFES",
            "Departemen Eksternal",
            "Departemen Internal",
            "Departemen SSD",
        ],
        icons=[
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
        ],
        default_index=0,
        orientation="horizontal",
        styles={
            "container": {"padding": "0!important", "background-color": "#fafafa"},
            "icon": {"color": "black", "font-size": "19px"},
            "nav-link": {
                "font-size": "15px",
                "text-align": "left",
                "margin": "0px",
                "--hover-color": "#eee",
            },
            "nav-link-selected": {"background-color": "#3FBAD8"},
        },
    )
    return selected

@st.cache_data
def load_image(url):
    response = requests.get(url)
    if response.status_code != 200:
        st.error(
            f"Failed to fetch image from {url}, status code: {response.status_code}"
        )
        return None
    try:
        img = Image.open(BytesIO(response.content))
        img = ImageOps.exif_transpose(img)
        img = img.resize((300, 400))
        return img
    except Exception as e:
        st.error(f"Error loading image: {e}")
        return None
    
@st.cache_data
def display_images_with_data(gambar_urls, data_list):
    images = []
    for i, url in enumerate(gambar_urls):
        with st.spinner(f"Memuat gambar {i + 1} dari {len(gambar_urls)}"):
            img = load_image(url)
            if img is not None:
                images.append(img)

    for i, img in enumerate(images):
        # Menggunakan Streamlit untuk menampilkan gambar di tengah kolom
        col1, col2, col3 = st.columns([1, 2, 1])
        with col2:
            st.image(img, use_column_width=True)

        if i < len(data_list):
            st.write(f"Nama: {data_list[i]['nama']}")
            st.write(f"NIM: {data_list[i]['nim']}")
            st.write(f"Umur: {data_list[i]['umur']}")
            st.write(f"Asal: {data_list[i]['asal']}")
            st.write(f"Alamat: {data_list[i]['alamat']}")
            st.write(f"Hobbi: {data_list[i]['hobbi']}")
            st.write(f"Sosial Media: {data_list[i]['sosmed']}")
            st.write(f"Kesan: {data_list[i]['kesan']}")
            st.write(f"Pesan: {data_list[i]['pesan']}")
            st.write("  ")
    st.write("Semua gambar telah dimuat!")
menu = streamlit_menu()

# BAGIAN SINI YANG HANYA BOLEH DIUABAH
if menu == "Kesekjenan":
    def kesekjenan():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1QxHPQMAXMZh5IPPcRbDXOfCnSn-OMj1V",
            "https://drive.google.com/uc?export=view&id=1R3JIrOSmUwI-b1gdL5uCdHiSNgdXBdfz",
            "https://drive.google.com/uc?export=view&id=1RI0qpxRk7gMwvLw94HHcXHjgqhDzgnCR",
            "https://drive.google.com/uc?export=view&id=1QzqRkQq18eiO_1b_Jo8KV71WTdreQGCi",
            "https://drive.google.com/uc?export=view&id=1ROce75jm9fDI5htchlAigsiZ7WartHrs",
            "https://drive.google.com/uc?export=view&id=1QspfzsUd-A5OvdMtvgYicX1mJVq55-wZ",
        ]
        data_list = [
            {

                "nama": "Kharisma Gumilang",
                "nim": "121450142",
                "umur": "21",
                "asal": "Palembang",
                "alamat": "Jl.Pulau Damar",
                "hobbi": "Dengerin Musik",
                "sosmed": "@gumilangkharisma",
                "kesan": "Berkharisma dan Menginspirasi",  
                "pesan":"Semangat buat TA nya, sehat selalu!"# 1
            },
            {   
                "nama": "Pandra Insani Putra Anwar",
                "nim": "121450147",
                "umur": "21",
                "asal":"Lampung Utara",
                "alamat": "Sukarame",
                "hobbi": "Main Gitar",
                "sosmed": "@pandrainsani27",
                "kesan": "Keren banget dan Insight full",  
                "pesan":"Semangat bang !!!, tetap ganteng -juesi"# 1
            },
            {   
                "nama": "Meliza Wulandari",
                "nim": "121450065",
                "umur": "20",
                "asal":"Sumatera Selatan",
                "alamat": "Jl.Pagar Alam",
                "hobbi": "Nonton Drakor",
                "sosmed": "@wulandarimeliza",
                "kesan": "keren banget kak",  
                "pesan":"semangat ngaspraknya kak !!!"# 1
            },
        
            {
                "nama": "Putri Maulida Chairani",
                "nim": "121450050",
                "umur": "21",
                "asal":"Sumatera Barat",
                "alamat": "Gg. Nangka 4",
                "hobbi": "Dengerin Bg Pandra Main Gitar",
                "sosmed": "@ptrimaulidaaa_",
                "kesan": "Cantik, pendengar yang baik ",  
                "pesan":"Terimakasih udah support kami"# 1
            },
        
            {   
                "nama": "Hartiti Fadilah",
                "nim": "121450031",
                "umur": "21",
                "asal":"Palembang",
                "alamat": "Pemda",
                "hobbi": "Nyanyi",
                "sosmed": "@htrpdla",
                "kesan": "cantik",  
                "pesan":"Semangat ngurus cuannya"# 1
            },
        
            {
                "nama": "Nadilla Andhara Putri",
                "nim": "121450003",
                "umur": "21",
                "asal":"Lampung",
                "alamat": "Metro",
                "hobbi": "Mainn Bola, Belajar",
                "sosmed": "@nadilaandr26",
                "kesan": "vibes bendaharanya kerasa bgt",  
                "pesan":"Semangat ngasprak strukdatnya!"# 1
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    kesekjenan()

elif menu == "Baleg":
    def baleg():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=16Z-GnyGp6g8Sz-MgW4u75EV9Nudpc_4y",
            "https://drive.google.com/uc?export=view&id=16KsUqpKZWVTehmvn7QCHWDvVWd1H50kq",
            "https://drive.google.com/uc?export=view&id=16MAw6m4U4NCi2PlQTUJBarug242rcHwQ",
            "https://drive.google.com/uc?export=view&id=16JeIPWLhwCxOU07HaPtt_kys9g7WBjCH",
            "https://drive.google.com/uc?export=view&id=16aaI524axqk0evjhnB8LuLZv_8fQWxXP",
            "https://drive.google.com/uc?export=view&id=16DKXsipXI_z7C57mr7JSVArxZwrPYj8Q",
            "https://drive.google.com/uc?export=view&id=16Hx2y8YA4oS8Rs6EOVFEmwMd0lolvIIH",
            "https://drive.google.com/uc?export=view&id=16_Cta-Aem-LMb4LSJi6VW6wx5ECwesWQ",
            "https://drive.google.com/uc?export=view&id=1Rg7EQZ9dOwwgvLS1w7EWRYqkZ-C5cccZ",
            "https://drive.google.com/uc?export=view&id=16VgJZx738bOzse76n03yqS0deCeMwiJz",
            "https://drive.google.com/uc?export=view&id=16JmY0wj9BUP0wYB_uxl5rrJRRhGk_L-o",
        ]
        data_list = [
            {
                "nama": "Tri murniya Ningsih",
                "nim": "121450038",
                "umur": "21",
                "asal":"Bogor",
                "alamat": "Raden saleh",
                "hobbi": "Nanya ke gpt",
                "sosmed": "@trimurniaa_",
                "kesan": "Kakak cantik asprak alpro RA",  
                "pesan":"semangat ngaspraknya kakak !!!"
            },
            {
                "nama": "Annisa cahyani surya",
                "nim": "121450114",
                "umur": "21",
                "asal":"Tangsel",
                "alamat": "Way huwi",
                "hobbi": "Membaca, nonton",
                "sosmed": "@anisacahyanisurya",
                "kesan": "Kakak nya cantik banget",  
                "pesan":"semoga TA nya lancar kakkk !!!"# 1
            },
            {
                "nama": "Wulan sabina",
                "nim": "121450150",
                "umur": "21",
                "asal":"Medan",
                "alamat": "Raden saleh",
                "hobbi": "Belajar, nonton film, tidur",
                "sosmed": "@wlsbn0",
                "kesan": "Kakak pasti orang baik kannn",  
                "pesan":"semoga dilancarkan dan dimudahkan segala urusannya ya kak!!!"# 1
            },
            {
                "nama": "Anisa dini amalia",
                "nim": "121450081",
                "umur": "20",
                "asal":"Tanggerang",
                "alamat": "Jati agung",
                "hobbi": "Nonton drachin",
                "sosmed": "@anisadini10",
                "kesan": "Waktu ngomongin hobinya, kakaknya keliatan seneng bgt",  
                "pesan":"semangat maraton drachinnya kak !!!"# 1
            },
            {
                "nama": "Feriyadi yulius",
                "nim": "122450087",
                "umur": "20",
                "asal":"Sumatera selatan",
                "alamat": "Way kandis",
                "hobbi": "Baca buku",
                "sosmed": "@fer_yulius",
                "kesan": "Abangnya keren",  
                "pesan":"semangat menjalani semester 5 bang!!!"# 1
            },
            {
                "nama": "Renisha Putri Giani",
                "nim": "122450079",
                "umur": "21",
                "asal":"Bandar Lampung",
                "alamat": "Teluk Betung",
                "hobbi": "Jualan pancing",
                "sosmed": "@fleurnsh",
                "kesan": "Kakaknya lucu",  
                "pesan":" Semangat kuliahnya kakak !!!"# 1
            },
            {
                "nama": "Claudhia Angeliani",
                "nim": "121450124",
                "umur": "21",
                "asal":"Lampung Timur",
                "alamat": "Lampung Timur",
                "hobbi": "Tidur",
                "sosmed": "@dylebee",
                "kesan": "Seru bgt ngobrol sama kakak",  
                "pesan":" Semangat berproses kak!!!"# 1
            },
            {
                "nama": "Mirzan Yusuf Rabbani",
                "nim": "122450110",
                "umur": "20",
                "asal":"Jakarta",
                "alamat": "Korpri",
                "hobbi": "Tidur yang lama, main kucing",
                "sosmed": "@myrrinn",
                "kesan": "ucul kakaknya,tinngi lagi",  
                "pesan":"semangat berhibernasinya kak !!!"# 1
            },
            {
                "nama": "Muhammad fahrul Aditya",
                "nim": "121450156",
                "umur": "22",
                "asal":"Surakarta",
                "alamat": "Sukarame",
                "hobbi": "Melukis, olahraga",
                "sosmed": "@fhrul.pdf",
                "kesan": "Kakaknya keren banget",  
                "pesan":"Terus semangat bangg"# 1
            },
            {
                "nama": "Jeremia susanto",
                "nim": "122450022",
                "umur": "20",
                "asal":"Bandar Lampung",
                "alamat": "Bandar Lampung",
                "hobbi": "Bengong",
                "sosmed": "@jeremia_s_",
                "kesan": "Bang jere ramah bgt orangnya",  
                "pesan":"semangat kuliahnya bang !!!"# 1
            },
            {
                "nama": "Berliana enda putri",
                "nim": "122450065",
                "umur": "20",
                "asal":"Sumatera barat",
                "alamat": "Way huwi",
                "hobbi": "Duduk di tepi pantai sambil galauin bintang yang tinggal satu",
                "sosmed": "@berlyyanda",
                "kesan": " kakaknya lucuu dan seruu",  
                "pesan":"Tetap semangat, jangan menyerah!!!"# 1
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    baleg()

elif menu == "Senator":
    def senator():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1KbksD7Iq3FqQesHdfyPypfSB9_YS6W-E",
            "https://drive.google.com/uc?export=view&id=1N6NuU-_QzSIw-5v7pAzdFpBOSGe5XbzC",
        ]
        data_list = [
            {
                "nama": "Anissa Luthfi Alifia",
                "nim": "121450093",
                "umur": "22",
                "asal": "Lampung Tengah",
                "alamat": "Kost Putri Rahayu",
                "hobbi": "Dengerin bintang nyanyi",
                "sosmed": "@anissalutfi_",
                "kesan": "Kak luthfi kalau ngomong berkharisma",
                "pesan": "Semangat kuliahnya kak, semangat ngerjain TA nya", 
            },
            {
                "nama": "Rian Bintang Wijaya",
                "nim": "122450094",
                "umur": "20",
                "asal": "Palembang",
                "alamat": "Kota Baru",
                "hobbi": "Nyanyi",
                "sosmed": "@bintangtwinkle",
                "kesan": "ramah, baik, selalu senyum",
                "pesan": "Semangat menjalani hari hari nya bang, semoga bahagia selalu",
            }
        ]
        display_images_with_data(gambar_urls, data_list)
    senator()

elif menu == "Departemen PSDA":
    def Psda():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1Vkr1xfU9VCIA8lFVO6SmpYRWJUi6NSV_",
            "https://drive.google.com/uc?export=view&id=1WbOkcSqjmB4lEofJOXVy2jSmgRjgU5Ip",
            "https://drive.google.com/uc?export=view&id=1WGoyPscWQiRhyAatDH8PKu7Td4KsITsX",
            "https://drive.google.com/uc?export=view&id=1W0R-HkAX9tCVB80eddvJrEGZ7bB_xg67",
            "https://drive.google.com/uc?export=view&id=1Vv3LOhLt0PNzaHtPf0ZHcvje5ZVdqcAd",
            "https://drive.google.com/uc?export=view&id=1WGXl9FarHsv9A_1N7CRsGLwgoNTAuhw2",
            "https://drive.google.com/uc?export=view&id=1VxYAdY4wTfb5VWz5_LBJg3UM7M8ow9Kt",
            "https://drive.google.com/uc?export=view&id=1VoNE-xtP7u9QCix3iDQ8E3rgBjgGr5Wh",
            "https://drive.google.com/uc?export=view&id=1VygxU5pXpmoPHbJk6A3qrdUnfsnuvaS4",
            "https://drive.google.com/uc?export=view&id=1WIIjKktwFM_5tfvXSNR-Kbu2ujmtXjC7",
            "https://drive.google.com/uc?export=view&id=1Wb2clJH6yz-PV23_NXBoRP_9yQZgYXrj",
            "https://drive.google.com/uc?export=view&id=1VjJV2YYnFfjkwcVb6LgNsvF73Jt6OOM1",
            "https://drive.google.com/uc?export=view&id=1W_jz6yBU_BwfJOfSC9zgbNcuiQ1D5oGK",
            "https://drive.google.com/uc?export=view&id=1W_h2eFxvBYW3nRozOZfXfquRC9K541nn",
            "https://drive.google.com/uc?export=view&id=1W71WGrsRfRnI9AQOOPLPIX8YDz9A5ANf",
            "https://drive.google.com/uc?export=view&id=1Vm4-Q13wDJbXzBVfbDoMSSHvPIb5Hh4r",
            "https://drive.google.com/uc?export=view&id=1WSaOHrxOhU7XiL0r0TwxwxosbOyienfL",
            "https://drive.google.com/uc?export=view&id=1WHBhFbHns07Bvahwmhf_vAJxg9yE--qe",
            "https://drive.google.com/uc?export=view&id=1WbIN3jIc6laQhxnlB70T7eLghjl8E1PO",

        ]
        data_list = [
            {
                "nama": "Ericson Chandra Sihombing",
                "nim": "121450026",
                "umur": "21",
                "asal": "Bekasi",
                "alamat": "Khobam",
                "hobbi": "Travelling",
                "sosmed": "@ericsonchandr99",
                "kesan": "kalau  ngomong berwibawa banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari", 
            },
            {
                "nama": "Elisabeth Claudia Simanjuntak",
                "nim": "122450123",
                "umur": "18",
                "asal": "Tanggerang",
                "alamat": "Kemiling",
                "hobbi": "Bernafas",
                "sosmed": "@celisabethh_",
                "kesan": "kak abet kalau senyum cantik",
                "pesan": "selalu ceria, dan bahagia kak",
            },
            {
                "nama": "Nisrina Nur Afifah",
                "nim": "122450052",
                "umur": "19",
                "asal": "Jawa Barat",
                "alamat": "Sukarame",
                "hobbi": " Muter-muter",
                "sosmed": " @afifahhnsrn",
                "kesan": "kakaknya cantik dan ramah",
                "pesan": "semangat terus kakakkk,semoga cita citanya tercapai ya",
            },
            {
                "nama": "Allya Nurul Islami Pasha",
                "nim": "122450033",
                "umur": "20",
                "asal": "Sumatera Barat",
                "alamat": "Belwis",
                "hobbi": "Nongs",
                "sosmed": "@allyaislami",
                "kesan": "kak alya baik dan asik",
                "pesan": "Selalu semangat dan jangan pernah menyerah kak",
            },
            {
                "nama": "Eksanty Febriana Sukma Islamiaty",
                "nim": "122450001",
                "umur": "20",
                "asal": "Lubuk Linggau",
                "alamat": "Rajabasa",
                "hobbi": "Nyari sinyal di gedung F",
                "sosmed": "@eksantyfebriana",
                "kesan": "kak eksanty baik dan ramah",
                "pesan": "Selalu ceria, dan jadi diri sendiri kak",
            },
            {
                "nama": "Farahanum Afifah Ardiansyah",
                "nim": "122450056",
                "umur": "20",
                "asal": "Padang",
                "alamat": "Sukarame",
                "hobbi": "Minum Kopi",
                "sosmed": "@farahanumafifahh",
                "kesan": "kak hanum cantik dan baik,ramah juga",
                "pesan": "semangat dan selalu tersenyum kak, senyum kakak cantik",
            },
            {
                "nama": "Ferdy Kevin Naibaho",
                "nim": "122450107",
                "umur": "20",
                "asal": "Medan",
                "alamat": "Senopati Raya",
                "hobbi": "Dengerin Musik",
                "sosmed": "@ferdy_kevin",
                "kesan": "Abangnya keren banget dan baik",
                "pesan": "Semangat kuliahnya bang, semoga sehat selalu",
            },
            {
                "nama": "M. Deriansyah Okutra",
                "nim": "122450101",
                "umur": "19",
                "asal": "Kayu Agung",
                "alamat": "Jl. Pagar Alam Kedaton",
                "hobbi": "Nongki-nongki",
                "sosmed": "@dransyh_",
                "kesan": "Abangnya keren dan baik banget",
                "pesan": "semoga yang disemogakan tersemogakan",
            },
            {
                "nama": "Oktavia Nurwenda Puspita Sari",
                "nim": "122450041",
                "umur": "20",
                "asal": "Lampung Timur",
                "alamat": "Way Huwi",
                "hobbi": "Scroll tik-tok",
                "sosmed": "@oktavianrwnda",
                "kesan": "Kakaknya baik dan ramah",
                "pesan": "Selalu semangat dan pantang menyerah kak",
            },
            {
                "nama": "Deyvan Loxefal",
                "nim": "121450148",
                "umur": "21",
                "asal": "Duri Riau",
                "alamat": "Khobam Pulau Damar",
                "hobbi": "Belajar",
                "sosmed": "@depanlo",
                "kesan": "bang devan selalu lucu dan out of the box",
                "pesan": "Semangat ngerjain TA nya bang, semoga dilancarkan",
            },
            {
                "nama": "Ibnu Farhan Al-Ghifari",
                "nim": "121450121",
                "umur": "21",
                "asal": "Kerinci Jambi",
                "alamat": "Khobam",
                "hobbi": "game online",
                "sosmed": "@al_ghifari032",
                "kesan": "abangnya ganteng dan baik",
                "pesan": "Semangat skripsiannya bang",
            },
            {
                "nama": "Kemas Veriandra Ramadhan",
                "nim": "122450016",
                "umur": "19",
                "asal": "Bekasi",
                "alamat": "Kojo Golf UIN",
                "hobbi": "Main game",
                "sosmed": "@kemasverii",
                "kesan": "Abangnya smart dan keren",
                "pesan": "Selalu jadi diri sendiri karena abang keren banget",
            },
            {
                "nama": "Leonard Andreas Napitupulu",
                "nim": "121450153",
                "umur": "21",
                "asal": "Medan",
                "alamat": "Khobam",
                "hobbi": "belajar",
                "sosmed": "@lndr.__",
                "kesan": "baik dan ramah",
                "pesan": "semangat dan pantang menyerah bang",
            },
            {
                "nama": "Presilia",
                "nim": "122450081",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Kota Baru",
                "hobbi": "Dengerin lomba sihir",
                "sosmed": "@presiliamy",
                "kesan": "Kakaknya cantik banget dan ramah",
                "pesan": "Semangat kuliahnya kakk",
            },
            {
                "nama": "Sahid Maulana",
                "nim": "122450109",
                "umur": "21",
                "asal": "Depok, Jabar",
                "alamat": "Jl. Airan Raya",
                "hobbi": "Dengerin musik",
                "sosmed": "@sahid_maul19",
                "kesan": "Word of affirmation parahhh",
                "pesan": "Selalu bang, semoga apa yang dicita citakan tercapai ya bang",
            },
            {
                "nama": "M. Farhan Athaulloh",
                "nim": "121450117",
                "umur": "21",
                "asal": "Lampung ",
                "alamat": "Kota Baru",
                "hobbi": "Menolong",
                "sosmed": "@mfarhan.ath",
                "kesan": "Keren dan ramah abangnya,apalagi waktu wawancara kemarin",
                "pesan": "Semangat dan selalu ramah bang",
            },
            {
                "nama": "Gede Moana",
                "nim": "121450014",
                "umur": "21",
                "asal": "Bekasi",
                "alamat": "Korpri Raya",
                "hobbi": "Belajar, game, baca komik",
                "sosmed": "@gedemoenaa",
                "kesan": "Abangnya lucu dan baik",
                "pesan": "Semangat ngerjain TA bang",
            },
            {
                "nama": "Jaclin Alcavella",
                "nim": "122450015",
                "umur": "19",
                "asal": "Sumatera Selatan",
                "alamat": "Korpri",
                "hobbi": "Berenang",
                "sosmed": "@jaclinalcv_",
                "kesan": "cantik, baik, ramah, paket komplit",
                "pesan": "Semangat meraih cita citanya kak",
            },
            {
                "nama": "Syalaisha Andini Putriansyah",
                "nim": "122450111",
                "umur": "21",
                "asal": "Tangerang",
                "alamat": "Sukarame",
                "hobbi": "Baca",
                "sosmed": "@syalaisha.i__",
                "kesan": "Kakaknya pendiam tapi baik",
                "pesan": "Semangat selalu kuliahnya kak",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Psda()

elif menu == "Departemen MEDCRAF":

    def Medcraf():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=16Bg1DdSd779c3P7hgZ7zV13V1nYwMbYT",
            "https://drive.google.com/uc?export=view&id=16-PdBYb1BRQye9b5D-AgBYleegjv2D3r",
            "https://drive.google.com/uc?export=view&id=15sTnRaofi-Bi5qwVNpCd4-qrKcVBSfqR",
            "https://drive.google.com/uc?export=view&id=16DK8j3i5l8vry1CCOwNAzj2rFO4BLeRA",
            "https://drive.google.com/uc?export=view&id=161iY1tj3s_dIHnZa0K7MYiM--MT0M4vs",
            "https://drive.google.com/uc?export=view&id=165cWdj4Wng_dOBH2dHtUCw2Z5Kt7lfe0",
            "https://drive.google.com/uc?export=view&id=15zabpiBSQ4W37BbmDLNr9Sc0uPUSqBzK",
            "https://drive.google.com/uc?export=view&id=162S3bx5rMQtvKrg0GRoDHmvbCUAurERU",
            "https://drive.google.com/uc?export=view&id=166rT7Tfs7swA2Mq4xG-W0b5ZoP6Bjule",
            "https://drive.google.com/uc?export=view&id=162z_j7f30xpGTy2PrN-zoQkZxN3mTG3n",
            "https://drive.google.com/uc?export=view&id=15s5DU281mUK6Z3iW0AF0UTFWHYsQX_Jn",
            "https://drive.google.com/uc?export=view&id=161_eu2VzUjkQ7l120PM4cpAeBqgb2fpB",
            "https://drive.google.com/uc?export=view&id=16BoAgL1XL-HXjwPjO-R_XGz_n_K2IWEG",
            "https://drive.google.com/uc?export=view&id=169bAJQmtkIGZdikQZOrC-BQdwfbWdLu4",
            "https://drive.google.com/uc?export=view&id=166QmPSZ8Oj1wuTi2crTXBYNKJOzIVlVH",
        ]
        data_list = [
            {
                "nama": "Wahyudiyanto",
                "nim": "121450040",
                "umur": "22",
                "asal": "Makassar",
                "alamat": "Sukarame",
                "hobbi": "Nonton",
                "sosmed": " ",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
            {
                "nama": "Elok Fiola",
                "nim": "122450051",
                "umur": "19",
                "asal": "Bandar Lampung",
                "alamat": "Bandar Lampung",
                "hobbi": "Editing",
                "sosmed": "@elokfiola",
                "kesan": "Manis bangett kakk",
                "pesan": "Semangat ya kak, tetap ramah", 
            },
            {
                "nama": "Muhammad Kaisar Firdaus ",
                "nim": " 121450135",
                "umur": "21",
                "asal": "Pesawaran",
                "alamat": "Pulau Damar",
                "hobbi": "Lagi Nyari",
                "sosmed": " @dino_kiper",
                "kesan": "keren abangnya",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari", 
            },
            {
                "nama": "Muhammad Arsal Ranjana Putra",
                "nim": "121450111",
                "umur": "21",
                "asal": "Depok",
                "alamat": "Nangka 4",
                "hobbi": "Ngoding",
                "sosmed": "@arsal.utama",
                "kesan": "parah si keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari", 
            },
            {
                "nama": "Cintya  Bella",
                "nim": "122450066",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Teluk",
                "hobbi": "Ngegym",
                "sosmed": "@cintyabella28",
                "kesan": "Suka banget sama outfit kakak, cocok banget di divisi media & konten",
                "pesan": "Semangat kuliahnya kak, jangan lupa belajar tiap hari", 
            },
            {
                "nama": "Patricia Leondra Diajeng Putri ",
                "nim": "122450050",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Jatimulyo",
                "hobbi": "Nonton Film",
                "sosmed": "@patriciadiajeng",
                "kesan": "ini juga ramah banget",
                "pesan": "Semangat kuliahnya kak, jangan lupa belajar tiap hari", 
            },
            {
                "nama": "Rahma Neliyana",
                "nim": "122450036",
                "umur": "20",
                "asal": "Lampung",
                "alamat": "Sukarame",
                "hobbi": "Baca Coding",
                "sosmed": "@rahmanellyana",
                "kesan": "ramah bintang 1000",
                "pesan": "Semangat kuliahnya kak, jangan lupa belajar tiap hari", 
            },
            {
                "nama": "Try Yani Rizki Nur Rohmah ",
                "nim": "122450020",
                "umur": "20",
                "asal": "Lampung Barat",
                "alamat": "Korpri",
                "hobbi": "Bernyanyi dan Menonton",
                "sosmed": "@tryyaniciaaa",
                "kesan": "cantik sekali",
                "pesan": "Semangat kuliahnya kak, jangan lupa belajar tiap hari", 
            },
            {
                "nama": "Gymnastiar Al Khoarizmy",
                "nim": "122450096",
                "umur": "20",
                "asal": "Serang",
                "alamat": "Lapangan Golf UIN",
                "hobbi": "Baca Komik",
                "sosmed": "@jimnn.as",
                "kesan": "keren parah",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari", 
            },
            {
                "nama": "Nasywa Nur Afifah ",
                "nim": "122450125",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Jalan Durian 1 Pemda",
                "hobbi": "Nonton Drakor",
                "sosmed": "@nsywanaf",
                "kesan": "sangat baik",
                "pesan": "semangat kuliahnya kak", 
            },
            {
                "nama": "Abit Ahmad Oktarian",
                "nim": "122450042",
                "umur": "19",
                "asal": "Bandar Lampung",
                "alamat": "Rajabasa, Labuhan Dalam",
                "hobbi": "Ngoding, Gaming",
                "sosmed": "@abitahmad",
                "kesan": "baik sekalee",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari", 
            },
            {
                "nama": "Akmal Faiz Abdillah",
                "nim": "122450114",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Perumahan Griya Sukarame",
                "hobbi": "Main HP",
                "sosmed": "@_akmal.faiz",
                "kesan": "abangnya baikk",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari", 
            },
            {
                "nama": "Hermawan Manurung ",
                "nim": "122450069",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Dekat Jalan Tol (Wisma Hana Hani) ",
                "hobbi": "Bengong/Membaca Buku",
                "sosmed": "@hermawan.mnrng",
                "kesan": "keren si kalo kataku",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari", 
            },
            {
                "nama": "Khusnun Nisa",
                "nim": "122450078",
                "umur": "20",
                "asal": "Lampung Selatan",
                "alamat": "",
                "hobbi": "Mengerjakan Tugas",
                "sosmed": "@khusnun_nisa335",
                "kesan": "imut, lucu",
                "pesan": "Semangat kuliahnya kak, jangan lupa belajar tiap hari", 
            },
            {
                "nama": "Priska Silvia Ferantiana",
                "nim": "122450053",
                "umur": "20",
                "asal": "Palembang",
                "alamat": "Jalan Nangka 2",
                "hobbi": "Baca Novel yang Bikin Nangis",
                "sosmed": "@prskslv",
                "kesan": "baikk sekalii",
                "pesan": "Semangat kuliahnya kak, jangan lupa belajar tiap hari", 
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Medcraf()

elif menu == "Departemen MIKFES":

    def Mikfes():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=16rNuxHBsLQ2Ho-Cs0zSineS2n9_wuj7a",
            "https://drive.google.com/uc?export=view&id=17HBwaCfKjy28Ow7kKjOmWONf-6Poo1T_",
            "https://drive.google.com/uc?export=view&id=16dCLB6hkRx9fokHRnHWvp3E7J_Q8q0DS",
            "https://drive.google.com/uc?export=view&id=172JYInXWbBeB0emHcGI7qs1eQhlu1DCW",
            "https://drive.google.com/uc?export=view&id=16h5XKcRSq-ReCZbFA6W3Ehd2gjABJK44",
            "https://drive.google.com/uc?export=view&id=17Blw7gpT-KzVMlUTzrpnEgVcNSXZwiWR",
            "https://drive.google.com/uc?export=view&id=16qic5edWbczUanMtnTAXV94rojLw4C6o",
            "https://drive.google.com/uc?export=view&id=16kaypJWQtDB03pUoLAbbhRQYEb_JSWJe",
            "https://drive.google.com/uc?export=view&id=176VQFsOQahsMh8B7KgDaUJaLETCk1dhc",
            "https://drive.google.com/uc?export=view&id=17DLDjpV6b_JZe-5pAHoXNiZ7JYa3perF",
            "https://drive.google.com/uc?export=view&id=17Lgluhq1NhRHIR0v_waMhVJrPX4ULcXa",
            "https://drive.google.com/uc?export=view&id=17ADOrTCyMyIMxmYkgxdlC9JY0siIqHvk",
            "https://drive.google.com/uc?export=view&id=179c8D_ZuuoFf4ZcdgOcCNNBzryyG_mAf",
            "https://drive.google.com/uc?export=view&id=174iUDf4VHk2npsUQdvqCgsuyKVSYL02r",
            "https://drive.google.com/uc?export=view&id=171gF0xcYFMLMsrqJzFPSxqV8FCr5TGLm",
            "https://drive.google.com/uc?export=view&id=16wPOF11IJiZBoCE3_jiPzLA5p65HomBY",
            "https://drive.google.com/uc?export=view&id=17LPTTgPii1_BWUw0B2lrrHOaptgOMH_B",
            "https://drive.google.com/uc?export=view&id=17107sK0Vwsuyd0yupHktSWq2J2fevjlM",
            "https://drive.google.com/uc?export=view&id=172AX8R5wV3OHrRJ7femr6xJ_f6-Z6PwF",
        ] 
        data_list = [
            {
                "nama": "Rafi Fadhlillah",
                "nim": "121450143",
                "umur": "21 Tahun",
                "asal": "Lubuk Linggau",
                "alamat": "Jl. Nangka 4",
                "hobbi": "Olahraga",
                "sosmed": "@rafadhilillahh13",
                "kesan": "sangat baik dan ramah",
                "pesan": "semangta bang rafi",
            },
            {
                "nama": "Annisa Novantika",
                "nim": "121450005",
                "umur": "21 Tahun",
                "asal": "Lampung Utara",
                "alamat": "Jl. Pulau Sebesi, Sukarame",
                "hobbi": " Memasak",
                "sosmed": "@anovavona",
                "kesan": "baikkkk",
                "pesan": "semoga selalu bahagia kakak",
            },
            {
                "nama": " Ahmad Sahidin Akbar",
                "nim": "122450044",
                "umur": " 20",
                "asal": "Tulang Bawang",
                "alamat": " Sukarame",
                "hobbi": "Olahraga",
                "sosmed": "@sahid22__",
                "kesan": "kerenn",
                "pesan": "semangat abang daplok ",
            },
            {
                "nama": "Fadhil Fitra Wijaya",
                "nim": "122450082",
                "umur": "20 Tahun",
                "asal": "Bekasi",
                "alamat": "Teluk Betung ",
                "hobbi": "Main Game",
                "sosmed": "@fadhilfwee",
                "kesan": "kerenn powl",
                "pesan": "semoga sehat selalu",
            },
            {
                "nama": "Muhammad Regi Abdi Putra Amanta",
                "nim": " 122450031",
                "umur": "19 Tahun",
                "asal": "Palembang",
                "alamat": "Jl. Permadi Sukarame  ",
                "hobbi": "Main Game",
                "sosmed": "@mregiiii_",
                "kesan": "aktif banget abangnya",
                "pesan": "semangat meraih mimpi bang",
            },
            {
                "nama": "Syalaisha Andina Putriansyah",
                "nim": "122450121",
                "umur": "21 Tahun",
                "asal": "Tangerang",
                "alamat": "Gg Yudhistira ",
                "hobbi": "Baca Novel",
                "sosmed": "@dkselsd_31",
                "kesan": "baik bintang 100",
                "pesan": "semangat kakak",
            },
            {
                "nama": "Natanael Oktavianus Partahan Sihombing ",
                "nim": "121450107",
                "umur": "20 Tahun",
                "asal": "Jakarta",
                "alamat": "Kemiling ",
                "hobbi": "Membuka Wisata HMSD",
                "sosmed": "@natanaeloks",
                "kesan": "seru powl",
                "pesan": "semoga sukses selalu",
            },
            {
                "nama": "Anwar Muslim",
                "nim": "122450117",
                "umur": "21 Tahun",
                "asal": "Bukittinggi",
                "alamat": "Korpri ",
                "hobbi": " ML (Machine Learning)",
                "sosmed": "@here.am.ai",
                "kesan": "baik ",
                "pesan": "banyakin senyum bang",
            },
            {
                "nama": "Deva Anjani Khayyuninafsyah",
                "nim": "122450014",
                "umur": "21 Tahun",
                "asal": " Bandar Lampung",
                "alamat": "Kemiling",
                "hobbi": "Menonton Film",
                "sosmed": "@anjaniiidev",
                "kesan": "sangat baik",
                "pesan": "jangan menyerahh",
            },
            {
                "nama": "Dinda Nababan",
                "nim": "122450120",
                "umur": "20 Tahun",
                "asal": "Medan",
                "alamat": "Jl. Lapas",
                "hobbi": "Main Game",
                "sosmed": "@dindanababan_",
                "kesan": "baik sekali",
                "pesan": "selalu baik kakk",
            },
            {
                "nama": "Marleta Cornelia Leander",
                "nim": "122450092",
                "umur": "20 Tahun",
                "asal": "Depok, Jawa Barat",
                "alamat": "Gg. Nangka 3",
                "hobbi": "Liatin Jurnal",
                "sosmed": "@marletacornelia",
                "kesan": "ihiy ada kakak cantik",
                "pesan": "semangat terus ya kakk",
            },
            {
                "nama": "Rut Junita Sari Siburian",
                "nim": "122450103",
                "umur": "20 Tahun",
                "asal": "Batam, Kep.Riau",
                "alamat": "Gg. Nangka 3",
                "hobbi": "Resume Jurnal",
                "sosmed": "@junitaa_0406",
                "kesan": "lucu dan menggemaskan",
                "pesan": "semangat kak",
            },
            {
                "nama": "Syadza Puspadari Azhar",
                "nim": " 122450072",
                "umur": "20 Tahun",
                "asal": "Palembang",
                "alamat": "Belwis ",
                "hobbi": "Membaca",
                "sosmed": "@puspadrr",
                "kesan": "yang ini favorit aku sii",
                "pesan": "aku tau kakak pasti bisa, semangat kakk",
            },
            {
                "nama": " Abdurrahman Al-atsary",
                "nim": "121450128",
                "umur": "23 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "Perumnas Way Kandis",
                "hobbi": " Membaca",
                "sosmed": "@rahmn_abdr",
                "kesan": "baikk sekali",
                "pesan": "semangat banggg",
            },
            {
                "nama": "Aditya Rahman",
                "nim": "122450113",
                "umur": "20 Tahun",
                "asal": " Lampung Timur",
                "alamat": "Korpri",
                "hobbi": "Ngoding WISATA",
                "sosmed": "@rahm_adityaa",
                "kesan": "keren, no fake no fake",
                "pesan": "semoga apa yang disemogakan tersemogakan",
            },
            {
                "nama": "Eggi Satria",
                "nim": "122450032",
                "umur": "20 Tahun",
                "asal": "Sukabumi",
                "alamat": "Korpri",
                "hobbi": "Ngoding dan buat konten WISATA",
                "sosmed": "@egistr ",
                "kesan": "pinter banget abangnyaa",
                "pesan": "semangat terus bang",
            },
            {
                "nama": "Febiya Jomy Pratiwi",
                "nim": "122450074",
                "umur": "20 Tahun",
                "asal": "Tulang Bawang",
                "alamat": "Jl Kelengkeng Raya",
                "hobbi": "Nonton K-Drama ",
                "sosmed": "@pratiwifebiya",
                "kesan": "seru powl",
                "pesan": "semangatt kakkk",
            },
            {
                "nama": "Happy Syahrul Ramadhan",
                "nim": "122450013",
                "umur": "20 Tahun",
                "asal": "Lampung",
                "alamat": "Karang Anyar ",
                "hobbi": " Main Game",
                "sosmed": "@sudo.syahrulramadhannn",
                "kesan": "selalu happy ya kak",
                "pesan": "semangat kuliahnya bang",
            },
            {
                "nama": "Randa Andriana Putra",
                "nim": "122450083",
                "umur": "21 Tahun",
                "asal": "Banten",
                "alamat": " Sukarame",
                "hobbi": " Tidur dan Berkembang",
                "sosmed": "@randaandriana_",
                "kesan": "baik sekali",
                "pesan": "Selamat mengemban tugas baru",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Mikfes()

elif menu == "Departemen Eksternal":
    def Eksternal():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1RVhGP7scHrJwBkaW4kssLmmmZfBzUQeT",
            "https://drive.google.com/uc?export=view&id=1RTmjx2N7AGJBSivGzjvId7EtsdgbaQIz",
            "https://drive.google.com/uc?export=view&id=1RNl7JUj7AQM4qpZoLDoDJN5KxtTfjRTM",
            "https://drive.google.com/uc?export=view&id=1Rcg1YZkIYMdZ7r-4vR33KqksnKePero4",
            "https://drive.google.com/uc?export=view&id=1R_Tk5dnO0SG63Ysw7_svw-RdUjA_tDgw",
            "https://drive.google.com/uc?export=view&id=1RG7O-gMrLlDT9htgMHNY5yYmnroYARRE",
            "https://drive.google.com/uc?export=view&id=1RD1IAwSTzlq_xtA1auFehEi9Gzcp1n3A",
            "https://drive.google.com/uc?export=view&id=1R1EF4bzFGm0m7tWFG7pWpZXUm6-TFidM",
            "https://drive.google.com/uc?export=view&id=1QeyxfSjSALhknxsb2UyHh76KgNyJTKxV",
            "https://drive.google.com/uc?export=view&id=1Qcznz689t0f6bhuRHRLu6mtS9TVvFj75",
            "https://drive.google.com/uc?export=view&id=1R5P31EiDoHwSOjJ-WHqRF5R7DjQz1xgm",
            "https://drive.google.com/uc?export=view&id=1RDnCAvxBXvGQIay93XI3RQsmoBGr0i1k",
            "https://drive.google.com/uc?export=view&id=1QgjYODGtuf8JOJOaHHU-H16kwSRoy5PO",
            "https://drive.google.com/uc?export=view&id=1R6b4AcNfGUvxETdKmMIl9WTGQ0-n0fWe",
            "https://drive.google.com/uc?export=view&id=1QgcLUxP_NooFUSGsa6ILBtLnEnv0LEde",
        ]
        data_list = [
            {
                "nama": "Yogy Sae Tama",
                "nim": "121450041",
                "umur": "21",
                "asal": "Burkinapaso",
                "alamat": "Jatimulyo",
                "hobbi": "nyari solar",
                "sosmed": "@",
                "kesan": "Selalu senyum, dan baik banget abangnya",
                "pesan": "Semangat berproses bang, semoga menjadi pribadi yang lebih baik lagi", 
            },
            {
                "nama": "Ramadhita atifa Hendri",
                "nim": "121450131",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Rajabasa",
                "hobbi": "jalan-jalan",
                "sosmed": "@ramadhitatifa",
                "kesan": "cantik dan keren banget kakakk",
                "pesan": "Semoga cita cita kakak tercapai ya, dan selalu bahagia",
            },
            {
                "nama": "Nazwa Nabilla",
                "nim": "121450122",
                "umur": "25",
                "asal": "Jakarta Selatan",
                "alamat": "Kandis",
                "hobbi": "Main Golf",
                "sosmed": "@nazwanbilla",
                "kesan": "Cantik selalu tersenyum dan baik",
                "pesan": "Apapun yang terjadi selalu semangat kakak",
            },
            {
                "nama": "Dea Mutia Risani",
                "nim": "122450099",
                "umur": "20",
                "asal": "Sumatera Barat",
                "alamat": "Korpri",
                "hobbi": "Dengerin musik",
                "sosmed": "@deaa.rsn",
                "kesan": "Kakaknya baik dan cantik banget",
                "pesan": "Selalu semangat kakak, semoga apa yang kamu cita citakan tercapai ya",
            },
            {
                "nama": "Novelia Adinda",
                "nim": "122450104",
                "umur": "21",
                "asal": "Jakarta Timur",
                "alamat": "Belwis",
                "hobbi": "Tidur",
                "sosmed": "@nvliaadinda",
                "kesan": "Ramah dan baik banget asprak strukdat yang satu ini",
                "pesan": "Semangat kuliahnya kakk, semangat ngaspraknya, selalu baik ya kak",
            },
            {
                "nama": "Tobias David Manogari",
                "nim": "122450091",
                "umur": "19",
                "asal": "Kalianda",
                "alamat": "Korpri",
                "hobbi": "Berenang",
                "sosmed": "@tobiassiagian",
                "kesan": "Abangnya ganteng dan baik ",
                "pesan": "Semangat aspak ads RA, selalu bahagia bang",
            },
            {
                "nama": "Rizki Adrian Bennoviry",
                "nim": "121450073",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "TVRI",
                "hobbi": "Berenang",
                "sosmed": "@rzkdrnnn",
                "kesan": "Abangnya keren, baik, dan ramah",
                "pesan": "Semoga kuliahnya selalu dilancarkan ya bang",
            },
            {
                "nama": "Arafi Ramadhan Maulana",
                "nim": "122450022",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Bandar Lampung",
                "hobbi": "Berkuda",
                "sosmed": "@arafiramadhanmaulana",
                "kesan": "Abangnya keren juga lucu",
                "pesan": "jadi diri sendiri ya bang, karena abang unik",
            },
            {
                "nama": "Asa Doa Unyi",
                "nim": "121450010",
                "umur": "22",
                "asal": "Jakarta",
                "alamat": "Jakarta",
                "hobbi": "Baca",
                "sosmed": "@yusuf_fikri",
                "kesan": "kakaknya moodboster",
                "pesan": "semangat teruss kakkk",
            },
            {
                "nama": "Chalifia Wananda",
                "nim": "122450076",
                "umur": "20",
                "asal": "Padang ",
                "alamat": "Sukarame",
                "hobbi": "Membaca",
                "sosmed": "@chipawww",
                "kesan": "Kakaknya keren dan baik juga ramah",
                "pesan": "Semangat kuliahnya kak, selalu ceria kak",
            },
            {
                "nama": "Irvan Alfaritzi",
                "nim": "122450093",
                "umur": "21",
                "asal": "Sumatera Barat",
                "alamat": "Sukarame",
                "hobbi": "Nonton Youtube",
                "sosmed": "@alfaritziirvan",
                "kesan": "Ramah dan baikkk kerenn juga ",
                "pesan": "Semangat kuliahnya, semoga selalu bahagiaa dan sehatt",
            },
            {
                "nama": "Izza Luthfia",
                "nim": "122450090",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Teluk",
                "hobbi": "bertemu anak Pengmas",
                "sosmed": "@izzalutfiaa",
                "kesan": "baik, ramah cantik jugaa",
                "pesan": "semangat terus kak, semangat pengmasnyaa",
            },
            {
                "nama": "Khaalishah Zuhrah Alyaa Valefi",
                "nim": "122450034",
                "umur": "20",
                "asal": "Lampung",
                "alamat": "Rajabasa",
                "hobbi": "Mengaji",
                "sosmed": "@alyaavalefi",
                "kesan": "Kakaknya keren dan lucuu moodboster sekalu",
                "pesan": "Semangat kuliahnya kak, semangat di eksternalnya kakak",
            },
            {
                "nama": "Raid Muhammad Naufal",
                "nim": "122450027",
                "umur": "20",
                "asal": "Lampung Tengah",
                "alamat": "Sukarame",
                "hobbi": "Duduk di wico",
                "sosmed": "@rayths_",
                "kesan": "cool tapi baik",
                "pesan": "semangat asprak ads RA",
            },
            {
                "nama": " Tria Yunani",
                "nim": "122450062",
                "umur": "20",
                "asal": "Way Kanan",
                "alamat": "Sukarame",
                "hobbi": "Tidur",
                "sosmed": "@tria_yo62",
                "kesan": "cantik dan ramah,baik juga",
                "pesan": "Semangat kuliahnya kak, selalu tersenyum dan ceria ya kak",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Eksternal()
elif menu == "Departemen Internal":
    def Internal():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1NrisZKkxoUmdS0Guq6OMJa2Rafl2ewvk",
            "https://drive.google.com/uc?export=view&id=1O5o3Ib92x_t_g8CNCCUKzvGiz6eXRzck",
            "https://drive.google.com/uc?export=view&id=1O3qM_yrPMh-k30F3PHfLXMaVW67jsHh7",
            "https://drive.google.com/uc?export=view&id=1O5i4sSQpO1zu-qMnO_-lcAPia68vJTF5",
            "https://drive.google.com/uc?export=view&id=1O3oGDPkBkCMKbXc26rBL40SKkQPTXS_0",
            "https://drive.google.com/uc?export=view&id=1O4H8sZDXOSW0HvaZYXe7iAqU7srlYemc",
            "https://drive.google.com/uc?export=view&id=1NwXaoAoCf5rsYFfyx36g3xQyj5kofjJC",
            "https://drive.google.com/uc?export=view&id=1O3OgLXeLexXxGbXYd9YOJvynD_g3HTJ2",
            "https://drive.google.com/uc?export=view&id=1NvA5PWqL2n8faYk7elBmcu5ECp-OFe4g",
            "https://drive.google.com/uc?export=view&id=1Nvo2IhxNRQ_FulXyDCjK0lSInq3-WMhD",
            "https://drive.google.com/uc?export=view&id=1O6NZgcirpEnYrrNNS-3tACt2ZvzAnG7h",
            "https://drive.google.com/uc?export=view&id=1O5jhi9q_MFvRaeN2qB7cNEGrWkFCuyRF",
            "https://drive.google.com/uc?export=view&id=1NvmKQ9MDIbjrpjn0uuzoK0XC1usxKhzu",
        ]
        data_list = [
            {
                "nama": "Dimas rizky ramadhani",
                "nim": "121450027",
                "umur": "20",
                "asal": "Pamulang",
                "alamat": "Way kandis",
                "hobbi": "Manjat tower sutet",
                "sosmed": "@dimzrky",
                "kesan": "Berkharisma banget",
                "pesan": "Semangat nyusun TA nya bang dimas", 
            },
            {
                "nama": "Catherine firdhasari maulina sinaga",
                "nim": "121450072",
                "umur": "20",
                "asal": "Sumatera Utara",
                "alamat": "Airan",
                "hobbi": "Baca novel",
                "sosmed": "@chatherine.sinaga",
                "kesan": "kakanya ramah bintang 100",
                "pesan": "Semangat berproses kak",
            },    
            {
                "nama": "M. Akbar resdika",
                "nim": "121450066",
                "umur": "20",
                "asal": "Lampung Barat",
                "alamat": "Labuhan dalam",
                "hobbi": "Memelihara dino",
                "sosmed": "@akbar_resdika",
                "kesan": "Kelihatannya baik (emot senyum)",
                "pesan": "Semangat nyusun TA bang",
            },
            {
                "nama": "Rani puspita sari",
                "nim": "122450030",
                "umur": "20",
                "asal": "Metro",
                "alamat": "Rajabasa",
                "hobbi": "Mengaji",
                "sosmed": "@ranipu",
                "kesan": "Kakak baik",
                "pesan": "Selalu bermanfaat untuk orang sekitar ya kak",
            },
            {
                "nama": "Rendra eka prayoga",
                "nim": "122450112",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Jalan lapas raya",
                "hobbi": "nulis lagu",
                "sosmed": "@rendraepr",
                "kesan": "Ramah bintang 1000",
                "pesan": "Semoga jadi pribadi yang lebih baik lagi ",
            },
            {
                "nama": "Salwa farhanatussaidah",
                "nim": "122450055",
                "umur": "20",
                "asal": "Pesawaran",
                "alamat": "Airan raya",
                "hobbi": "ngeliat cogan",
                "sosmed": "@slwfhn_694",
                "kesan": "Cantik bangett",
                "pesan": "semangat kuliahnya kak",
            },
            {
                "nama": "Ari sigit",
                "nim": "121450069",
                "umur": "23",
                "asal": "Lampung barat",
                "alamat": "Labuhan ratu",
                "hobbi": "Main futsal",
                "sosmed": "@ari_sigit17",
                "kesan": "keren banget abangnya",
                "pesan": "semangat kuliahnya bang ari",
            },
            {
                "nama": "Azizah kusumah putri",
                "nim": "122450068",
                "umur": "21",
                "asal": "Lampung Selatan",
                "alamat": "Natar",
                "hobbi": "berkebun",
                "sosmed": "@azizahksmh15",
                "kesan": "Ramah bangett",
                "pesan": "Semangkaaa semangat kakak!!!",
            },
            {
                "nama": "Meira listyaningrum",
                "nim": "122450011",
                "umur": "20",
                "asal": "Pesawaran",
                "alamat": "Airan raya",
                "hobbi": "Menghalu",
                "sosmed": "@meiraln",
                "kesan": "Baik bangett",
                "pesan": "Semangat kakk!!!",
            },
            {
                "nama": "Rendi alexander hutagalung",
                "nim": "122450057",
                "umur": "20",
                "asal": "Tangerang",
                "alamat": "Kost gunawan",
                "hobbi": "Menyanyi",
                "sosmed": "@alexanderr",
                "kesan": "Baik bangett",
                "pesan": "jangan pentang menyerah,selalu berusaha",
            },
            {
                "nama": "Renta siahaan",
                "nim": "122450070",
                "umur": "21",
                "asal": "Sumatera utara",
                "alamat": "Gerbang barat",
                "hobbi": "Memancing",
                "sosmed": "@renta.shn",
                "kesan": "Keren banget",
                "pesan": "selalu semangat kakak ",
            },
            {
                "nama": "Yosia lehare banurea",
                "nim": "121450149",
                "umur": "20",
                "asal": "Dairi, Sumatera utara",
                "alamat": "Perum griya indah",
                "hobbi": "Bawa motor pakai kaki",
                "sosmed": "@yosiabanurea",
                "kesan": "Baik bangett",
                "pesan": "semangat kakak!!!",
            },
            {
                "nama": "Josua panggabean",
                "nim": "121450061",
                "umur": "21",
                "asal": "Pematang siantar",
                "alamat": "Gya kost",
                "hobbi": "Ngawinin cupang",
                "sosmed": "@josuapanggabean16_",
                "kesan": "sangat soft spoken",
                "pesan": "semangat kuliah bang",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Internal()
elif menu == "Departemen SSD":
    def Ssd():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1AffVElt41QiP03Y7UwUbd96bffmibDZ4",
            "https://drive.google.com/uc?export=view&id=1AnOmwVxlUXBfWXPRCWnOvghKRvrboydZ",
            "https://drive.google.com/uc?export=view&id=1AmE35__of5YK-nYBf0rR888Gj_fcI6J_",
            "https://drive.google.com/uc?export=view&id=1Almswlb0IjRGV_3DmDfeZ5V7VUGICHNz",
            "https://drive.google.com/uc?export=view&id=1AqEfTcJCptuDkWViZamjtQA1iMTARSrb",
            "https://drive.google.com/uc?export=view&id=1Afqe8Or4OmZ-mEdki19_iB5D76noEAtU",
            "https://drive.google.com/uc?export=view&id=1AoCGRNeDA4mX9-w969ewutcVxvxBZtzs",
            "https://drive.google.com/uc?export=view&id=1AoP6P3nZA4esHEirhiSRlaSXe6K4p0hE",
            "https://drive.google.com/uc?export=view&id=1AovOXILpD6XNjvBJAeQ6Vt9m9yil2Ro3",

        ]
        data_list = [
            {
                "nama": "Andrian Agustinus Lumban Gaol",
                "nim": "121450090",
                "umur": "17 +",
                "asal": "Sidikalang",
                "alamat": "Lapas",
                "hobbi": "Nyari Hobi",
                "sosmed": "@andrialgaol",
                "kesan": "Public speakingnya bagus bangett",
                "pesan": "Semangat cari duitnya bang", 
            },
            {
                "nama": "Adisty Syawaida Ariyanto",
                "nim": "121450136",
                "umur": "21",
                "asal": "Metro",
                "alamat": "Metro",
                "hobbi": "Nonton film",
                "sosmed": "@adistisa_",
                "kesan": "Keren banget kak",
                "pesan": "Semangat kuliahnya kak",
            },
            {
                "nama": "Nabila Azhari",
                "nim": "121450029",
                "umur": "21",
                "asal": "Simalungun",
                "alamat": "Airan",
                "hobbi": "Menghitung",
                "sosmed": "@zhjung",
                "kesan": "baik pake banget",
                "pesan": "semangat menjalani hari hari",
            },
            {
                "nama": "Danang Hilal Kurniawan",
                "nim": "122450085",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "TB 3 Asrama",
                "hobbi": "Belajar",
                "sosmed": "@dananghk_",
                "kesan": "cuan cuann",
                "pesan": "lancar lancar di sulawesi",
            },
            {
                "nama": "Farel Julio Akbar",
                "nim": "122450110",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Jalan Lapas",
                "hobbi": "Bebas",
                "sosmed": "@farel__julio",
                "kesan": "berotot bgt",
                "pesan": "semangat jadi capo bang",
            },
            {
                "nama": "Nabilah Andika Fitriani",
                "nim": "121450129",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Kedaton",
                "hobbi": "Tidur",
                "sosmed": "@nabilaafrn",
                "kesan": "imut sekali",
                "pesan": "semangat mengejar cita cita nya kak",
            },
            {
                "nama": "Alvia Asrinda Br.Ginting",
                "nim": "122450077",
                "umur": "20",
                "asal": "Binjai",
                "alamat": "Korpri",
                "hobbi": "Nonton Windah",
                "sosmed": "@alviaginting",
                "kesan": "salah satu kating terhumble siii",
                "pesan": "semangkaaa",
            },
            {
                "nama": "Dhafin Razaka Luthfia",
                "nim": "122450133",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Jalan nangka 1",
                "hobbi": "Olahraga",
                "sosmed": "@dhafinrzqri3",
                "kesan": "baik sekaliii",
                "pesan": "semangat selalu bang",
            },
            {
                "nama": "Elia Meylani Simanjuntak",
                "nim": "122450026",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Korpri",
                "hobbi": "Main Alat Musik",
                "sosmed": "@meylanielia",
                "kesan": "baik sekaliii",
                "pesan": "Kakak hebat! Semoga selalu sukses di masa depan."
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Ssd()

# Tambahkan menu lainnya sesuai kebutuhan
