import streamlit as st
from streamlit_option_menu import option_menu
import requests
from PIL import Image, ImageOps
from io import BytesIO

st.markdown("""<style>.centered-title {text-align: center;}</style>""",unsafe_allow_html=True)
st.markdown("<h1 class='centered-title'>BUKU KATING</h1>", unsafe_allow_html=True)

# bagian sini jangan diubah
def streamlit_menu():
    selected = option_menu(
        menu_title=None,
        options=[
            "Kesekjenan",
            "Baleg",
            "Senator",
            "Departemen PSDA",
            "Departemen MEDKRAF",
            "Departemen MIKFES",
            "Departemen Eksternal",
            "Departemen Internal",
            "Departemen SSD",
        ],
        icons=[
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
        ],
        default_index=0,
        orientation="horizontal",
        styles={
            "container": {"padding": "0!important", "background-color": "#fafafa"},
            "icon": {"color": "black", "font-size": "19px"},
            "nav-link": {
                "font-size": "15px",
                "text-align": "left",
                "margin": "0px",
                "--hover-color": "#eee",
            },
            "nav-link-selected": {"background-color": "#3FBAD8"},
        },
    )
    return selected

@st.cache_data
def load_image(url):
    response = requests.get(url)
    if response.status_code != 200:
        st.error(
            f"Failed to fetch image from {url}, status code: {response.status_code}"
        )
        return None
    try:
        img = Image.open(BytesIO(response.content))
        img = ImageOps.exif_transpose(img)
        img = img.resize((300, 400))
        return img
    except Exception as e:
        st.error(f"Error loading image: {e}")
        return None
    
@st.cache_data
def display_images_with_data(gambar_urls, data_list):
    images = []
    for i, url in enumerate(gambar_urls):
        with st.spinner(f"Memuat gambar {i + 1} dari {len(gambar_urls)}"):
            img = load_image(url)
            if img is not None:
                images.append(img)

    for i, img in enumerate(images):
        # Menggunakan Streamlit untuk menampilkan gambar di tengah kolom
        col1, col2, col3 = st.columns([1, 2, 1])
        with col2:
            st.image(img, use_column_width=True)

        if i < len(data_list):
            st.write(f"Nama: {data_list[i]['nama']}")
            st.write(f"NIM: {data_list[i]['nim']}")
            st.write(f"Umur: {data_list[i]['umur']}")
            st.write(f"Asal: {data_list[i]['asal']}")
            st.write(f"Alamat: {data_list[i]['alamat']}")
            st.write(f"Hobbi: {data_list[i]['hobbi']}")
            st.write(f"Sosial Media: {data_list[i]['sosmed']}")
            st.write(f"Kesan: {data_list[i]['kesan']}")
            st.write(f"Pesan: {data_list[i]['pesan']}")
            st.write("  ")
    st.write("Semua gambar telah dimuat!")
menu = streamlit_menu()

# BAGIAN SINI YANG HANYA BOLEH DIUABAH
if menu == "Kesekjenan":
    def kesekjenan():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1ksfMDdpx9ZeZ9E4TGEsfqXW28puC03U0",
            "https://drive.google.com/uc?export=view&id=1i_M8nbvubNHOcKLnIgtAIVjC5hDwVGeq",
            "https://drive.google.com/uc?export=view&id=1iYwJdbLeWbS4AnaDLFUYhNrLF3ALjd7q",
            "https://drive.google.com/uc?export=view&id=1ktXpw1FZ3PXSi_vRLSMBB5P2_0cj0Arl",
            "https://drive.google.com/uc?export=view&id=1iUuTI7q-8E9HgaCP81OB82vCrSVSzury",
            "https://drive.google.com/uc?export=view&id=1l6M0nwgWQiQI6RcZ-ANIgFjXyU2RiAZj",
        ]
        data_list = [
            {

                "nama": "Kharisma Gumilang",
                "nim": "121450142",
                "umur": "21",
                "asal": "Palembang",
                "alamat": "Jl.Pulau Damar",
                "hobbi": "Dengerin Musik",
                "sosmed": "@gumilangkharisma",
                "kesan": "Asik, Menginspirasi, Panutan",  
                "pesan":"Semoga diperlancar segala urusannya, terutama TAnya!"# 1
            },
            {   
                "nama": "Pandra Insani Putra Anwar",
                "nim": "121450147",
                "umur": "21",
                "asal":"Lampung Utara",
                "alamat": "Sukarame",
                "hobbi": "Main Gitar",
                "sosmed": "@pandrainsani27",
                "kesan": "Jago Main Gitar",  
                "pesan":"sukses selalu bg ditiap usahanya"# 1
            },
            {   
                "nama": "Meliza Wulandari",
                "nim": "121450065",
                "umur": "20",
                "asal":"Sumatera Selatan",
                "alamat": "Jl.Pagar Alam",
                "hobbi": "Nonton Drakor",
                "sosmed": "@wulandarimeliza",
                "kesan": "Murah Senyum",  
                "pesan":"semangat kuliah, asprak, dan tugas sekum nya kak"# 1
            },
        
            {
                "nama": "Putri Maulida Chairani",
                "nim": "121450050",
                "umur": "21",
                "asal":"Sumatera Barat",
                "alamat": "Gg. Nangka 4",
                "hobbi": "Dengerin Bg Pandra Main Gitar",
                "sosmed": "@ptrimaulidaaa_",
                "kesan": "kakak baik, perhatian",  
                "pesan":"terimakash kak , kata-kata penyemangatnya"# 1
            },
        
            {   
                "nama": "Hartiti Fadilah",
                "nim": "121450031",
                "umur": "21",
                "asal":"Palembang",
                "alamat": "Pemda",
                "hobbi": "Nyanyi",
                "sosmed": "@htrpdla",
                "kesan": "Cantik, Pendiem,Pinter",  
                "pesan":"Semangat TA nya kak, Semoga lancar-lancar"# 1
            },
        
            {
                "nama": "Nadilla Andhara Putri",
                "nim": "121450003",
                "umur": "21",
                "asal":"Lampung",
                "alamat": "Metro",
                "hobbi": "Mainn Bola, Belajar",
                "sosmed": "@nadilaandr26",
                "kesan": "kakaknya tegas banget apa lagi soal uang kas",  
                "pesan":"Tetap menjadi pribadi yg baik, sehat selalu kak"# 1
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    kesekjenan()


elif menu == "Baleg":

    def Baleg():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=15DajSHzIaFfGH0Kl1106c-05a8Y4cPEv",
            "https://drive.google.com/uc?export=view&id=1hnbmSA9CKLpCe4p1RCem3Oe7oNoetkFi",
            "https://drive.google.com/uc?export=view&id=1hl2TSYv-7WKxt4QPzqpHkgwQtQguRga2",
            "https://drive.google.com/uc?export=view&id=1hrOreXC13GhbfeuGvoVokwG7vKXGkvb8",
            "https://drive.google.com/uc?export=view&id=15Tddh4fAtXEmFJKLutMHDMCpai65vzi8",
            "https://drive.google.com/uc?export=view&id=1OIvKgSL5AKy2TLq8Lrc3GL63uTesn8aH",
            "https://drive.google.com/uc?export=view&id=1hvGBYmT2yJUjBXztvGqTleK7_LFbQdyY",
            "https://drive.google.com/uc?export=view&id=15IK8QJsanl6ZTb-NQOADYM7VDbcY15FL",
            "https://drive.google.com/uc?export=view&id=15UU5xSE4sJ4dzxQ2sA2DNRYe-OECVp6b",
            "https://drive.google.com/uc?export=view&id=1hoZN9I2TfzVPaRoWJBCath3H2pInL59r",
        ]
        data_list = [
            {
                "nama": "Tri Murniya Ningsih",
                "nim": "121450038",
                "umur": "21",
                "asal": "Bogor",
                "alamat": "Raden Saleh",
                "hobbi": "Tanya sama GPT",
                "sosmed": "@trimurniaa",
                "kesan": "Beribawa, Perhatian",
                "pesan": "Tetap aktif dimanapun kak, kakak hebat",
            },
            {
                "nama": "Annisa Cahyani Surya",
                "nim": "121450114",
                "umur": "21",
                "asal": "Tangerang Selatan",
                "alamat": "Way Huwi",
                "hobbi": "Puasa Senin Kamis",
                "sosmed": "@annisacahyanisurya",
                "kesan": "Pinter, humble, panutan",
                "pesan": "Semoga diperlancar urusan kuliahnya kak", 
            },
            {
                "nama": "Wulan Sabina",
                "nim": "121450150",
                "umur": "21",
                "asal": "Medan",
                "alamat": "Raden Saleh",
                "hobbi": "Menonton film",
                "sosmed": "wlsbn0",
                "kesan": "Asik,Humoris, Berwibawa",
                "pesan": "Semangat kuliahnya kak, semoga lancar TA-nya", 
            },
            {
                "nama": "Anisa Dini Amalia",
                "nim": "121450021",
                "umur": "20",
                "asal": "Tangerang",
                "alamat": "Jati Agung",
                "hobbi": "Baca Webtoon",
                "sosmed": " @anisadini10",
                "kesan": "Kakaknya ramahh, asik,baik",
                "pesan": "semangat terus kuliahnya kakak, jangan mudah menyerah", 
            },
            {
                "nama": "Feryadi Yulius ",
                "nim": "122450087",
                "umur": "20",
                "asal": "Padang",
                "alamat": "Belwis",
                "hobbi": "Sholat Dhuha",
                "sosmed": "@fer_yulius",
                "kesan": "Enak diajak bicara, Asik",
                "pesan": "Ajari saya menjadi sepuh alpro bang", 
            },
            {
                "nama": "Renisha Putri Giani",
                "nim": "122450079",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Teluk Betung",
                "hobbi": "Baca Al-Qur'an",
                "sosmed": "@fleurnsh",
                "kesan": "MasyaAllah kak pertahankan hobinya",
                "pesan": "Tetap konsisten dijalannya kak, Dan Diperlancar urusan kuliahnya",
            },
            {
                "nama": "Claudhia Angeliani",
                "nim": "121450124",
                "umur": "21",
                "asal": "Lampung Timur",
                "alamat": "Lampung Timur",
                "hobbi": "Baca Jurnal",
                "sosmed": " @dylebee",
                "kesan": "hobinya keren",
                "pesan": "Tetap menjadi orang baik kak", 
            },
            {
                "nama": "Mirzan Yusuf Rabbani",
                "nim": "122450118",
                "umur": "20",
                "asal": "Jakarta",
                "alamat": "Korpri",
                "hobbi": "Main Kucing",
                "sosmed": "@myrrinn",
                "kesan": "Abangnya baik dan kalem",
                "pesan": "Semangat kuliahnya bang", 
            },
            {
                "nama": "Jeremia Susanto",
                "nim": "122450022",
                "umur": "21",
                "asal": "Palembang",
                "alamat": "Bilabong",
                "hobbi": "Cerita",
                "sosmed": "@jeremia_s_",
                "kesan": "ceria terus bang jere",
                "pesan": "tetap aktif bang jere, sabar ya bang ajarin alpronya", 
            }, 
            {
                "nama": " Berliana Enda Putri",
                "nim": "122450065",
                "umur": "20",
                "asal": "Sumatera Barat",
                "alamat": "Way Huwi",
                "hobbi": "Baca Buku, Ngoding, Ibadah",
                "sosmed": "@berlyyanda",
                "kesan": "ramah, murah senyum",
                "pesan": "semangat kuliahnya kak, saya suka baca buku juga", 
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Baleg()

elif menu == "Senator":
    def senator():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=197LRPaNwf2AkI1YE7D7IrZOFJTK3uDhA",
            "https://drive.google.com/uc?export=view&id=19EX8AKR4_3nwGnMMSK4qU0IYY5V9nk5r",
        ]
        data_list = [
            {
                "nama": "Anissa Luthfi Alifia",
                "nim": "121450093",
                "umur": "22",
                "asal": "Lampung Tengah",
                "alamat": "Kost Putri Rahayu",
                "hobbi": "Dengerin bintang nyanyi",
                "sosmed": "@anissalutfi_",
                "kesan": "tegas, pintar berargument, berani",
                "pesan": "Semangat kuliahnya kak, tetap menjadi panutan senator HMSD", 
            },
            {
                "nama": "Rian Bintang Wijaya",
                "nim": "122450094",
                "umur": "20",
                "asal": "Palembang",
                "alamat": "Kota Baru",
                "hobbi": "Nyanyi",
                "sosmed": "@bintangtwinkle",
                "kesan": "orangnya sibuk",
                "pesan": "Semangat selalu bang, dan sehat selalu",
            }
        ]
        display_images_with_data(gambar_urls, data_list)
    senator()

elif menu == "Departemen PSDA":
    def Psda():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1PJc5I9KZsCksCIwmJr9GlKJKWyzhbK1v",
            "https://drive.google.com/uc?export=view&id=1PCY8Vg_238PbI2wF4__h4vPFCqYEXkIk",
            "https://drive.google.com/uc?export=view&id=1P0wmiV70DMX2aixE2TyppHDER9f62BTz",
            "https://drive.google.com/uc?export=view&id=1OC5Qw0Ls51NZdCjNzp6MOgYyfoL6fBz-",
            "https://drive.google.com/uc?export=view&id=1PRKxVvT4_RA84uoJ1YAzhJafZHPYUeG5",
            "https://drive.google.com/uc?export=view&id=1P5maJtbFsrKQpbn3r7x3lBy6FvCEfrjY",
            "https://drive.google.com/uc?export=view&id=1P5FLhQV2EwMmMmPw422Jo1P1Mg0JpPos",
            "https://drive.google.com/uc?export=view&id=1O0gpsPajB5VyV7mYAzrFIK0MfdB1A8Xj",
            "https://drive.google.com/uc?export=view&id=1P-9f5QvV4RSfumMqXef6xlSapCZcXv4J",
            "https://drive.google.com/uc?export=view&id=1P7TKLiIxONF6aNnRJZEin-QzxO4ENYNl",
            "https://drive.google.com/uc?export=view&id=1Oh-jjGWKJ2P37JHhqFeMAwYwljCFFh1T",
            "https://drive.google.com/uc?export=view&id=1OI58FaN6cbbtp7LTU0a6hRfvNuBydfDW",
            "https://drive.google.com/uc?export=view&id=1OKlYLCtHDJz1qGotFrzdVUlGRDKJcK9p",
            "https://drive.google.com/uc?export=view&id=1OZBCsklltn4rjrGrIQXQhB_OxGt2nHF-",
            "https://drive.google.com/uc?export=view&id=1OzgFe2CvqNVcFK0htYoSTDLrp_ljS4vx",
            "https://drive.google.com/uc?export=view&id=1OwQ0V-p-lw0T3jhuniCkrYzvX1ih3T3Z",
            "https://drive.google.com/uc?export=view&id=1O9Ri1gg_e9_TvlUzbMlqtggM5bp4tJjw",
            "https://drive.google.com/uc?export=view&id=1PVJtI73pQs8BSBccZ0yNS2QTy7fiozEi",
            "https://drive.google.com/uc?export=view&id=1OO7g1k9fUaemsQo221W-vKLnTgbAuBDt",
            "https://drive.google.com/uc?export=view&id=1OQnDkAIfvmmWG5rz27V9wtcmcFRCKKV9",
        ]
        data_list = [
              {
                "nama": "Ericson Chandra Sihombing",
                "nim": "121450026",
                "umur": "21",
                "asal":"Bekasi",
                "alamat": "Khobam",
                "hobbi": "Travelling",
                "sosmed": "@ericsonchandra99",
                "kesan": "Unik",  
                "pesan":"Tetap menjadi orang batak dijalan yang benar",
            },
            {
                "nama": "Elisabeth Claudia Simanjuntak",
                "nim": "122450123",
                "umur": "18",
                "asal":"Tangerang",
                "alamat": "Kemiling",
                "hobbi": "Bernafas",
                "sosmed": "@celisabethh_",
                "kesan": "ceria, keren, berbakat",  
                "pesan":"Terus semangat kuliahnya Kak, ceria terus",
            },
	        { 
                "nama": " Deyvan Loxefal", 
                "nim": " 121450148 ", 
                "umur":  "21", 
                "asal":" Duri Riau  ", 
                "alamat": "Khobam Pulau Damar", 
                "hobbi": "Belajar", 
                "sosmed": "@depanlo", 
                "kesan": "humoris, selalu ada gebrakan",   
                "pesan":"Semangat bang de kuliahnya, tetap membuat gebrakan",
            },
            {
                "nama": "Nisrina Nur Afifah",
                "nim": "122450052",
                "umur": "19",
                "asal":"Jawa Barat",
                "alamat": "Sukarame",
                "hobbi": "Muter-muter",
                "sosmed": "@afifahhnsrn",
                "kesan": "Berani dan berwibawa",  
                "pesan":"Semangat kuliah dan organisasi juga percintaannya",
            },
            {
                "nama": "M. Farhan Athaulloh",
                "nim": "121450117",
                "umur": "21",
                "asal":"Lampung",
                "alamat": "Kota Baru",
                "hobbi": "Menolong",
                "sosmed": "@mfarhan.ath",
                "kesan": "Pinter, Banyak Bakat, Cepat paham",  
                "pesan":"Main Speed lagi yok bang sama catur",
            },
	        { 
                "nama": " Ibnu Farhan Al-Ghifari", 
                "nim": " 121450121 ", 
                "umur":  "21", 
                "asal":" Kerinci Jambi  ", 
                "alamat": "Khobam", 
                "hobbi": "game online", 
                "sosmed": "@al_ghifari032", 
                "kesan": "kalem, keren",   
                "pesan":"Semangat kuliahnya bang sukses terus",
            },
            { 
                "nama": "Johannes Krisjon Silitonga", 
                "nim": "122450043", 
                "umur": "19", 
                "asal":"Tangerang", 
                "alamat": "Jl. Lapas", 
                "hobbi": "Ngasprak", 
                "sosmed": "@johanneskrisjon", 
                "kesan": "Asik, Profesional",   
                "pesan":"Horas bang, sukses terus", 
            },
            { 
                "nama": "Kemas Veriandra Ramadhan", 
                "nim": "122450016", 
                "umur": "19", 
                "asal":"Bekasi", 
                "alamat": "Kojo Golf UIN", 
                "hobbi": "Main game", 
                "sosmed": "@kemasverii", 
                "kesan": "sepuh coding",   
                "pesan":"Ajarin ngoding biar jadi pawang ular bg", 
            },
            { 
                "nama": "Leonard Andreas Napitupulu", 
                "nim": "121450153", 
                "umur": "21", 
                "asal":"Medan", 
                "alamat": "Khobam", 
                "hobbi": "belajar", 
                "sosmed": "@lndr.__", 
                "kesan": "baik dan asik, sonakmalela juga",   
                "pesan":"baik-baik kuliah bang, dan jadi kebanggaan ", 
            },
            { 
                "nama": "Presilia", 
                "nim": "122450081", 
                "umur": "20", 
                "asal":"Bekasi", 
                "alamat": "Kota Baru", 
                "hobbi": "Dengerin lomba sihir", 
                "sosmed": "@presiliamy", 
                "kesan": "Kakaknya cantik",   
                "pesan":"Tetap menjadi pribadi yang aktif dan berdampak kak", 
            },
            { 
                "nama": "Sahid Maulana", 
                "nim": "122450109", 
                "umur": "21", 
                "asal":"Depok, Jabar", 
                "alamat": "Jl. Airan Raya", 
                "hobbi": "Dengerin musik", 
                "sosmed": "@sahid_maul19", 
                "kesan": "baik, keren, daplok terbaek",   
                "pesan":"ayo colab main musik bang", 
            },
            {
                "nama": "Allya Nurul Islami Pasha",
                "nim": "122450033",
                "umur": "20",
                "asal":"Sumatera Barat",
                "alamat": "Belwis",
                "hobbi": "Nongs",
                "sosmed": "@allyaislami",
                "kesan": "Cerewet, Berani, Berwibawa",  
                "pesan":"Semangat kuliah dan organisasiya, sukses terus",
            },
            {
                "nama": "Eksanty Febriana Sukma Islamiaty",
                "nim": "122450001",
                "umur": "20",
                "asal":"Lubuk Linggau",
                "alamat": "Rajabasa",
                "hobbi": "Nyari sinyal di gedung F",
                "sosmed": "@eksantyfebriana",
                "kesan": "Asik, dan pinter",  
                "pesan": "semoga sukses dan keren terus kak",
            },
            {
                "nama": "Farahanum Afifah Ardiansyah",
                "nim": "122450056",
                "umur": "20",
                "asal":"Padang",
                "alamat": "Sukarame",
                "hobbi": "Minum Kopi",
                "sosmed": "@farahanumafifahh",
                "kesan": "baik dan perhatian",  
                "pesan":"semangat-semangat selalu",
            },
            {
                "nama": "Ferdy Kevin Naibaho",
                "nim": "122450107",
                "umur": "20",
                "asal":"Medan",
                "alamat": "Senopati Raya",
                "hobbi": "Dengerin Musik",
                "sosmed": "@ferdy_kevin",
                "kesan": "Asik, Kata-katanya bagus",  
                "pesan":"Rajin ke gereja ya bang",
            },
            {
                "nama": "M. Deriansyah Okutra",
                "nim": "122450101",
                "umur": "19",
                "asal":"Kayu Agung",
                "alamat": "Jl. Pagar Alam Kedaton",
                "hobbi": "Nongki-nongki",
                "sosmed": "@dransyh_",
                "kesan": "Abangnya baik dan asik",  
                "pesan":"Gmeet lagi yok bang",
            },
            {
                "nama": "Oktavia Nurwinda Puspita Sari",
                "nim": "122450041",
                "umur": "20",
                "asal":"Lampung Timur",
                "alamat": "Way Huwi",
                "hobbi": "Scroll tik-tok",
                "sosmed": "@oktavianrwnda",
                "kesan": "Kalem tapi bisa ngomel",  
                "pesan":"Semangat dunia perkuliahannya",
            },
            {
                "nama": "Gede Moana",
                "nim": "121450014",
                "umur": "21",
                "asal":"Bekasi",
                "alamat": "Korpri Raya",
                "hobbi": "Belajar, game, baca komik",
                "sosmed": "@gedemoenaa",
                "kesan": "abangnya asik dan seru.",  
                "pesan":"P mabar ml lagi yok bang",
            },
            {
                "nama": "Jaclin Alcavella",
                "nim": "122450015",
                "umur": "19",
                "asal":"Sumatera Selatan",
                "alamat": "Korpri",
                "hobbi": "Berenang",
                "sosmed": "@jaclinalcv_",
                "kesan": "kakak asik, dan berbakat",  
                "pesan":"Mau liat kak jaclin nari",
            },
            {
                "nama": "Syalaisha Andini Putriansyah",
                "nim": "122450111",
                "umur": "21",
                "asal":"Tangerang",
                "alamat": "Sukarame",
                "hobbi": "Baca",
                "sosmed": "@syalaisha.i__",
                "kesan": "kakaknya manis banget, pendiem juga",  
                "pesan":"Semangat terus kuliahnya kak",
            }
        ]
        display_images_with_data(gambar_urls, data_list)
    Psda()

elif menu == "Departemen MEDKRAF":

    def Medkraf():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=18JwTfSMiOVZ43NJBuSOotikfhGMEWKis", #1
            "https://drive.google.com/uc?export=view&id=14ndurMNz2JFb7kPWHCOpjtnjwF0jqbD5", #2
            "https://drive.google.com/uc?export=view&id=18G1OoTLXkByQ-lExVdBffitkXK0QKkBx",
            "https://drive.google.com/uc?export=view&id=14lss5ZU1-RhFdBTmLakH-3n9tR3n_4pw",
            "https://drive.google.com/uc?export=view&id=14qHuck5rj0uSyd8SKcMioo4MRTUshSev",
            "https://drive.google.com/uc?export=view&id=18Gt9uUBfxwqMbcpMj3yR7iJfc6yjuSTG",
            "https://drive.google.com/uc?export=view&id=18LP_PNfPZV1jiP5TzMKSOUuPB743w67W",
            "https://drive.google.com/uc?export=view&id=1Gt5BXQFWEQvSDbj9z9YOOGsYbVd6Jksd",
            "https://drive.google.com/uc?export=view&id=1_pY2cyI-wj5oz6cFY4hB4SkHWSyKFsz_",
            "https://drive.google.com/uc?export=view&id=18JZdirnLhJBvxyrl8oA8fC-3DNKrZdCf",
            "https://drive.google.com/uc?export=view&id=18IF9jlfBeiKr_6VuJBMA9UPO0sQJ6qeu",
            "https://drive.google.com/uc?export=view&id=14xTyuxVaA-E9xPudklLVCrTEWCkvecwq",
            "https://drive.google.com/uc?export=view&id=14tIfgBUDq_5TNQzKPkGP8-TD34aLW_Lx",
            "https://drive.google.com/uc?export=view&id=18GsRkKq2wGVBrsE9Wua1jCBT_xn5tPry",
         
        ]
        data_list = [
            {
                "nama": "Wahyudiyanto",
                "nim": "121450040",
                "umur": "22",
                "asal": "Makassar",
                "alamat": "Sukarame",
                "hobbi": "Nonton",
                "sosmed": "@wayyulaja",
                "kesan": "kalem, dan berwibawa!",
                "pesan": "Semoga selalu inovatif dan terus semangat berkarya, bg",
            },
            {
                "nama": "Elok Fiola",
                "nim": "122450051",
                "umur": "19",
                "asal": "Bandar Lampung",
                "alamat": "Bandar Lampung",
                "hobbi": "Editing",
                "sosmed": "@elokfiola",
                "kesan": "cantik dan baik",
                "pesan": "Tetap aktif selalu kak", 
            },
            {
                "nama": "Muhammad Kaisar Firdaus ",
                "nim": " 121450135",
                "umur": "21",
                "asal": "Pesawaran",
                "alamat": "Pulau Damar",
                "hobbi": "Lagi Nyari",
                "sosmed": " @dino_kiper",
                "kesan": "asik, humoris, keren",
                "pesan": "Sehat-sehat bang", 
            },
            {
                "nama": "Muhammad Arsal Ranjana Putra",
                "nim": "121450111",
                "umur": "21",
                "asal": "Depok",
                "alamat": "Nangka 4",
                "hobbi": "Ngoding",
                "sosmed": "@arsal.utama",
                "kesan": "Jago Desain",
                "pesan": "Ajarin Ngedesain bang", 
            },
            {
                "nama": "Cintya  Bella",
                "nim": "122450066",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Teluk",
                "hobbi": "Ngegym",
                "sosmed": "@cintyabella28",
                "kesan": "stylist, kalem, dan berwibawa",
                "pesan": "Semangat kontennya kak", 
            },
            {
                "nama": "Dwi Ratna Anggraeni",
                "nim": "122450008",
                "umur": "20",
                "asal": "Jambi",
                "alamat": "Perumahan Pemda",
                "hobbi": "Baca",
                "sosmed": "@dwiratn_",
                "kesan": "Kakaknya baik dan kalem",
                "pesan": "Semangat Medkrafnya kak", 
            },
            {
                "nama": "Patricia Leondra Diajeng Putri ",
                "nim": "122450050",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Jatimulyo",
                "hobbi": "Nonton Film",
                "sosmed": "@patriciadiajeng",
                "kesan": "cantik, dan kretif",
                "pesan": "Semangat kontennya kak", 
            },
            {
                "nama": "Rahma Neliyana",
                "nim": "122450036",
                "umur": "20",
                "asal": "Lampung",
                "alamat": "Sukarame",
                "hobbi": "Baca Coding",
                "sosmed": "@rahmanellyana",
                "kesan": "Ceria, dan baik",
                "pesan": "Semangat kontennya kak", 
            },
            {
                "nama": "Try Yani Rizki Nur Rohmah ",
                "nim": "122450020",
                "umur": "20",
                "asal": "Lampung Barat",
                "alamat": "Korpri",
                "hobbi": "Bernyanyi dan Menonton",
                "sosmed": "@tryyaniciaaa",
                "kesan": "cantik dan kalem",
                "pesan": "Semangat konten di medcrafnya kak", 
            },
            {
                "nama": "Gymnastiar Al Khoarizmy",
                "nim": "122450096",
                "umur": "20",
                "asal": "Serang",
                "alamat": "Lapangan Golf UIN",
                "hobbi": "Baca Komik",
                "sosmed": "@jimnn.as",
                "kesan": "Keren dan jago foto",
                "pesan": "Ajarin foto pake kamera bang", 
            },
            {
                "nama": "Nasywa Nur Afifah ",
                "nim": "122450125",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Jalan Durian 1 Pemda",
                "hobbi": "Nonton Drakor",
                "sosmed": "@nsywanaf",
                "kesan": "baik dan ramah",
                "pesan": "tetap menjadi orang baik kak", 
            },
            {
                "nama": "Hermawan Manurung ",
                "nim": "122450069",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Dekat Jalan Tol (Wisma Hana Hani) ",
                "hobbi": "Bengong/Membaca Buku",
                "sosmed": "@hermawan.mnrng",
                "kesan": "Keren, rasa pedulinya tinggi",
                "pesan": "Tetap menjadi abang panutan manurung", 
            },
             {
                "nama": "Khusnun Nisa",
                "nim": "122450078",
                "umur": "20",
                "asal": "Lampung Selatan",
                "alamat": "",
                "hobbi": "Mengerjakan Tugas",
                "sosmed": "@khusnun_nisa335",
                "kesan": "baik, jago desain",
                "pesan": "ajarin desain figma kak", 
            },
             {
                "nama": "Priska Silvia Ferantiana",
                "nim": "122450053",
                "umur": "20",
                "asal": "Palembang",
                "alamat": "Jalan Nangka 2",
                "hobbi": "Baca Novel yang Bikin Nangis",
                "sosmed": "@prskslv",
                "kesan": "kalem",
                "pesan": "Semangat kuliah , dan medkrafnya kak", 
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Medkraf()

elif menu == "Departemen MIKFES":

    def Mikfes():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1Jrx9NOBvZPXN6BepxIwRNawCNAG0-ncZ",
            "https://drive.google.com/uc?export=view&id=1JasE9eTsWkmP6BHhxV_fyh4UQufRNbVt",
            "https://drive.google.com/uc?export=view&id=1JjF0j-PWAxz1WQEGN-AfaYSXnq4nkhxP",
            "https://drive.google.com/uc?export=view&id=1JE_8j2XG06ctVbwEWq_Tgm6wKYNYdu5z",
            "https://drive.google.com/uc?export=view&id=1JRVmTwis2_b9c98UR41o-31ZKqSdTpTE",
            "https://drive.google.com/uc?export=view&id=1K2vE5OCM4MzKHnTxgeux341BuNq6CrlK",
            "https://drive.google.com/uc?export=view&id=1JJWDaMVtowellHgaVIJBBP2QTT3oWvRK",
            "https://drive.google.com/uc?export=view&id=1KE-6H4L9-9K_ZFAL_zPO5kXZZVtnOvEg",
            "https://drive.google.com/uc?export=view&id=1JWFDnmKguY_qWRqAksPClsLkYW4c8OQJ",
            "https://drive.google.com/uc?export=view&id=1K7L1gkgR6YYLQX0PFi_Ym-DfnMX97WyW",
            "https://drive.google.com/uc?export=view&id=1JNC5BmYUPECvd4BIck8MwCSDRzuYanjt",
            "https://drive.google.com/uc?export=view&id=1JLWXFrDVNlwrrHC3rsHO10cN4NRVgn8R",
            "https://drive.google.com/uc?export=view&id=1KFdou8cheSpWbsln0oukWe_Is3RZ9S8p",
            "https://drive.google.com/uc?export=view&id=1KJgHcp2k4GZln-j6a3il3_7L2QJ0iS1C",
            "https://drive.google.com/uc?export=view&id=1KNkvH1MCoRg_gQPJC-VL4Pl8wQMMUsEX",
            "https://drive.google.com/uc?export=view&id=1JdgoKkcu6vMg1p4UEkPLWdg-teZ2ZBNs",
            "https://drive.google.com/uc?export=view&id=1JlVwT8Z-1FaqVxmDvvUGrHrURkYe0Fam",
            "https://drive.google.com/uc?export=view&id=1JkIoWZNbq9g84ztk3IUpMNEhygshHts7",

        ] 
        data_list = [
            {
                "nama": "Rafi Fadhlillah",
                "nim": "121450143",
                "umur": "21 Tahun",
                "asal": "Lubuk Linggau",
                "alamat": "Jl. Nangka 4",
                "hobbi": "Olahraga",
                "sosmed": "@rafadhilillahh13",
                "kesan": "Pinter dan Panutan",
                "pesan": "Sukses selalu bang",
            },
            {
                "nama": "Annisa Novantika",
                "nim": "121450005",
                "umur": "21 Tahun",
                "asal": "Lampung Utara",
                "alamat": "Jl. Pulau Sebesi, Sukarame",
                "hobbi": " Memasak",
                "sosmed": "@anovavona",
                "kesan": "Baik, perhatian, tegas",
                "pesan": "Semangat kuliah, dan TA nya kak",
            },
            {
                "nama": "Fadhil Fitra Wijaya",
                "nim": "122450082",
                "umur": "20 Tahun",
                "asal": "Bekasi",
                "alamat": "Teluk Betung ",
                "hobbi": "Main Game",
                "sosmed": "@fadhilfwee",
                "kesan": "Kece banget abangnya",
                "pesan": "Sukses terus kuliahnya sampai akhir bang",
            },
            {
                "nama": "Muhammad Regi Abdi Putra Amanta",
                "nim": " 122450031",
                "umur": "19 Tahun",
                "asal": "Palembang",
                "alamat": "Jl. Permadi Sukarame  ",
                "hobbi": "Main Game",
                "sosmed": "@mregiiii_",
                "kesan": "Keren banget abang Duta Genre",
                "pesan": "Semangat terus kuliah dan ngaspraknya bang, teruslah menginspirasi",
            },
            {
                "nama": "Syalaisha Andina Putriansyah",
                "nim": "122450121",
                "umur": "21 Tahun",
                "asal": "Tangerang",
                "alamat": "Gg Yudhistira ",
                "hobbi": "Baca Novel",
                "sosmed": "@dkselsd_31",
                "kesan": "Lucu banget kakaknya ada kembaran",
                "pesan": "Semangat terus kuliahnya kak, jangan mudah menyerah",
            },
            {
                "nama": "Natanael Oktavianus Partahan Sihombing ",
                "nim": "121450107",
                "umur": "20 Tahun",
                "asal": "Jakarta",
                "alamat": "Kemiling ",
                "hobbi": "Membuka Wisata HMSD",
                "sosmed": "@natanaeloks",
                "kesan": "Abangnya kece dan pinter",
                "pesan": "Tetap rendah hati dan rajin ibadah bang",
            },
            {
                "nama": "Anwar Muslim",
                "nim": "122450117",
                "umur": "21 Tahun",
                "asal": "Bukittinggi",
                "alamat": "Korpri ",
                "hobbi": " ML (Machine Learning)",
                "sosmed": "@here.am.ai",
                "kesan": "Abangnya seru abis",
                "pesan": "Membara terus jiwa semangatnya bang!",
            },
            {
                "nama": "Deva Anjani Khayyuninafsyah",
                "nim": "122450014",
                "umur": "21 Tahun",
                "asal": " Bandar Lampung",
                "alamat": "Kemiling",
                "hobbi": "Menonton Film",
                "sosmed": "@anjaniiidev",
                "kesan": "Cantik dan humble",
                "pesan": "Jangan kasih kendor belajarnya kak, jangan lupa istirahat juga",
            },
            {
                "nama": "Dinda Nababan",
                "nim": "122450120",
                "umur": "20 Tahun",
                "asal": "Medan",
                "alamat": "Jl. Lapas",
                "hobbi": "Main Game",
                "sosmed": "@dindanababan_",
                "kesan": "Orang Batak Yang Kalem",
                "pesan": "Semangat kuliahnya dan asprak ads nya kak",
            },
            {
                "nama": "Marleta Cornelia Leander",
                "nim": "122450092",
                "umur": "20 Tahun",
                "asal": "Depok, Jawa Barat",
                "alamat": "Gg. Nangka 3",
                "hobbi": "Liatin Jurnal",
                "sosmed": "@marletacornelia",
                "kesan": "pinter matematika",
                "pesan": "sukses terus kak",
            },
            {
                "nama": "Rut Junita Sari Siburian",
                "nim": "122450103",
                "umur": "20 Tahun",
                "asal": "Batam, Kep.Riau",
                "alamat": "Gg. Nangka 3",
                "hobbi": "Resume Jurnal",
                "sosmed": "@junitaa_0406",
                "kesan": "kakak nim, baik, pinter",
                "pesan": "Kalau kebatam ayo colab projek kak",
            },
            {
                "nama": "Syadza Puspadari Azhar",
                "nim": " 122450072",
                "umur": "20 Tahun",
                "asal": "Palembang",
                "alamat": "Belwis ",
                "hobbi": "Membaca",
                "sosmed": "@puspadrr",
                "kesan": "baik, perhatian, daplok terbaik",
                "pesan": "sehat selalu kak, dan sukses",
            },
            {
                "nama": " Abdurrahman Al-atsary",
                "nim": "121450128",
                "umur": "23 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "Perumnas Way Kandis",
                "hobbi": " Membaca",
                "sosmed": "@rahmn_abdr",
                "kesan": "baik dan nasihatnya bagus",
                "pesan": "ajarin ngoding bang",
            },
            {
                "nama": "Aditya Rahman",
                "nim": "122450113",
                "umur": "20 Tahun",
                "asal": " Lampung Timur",
                "alamat": "Korpri",
                "hobbi": "Ngoding WISATA",
                "sosmed": "@rahm_adityaa",
                "kesan": "Pinter dan Sepuh sql",
                "pesan": "Ajarin sql bang, sukses kuliahnya bg",
            },
            {
                "nama": "Eggi Satria",
                "nim": "122450032",
                "umur": "20 Tahun",
                "asal": "Sukabumi",
                "alamat": "Korpri",
                "hobbi": "Ngoding dan buat konten WISATA",
                "sosmed": "@egistr ",
                "kesan": "Ceria dan Sepuh Coding",
                "pesan": "ajarin backend python bang",
            },
            {
                "nama": "Febiya Jomy Pratiwi",
                "nim": "122450074",
                "umur": "20 Tahun",
                "asal": "Tulang Bawang",
                "alamat": "Jl Kelengkeng Raya",
                "hobbi": "Nonton K-Drama ",
                "sosmed": "@pratiwifebiya",
                "kesan": "cantik dan pinter",
                "pesan": "sukses kuliahnya kak",
            },
            {
                "nama": "Happy Syahrul Ramadhan",
                "nim": "122450013",
                "umur": "20 Tahun",
                "asal": "Lampung",
                "alamat": "Karang Anyar ",
                "hobbi": " Main Game",
                "sosmed": "@sudo.syahrulramadhannn",
                "kesan": "lekku kenal dari awal masuk ITERA",
                "pesan": "sukses kuliahnya, ayo colab projek lagi",
            },
            {
                "nama": "Randa Andriana Putra",
                "nim": "122450083",
                "umur": "21 Tahun",
                "asal": "Banten",
                "alamat": " Sukarame",
                "hobbi": " Tidur dan Berkembang",
                "sosmed": "@randaandriana_",
                "kesan": "Ceria dan Sepuh All Program",
                "pesan": "Sukses kuliah,kerja, dan tetap menjadi orangnya suka menolong",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Mikfes()

elif menu == "Departemen Eksternal":
    def Eksternal():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=12S9fJqEKxS6_irrYL96-7YACnOFjW2uo",
            "https://drive.google.com/uc?export=view&id=12UveFDE8RhfACYAeNopT2MYQ4nirBY7I",
            "https://drive.google.com/uc?export=view&id=13D8Yk6rz2wtwuF7vzYJIAqSFJBhaqBM-",
            "https://drive.google.com/uc?export=view&id=12ZnUFNAcWKqx88js323grqVCz7v3Hi85",
            "https://drive.google.com/uc?export=view&id=12ZmI1Dauor4zswmgyYUpiTM81z0rHjvf",     
            "https://drive.google.com/uc?export=view&id=12slktINmSpHlPReiypNQUqRM7DWiCXwm", 
            "https://drive.google.com/uc?export=view&id=13CLlL1a7dWucpljPs01PAca2OXojlsvX",
            "https://drive.google.com/uc?export=view&id=1NHyzUbst_pL6VlVkqjxpgTtoufUJIroI",
            "https://drive.google.com/uc?export=view&id=1Wwk87Z1Ou65EhV9Akuj1RRxnVUQHNaBJ",
            "https://drive.google.com/uc?export=view&id=1N1T40xAR6Q7PrjvedBkKj_JvjAPYh6Mb",
            "https://drive.google.com/uc?export=view&id=13Eeu9UDSEZ8wy500vmuihy2rj-qeNJeV",
            "https://drive.google.com/uc?export=view&id=1NIYN9zlcJ7mQ4vqzmf9kwhjoGk71G6ak",
            "https://drive.google.com/uc?export=view&id=13EZONCRFnteEdEGKDcCE37D8W5XO2oPQ",
            "https://drive.google.com/uc?export=view&id=1Wwk87Z1Ou65EhV9Akuj1RRxnVUQHNaBJ",
            "https://drive.google.com/uc?export=view&id=1NGxx8MY6d03z6yqPd8LYy-lkKglOph6L",
            "https://drive.google.com/uc?export=view&id=1N1q1hLTcbx2YTKpPV1ravNgZvs10zZlB",

        ]
        data_list = [
            {
                "nama": "Yogy Sea Tama",
                "nim": "121450041",
                "umur": "21",
                "asal": "Tangerang",
                "alamat": "Jatimulyo",
                "hobbi": "Ngisi Bensin",
                "sosmed": "@yogyyyyyyy",
                "kesan": "Abangnya kece bangett",
                "pesan": "Semangat menjalani hari-hari dan Persiapan TA nya ya bang!!", 
            },
            {
                "nama": "Ramadhita Asifa Hendri",
                "nim": "121450131",
                "umur": "21",
                "asal": "Rajabasa",
                "alamat": "Rajabasa",
                "hobbi": "Belajar",
                "sosmed": "@Ramadhitaasifa",
                "kesan": "kakanya keren banget!!",
                "pesan": "Semangat menjalani ahri-hari dan Persiapan TA nya kak!!",
            },
            {
                "nama": "Nazwa Nabilla",
                "nim": "121450112",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Way Kandis",
                "hobbi": "Belajar dengan Rajin",
                "sosmed": "@nazwanbilla",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan Persiapan TA nya kak!!",
            },
            {
                "nama": "Dea Mutia Risani",
                "nim": "122450099",
                "umur": "20",
                "asal": "Sumatera Barat",
                "alamat": "Korpri",
                "hobbi": "Bikin Surat",
                "sosmed": "@deaa.rsn",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Novelia Adinda",
                "nim": "122450104",
                "umur": "21",
                "asal": "Jakarta",
                "alamat": "Belwis",
                "hobbi": "Tidur",
                "sosmed": "@nvliadinda",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Ratu Keisha Jasmin Deonova",
                "nim": "122450106",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Way Kandis",
                "hobbi": "Ngerjain ADW",
                "sosmed": "@jasminednva",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Tobias David Monogari",
                "nim": "121450081",
                "umur": "20",
                "asal": "Jakarta Barat",
                "alamat": "Pemda",
                "hobbi": "Bikin Puisi",
                "sosmed": "@tobiassiagian",
                "kesan": "abangnya kece banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya bang!!",
            },
            {
                "nama": "Rizki Adrian Bennovry",
                "nim": "121450073",
                "umur": "21",
                "asal": "Bekasi",
                "alamat": "TVRI",
                "hobbi": "Buat Portopolio",
                "sosmed": "@rzkdrnnn",
                "kesan": "Abangnya kece banget",
                "pesan": "Semangat menjalani hari-hari dan persiapan TA nya bang!!",
            },
            {
                "nama": "Arafi Ramadhan Maulana",
                "nim": "12245022",
                "umur": "20",
                "asal": "Jogja, Depok",
                "alamat": "Way Huwi",
                "hobbi": "menghafal al-quran",
                "sosmed": "@arafiramadhanmaulana",
                "kesan": "Abangnya kece banget",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya bang!!",
            },
            {
                "nama": "Asa Do'a Uyi",
                "nim": "122450005",
                "umur": "20",
                "asal": "Muara",
                "alamat": "Korpri",
                "hobbi": "cuci baju",
                "sosmed": "@u_yippy",
                "kesan": "kakaknya keren banget",
                "pesan": "semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Chalifia Wananda",
                "nim": "122450076",
                "umur": "20",
                "asal": "Padang",
                "alamat": "sukarame",
                "hobbi": "Quality Time",
                "sosmed": "@chipawww",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Irvan Alfaritzi",
                "nim": "122450093",
                "umur": "21",
                "asal": "Sumatera Barat",
                "alamat": "Jakarta",
                "hobbi": "Nonton Youtube dan main ML",
                "sosmed": "@Alfaritziirfan",
                "kesan": "Abangnya kece banget",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya bang",
            },
            {
                "nama": "Izza Lutfia",
                "nim": "122450090",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Teluk",
                "hobbi": "main vollly",
                "sosmed": "@izzalutfiaa",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Khaalishah Zuhrah ALyaa Valefi",
                "nim": "122450034",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Rajabasa",
                "hobbi": "Nyanyi",
                "sosmed": "@alyaavalefi",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
            {
                "nama": "Raid Muhammad Naufal",
                "nim": "122450027",
                "umur": "20",
                "asal": "Lampung Tengah",
                "alamat": "Sukarame",
                "hobbi": "Ngeresume Seminar",
                "sosmed": "@rayHis_",
                "kesan": "Abangnya kece banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya bang!!",
            },
            {
                "nama": "Tria Yunanni",
                "nim": "122450062",
                "umur": "20",
                "asal": "Way Kanan",
                "alamat": "Jakarta",
                "hobbi": "Baca",
                "sosmed": "@tria_y062",
                "kesan": "kakaknya keren banget!!",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya kak!!",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Eksternal()
elif menu == "Departemen Internal":
    def Internal():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=159ar1tgoGAy8EBnw5Nlc_2uglefybX9_",
            "https://drive.google.com/uc?export=view&id=19RSJKotujYoxAFvPKlhFdE0QFAJh_826",
            "https://drive.google.com/uc?export=view&id=14yUVUqZ6wHxvL5ZZyBTOXs9aXVobFqK9",
            "https://drive.google.com/uc?export=view&id=1Wwk87Z1Ou65EhV9Akuj1RRxnVUQHNaBJ",
            "https://drive.google.com/uc?export=view&id=15-WC3yJNajKydr1PKldWmdvRJ0UXnyNn",
            "https://drive.google.com/uc?export=view&id=159IwACBcDj2BKzIe6K5R8CpTbnJtd1t8",
            "https://drive.google.com/uc?export=view&id=14y3v91BDQosvhxdTsKDbg30uJO85o8Tc",
            "https://drive.google.com/uc?export=view&id=158XyPOWB_8l6PHLvEI3M3i-uktVgFYhb",
            "https://drive.google.com/uc?export=view&id=1514OPADZUZLxFtLupb7ZFbQtEhjNj9PE",
            "https://drive.google.com/uc?export=view&id=1Wwk87Z1Ou65EhV9Akuj1RRxnVUQHNaBJ",
            "https://drive.google.com/uc?export=view&id=15AekqBWc0ewIuCRI0mUzmiWlCPr468x9",
            "https://drive.google.com/uc?export=view&id=14ziPHsobhLPsksLA4ARqZa1L2yT8aZXd",
            "https://drive.google.com/uc?export=view&id=1Wwk87Z1Ou65EhV9Akuj1RRxnVUQHNaBJ",
        ]
        data_list = [
            {
                "nama": "Dimas rizky ramadhani",
                "nim": "121450027",
                "umur": "20",
                "asal": "Pamulang",
                "alamat": "Way kandis",
                "hobbi": "Manjat tower sutet",
                "sosmed": "@dimzrky",
                "kesan": "Berkharisma banget",
                "pesan": "Semangat nyusun TA nya bang dimas", 
            },
            {
                "nama": "Catherine firdhasari maulina sinaga",
                "nim": "121450072",
                "umur": "20",
                "asal": "Sumatera Utara",
                "alamat": "Airan",
                "hobbi": "Baca novel",
                "sosmed": "@chatherine.sinaga",
                "kesan": "kakanya ramah bintang 100",
                "pesan": "Semangat berproses kak",
            },    
            {
                "nama": "M. Akbar resdika",
                "nim": "121450066",
                "umur": "20",
                "asal": "Lampung Barat",
                "alamat": "Labuhan dalam",
                "hobbi": "Memelihara dino",
                "sosmed": "@akbar_resdika",
                "kesan": "Kelihatannya baik (emot senyum)",
                "pesan": "Semangat nyusun TA bang",
            },
            {
                "nama": "Rani puspita sari",
                "nim": "122450030",
                "umur": "20",
                "asal": "Metro",
                "alamat": "Rajabasa",
                "hobbi": "Mengaji",
                "sosmed": "@ranipu",
                "kesan": "Kakak baik",
                "pesan": "Selalu bermanfaat untuk orang sekitar ya kak",
            },
            {
                "nama": "Rendra eka prayoga",
                "nim": "122450112",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Jalan lapas raya",
                "hobbi": "nulis lagu",
                "sosmed": "@rendraepr",
                "kesan": "Ramah bintang 1000",
                "pesan": "Semoga jadi pribadi yang lebih baik lagi ",
            },
            {
                "nama": "Salwa farhanatussaidah",
                "nim": "122450055",
                "umur": "20",
                "asal": "Pesawaran",
                "alamat": "Airan raya",
                "hobbi": "ngeliat cogan",
                "sosmed": "@slwfhn_694",
                "kesan": "Cantik bangett",
                "pesan": "semangat kuliahnya kak",
            },
            {
                "nama": "Ari sigit",
                "nim": "121450069",
                "umur": "23",
                "asal": "Lampung barat",
                "alamat": "Labuhan ratu",
                "hobbi": "Main futsal",
                "sosmed": "@ari_sigit17",
                "kesan": "keren banget abangnya",
                "pesan": "semangat kuliahnya bang ari",
            },
            {
                "nama": "Azizah kusumah putri",
                "nim": "122450068",
                "umur": "21",
                "asal": "Lampung Selatan",
                "alamat": "Natar",
                "hobbi": "berkebun",
                "sosmed": "@azizahksmh15",
                "kesan": "Ramah bangett",
                "pesan": "Semangkaaa semangat kakak!!!",
            },
            {
                "nama": "Meira listyaningrum",
                "nim": "122450011",
                "umur": "20",
                "asal": "Pesawaran",
                "alamat": "Airan raya",
                "hobbi": "Menghalu",
                "sosmed": "@meiraln",
                "kesan": "Baik bangett",
                "pesan": "Semangat kakk!!!",
            },
            {
                "nama": "Rendi alexander hutagalung",
                "nim": "122450057",
                "umur": "20",
                "asal": "Tangerang",
                "alamat": "Kost gunawan",
                "hobbi": "Menyanyi",
                "sosmed": "@alexanderr",
                "kesan": "Baik bangett",
                "pesan": "jangan pentang menyerah,selalu berusaha",
            },
            {
                "nama": "Renta siahaan",
                "nim": "122450070",
                "umur": "21",
                "asal": "Sumatera utara",
                "alamat": "Gerbang barat",
                "hobbi": "Memancing",
                "sosmed": "@renta.shn",
                "kesan": "Keren banget",
                "pesan": "selalu semangat kakak ",
            },
            {
                "nama": "Yosia lehare banurea",
                "nim": "121450149",
                "umur": "20",
                "asal": "Dairi, Sumatera utara",
                "alamat": "Perum griya indah",
                "hobbi": "Bawa motor pakai kaki",
                "sosmed": "@yosiabanurea",
                "kesan": "Baik bangett",
                "pesan": "semangat kakak!!!",
            },
            {
                "nama": "Josua panggabean",
                "nim": "121450061",
                "umur": "21",
                "asal": "Pematang siantar",
                "alamat": "Gya kost",
                "hobbi": "Ngawinin cupang",
                "sosmed": "@josuapanggabean16_",
                "kesan": "sangat soft spoken",
                "pesan": "semangat kuliah bang",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Internal()
elif menu == "Departemen SSD":
    def Ssd():
        gambar_urls = [
           "https://drive.google.com/uc?export=view&id=1J6hGp9Lq2S7fDs4jS7eY7jfbM_ypMS7n",
           "https://drive.google.com/uc?export=view&id=1JCToT0fZxcLj4b2Z4gc2lf-CGbGtm5kc",
           "https://drive.google.com/uc?export=view&id=1J9lFI1O2vJk6IzdMNkwlk8AWpS50LIIt",
           "https://drive.google.com/uc?export=view&id=1WEZICrRVHcecfU-nVctqUIC3VkOzc5bi",
           "https://drive.google.com/uc?export=view&id=1SxyEs4BMLZr6G7Npy-YWbp__u4c0Lq3I",
           "https://drive.google.com/uc?export=view&id=1J7O346rWhRDhVedxKgpwFYP-m2L2Ig7Z",
           "https://drive.google.com/uc?export=view&id=1JDKKRlISEjY34sJAriYq0ULpVcabrUv1",
           "https://drive.google.com/uc?export=view&id=1J4QRdW3Ky7_TX7ZoqwSIGFNDnJx5q1Rk",
           "https://drive.google.com/uc?export=view&id=1J21B97dRscbs1p9HjiKP4aSMRgpioYOh",

        ]
        data_list = [
            {
                "nama": "Andrian Agustinus Lumban Gaol",
                "nim": "121450090",
                "umur": "17 +",
                "asal": "Sidikalang",
                "alamat": "Lapas",
                "hobbi": "Nyari Hobi",
                "sosmed": "@andrialgaol",
                "kesan": "Public speakingnya bagus bangett",
                "pesan": "Semangat cari duitnya bang", 
            },
            {
                "nama": "Adisty Syawaida Ariyanto",
                "nim": "121450136",
                "umur": "21",
                "asal": "Metro",
                "alamat": "Metro",
                "hobbi": "Nonton film",
                "sosmed": "@adistisa_",
                "kesan": "Keren banget kak",
                "pesan": "Semangat kuliahnya kak",
            },
            {
                "nama": "Nabila Azhari",
                "nim": "121450029",
                "umur": "21",
                "asal": "Simalungun",
                "alamat": "Airan",
                "hobbi": "Menghitung",
                "sosmed": "@zhjung",
                "kesan": "",
                "pesan": "",
            },
            {
                "nama": "Danang Hilal Kurniawan",
                "nim": "122450085",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "TB 3 Asrama",
                "hobbi": "Belajar",
                "sosmed": "@dananghk_",
                "kesan": "",
                "pesan": "",
            },
            {
                "nama": "Farel Julio Akbar",
                "nim": "122450110",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Jalan Lapas",
                "hobbi": "Bebas",
                "sosmed": "@farel__julio",
                "kesan": "",
                "pesan": "",
            },
            {
                "nama": "Nabilah Andika Fitriani",
                "nim": "121450129",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Kedaton",
                "hobbi": "Tidur",
                "sosmed": "@nabilaafrn",
                "kesan": "",
                "pesan": "",
            },
            {
                "nama": "Alvia Asrinda Br.Ginting",
                "nim": "122450077",
                "umur": "20",
                "asal": "Binjai",
                "alamat": "Korpri",
                "hobbi": "Nonton Windah",
                "sosmed": "@alviaginting",
                "kesan": "",
                "pesan": "",
            },
            {
                "nama": "Dhafin Razaka Luthfia",
                "nim": "122450133",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Jalan nangka 1",
                "hobbi": "Olahraga",
                "sosmed": "@dhafinrzqri3",
                "kesan": "",
                "pesan": "",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Ssd()

# Tambahkan menu lainnya sesuai kebutuhan
