import streamlit as st
from streamlit_option_menu import option_menu
import requests
from PIL import Image, ImageOps
from io import BytesIO

st.markdown("""<style>.centered-title {text-align: center;}</style>""",unsafe_allow_html=True)
st.markdown("<h1 class='centered-title'>BUKU KATING</h1>", unsafe_allow_html=True)

# bagian sini jangan diubah
def streamlit_menu():
    selected = option_menu(
        menu_title=None,
        options=[
            "Kesekjenan",
            "Baleg",
            "Senator",
            "Departemen PSDA",
            "Departemen MEDKRAF",
            "Departemen MIKFES",
            "Departemen Eksternal",
            "Departemen Internal",
            "Departemen SSD",
        ],
        icons=[
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
        ],
        default_index=0,
        orientation="horizontal",
        styles={
            "container": {"padding": "0!important", "background-color": "#fafafa"},
            "icon": {"color": "black", "font-size": "19px"},
            "nav-link": {
                "font-size": "15px",
                "text-align": "left",
                "margin": "0px",
                "--hover-color": "#eee",
            },
            "nav-link-selected": {"background-color": "#3FBAD8"},
        },
    )
    return selected

@st.cache_data
def load_image(url):
    response = requests.get(url)
    if response.status_code != 200:
        st.error(
            f"Failed to fetch image from {url}, status code: {response.status_code}"
        )
        return None
    try:
        img = Image.open(BytesIO(response.content))
        img = ImageOps.exif_transpose(img)
        img = img.resize((300, 400))
        return img
    except Exception as e:
        st.error(f"Error loading image: {e}")
        return None
    
@st.cache_data
def display_images_with_data(gambar_urls, data_list):
    images = []
    for i, url in enumerate(gambar_urls):
        with st.spinner(f"Memuat gambar {i + 1} dari {len(gambar_urls)}"):
            img = load_image(url)
            if img is not None:
                images.append(img)

    for i, img in enumerate(images):
        # Menggunakan Streamlit untuk menampilkan gambar di tengah kolom
        col1, col2, col3 = st.columns([1, 2, 1])
        with col2:
            st.image(img, use_column_width=True)

        if i < len(data_list):
            st.write(f"Nama: {data_list[i]['nama']}")
            st.write(f"NIM: {data_list[i]['nim']}")
            st.write(f"Umur: {data_list[i]['umur']}")
            st.write(f"Asal: {data_list[i]['asal']}")
            st.write(f"Alamat: {data_list[i]['alamat']}")
            st.write(f"Hobbi: {data_list[i]['hobbi']}")
            st.write(f"Sosial Media: {data_list[i]['sosmed']}")
            st.write(f"Kesan: {data_list[i]['kesan']}")
            st.write(f"Pesan: {data_list[i]['pesan']}")
            st.write("  ")
    st.write("Semua gambar telah dimuat!")
menu = streamlit_menu()

# BAGIAN SINI YANG HANYA BOLEH DIUABAH
if menu == "Kesekjenan":
    def kesekjenan():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=15k6WmJYG25SqGVX_Lz7IbHPF3NW3bmb7",
            "https://drive.google.com/uc?export=view&id=15nVedfkgbYjIyzM3ZUOzxTIJNLuxqLnW",
            "https://drive.google.com/uc?export=view&id=15vkgrozNC2IYS_skL9LOcEvsra9kaax1",
            "https://drive.google.com/uc?export=view&id=15qqwaFuP3RHFVJ_VuplEarvZOcVF8sTt",
            "https://drive.google.com/uc?export=view&id=167jI1TKTylVv32MWyNU6qJFTxB8vesAE",
            "https://drive.google.com/uc?export=view&id=165fv43i1tgT1hgiw7s480RzeBP1LQNXb",
        ]
        data_list = [
            {
                "nama": "Kharisma Gumilang",
                "nim": "121450042",
                "umur": "21",
                "asal": "Palembang",
                "alamat": "Jl.Pulau Damar",
                "hobbi": "Dengerin Musik",
                "sosmed": "@gumilangkharisma",
                "kesan": "kereeen banget bang Gumi dan sangat menginspirasi",  
                "pesan":"Semangat, sukses terus dan keren selalu bang"# 1
            },
            {   
                "nama": "Pandra Insani Putra Anwar",
                "nim": "121450147",
                "umur": "21",
                "asal":"Lampung Utara",
                "alamat": "Sukarame",
                "hobbi": "Main Gitar",
                "sosmed": "@pandrainsani27",
                "kesan": "Bang Pandra keren banget dan kece",  
                "pesan":"Semangat terus bang dan tetap kece"# 1
            },
            {   
                "nama": "Meliza Wulandari",
                "nim": "121450065",
                "umur": "20",
                "asal":"Sumatera Selatan",
                "alamat": "Jl.Pagar Alam",
                "hobbi": "Nonton Drakor",
                "sosmed": "@wulandarimeliza",
                "kesan": "keren banget kak dan kakanya baik banget",  
                "pesan":"semangat dan sukses terus kak"# 1
            },
        
            {
                "nama": "Putri Maulida Chairani",
                "nim": "121450050",
                "umur": "21",
                "asal":"Sumatera Barat",
                "alamat": "Gg. Nangka 4",
                "hobbi": "Dengerin Bg Pandra Main Gitar",
                "sosmed": "@ptrimaulidaaa_",
                "kesan": "Cantik, pendengar yang baik ",  
                "pesan":"Semangat Kak sukses terusss"# 1
            },
        
            {   
                "nama": "Hartiti Fadilah",
                "nim": "121450031",
                "umur": "21",
                "asal":"Palembang",
                "alamat": "Pemda",
                "hobbi": "Nyanyi",
                "sosmed": "@htrpdla",
                "kesan": "cantik dan baik ",  
                "pesan":"Sukses selalu dan semangat kaak"# 1
            },
        
            {
                "nama": "Nadilla Andhara Putri",
                "nim": "121450003",
                "umur": "21",
                "asal":"Lampung",
                "alamat": "Metro",
                "hobbi": "Mainn Bola, Belajar",
                "sosmed": "@nadilaandr26",
                "kesan": "vibes bendaharanya kerasa bgt",  
                "pesan":"Semangat ngasprak strukdatnya kak!"# 1
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    kesekjenan()

elif menu == "Baleg":

    def Baleg():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1haZT5Dauha0d4ZOE9v46MymyqSh-5DUh",
            "https://drive.google.com/uc?export=view&id=1h7Dvk43tmrw0KsBhq8drKaU1C9_WJHYS",
            "https://drive.google.com/uc?export=view&id=1guHepHOvIV2UoTdZYDsW894kcHKVlPty",
            "https://drive.google.com/uc?export=view&id=1hJ5iJRpDOdqm-yPC_JmN2QebF2qYR5nX",
            "https://drive.google.com/uc?export=view&id=1hcR06qPmHY7sNE-TCQCykVlOPVHSAjRz",
            "https://drive.google.com/uc?export=view&id=1hZOdUBHjTZC71ZYhH72DKw3CncdMRk1F",
            "https://drive.google.com/uc?export=view&id=1hM-nLhFyyBfaehTIxXFTUYBl6j7GPk06",
            "https://drive.google.com/uc?export=view&id=1hbakEIkeXNLoqcGdY8dBcUf2o1LgKH9d",
            "https://drive.google.com/uc?export=view&id=1gterE2Vv5JkmWZo8ZO16hXS_oyd-jv-Q",
            "https://drive.google.com/uc?export=view&id=1he2k-I-iqiZ5n1RVVXoyfRQQcLcFCBT8",
            "https://drive.google.com/uc?export=view&id=1hADjAD2O-5gKUQW0zLvsIoa3tmQ2NYVO",
        ]
        data_list = [
            {
                "nama": "Tri Murniya Ningsih",
                "nim": "121450038",
                "umur": "21",
                "asal": "Bogor",
                "alamat": "Raden Saleh",
                "hobbi": "Tanya sama GPT",
                "sosmed": "@trimurniaa",
                "kesan": "cantik, ramah, pendengar yang baik, suka banget sama public speakingnya",
                "pesan": "semangat kuliahnya kakak, sukses terus kak Niya",
            },
            {
                "nama": "Annisa Cahyani Surya",
                "nim": "121450114",
                "umur": "21",
                "asal": "Tangerang Selatan",
                "alamat": "Way Huwi",
                "hobbi": "Puasa Senin Kamis",
                "sosmed": "@annisacahyanisurya",
                "kesan": "Baik banget dan ramah",
                "pesan": "Sukses terus dan semangat selalu kaak", 
            },
            {
                "nama": "Wulan Sabina",
                "nim": "121450150",
                "umur": "21",
                "asal": "Medan",
                "alamat": "Raden Saleh",
                "hobbi": "Menonton film",
                "sosmed": "wlsbn0",
                "kesan": "Ramah banget kakanya dan cantik",
                "pesan": "semangat ya kak, happy and sukses terus", 
            },
            {
                "nama": "Anisa Dini Amalia",
                "nim": "121450021",
                "umur": "20",
                "asal": "Tangerang",
                "alamat": "Jati Agung",
                "hobbi": "Baca Webtoon",
                "sosmed": " @anisadini10",
                "kesan": "Kakaknya baik, ramah, dan asik",
                "pesan": "semangat terus kuliahnya dan sukses selalu", 
            },
            {
                 "nama": "Feryadi Yulius ",
                "nim": "122450087",
                "umur": "20",
                "asal": "Padang",
                "alamat": "Belwis",
                "hobbi": "Sholat Dhuha",
                "sosmed": "@fer_yulius",
                "kesan": "Abannya keren banget",
                "pesan": "semangat kuliahnya bang, sukses terus", 
            },
            {
                "nama": "Renisha Putri Giani",
                "nim": "122450079",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Teluk Betung",
                "hobbi": "Baca Al-Qur'an",
                "sosmed": "@fleurnsh",
                "kesan": "Manis dan seruuu",
                "pesan": "Semangat kuliahnya kak, sukses terus",
            },
            {
                "nama": "Claudhia Angeliani",
                "nim": "121450124",
                "umur": "21",
                "asal": "Lampung Timur",
                "alamat": "Lampung Timur",
                "hobbi": "Baca Jurnal",
                "sosmed": " @dylebee",
                "kesan": "cantik dan baik",
                "pesan": "semangat dan happy selalu kak", 
            },
            {
                "nama": "Mirzan Yusuf Rabbani",
                "nim": "122450118",
                "umur": "20",
                "asal": "Jakarta",
                "alamat": "Korpri",
                "hobbi": "Main Kucing",
                "sosmed": "@myrrinn",
                "kesan": "Abangnya tinggi banget, baik, kalem, dan ramah",
                "pesan": "Bang jangan lupa kasih makan kucing and happy selalu", 
            },
            {
                "nama": "Muhammad Fachrul Aditya",
                "nim": "121450156",
                "umur": "22",
                "asal": "Surakarta",
                "alamat": "Sukarame",
                "hobbi": "Sholat Malam",
                "sosmed": "@fhrul.pdf",
                "kesan": "kereen dan baik",
                "pesan": "sukses terus bang, semangat kuliahnya", 
            },
             {
                "nama": "Jeremia Susanto",
                "nim": "122450022",
                "umur": "21",
                "asal": "Palembang",
                "alamat": "Bilabong",
                "hobbi": "Cerita",
                "sosmed": "@jeremia_s_",
                "kesan": "Bang Jere keren banget dan seru",
                "pesan": "semangat kuliahnya bang, keren terus ya bang", 
            }, 
            {
                "nama": " Berliana Enda Putri",
                "nim": "122450065",
                "umur": "20",
                "asal": "Sumatera Barat",
                "alamat": "Way Huwi",
                "hobbi": "Baca Buku, Ngoding, Ibadah",
                "sosmed": "@berlyyanda",
                "kesan": "Kakanya kereeen banget",
                "pesan": "semangat kuliahnya kak, sukses terus kak", 
            }
        ]
        display_images_with_data(gambar_urls, data_list)
    Baleg()

elif menu == "Senator":
    def senator():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=16Ao0h6PIubzO9bdZMoGAGqSORh1K8AuR",
            "https://drive.google.com/uc?export=view&id=1697dVn1aqXbW-9NJFbOZX4H7vyAqPMpH",
        ]
            
        data_list = [
            {
                "nama": "Anissa Luthfi Alifia",
                "nim": "121450093",
                "umur": "22",
                "asal": "Lampung Tengah",
                "alamat": "Kost Putri Rahayu",
                "hobbi": "Dengerin bintang nyanyi",
                "sosmed": "@anissalutfi_",
                "kesan": "sangat menginspirasi, kakaknya keren banget",
                "pesan": "Sukses terus kak", 
            },
            {
                "nama": "Rian Bintang Wijaya",
                "nim": "122450094",
                "umur": "20",
                "asal": "Palembang",
                "alamat": "Kota Baru",
                "hobbi": "Nyanyi",
                "sosmed": "@bintangtwinkle",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, sukses terus",
            }
        ]
        display_images_with_data(gambar_urls, data_list)
    senator()

elif menu == "Departemen PSDA":
    def Psda():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1UYFWnP1ICcljyvVjBsx2903cvKTmMJVj",
            "https://drive.google.com/uc?export=view&id=1UYp-UI7_QUx3OpDRX9NscVDokAW6JYkg",
            "https://drive.google.com/uc?export=view&id=1UZvcXrh3_bJsT8-v25qO2X_4PnLUgmPC",
            "https://drive.google.com/uc?export=view&id=1UZwP55X05585CmSzjSDQKiyiVR6i5KT8",
            "https://drive.google.com/uc?export=view&id=1UazcxXdSzY7dWzatBIfVK_1O5jYWDYtK",
            "https://drive.google.com/uc?export=view&id=1Ue9Ys9SVuXalbG0QhsX7HyaGnDUO552h",
            "https://drive.google.com/uc?export=view&id=1Uilyouf1DWYZtaxnP2Sabts1jWPbB25P",
            "https://drive.google.com/uc?export=view&id=1UmcKVUrY2Gmedd2YqlCZxEeBx7xBjyEp",
            "https://drive.google.com/uc?export=view&id=1Uu3xNhHRHhlqbi7LoZ-54oHxx_kkOMa3",
            "https://drive.google.com/uc?export=view&id=1UycskCssVJ6iX-6GonVawkn8jnltCh1K",
            "https://drive.google.com/uc?export=view&id=1VH1ytUAbMdUD2zNiJO15eqEQExZCTJ7G",
            "https://drive.google.com/uc?export=view&id=1UzdAzM_oyYPpj8yvFIATsR864TbhtavV",
            "https://drive.google.com/uc?export=view&id=1V22zsDlf55kcQwh8g3xCvdDQJEnpKWDu",
            "https://drive.google.com/uc?export=view&id=1Uvh8YprOV0DkOMRw7pwqT75xImCuiDeG",
            "https://drive.google.com/uc?export=view&id=1UzRsSqqGuLd6VIuB1xoBFuTr3mg-PfiQ",
            "https://drive.google.com/uc?export=view&id=1V3HP287tMFfJ_90c85t1DurtRri1t9ZI",
            "https://drive.google.com/uc?export=view&id=1V5-pbwQNed2blYu_lNF2QVptJ34_32by",
            "https://drive.google.com/uc?export=view&id=1V6aKwPPfM1ZtQ_hTIDULwYH3OGx9MRBS",
            "https://drive.google.com/uc?export=view&id=1VAUBWqEhzlvx0ND4Na1Hj_MkXMvzpjT7",
            "https://drive.google.com/uc?export=view&id=1VDN8nQW8e7EYmbtcX597Owk9ZEsq96e9",
            "https://drive.google.com/uc?export=view&id=1Wwk87Z1Ou65EhV9Akuj1RRxnVUQHNaBJ",
            "https://drive.google.com/uc?export=view&id=1X6YO1GlhHRoagL0PPQ0c4C8yul2nk63F",
            "https://drive.google.com/uc?export=view&id=1WsPAxbrQuyzlhxdkMfZ_j0-n6oQ1socC",
        ]
        data_list = [
            {
                "nama": "Ericson Chandra Sihombing",
                "nim": "121450026",
                "umur": "21",
                "asal":"Bekasi",
                "alamat": "Khobam",
                "hobbi": "Travelling",
                "sosmed": "@ericsonchandra99",
                "kesan": "Abangnya keren banget",  
                "pesan":"Sukses terus bang",
            },
            {
                "nama": "Elisabeth Claudia Simanjuntak",
                "nim": "122450123",
                "umur": "18",
                "asal":"Tangerang",
                "alamat": "Kemiling",
                "hobbi": "Bernafas",
                "sosmed": "@celisabethh_",
                "kesan": "Kakaknya lucu, cantik, dan keren",  
                "pesan":"Terus semangat kuliahnya Kak, ceria terus",
            },
            {
                "nama": "Nisrina Nur Afifah",
                "nim": "122450052",
                "umur": "19",
                "asal":"Jawa Barat",
                "alamat": "Sukarame",
                "hobbi": "Muter-muter",
                "sosmed": "@afifahhnsrn",
                "kesan": "cantik dan keren",  
                "pesan":"Semangat terus kak kuliahnya",
            },
            {
                "nama": "Allya Nurul Islami Pasha",
                "nim": "122450033",
                "umur": "20",
                "asal":"Sumatera Barat",
                "alamat": "Belwis",
                "hobbi": "Nongs",
                "sosmed": "@allyaislami",
                "kesan": "kakak ini keren banget asik dan seru",  
                "pesan":"sukses selalu kak dan semangat kuliahnya kak",
            },
            {
                "nama": "Eksanty Febriana Sukma Islamiaty",
                "nim": "122450001",
                "umur": "20",
                "asal":"Lubuk Linggau",
                "alamat": "Rajabasa",
                "hobbi": "Nyari sinyal di gedung F",
                "sosmed": "@eksantyfebriana",
                "kesan": "kak manis bangettt",  
                "pesan": "semoga sukses dan keren terus kak",
            },
            {
                "nama": "Farahanum Afifah Ardiansyah",
                "nim": "122450056",
                "umur": "20",
                "asal":"Padang",
                "alamat": "Sukarame",
                "hobbi": "Minum Kopi",
                "sosmed": "@farahanumafifahh",
                "kesan": "kakanyanya cantik dan baik",  
                "pesan":"semangat terus kuliahnya kak, kereeen terus",
            },
            {
                "nama": "Ferdy Kevin Naibaho",
                "nim": "122450107",
                "umur": "20",
                "asal":"Medan",
                "alamat": "Senopati Raya",
                "hobbi": "Dengerin Musik",
                "sosmed": "@ferdy_kevin",
                "kesan": "Abangnya baik dan seruuu",  
                "pesan":"semangat kuliahnya bang, dan sukses teruss",
            },
            {
                "nama": "M. Deriansyah Okutra",
                "nim": "122450101",
                "umur": "19",
                "asal":"Kayu Agung",
                "alamat": "Jl. Pagar Alam Kedaton",
                "hobbi": "Nongki-nongki",
                "sosmed": "@dransyh_",
                "kesan": "Abangnya baik dan asik",  
                "pesan":"Semangat terus kuliahnya bang dan sukses terus",
            },
            {
                "nama": "Oktavia Nurwenda Puspita Sari",
                "nim": "122450041",
                "umur": "20",
                "asal":"Lampung Timur",
                "alamat": "Way Huwi",
                "hobbi": "Scroll tik-tok",
                "sosmed": "@oktavianrwnda",
                "kesan": "Kakaknya manis banget",  
                "pesan":"Semangat terus Kak kuliahnya",
            },
            { 
                "nama": " Deyvan Loxefal", 
                "nim": " 121450148 ", 
                "umur":  "21", 
                "asal":" Duri Riau  ", 
                "alamat": "Khobam Pulau Damar", 
                "hobbi": "Belajar", 
                "sosmed": "@depanlo", 
                "kesan": "Abangnya keren asik dan seruu",   
                "pesan":"Sukses terus bang",
            },
            { 
                "nama": " Ibnu Farhan Al-Ghifari", 
                "nim": " 121450121 ", 
                "umur":  "21", 
                "asal":" Kerinci Jambi  ", 
                "alamat": "Khobam", 
                "hobbi": "game online", 
                "sosmed": "@al_ghifari032", 
                "kesan": "Abangnya baik dan keren",   
                "pesan":"Semangat kuliahnya bangg sukses terus",
            },
            { 
                "nama": "Johannes Krisjon Silitonga", 
                "nim": "122450043", 
                "umur": "19", 
                "asal":"Tangerang", 
                "alamat": "Jl. Lapas", 
                "hobbi": "Ngasprak", 
                "sosmed": "@johanneskrisjon", 
                "kesan": "Kakaknya asik, baik, keren dan seru.",   
                "pesan":"Keren terus bang, sukses selalu", 
            },
            { 
                "nama": "Kemas Veriandra Ramadhan", 
                "nim": "122450016", 
                "umur": "19", 
                "asal":"Bekasi", 
                "alamat": "Kojo Golf UIN", 
                "hobbi": "Main game", 
                "sosmed": "@kemasverii", 
                "kesan": "pinter banget dan baik",   
                "pesan":"Keren terus bang", 
            },
            { 
                "nama": "Leonard Andreas Napitupulu", 
                "nim": "121450153", 
                "umur": "21", 
                "asal":"Medan", 
                "alamat": "Khobam", 
                "hobbi": "belajar", 
                "sosmed": "@lndr.__", 
                "kesan": "Abangnya baik",   
                "pesan":"ssemangat dan sukses terus bang", 
            },
            { 
                "nama": "Presilia", 
                "nim": "122450081", 
                "umur": "20", 
                "asal":"Bekasi", 
                "alamat": "Kota Baru", 
                "hobbi": "Dengerin lomba sihir", 
                "sosmed": "@presiliamy", 
                "kesan": "Kakaknya cantik",   
                "pesan":"Semangat terus kak kuliahnya kereen terus", 
            },
            { 
                "nama": "Sahid Maulana", 
                "nim": "122450109", 
                "umur": "21", 
                "asal":"Depok, Jabar", 
                "alamat": "Jl. Airan Raya", 
                "hobbi": "Dengerin musik", 
                "sosmed": "@sahid_maul19", 
                "kesan": "Bang Sahid baik bangeet, soft spoken dan keren",   
                "pesan":"Kereen terus bang, terus jadi orang baik ya bang", 
            },
            {
                "nama": "M. Farhan Athaulloh",
                "nim": "121450117",
                "umur": "21",
                "asal":"Lampung",
                "alamat": "Kota Baru",
                "hobbi": "Menolong",
                "sosmed": "@mfarhan.ath",
                "kesan": "Abangnya baik dan ramah juga kereen",  
                "pesan":"Keren terus bang, sukses terus ",
            },
            {
                "nama": "Gede Moana",
                "nim": "121450014",
                "umur": "21",
                "asal":"Bekasi",
                "alamat": "Korpri Raya",
                "hobbi": "Belajar, game, baca komik",
                "sosmed": "@gedemoenaa",
                "kesan": "abangnya asik dan seru.",  
                "pesan":"Sukses terus bang",
            },
            {
                "nama": "Jaclin Alcavella",
                "nim": "122450015",
                "umur": "19",
                "asal":"Sumatera Selatan",
                "alamat": "Korpri",
                "hobbi": "Berenang",
                "sosmed": "@jaclinalcv_",
                "kesan": "kakak asik, manis dan baik banget ",  
                "pesan":"Semangat kuliahnya kak, sukses terus",
            },
            {
                "nama": "Syalaisha Andini Putriansyah",
                "nim": "122450111",
                "umur": "21",
                "asal":"Tangerang",
                "alamat": "Sukarame",
                "hobbi": "Baca",
                "sosmed": "@syalaisha.i__",
                "kesan": "kakaknya manis banget",  
                "pesan":"Semangat terus kuliahnya kak",
            },
            {
                "nama": "Rafly Prabu Darmawan",
                "nim": "122450140",
                "umur": "20",
                "asal":"Bangka Belitung",
                "alamat": "Sukarame",
                "hobbi": "Main Game",
                "sosmed": "@raflyy_pd2684",
                "kesan": "Abangnya baik dan keren",  
                "pesan":"Sukses terus bang",
            },
            { 
                "nama": "Rafa Aqilla Jungjunan", 
                "nim": "122450142", 
                "umur": "20", 
                "asal":"Pekanbaru", 
                "alamat": "JBelwis", 
                "hobbi": "Baca webtoon", 
                "sosmed": "@rafaaqilla", 
                "kesan": "Kakaknya keren",   
                "pesan":"semangat kuliahnya kak" 
            },
            { 
                "nama": "Vanessa Olivia Rose", 
                "nim": "121450108", 
                "umur": "20", 
                "asal":"Jakarta", 
                "alamat": "Perum korpri", 
                "hobbi": "Belajar", 
                "sosmed": "@roselivnes__", 
                "kesan": "Kakaknya keren",   
                "pesan":"sukses terus kak" 
            }
        ]
        display_images_with_data(gambar_urls, data_list)
    Psda()

elif menu == "Departemen MEDKRAF":

    def Medkraf():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1_9DsoY3KAKu8kFCT4Y2y9C_nLMR8PZ7F",
            "https://drive.google.com/uc?export=view&id=1_30DOy2W3ELLQNbBr9YhwH4DsdKOqSgf",
            "https://drive.google.com/uc?export=view&id=1_7TRH8ms7udsG53k11GXa4Yj22YJohK-",
            "https://drive.google.com/uc?export=view&id=1_W3IikthhdiPK10fsTRM5ZBTnItxNWv5",
            "https://drive.google.com/uc?export=view&id=1aKbFnY8m_0rnSmGjSBPv10T-KhwPqdIX",
            "https://drive.google.com/uc?export=view&id=1_c0M6WLx-1hDbDC5f3O8SFZ6YQInYIQw",
            "https://drive.google.com/uc?export=view&id=1_OCT5dz0KZVeTWoOMnObggFFMPxAIUpc",
            "https://drive.google.com/uc?export=view&id=1_JDwFQVInVjZrSO6_5fJlXeo0YfN59yh",
            "https://drive.google.com/uc?export=view&id=1_ZaX2RXHilPkaWnH81CxypBBG40L4FgG",
            "https://drive.google.com/uc?export=view&id=1_H-cZSyIVq2gsuJ7IBaSqQ7Io_MpyYHT",
            "https://drive.google.com/uc?export=view&id=1_MmxUFeRxaK-fh58GJmI2evD8WotiwS4",
            "https://drive.google.com/uc?export=view&id=1_bNaIIBylPY_eznBY26oc2N3G2bfsK4T",
            "https://drive.google.com/uc?export=view&id=1_EvCP-WdJeGmjtNBOpSMaIH_btbqq6yl",
            "https://drive.google.com/uc?export=view&id=1_DEvY8kyNdjOCtIDIiWSEFNL4t9DqeGD",
            "https://drive.google.com/uc?export=view&id=1_BU4bdElG2HIhQOAntbUkR2HuhpFiDDE",
            "https://drive.google.com/uc?export=view&id=1_8TM-XZyBCMGoCR9wjn2cdzrGb9QAFPk",
            "https://drive.google.com/uc?export=view&id=1Wng2_anrq0HxI8Uc8H5GoHnK_pemjmnl",
            "https://drive.google.com/uc?export=view&id=1WbR7mnha13MCEyRR7xrY7OQtfF-gYBIN",
            
        ]
        data_list = [
            {
                "nama": "Wahyudiyanto",
                "nim": "121450040",
                "umur": "22",
                "asal": "Makassar",
                "alamat": "Sukarame",
                "hobbi": "Nonton",
                "sosmed": "@wayyulaja",
                "kesan": "Keren banget bang wahyu dan baik bangett",
                "pesan": "Sukses terus bang, semangat selalu",
            },
            {
                "nama": "Elok Fiola",
                "nim": "122450051",
                "umur": "19",
                "asal": "Bandar Lampung",
                "alamat": "Bandar Lampung",
                "hobbi": "Editing",
                "sosmed": "@elokfiola",
                "kesan": "Manis bangett kak",
                "pesan": "Semangat kak elok", 
            },
            {
                "nama": "Cintya Bella",
                "nim": "122450066",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Teluk",
                "hobbi": "Ngegym",
                "sosmed": "@cintyabella28",
                "kesan": "cantik, baik, dan suka banget sama outfitnya",
                "pesan": "semangat kuliahnya kak, sukses terus", 
            },
            {
                "nama": "Patricia Leondra Diajeng Putri ",
                "nim": "122450050",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Jatimulyo",
                "hobbi": "Nonton Film",
                "sosmed": "@patriciadiajeng",
                "kesan": "Cantik dan seruuu",
                "pesan": "Keren terus kak dan semangat kuliahnya", 
            },
            {
                "nama": "Rahma Neliyana",
                "nim": "122450036",
                "umur": "20",
                "asal": "Lampung",
                "alamat": "Sukarame",
                "hobbi": "Baca Coding",
                "sosmed": "@rahmanellyana",
                "kesan": "ramah banget, manis dan baik",
                "pesan": "Semangat terus kak neli, happy selalu", 
            },
            {
                "nama": "Try Yani Rizki Nur Rohmah ",
                "nim": "122450020",
                "umur": "20",
                "asal": "Lampung Barat",
                "alamat": "Korpri",
                "hobbi": "Bernyanyi dan Menonton",
                "sosmed": "@tryyaniciaaa",
                "kesan": "kakaknya baik, manis, dan cantik",
                "pesan": "keren terus kak dan semangat", 
            },
            {
                "nama": "Muhammad Kaisar Firdaus ",
                "nim": " 121450135",
                "umur": "21",
                "asal": "Pesawaran",
                "alamat": "Pulau Damar",
                "hobbi": "Lagi Nyari",
                "sosmed": " @dino_kiper",
                "kesan": "Abangnya kece banget",
                "pesan": "Sukses terus bangg dan semangatt", 
            },
            {
                "nama": "Dwi Ratna Anggraeni",
                "nim": "122450008",
                "umur": "20",
                "asal": "Jambi",
                "alamat": "Perumahan Pemda",
                "hobbi": "Baca",
                "sosmed": "@dwiratn_",
                "kesan": "Kakaknya baik banget dan cantik",
                "pesan": "Semangat terus kak, sukses selalu kak", 
            },
            {
                "nama": "Gymnastiar Al Khoarizmy",
                "nim": "122450096",
                "umur": "20",
                "asal": "Serang",
                "alamat": "Lapangan Golf UIN",
                "hobbi": "Baca Komik",
                "sosmed": "@jimnn.as",
                "kesan": "Keren banget bang",
                "pesan": "semangat terus bangg dan tetap keren", 
            },
            {
                "nama": "Nasywa Nur Afifah ",
                "nim": "122450125",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Jalan Durian 1 Pemda",
                "hobbi": "Nonton Drakor",
                "sosmed": "@nsywanaf",
                "kesan": "baik banget , cantik",
                "pesan": "sukses terus kak, semangat kuliahnya kak", 
            },
            {
                "nama": "Priska Silvia Ferantiana",
                "nim": "122450053",
                "umur": "20",
                "asal": "Palembang",
                "alamat": "Jalan Nangka 2",
                "hobbi": "Baca Novel yang Bikin Nangis",
                "sosmed": "@prskslv",
                "kesan": "Keren banget dan baik",
                "pesan": "Semangat kuliahnya kak, sukses selalu", 
            },   
            {
                "nama": "Muhammad Arsal Ranjana Putra",
                "nim": "121450111",
                "umur": "21",
                "asal": "Depok",
                "alamat": "Nangka 4",
                "hobbi": "Ngoding",
                "sosmed": "@arsal.utama",
                "kesan": "Bang Arsal keren banget pliss dan baik banget",
                "pesan": "Sukses dan keren terus bang Arsal", 
            },
            {
                "nama": "Abit Ahmad Oktarian",
                "nim": "122450042",
                "umur": "19",
                "asal": "Bandar Lampung",
                "alamat": "Rajabasa, Labuhan Dalam",
                "hobbi": "Ngoding, Gaming",
                "sosmed": "@abitahmad",
                "kesan": "Bang Abit kereeen banget dan baik",
                "pesan": "keren terus ya bang, semangattt", 
            },
             {
                "nama": "Akmal Faiz Abdillah",
                "nim": "122450114",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Perumahan Griya Sukarame",
                "hobbi": "Main HP",
                "sosmed": "@_akmal.faiz",
                "kesan": "baik banget dan Keren banget bang Akmal ",
                "pesan": "Semangat kuliahnya bang, sukses terus", 
            },
             {
                "nama": "Hermawan Manurung ",
                "nim": "122450069",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Dekat Jalan Tol (Wisma Hana Hani) ",
                "hobbi": "Bengong/Membaca Buku",
                "sosmed": "@hermawan.mnrng",
                "kesan": "Abangnya keren, seru banget dan jail",
                "pesan": "Sukses terus ya bang, dan tetap keren", 
            },
             {
                "nama": "Khusnun Nisa",
                "nim": "122450078",
                "umur": "20",
                "asal": "Lampung Selatan",
                "alamat": "Jati Agung",
                "hobbi": "Mengerjakan Tugas",
                "sosmed": "@khusnun_nisa335",
                "kesan": "Baik banget dan ramah",
                "pesan": "Sukses terus kak, semangat terus ya kak", 
            },
            {
                "nama": "Eka Fidiya Putri",
                "nim": " 122450045",
                "umur": "20",
                "asal": "Natar, Lampung Selatan",
                "alamat": "Natar, Lampung Selatan",
                "hobbi": "Menyibukkan Diri",
                "sosmed": "@ekafdyaptri",
                "kesan": "keren banget kak",
                "pesan": "Sukses terus kak", 
            },
            {
                "nama": "Arsyiah Azahra",
                "nim": "121450035",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Tanjung Senang",
                "hobbi": "Nugas",
                "sosmed": "@arsyiah._",
                "kesan": "Keren banget kak",
                "pesan": "Semangat kak", 
            }
            
        ]
        display_images_with_data(gambar_urls, data_list)
    Medkraf()

elif menu == "Departemen MIKFES":

    def Mikfes():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=16chgwiqHtny3dp0lzMzDe_KAmYLtqDE2",
            "https://drive.google.com/uc?export=view&id=16raZweavQOkTfXa0qRyZQC4Eg1SBS1l9",
            "https://drive.google.com/uc?export=view&id=16WbKwqvuVPMdzpprPzTy3XzlzSXinNzb",
            "https://drive.google.com/uc?export=view&id=16jEQ6lqHYYD3zfqZREUP2LonUCG-OFuM",
            "https://drive.google.com/uc?export=view&id=17Bn88hU2NPTrpByzXuSOZADrdtURCqLy",
            "https://drive.google.com/uc?export=view&id=16wVeg8pG_TfDBOw--VP_cIuR49SXVnkY",
            "https://drive.google.com/uc?export=view&id=16WebzE-mWUuanC9SRikrIB1smFz37Lmu",
            "https://drive.google.com/uc?export=view&id=176XYLz1KEhJcxr3D02T0DKoZvE1Bcsh-",
            "https://drive.google.com/uc?export=view&id=173D7xCH1sBud4521oOntpZPbzLgogExz",
            "https://drive.google.com/uc?export=view&id=16tu6ZtJkgKc6HeQnwbvm4TvHh_DJITfJ",
            "https://drive.google.com/uc?export=view&id=175nhEHbD8ufntwhKuo6BclOg8q5x7kzL",
            "https://drive.google.com/uc?export=view&id=17-GpjpXy-t0BjGNJJts-tl4bB7Q889Wo",
            "https://drive.google.com/uc?export=view&id=172jk6sZ4-tAkVwe9K-ZbF-GyUsbXVCdE",
            "https://drive.google.com/uc?export=view&id=16mSElVphn4aCuh-kN4_s6ccjK_n3ecxt",
            "https://drive.google.com/uc?export=view&id=16hipVkIAOiQZiw_bPbX7_r0L3PTi0GsK",
            "https://drive.google.com/uc?export=view&id=16Uv0Nz388Z2waNp3-YrLYmH3_MU5oYvu",
            "https://drive.google.com/uc?export=view&id=16oNPNoSXosjCCRrSL1xtuPf14daZ0FUQ",
            "https://drive.google.com/uc?export=view&id=16gOsP66Nk3J7uyAKy219VvvOdrvMMTxA",
            "https://drive.google.com/uc?export=view&id=16kccEgMqKIfOPZXcjCnXPKVPZ2_05qht",
        ] 
        data_list = [
            {
                "nama": "Rafi Fadhlillah",
                "nim": "121450143",
                "umur": "21 Tahun",
                "asal": "Lubuk Linggau",
                "alamat": "Jl. Nangka 4",
                "hobbi": "Olahraga",
                "sosmed": "@rafadhilillahh13",
                "kesan": "Keren banget",
                "pesan": "Sukses terus bang",
            },
            {
                "nama": "Annisa Novantika",
                "nim": "121450005",
                "umur": "21 Tahun",
                "asal": "Lampung Utara",
                "alamat": "Jl. Pulau Sebesi, Sukarame",
                "hobbi": " Memasak",
                "sosmed": "@anovavona",
                "kesan": "Cantik",
                "pesan": "Sukses terus kak",
            },
            {
                "nama": " Ahmad Sahidin Akbar",
                "nim": "122450044",
                "umur": " 20",
                "asal": "Tulang Bawang",
                "alamat": " Sukarame",
                "hobbi": "Olahraga",
                "sosmed": "@sahid22__",
                "kesan": "Baik banget",
                "pesan": "Sukses terus kak",
            },
            {
                "nama": "Fadhil Fitra Wijaya",
                "nim": "122450082",
                "umur": "20 Tahun",
                "asal": "Bekasi",
                "alamat": "Teluk Betung ",
                "hobbi": "Main Game",
                "sosmed": "@fadhilfwee",
                "kesan": "Keren banget",
                "pesan": "Sukses terus bang",
            },
            {
                "nama": "Muhammad Regi Abdi Putra Amanta",
                "nim": " 122450031",
                "umur": "19 Tahun",
                "asal": "Palembang",
                "alamat": "Jl. Permadi Sukarame  ",
                "hobbi": "Main Game",
                "sosmed": "@mregiiii_",
                "kesan": "Keren banget bang",
                "pesan": "Sukses terus bang",
            },
            {
                "nama": "Syalaisha Andina Putriansyah",
                "nim": "122450121",
                "umur": "21 Tahun",
                "asal": "Tangerang",
                "alamat": "Gg Yudhistira ",
                "hobbi": "Baca Novel",
                "sosmed": "@dkselsd_31",
                "kesan": "kakanya manis banget",
                "pesan": "Semangat terus kak",
            },
            {
                "nama": "Natanael Oktavianus Partahan Sihombing ",
                "nim": "121450107",
                "umur": "20 Tahun",
                "asal": "Jakarta",
                "alamat": "Kemiling ",
                "hobbi": "Membuka Wisata HMSD",
                "sosmed": "@natanaeloks",
                "kesan": "Keren banget",
                "pesan": "Sukses terus bang",
            },
            {
                "nama": "Anwar Muslim",
                "nim": "122450117",
                "umur": "21 Tahun",
                "asal": "Bukittinggi",
                "alamat": "Korpri ",
                "hobbi": " ML (Machine Learning)",
                "sosmed": "@here.am.ai",
                "kesan": "Keren banget bang",
                "pesan": "semangat bang",
            },
            {
                "nama": "Deva Anjani Khayyuninafsyah",
                "nim": "122450014",
                "umur": "21 Tahun",
                "asal": " Bandar Lampung",
                "alamat": "Kemiling",
                "hobbi": "Menonton Film",
                "sosmed": "@anjaniiidev",
                "kesan": "keren banget",
                "pesan": "semangat kuliahnya kak",
            },
            {
                "nama": "Dinda Nababan",
                "nim": "122450120",
                "umur": "20 Tahun",
                "asal": "Medan",
                "alamat": "Jl. Lapas",
                "hobbi": "Main Game",
                "sosmed": "@dindanababan_",
                "kesan": "keren banget",
                "pesan": "semangat kuliahnya kak",
            },
            {
                "nama": "Marleta Cornelia Leander",
                "nim": "122450092",
                "umur": "20 Tahun",
                "asal": "Depok, Jawa Barat",
                "alamat": "Gg. Nangka 3",
                "hobbi": "Liatin Jurnal",
                "sosmed": "@marletacornelia",
                "kesan": "keren dan banget",
                "pesan": "semangat kuliahnya kak",
            },
            {
                "nama": "Rut Junita Sari Siburian",
                "nim": "122450103",
                "umur": "20 Tahun",
                "asal": "Batam, Kep.Riau",
                "alamat": "Gg. Nangka 3",
                "hobbi": "Resume Jurnal",
                "sosmed": "@junitaa_0406",
                "kesan": "keren banget",
                "pesan": "sukses terus kak",
            },
            {
                "nama": "Syadza Puspadari Azhar",
                "nim": " 122450072",
                "umur": "20 Tahun",
                "asal": "Palembang",
                "alamat": "Belwis ",
                "hobbi": "Membaca",
                "sosmed": "@puspadrr",
                "kesan": "baik banget keren cantik manis, the best",
                "pesan": "sukses terus kak puspaa, semangat dan tetap keren ya kak",
            },
            {
                "nama": " Abdurrahman Al-atsary",
                "nim": "121450128",
                "umur": "23 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "Perumnas Way Kandis",
                "hobbi": " Membaca",
                "sosmed": "@rahmn_abdr",
                "kesan": "keren banget",
                "pesan": "sukses terus kak",
            },
            {
                "nama": "Aditya Rahman",
                "nim": "122450113",
                "umur": "20 Tahun",
                "asal": " Lampung Timur",
                "alamat": "Korpri",
                "hobbi": "Ngoding WISATA",
                "sosmed": "@rahm_adityaa",
                "kesan": "keren banget",
                "pesan": "semangat kuliahnya bang",
            },
            {
                "nama": "Eggi Satria",
                "nim": "122450032",
                "umur": "20 Tahun",
                "asal": "Sukabumi",
                "alamat": "Korpri",
                "hobbi": "Ngoding dan buat konten WISATA",
                "sosmed": "@egistr ",
                "kesan": "kereeen banget",
                "pesan": "sukses terus bang",
            },
            {
                "nama": "Febiya Jomy Pratiwi",
                "nim": "122450074",
                "umur": "20 Tahun",
                "asal": "Tulang Bawang",
                "alamat": "Jl Kelengkeng Raya",
                "hobbi": "Nonton K-Drama ",
                "sosmed": "@pratiwifebiya",
                "kesan": "keren banget",
                "pesan": "semangat kuliahnya kak",
            },
            {
                "nama": "Happy Syahrul Ramadhan",
                "nim": "122450013",
                "umur": "20 Tahun",
                "asal": "Lampung",
                "alamat": "Karang Anyar ",
                "hobbi": " Main Game",
                "sosmed": "@sudo.syahrulramadhannn",
                "kesan": "kereen banget",
                "pesan": "sukses terus bang",
            },
            {
                "nama": "Randa Andriana Putra",
                "nim": "122450083",
                "umur": "21 Tahun",
                "asal": "Banten",
                "alamat": " Sukarame",
                "hobbi": " Tidur dan Berkembang",
                "sosmed": "@randaandriana_",
                "kesan": "baik banget bang randa dan kereeen",
                "pesan": "keren terus bang",
            }
        ]
        display_images_with_data(gambar_urls, data_list)
    Mikfes()

elif menu == "Departemen Eksternal":
    def Eksternal():
        gambar_urls = [

            "https://drive.google.com/uc?export=view&id=1M900_d6CrEDiR08zolwG6dBaQQu9l393",
            "https://drive.google.com/uc?export=view&id=1MAQtEtuKbyb18uMcs0L2JvqOv_psBbxp",
            "https://drive.google.com/uc?export=view&id=1MPSNH28kQUtABflsnZuR_XzHGnVtZMbF",
            "https://drive.google.com/uc?export=view&id=1MAoqZbGjqosRyi4MEJQpTosfhkjv0EiH",
            "https://drive.google.com/uc?export=view&id=1MDnDwu6-smIzz7VDzkvTxYCYF0X3mt-L",
            "https://drive.google.com/uc?export=view&id=1MOAfSxFJIFxEsvLfNCuwCZup8ZquwQUQ",
            "https://drive.google.com/uc?export=view&id=1MPEWdXUxPhntMTpcHvhP_QTi1Ze_SVhe",
            "https://drive.google.com/uc?export=view&id=1Mj62yZmltDPHNL28ReH8vN6lM11vNB4i",
            "https://drive.google.com/uc?export=view&id=1MfKd0rrrchM5zt3B9ZFOo_diq0H2ZjGI",
            "https://drive.google.com/uc?export=view&id=1MSGtm0l4JQjMkJSQHHDx-1hma0MUovdF",
            "https://drive.google.com/uc?export=view&id=1MQtbeLV4OYKXlEQN-3058U_7RMICV5XK",
            "https://drive.google.com/uc?export=view&id=1MjmQXrFEPA4E2N48QWFkebpwnfsM1nXo",
            "https://drive.google.com/uc?export=view&id=1MmnQqAWIMP3eWTgBKA31wVkqhjAz4wPN",
            "https://drive.google.com/uc?export=view&id=1MdPbX-YYgrTDlX9VOAbC2zfteiGZ3cgC",
            "https://drive.google.com/uc?export=view&id=1MfshVAKeVsQtyMBmWJ9Edy-hTWYiRN3j",
            "https://drive.google.com/uc?export=view&id=1MZuCkjsocf6brE2E5eiuAcdbh-KRXqE8",         

        ]
        data_list = [
            {
                "nama": "Yogy Sea Tama",
                "nim": "121450041",
                "umur": "21",
                "asal": "Tangerang",
                "alamat": "Jatimulyo",
                "hobbi": "Ngisi Bensin",
                "sosmed": "@yogyyyyyyy",
                "kesan": "Abangnya keren banget dan baiiik",
                "pesan": "keren terus ya bang, sukses selalu dan semangatt",  
            },
            {
                "nama": "Ramadhita Asifa Hendri",
                "nim": "121450131",
                "umur": "21",
                "asal": "Rajabasa",
                "alamat": "Rajabasa",
                "hobbi": "Belajar",
                "sosmed": "@Ramadhitaasifa",
                "kesan": "kakanya baik dan kereeen",
                "pesan": "Semangat kak, sukses terus ya kaak",
            },
            {
                "nama": "Nazwa Nabilla",
                "nim": "121450112",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Way Kandis",
                "hobbi": "Belajar dengan Rajin",
                "sosmed": "@nazwanbilla",
                "kesan": "kakaknya cantik dan baik",
                "pesan": "Sukses terus kak, semangat",
            },
            {
                "nama": "Dea Mutia Risani",
                "nim": "122450099",
                "umur": "20",
                "asal": "Sumatera Barat",
                "alamat": "Korpri",
                "hobbi": "Bikin Surat",
                "sosmed": "@deaa.rsn",
                "kesan": "kakaknya baik banget",
                "pesan": "Sukses terus kak, semangat kuliahnya",
            },
            {
                "nama": "Novelia Adinda",
                "nim": "122450104",
                "umur": "21",
                "asal": "Jakarta",
                "alamat": "Belwis",
                "hobbi": "Tidur",
                "sosmed": "@nvliadinda",
                "kesan": "kakaknya baik banget pliss dan cantik",
                "pesan": "Semangat kuliahnya kak, jangan berhenti jadi baik",
            },
            {
                "nama": "Ratu Keisha Jasmin Deonova",
                "nim": "122450106",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Way Kandis",
                "hobbi": "Ngerjain ADW",
                "sosmed": "@jasminednva",
                "kesan": "keren banget dan cantik",
                "pesan": "Sukses terus dan semangat kaaak",
            },
            {
                "nama": "Tobias David Monogari",
                "nim": "121450081",
                "umur": "20",
                "asal": "Jakarta Barat",
                "alamat": "Pemda",
                "hobbi": "Bikin Puisi",
                "sosmed": "@tobiassiagian",
                "kesan": "Abangnta baik banget dan kereen",
                "pesan": "Semangat kuliahnya bang, tetap keren ya bang",
            },
            {
                "nama": "Rizki Adrian Bennovry",
                "nim": "121450073",
                "umur": "21",
                "asal": "Bekasi",
                "alamat": "TVRI",
                "hobbi": "Buat Portopolio",
                "sosmed": "@rzkdrnnn",
                "kesan": "Abangnya keren banget",
                "pesan": "Sukses terus dan semangatt bang",
            },
            {
                "nama": "Arafi Ramadhan Maulana",
                "nim": "12245022",
                "umur": "20",
                "asal": "Jogja, Depok",
                "alamat": "Way Huwi",
                "hobbi": "menghafal al-quran",
                "sosmed": "@arafiramadhanmaulana",
                "kesan": "Abangnya kece banget",
                "pesan": "Sukses terus dan tetap kece ya bang",
            },
            {
                "nama": "Asa Do'a Uyi",
                "nim": "122450005",
                "umur": "20",
                "asal": "Muara",
                "alamat": "Korpri",
                "hobbi": "cuci baju",
                "sosmed": "@u_yippy",
                "kesan": "kakaknya baik banget, ramah, dan manis",
                "pesan": "semangat terus ya kak, sukses selalu",
            },
            {
                "nama": "Chalifia Wananda",
                "nim": "122450076",
                "umur": "20",
                "asal": "Padang",
                "alamat": "sukarame",
                "hobbi": "Quality Time",
                "sosmed": "@chipawww",
                "kesan": "keren banget kak",
                "pesan": "sukses terus ya kak, semangattt",
            },
            {
                "nama": "Irvan Alfaritzi",
                "nim": "122450093",
                "umur": "21",
                "asal": "Sumatera Barat",
                "alamat": "Jakarta",
                "hobbi": "Nonton Youtube dan main ML",
                "sosmed": "@Alfaritziirfan",
                "kesan": "Abangnya baik banget",
                "pesan": "Semangat kuliahnya bang",
            },
            {
                "nama": "Izza Lutfia",
                "nim": "122450090",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Teluk",
                "hobbi": "main vollly",
                "sosmed": "@izzalutfiaa",
                "kesan": "kakak Izza baik banget dan seruuu",
                "pesan": "Semangat terus kak, tetap keren ya kak",
            },
            {
                "nama": "Khaalishah Zuhrah ALyaa Valefi",
                "nim": "122450034",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Rajabasa",
                "hobbi": "Nyanyi",
                "sosmed": "@alyaavalefi",
                "kesan": "baik dan keren banget ",
                "pesan": "Sukses terus kak",
            },
            {
                "nama": "Raid Muhammad Naufal",
                "nim": "122450027",
                "umur": "20",
                "asal": "Lampung Tengah",
                "alamat": "Sukarame",
                "hobbi": "Ngeresume Seminar",
                "sosmed": "@rayHis_",
                "kesan": "Abangnya baik bangett",
                "pesan": "Semangat menjalani hari-hari dan kuliahnya bang",
            },
            {
                "nama": "Tria Yunanni",
                "nim": "122450062",
                "umur": "20",
                "asal": "Way Kanan",
                "alamat": "Jakarta",
                "hobbi": "Baca",
                "sosmed": "@tria_y062",
                "kesan": "kakaknya manis banget",
                "pesan": "Semangat kuliahnya kak, sukses terus",
            }
        ]
        display_images_with_data(gambar_urls, data_list)
    Eksternal()
elif menu == "Departemen Internal":
    def Internal():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=10RuXmtPkrE1FvGbnlh5L30_1_jYUk6iP",
            "https://drive.google.com/uc?export=view&id=1-wUVe_odhq6r8_6LvcHC76jqTWdpPjJ0",
            "https://drive.google.com/uc?export=view&id=10ycFQEhqiC5qrggKHRL-dAzKatR9mpJ2",
            "https://drive.google.com/uc?export=view&id=101WnVlOrS5zcAVYF1MxJd2mEoLML_iSA",
            "https://drive.google.com/uc?export=view&id=10OtysHBEAKd3mr-6i5kNyVw0U1sHJFPF",
            "https://drive.google.com/uc?export=view&id=105MuTbLQ7XzjZTCm5RReVT71PZZhy_qc",
            "https://drive.google.com/uc?export=view&id=10VBInQSFCnuqS6DeGEWixUwE5tn4j1kK",
            "https://drive.google.com/uc?export=view&id=10vbymuhYRVT0h-q7ypRyDvEUGN7kMBFy",
            "https://drive.google.com/uc?export=view&id=10VN94QKLZVU6Jgv4S0NWAkrXgKY9AnfR",
            "https://drive.google.com/uc?export=view&id=1NLtmuo7Tl72EKCobrMpOjEtPgbrDPJXm",
            "https://drive.google.com/uc?export=view&id=106KJ67t2l_78EU3YJA_MMAzKRq2V0bXV",
            "https://drive.google.com/uc?export=view&id=10-aw9ZfRkJz-Rs0TDanhhz-wvwYt3BCX",
            "https://drive.google.com/uc?export=view&id=10aV4JweipKjEs_nR7Xz3AytN300YQzEs",
        ]
        data_list = [
             {
                "nama": "Dimas rizky ramadhani",
                "nim": "121450027",
                "umur": "20",
                "asal": "Pamulang",
                "alamat": "Way kandis",
                "hobbi": "Manjat tower sutet",
                "sosmed": "@dimzrky",
                "kesan": "-",
                "pesan": "-", 
            },
            {
                "nama": "Catherine firdhasari maulina sinaga",
                "nim": "121450072",
                "umur": "20",
                "asal": "Sumatera Utara",
                "alamat": "Airan",
                "hobbi": "Baca novel",
                "sosmed": "@chatherine.sinaga",
                "kesan": "kakanya ramah dan baik",
                "pesan": "Semangat terus kak, sukses selalu",
            },    
            {
                "nama": "M. Akbar resdika",
                "nim": "121450066",
                "umur": "20",
                "asal": "Lampung Barat",
                "alamat": "Labuhan dalam",
                "hobbi": "Memelihara dino",
                "sosmed": "@akbar_resdika",
                "kesan": "Kereeen banget dan baik",
                "pesan": "Sukses terus bang",
            },    
            {
                "nama": "Rani puspita sari",
                "nim": "122450030",
                "umur": "20",
                "asal": "Metro",
                "alamat": "Rajabasa",
                "hobbi": "Mengaji",
                "sosmed": "@ranipu",
                "kesan": "Kakaknya keren banget",
                "pesan": "Sukses selalu kak, semangattt",
            },
            {
                "nama": "Rendra eka prayoga",
                "nim": "122450112",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Jalan lapas raya",
                "hobbi": "nulis lagu",
                "sosmed": "@rendraepr",
                "kesan": "Bang rendra baik banget kereeeen",
                "pesan": "keren terus ya bang, semangat kuliahnya ",
            },
            {
                "nama": "Salwa farhanatussaidah",
                "nim": "122450055",
                "umur": "20",
                "asal": "Pesawaran",
                "alamat": "Airan raya",
                "hobbi": "ngeliat cogan",
                "sosmed": "@slwfhn_694",
                "kesan": "Cantik bangett",
                "pesan": "sukses terus kak semangat kuliahnya",
            },
            {
                "nama": "Ari sigit",
                "nim": "121450069",
                "umur": "23",
                "asal": "Lampung barat",
                "alamat": "Labuhan ratu",
                "hobbi": "Main futsal",
                "sosmed": "@ari_sigit17",
                "kesan": "Abangnya keren banget serius, kalem dan baik",
                "pesan": "semangat untuk selalu berada di jalan Allah bang",
            },
            {
                "nama": "Azizah kusumah putri",
                "nim": "122450068",
                "umur": "21",
                "asal": "Lampung Selatan",
                "alamat": "Natar",
                "hobbi": "berkebun",
                "sosmed": "@azizahksmh15",
                "kesan": "kakanya ramah bangett dan baik",
                "pesan": "Semangat kak azizah",
            },
            {
                "nama": "Meira listyaningrum",
                "nim": "122450011",
                "umur": "20",
                "asal": "Pesawaran",
                "alamat": "Airan raya",
                "hobbi": "Menghalu",
                "sosmed": "@meiraln",
                "kesan": "Baik bangett",
                "pesan": "Sukses selalu kak",
            },
            {
                "nama": "Rendi alexander hutagalung",
                "nim": "122450057",
                "umur": "20",
                "asal": "Tangerang",
                "alamat": "Kost gunawan",
                "hobbi": "Menyanyi",
                "sosmed": "@alexanderr",
                "kesan": "abangnya Baik bangett",
                "pesan": "semangat kuliahnya bang",
            },
            {
                "nama": "Renta siahaan",
                "nim": "122450070",
                "umur": "21",
                "asal": "Sumatera utara",
                "alamat": "Gerbang barat",
                "hobbi": "Memancing",
                "sosmed": "@renta.shn",
                "kesan": "kakaknya baik dan keren",
                "pesan": "semangat kuliahnya kak",
            },
            {
                "nama": "Yosia lehare banurea",
                "nim": "121450149",
                "umur": "20",
                "asal": "Dairi, Sumatera utara",
                "alamat": "Perum griya indah",
                "hobbi": "Bawa motor pakai kaki",
                "sosmed": "@yosiabanurea",
                "kesan": "abangnya Baik bangett",
                "pesan": "semangat bang, sukses selalu",
            },
            {
                "nama": "Josua panggabean",
                "nim": "121450061",
                "umur": "21",
                "asal": "Pematang siantar",
                "alamat": "Gya kost",
                "hobbi": "Ngawinin cupang",
                "sosmed": "@josuapanggabean16_",
                "kesan": "Abangnya baik banget dan soft spoken",
                "pesan": "semangat kuliahnya bang, sukses terus",
            }
        ]
        display_images_with_data(gambar_urls, data_list)
    Internal()
elif menu == "Departemen SSD":
    def Ssd():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1LiOYscAZ8RC7s88Y82ZMa1M7Yxqq4EqJ",
            "https://drive.google.com/uc?export=view&id=1LzX2nd3jTVFDY8aB771XknIzlyxLx4DP",
            "https://drive.google.com/uc?export=view&id=1M0xdDF4l1IKvTecWqiBYYL3XAILX1ojG",
            "https://drive.google.com/uc?export=view&id=1LlvUub64ulimVG8tzg3tH4jNl8WZkYoq",
            "https://drive.google.com/uc?export=view&id=1M7iMi-tzNtw3hti0DSTnY__wgXGr_CoM",
            "https://drive.google.com/uc?export=view&id=1Ljszs7_Fl8_tORykfxzUGeFEO2EZtzFT",
            "https://drive.google.com/uc?export=view&id=1M6cJtUaN6QgQRUDSnq-6m6n6m45G_WBZ",
            "https://drive.google.com/uc?export=view&id=1LhwvjPUuwNG8hUTJ9QA8bN6bX7jSVx44",
            "https://drive.google.com/uc?export=view&id=1Lg8ucL6d29GxsW4go5zMeVaw_ryeSepv",
            "https://drive.google.com/uc?export=view&id=1W6yf6U1YvkTHR1toPcSQJLtPpm1iG918",
        ]
        data_list = [
            {
                "nama": "Andrian Agustinus Lumban Gaol",
                "nim": "121450090",
                "umur": "17 +",
                "asal": "Sidikalang",
                "alamat": "Lapas",
                "hobbi": "Nyari Hobi",
                "sosmed": "@andrialgaol",
                "kesan": "Public speakingnya bagus bangett",
                "pesan": "Semangat kuliahnya bang", 
            },
            {
                "nama": "Adisty Syawaida Ariyanto",
                "nim": "121450136",
                "umur": "21",
                "asal": "Metro",
                "alamat": "Metro",
                "hobbi": "Nonton film",
                "sosmed": "@adistisa_",
                "kesan": "Keren banget kak",
                "pesan": "Sukses terus kak",
            },
            {
                "nama": "Nabila Azhari",
                "nim": "121450029",
                "umur": "21",
                "asal": "Simalungun",
                "alamat": "Airan",
                "hobbi": "Menghitung",
                "sosmed": "@zhjung",
                "kesan": "seru banget kakaknya",
                "pesan": "semoga karir nya sukses kak",
            },
            {
                "nama": "Danang Hilal Kurniawan",
                "nim": "122450085",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "TB 3 Asrama",
                "hobbi": "Belajar",
                "sosmed": "@dananghk_",
                "kesan": "abangnya keren banget sangat menginsprirasi",
                "pesan": "Semangat kuliah dan ngaspraknya bang",
            },
            {
                "nama": "Farel Julio Akbar",
                "nim": "122450110",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Jalan Lapas",
                "hobbi": "Bebas",
                "sosmed": "@farel__julio",
                "kesan": "Abangnya baik dan ramah banget, keren",
                "pesan": "Semangat abang kapo",
            },
            {
                "nama": "Nabilah Andika Fitriani",
                "nim": "121450129",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Kedaton",
                "hobbi": "Tidur",
                "sosmed": "@nabilaafrn",
                "kesan": "kakaknya kereen banget",
                "pesan": "sukses selalu kak, semangatt",
            },
            {
                "nama": "Alvia Asrinda Br.Ginting",
                "nim": "122450077",
                "umur": "20",
                "asal": "Binjai",
                "alamat": "Korpri",
                "hobbi": "Nonton Windah",
                "sosmed": "@alviaginting",
                "kesan": "kakaknya keren banget",
                "pesan": "Sukses terus kak, semangat kuliahnya",
            },
            {
                "nama": "Dhafin Razaka Luthfia",
                "nim": "122450133",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Jalan nangka 1",
                "hobbi": "Olahraga",
                "sosmed": "@dhafinrzqri3",
                "kesan": "abangnya baik",
                "pesan": "Semangat kuliahnya ya bang, sukses terus",
            },
            {
                "nama": "Elia Meylani Simanjuntak ",
                "nim": "12145002",
                "umur": "20",
                "asal":"Bekasi",
                "alamat": "Korpri",
                "hobbi": "Nyanyi",
                "sosmed": "@meylaniellia",
                "kesan": "kakak cantik banget, manis, terus ramah dan baik, seruu",  
                "pesan":"semangat kuliahnya kak"
            },
            {
                "nama": "Tessa Kania Sagala",
                "nim": "122450040",
                "umur": "20",
                "asal":"Sumatera Utara",
                "alamat": "Pemda",
                "hobbi": "Menulis",
                "sosmed": "@tesakaniaa",
                "kesan": "kakanya ramah dan baikk",  
                "pesan":"semangat kuliahnya kak"
            }
        ]
        display_images_with_data(gambar_urls, data_list)
    Ssd()

# Tambahkan menu lainnya sesuai kebutuhan