import streamlit as st
from streamlit_option_menu import option_menu
import requests
from PIL import Image, ImageOps
from io import BytesIO

st.markdown("""<style>.centered-title {text-align: center;}</style>""",unsafe_allow_html=True)
st.markdown("<h1 class='centered-title'>BUKU KATING</h1>", unsafe_allow_html=True)

# bagian sini jangan diubah
def streamlit_menu():
    selected = option_menu(
        menu_title=None,
        options=[
            "Kesekjenan",
            "Baleg",
            "Senator",
            "Departemen PSDA",
            "Departemen MEDKRAF",
            "Departemen MIKFES",
            "Departemen Eksternal",
            "Departemen Internal",
            "Departemen SSD",
        ],
        icons=[
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
            "people-fill",
        ],
        default_index=0,
        orientation="horizontal",
        styles={
            "container": {"padding": "0!important", "background-color": "#fafafa"},
            "icon": {"color": "black", "font-size": "19px"},
            "nav-link": {
                "font-size": "15px",
                "text-align": "left",
                "margin": "0px",
                "--hover-color": "#eee",
            },
            "nav-link-selected": {"background-color": "#3FBAD8"},
        },
    )
    return selected

@st.cache_data
def load_image(url):
    response = requests.get(url)
    if response.status_code != 200:
        st.error(
            f"Failed to fetch image from {url}, status code: {response.status_code}"
        )
        return None
    try:
        img = Image.open(BytesIO(response.content))
        img = ImageOps.exif_transpose(img)
        img = img.resize((300, 400))
        return img
    except Exception as e:
        st.error(f"Error loading image: {e}")
        return None
    
@st.cache_data
def display_images_with_data(gambar_urls, data_list):
    images = []
    for i, url in enumerate(gambar_urls):
        with st.spinner(f"Memuat gambar {i + 1} dari {len(gambar_urls)}"):
            img = load_image(url)
            if img is not None:
                images.append(img)

    for i, img in enumerate(images):
        # Menggunakan Streamlit untuk menampilkan gambar di tengah kolom
        col1, col2, col3 = st.columns([1, 2, 1])
        with col2:
            st.image(img, use_column_width=True)

        if i < len(data_list):
            st.write(f"Nama: {data_list[i]['nama']}")
            st.write(f"NIM: {data_list[i]['nim']}")
            st.write(f"Umur: {data_list[i]['umur']}")
            st.write(f"Asal: {data_list[i]['asal']}")
            st.write(f"Alamat: {data_list[i]['alamat']}")
            st.write(f"Hobbi: {data_list[i]['hobbi']}")
            st.write(f"Sosial Media: {data_list[i]['sosmed']}")
            st.write(f"Kesan: {data_list[i]['kesan']}")
            st.write(f"Pesan: {data_list[i]['pesan']}")
            st.write("  ")
    st.write("Semua gambar telah dimuat!")
menu = streamlit_menu()

# BAGIAN SINI YANG HANYA BOLEH DIUABAH
if menu == "Kesekjenan":
    def kesekjenan():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1m71oaQ6qrHsmVVcQLaAcp_ddBTbPCRPh",
            "https://drive.google.com/uc?export=view&id=17N-KJ0QI59vu60m-nYO1CQ7j9HN1jC-q",
            "https://drive.google.com/uc?export=view&id=1iczTdb3RjMZbBk1JM_AkzU5CFDgKhfvo",
            "https://drive.google.com/uc?export=view&id=1oO2dyyOlKurAlcNWkMFMtXlIZ2MDl_Ql",
            "https://drive.google.com/uc?export=view&id=1tBo0l5pxH4N8o3rNk-Iupet4c12OATy_",
            "https://drive.google.com/uc?export=view&id=1m9B2NWuLI5GvZtR52eA9nG5M7_DAuI2R",
        ]
        data_list = [
            {

                "nama": "Kharisma Gumilang",
                "nim": "121450042",
                "umur": "21",
                "asal": "Palembang",
                "alamat": "Jl.Pulau Damar",
                "hobbi": "Dengerin Musik",
                "sosmed": "@gumilangkharisma",
                "kesan": "Sangat berkharisma menjadi seorang kahim",  
                "pesan": "Semangat buat TA nya bang dan tetap selalu menginspirasi!"# 1
            },
            {   
                "nama": "Pandra Insani Putra Anwar",
                "nim": "121450147",
                "umur": "21",
                "asal":"Lampung Utara",
                "alamat": "Sukarame",
                "hobbi": "Main Gitar",
                "sosmed": "@pandrainsani27",
                "kesan": " Keren bangett",  
                "pesan": "Sukses terus bang dan tetap menjadi panutan untuk hal-hal yang positif"# 1
            },
            {   
                "nama": "Meliza Wulandari",
                "nim": "121450065",
                "umur": "20",
                "asal":"Sumatera Selatan",
                "alamat": "Jl.Pagar Alam",
                "hobbi": "Nonton Drakor",
                "sosmed": "@wulandarimeliza",
                "kesan": "Positif vibes sekali",  
                "pesan": "Tetap jadi ibu sekretaris yang baik dan ramah kak !!!"# 1
            },
        
            {
                "nama": "Putri Maulida Chairani",
                "nim": "121450050",
                "umur": "21",
                "asal":"Sumatera Barat",
                "alamat": "Gg. Nangka 4",
                "hobbi": "Dengerin Bg Pandra Main Gitar",
                "sosmed": "@ptrimaulidaaa_",
                "kesan": "Baik dan lembut",  
                "pesan": "Tetap lemah lembut dan baik hati ya kak "# 1
            },
        
            {   
                "nama": "Hartiti Fadilah",
                "nim": "121450031",
                "umur": "21",
                "asal":"Palembang",
                "alamat": "Pemda",
                "hobbi": "Nyanyi",
                "sosmed": "@htrpdla",
                "kesan": "Cantik, baik",  
                "pesan":"Semangat ngurus cuannya kak"# 1
            },
        
            {
                "nama": "Nadilla Andhara Putri",
                "nim": "121450003",
                "umur": "21",
                "asal":"Lampung",
                "alamat": "Metro",
                "hobbi": "Mainn Bola, Belajar",
                "sosmed": "@nadilaandr26",
                "kesan": "Vibes bendaharanya kerasa bgt",  
                "pesan":"Semangat ngaspraknya kak !"# 1
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    kesekjenan()

elif menu == "Baleg":

    def Baleg():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=1lYdQt1x6JJgiwuoWJ4_8yG5dkuGodeHN",
            "https://drive.google.com/uc?export=view&id=1lK8pyQGNq7JOS8MB48vg-cqePW8kqacn",
            "https://drive.google.com/uc?export=view&id=1l7elwy67iWojIEL8FF_XImZ_TUXJVqVN",
            "https://drive.google.com/uc?export=view&id=1l84n3H3sFCqgQxSZCEctk4l69kkjHMk3",
            "https://drive.google.com/uc?export=view&id=1lwNxaY-VCkSknQ3I2AnJJNWlwYLS7jaE",
            "https://drive.google.com/uc?export=view&id=1lX2Th7taMEw1QMghn7yKEpgRMtw-9yH4",
            "https://drive.google.com/uc?export=view&id=1lPDuW-_ficuzXXYPxTnkaeK5LwsoyM81",
            "https://drive.google.com/uc?export=view&id=1lZzGIEUk-X_VuTQOcQ5byphv0-msPyS7",
            "https://drive.google.com/uc?export=view&id=12zC5u-eqk_LG6PHFqwSwweKn274yfIwc",
            "https://drive.google.com/uc?export=view&id=1lwX1YE9s-nBwLmfujgGoPToe_Nb33V-y",
            "https://drive.google.com/uc?export=view&id=1lHU5--mkZn8vEegIsB9o4U1-YDD2XJBZ",
        ]   
        data_list = [
            {
                "nama": "Tri Murniya Ningsih",
                "nim": "121450038",
                "umur": "21",
                "asal": "Bogor",
                "alamat": "Raden Saleh",
                "hobbi": "Tanya sama GPT",
                "sosmed": "@trimurniaa",
                "kesan": "Kakaknya seru, asik, baik",
                "pesan": "Semangat TA nya kakak, tetap menginspirasi",
            },
            {
                "nama": "Annisa Cahyani Surya",
                "nim": "121450114",
                "umur": "21",
                "asal": "Tangerang Selatan",
                "alamat": "Way Huwi",
                "hobbi": "Puasa Senin Kamis",
                "sosmed": "@annisacahyanisurya",
                "kesan": "Baik banget kakaknya, humble juga",
                "pesan": "Tetap jadi orang baik kak, dan pertahankan ibadahnya!!", 
            },
            {
                "nama": "Wulan Sabina",
                "nim": "121450150",
                "umur": "21",
                "asal": "Medan",
                "alamat": "Raden Saleh",
                "hobbi": "Menonton film",
                "sosmed": "@wlsbn0",
                "kesan": "Kakaknya cantik, baik pula",
                "pesan": "Sukses selalu kak, semangat menjelang semester akhir!", 
            },
            {
                "nama": "Anisa Dini Amalia",
                "nim": "121450021",
                "umur": "20",
                "asal": "Tangerang",
                "alamat": "Jati Agung",
                "hobbi": "Baca Webtoon",
                "sosmed": " @anisadini10",
                "kesan": "Kakaknya ramahh, asik, baik",
                "pesan": "Tetap jadi kakak yang seru dan asik", 
            },
            {
                "nama": "Anisa Fitriyani",
                "nim": "122450019",
                "umur": "20",
                "asal": "Batam",
                "alamat": "Kalianda",
                "hobbi": "Membaca Al waqiah setiap magrib",
                "sosmed": " @ansftynn_",
                "kesan": "Manis banget kakaknya, imut juga",
                "pesan": "Semangat kuliahnya kak, tetap baik hati kak", 
            },
            {
                 "nama": "Feryadi Yulius ",
                "nim": "122450087",
                "umur": "20",
                "asal": "Padang",
                "alamat": "Belwis",
                "hobbi": "Sholat Dhuha",
                "sosmed": "@fer_yulius",
                "kesan": "Abangnya mirip artis band siapa gitu",
                "pesan": "Semangat ngasprak dan tutornya bang, lancar terus!!", 
            },
            {
                "nama": "Renisha Putri Giani",
                "nim": "122450079",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Teluk Betung",
                "hobbi": "Baca Al-Qur'an",
                "sosmed": "@fleurnsh",
                "kesan": "Kakaknya positif vibes sekali",
                "pesan": "MasyaAllah kak pertahankan hobinya",
            },
            {
                "nama": "Claudhia Angeliani",
                "nim": "121450124",
                "umur": "21",
                "asal": "Lampung Timur",
                "alamat": "Lampung Timur",
                "hobbi": "Baca Jurnal",
                "sosmed": "@dylebee",
                "kesan": "Kakaknya cantik dan imut",
                "pesan": "Semangat ya kuliahnya jangan putus asa kak", 
            },
            {
                "nama": "Mirzan Yusuf Rabbani",
                "nim": "122450118",
                "umur": "20",
                "asal": "Jakarta",
                "alamat": "Korpri",
                "hobbi": "Main Kucing",
                "sosmed": "@myrrinn",
                "kesan": "Abangnya baik, kalem, dan ramah",
                "pesan": "Sukses selalu bang!!", 
            },
            {
                "nama": "Muhammad Fachrul Aditya",
                "nim": "121450156",
                "umur": "22",
                "asal": "Surakarta",
                "alamat": "Sukarame",
                "hobbi": "Sholat Malam",
                "sosmed": "@fhrul.pdf",
                "kesan": "Abangnya baik dan pinter",
                "pesan": "Tetap semangat dan pertahankan ibadahnya bang", 
            },
             {
                "nama": "Jeremia Susanto",
                "nim": "122450022",
                "umur": "21",
                "asal": "Palembang",
                "alamat": "Bilabong",
                "hobbi": "Cerita",
                "sosmed": "@jeremia_s_",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat terus ngasparak Alpro RB bang jangan bosan", 
            }, 
            {
                "nama": " Berliana Enda Putri",
                "nim": "122450065",
                "umur": "20",
                "asal": "Sumatera Barat",
                "alamat": "Way Huwi",
                "hobbi": "Baca Buku, Ngoding, Ibadah",
                "sosmed": "@berlyyanda",
                "kesan": "Kakaknya cantik dan ramah",
                "pesan": "Sukses selalu kak, tetap baik dan rendah hati", 
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Baleg()

elif menu == "Senator":
    def senator():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=18qCEntFDBhynfny1zG2W5JK9m5HcHpc3",
            "https://drive.google.com/uc?export=view&id=18qNIh36JFTpTt6D8CaqCMDcy8SELIrJv",
        ]
        data_list = [
            {
                "nama": "Anissa Luthfi Alifia",
                "nim": "121450093",
                "umur": "22",
                "asal": "Lampung Tengah",
                "alamat": "Kost Putri Rahayu",
                "hobbi": "Dengerin bintang nyanyi",
                "sosmed": "@anissalutfi_",
                "kesan": "kakaknya keren dan seru banget",
                "pesan": "Menginspirasi selalu kak, menyala senator HMSD!", 
            },
            {
                "nama": "Rian Bintang Wijaya",
                "nim": "122450094",
                "umur": "20",
                "asal": "Palembang",
                "alamat": "Kota Baru",
                "hobbi": "Nyanyi",
                "sosmed": "@bintangtwinkle",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, sukses selalu!",
            }
        ]
        display_images_with_data(gambar_urls, data_list)
    senator()

elif menu == "Departemen PSDA":
    def Psda():
        gambar_urls = [
            "https://drive.google.com/uc?export=1DAr-hsJ2K99CZU5Q1XxMiPBgaxpeRr6d",
            "https://drive.google.com/uc?export=14xx2lBXafI9pSFN8yxnqfc9L7YwQ4yIX",
            "https://drive.google.com/uc?export=16mEM0MAJMnkkSIMQDWV0Z29siBjbLDNi",
            "https://drive.google.com/uc?export=1qOesv0fB7R3LVVPYR_wcioPAkU7cRxna",
            "https://drive.google.com/uc?export=1-DFdiOyaC1SO0Suaqxnyc9i_Fxr0sCEI",
            "https://drive.google.com/uc?export=1W30OlHDjvsapZrPjvuesOvIhJLTw4I6K",
            "https://drive.google.com/uc?export=1HCmjoZwOBwQoU45hHIO402gfY43LaLHQ",
            "https://drive.google.com/uc?export=1vLkKhoNWsC_8YZOn1rk6RJqQ6JYZAmBL",
            "https://drive.google.com/uc?export=1teyA8p6UEKS6aeAImDCRgPYCDo196ko7",
            "https://drive.google.com/uc?export=1wRv2xsD1WVYVpNTryCms99KbipFbg3r_",
            "https://drive.google.com/uc?export=1VNm9HKZrkvNC3q7-CTWea3g5tlrUa0Zs",
            "https://drive.google.com/uc?export=1t1mL8S1uAIDwcZ67LVwZKHY90dJwtB4T",
            "https://drive.google.com/uc?export=14MvWDb840tCrebilzNBdT4WMGs3WH5xl",
            "https://drive.google.com/uc?export=1qqpqJa468CYzS7w9nYGA7y_PtcSUlOeZ",
            "https://drive.google.com/uc?export=1ZtZ_KVqtknHinsDzJUo6VM-4PgDhDvV4",
            "https://drive.google.com/uc?export=1yUVP5p15n8osNFrLkfvkWJRO5q974LZr",
            "https://drive.google.com/uc?export=1FXfY0GHdMv8YIzkHH8c6q_oNV11NHOw_",
            "https://drive.google.com/uc?export=1Z3CeGz3fngJ9ke7IfiRPUYzJgn_xrQem",
            "https://drive.google.com/uc?export=189BkgQ-UEfxOq6KCiWEl1k9brkRcsB0l",
            "https://drive.google.com/uc?export=1X5ShFpynBupwraMpS51VTMw9qC8OQfPB",
        ]
        data_list = [
            {
                "nama": "Ericson Chandra Sihombing",
                "nim": "121450026",
                "umur": "21",
                "asal": "Bekasi",
                "alamat": "Khobam",
                "hobbi": "Travelling",
                "sosmed": "@ericsonchandr99",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat TA nya bang, sukses selalu!!", 
            },
            {
                "nama": "Elisabeth Claudia Simanjuntak",
                "nim": "122450123",
                "umur": "20",
                "asal": "Tanggerang",
                "alamat": "Owen Kost",
                "hobbi": "Bernafas",
                "sosmed": "",
                "kesan": "",
                "pesan": "Semangat kuliahnya kak, jangan putus asa",
            },
            {
                "nama": "Nisrina Nur Afifah",
                "nim": "122450052",
                "umur": "19",
                "asal": "Bekasi",
                "alamat": "Sukarame",
                "hobbi": "Menonton",
                "sosmed": "@afifahhnsnr",
                "kesan": "Kakaknya baik dan cantik banget",
                "pesan": "Semangat kuliahnya kak, jangan lupa tidur kak",
            },
            {
                "nama": "Ferdy Kevin Naibaho",
                "nim": "1224500107",
                "umur": "19",
                "asal": "Medan",
                "alamat": "Jl. Pangeran Senopati Raya ",
                "hobbi": "Review jurnal",
                "sosmed": "@ferdy_kevin",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang, jangan lupa belajar tiap hari",
            },
            {
                "nama": "Farahanum Afifah Ardiansyah",
                "nim": "122450056",
                "umur": "20",
                "asal": "Padang",
                "alamat": "Gya Kost",
                "hobbi": "Tidur",
                "sosmed": "@farahanumafifah",
                "kesan": " Kakaknya baik bangett",
                "pesan": "Semangat terus kuliahnya kak, jangan lupa makan",
            },
            {
                "nama": "Oktavia Nurwendah Puspitasari",
                "nim": "122450041",
                "umur": "20",
                "asal": "Lampung Timur",
                "alamat": "Way Hui",
                "hobbi": "Masak",
                "sosmed": "@_oktavianrwndh",
                "kesan": "Kakaknya asik banget",
                "pesan": "Semangat kuliahnya kak, semoga nilainya A",
            },
            {
                "nama": "Allya Nurul Islami Pasha",
                "nim": "122450033",
                "umur": "20",
                "asal": "Sumatera Barat",
                "alamat": "Gg. Perwira Belwis",
                "hobbi": "Keliling Lampung",
                "sosmed": "@allyaislami_",
                "kesan": "Kakaknya keren banget",
                "pesan": "Semangat kuliahnya kak, jangan lupa belajar dan ibadahnya tiap hari kak",
            },
            {
                "nama": "Ekshanty Febriana Sukma Iksamiati",
                "nim": "122450001",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Rajabasa",
                "hobbi": "Ngumpulin tugas kurang dari 55 detik",
                "sosmed": "@ekshantyfebriana",
                "kesan": "Kakaknya asik banget",
                "pesan": "Semangat kuliahnya dan juga ngaspraknya kak",
            },
            {
                "nama": "Farahanum Afifah Ardiansyah",
                "nim": "122450056",
                "umur": "20",
                "asal":"Padang",
                "alamat": "Sukarame",
                "hobbi": "Minum Kopi",
                "sosmed": "@farahanumafifahh",
                "kesan": "kakanyanya cantik dan baik",  
                "pesan":"semangat terus kuliahnya kak, kereeen terus",
            },
            {
                "nama": "Ferdy Kevin Naibaho",
                "nim": "122450107",
                "umur": "20",
                "asal":"Medan",
                "alamat": "Senopati Raya",
                "hobbi": "Dengerin Musik",
                "sosmed": "@ferdy_kevin",
                "kesan": "Abangnya baik dan seruuu",  
                "pesan":"semangat kuliahnya bang, dan sukses teruss",
            },
            {
                "nama": "M. Deriansyah Okutra",
                "nim": "122450101",
                "umur": "19",
                "asal":"Kayu Agung",
                "alamat": "Jl. Pagar Alam Kedaton",
                "hobbi": "Nongki-nongki",
                "sosmed": "@dransyh_",
                "kesan": "Abangnya baik dan asik",  
                "pesan":"Semangat terus kuliahnya bang dan sukses terus",
            },
            {
                "nama": "Oktavia Nurwenda Puspita Sari",
                "nim": "122450041",
                "umur": "20",
                "asal":"Lampung Timur",
                "alamat": "Way Huwi",
                "hobbi": "Scroll tik-tok",
                "sosmed": "@oktavianrwnda",
                "kesan": "Kakaknya manis banget",  
                "pesan":"Semangat terus Kak kuliahnya",
            },
            { 
                "nama": " Deyvan Loxefal", 
                "nim": " 121450148 ", 
                "umur":  "21", 
                "asal":" Duri Riau  ", 
                "alamat": "Khobam Pulau Damar", 
                "hobbi": "Belajar", 
                "sosmed": "@depanlo", 
                "kesan": "Abangnya keren asik dan seruu",   
                "pesan":"Sukses terus bang",
            },
            { 
                "nama": " Ibnu Farhan Al-Ghifari", 
                "nim": " 121450121 ", 
                "umur":  "21", 
                "asal":" Kerinci Jambi  ", 
                "alamat": "Khobam", 
                "hobbi": "game online", 
                "sosmed": "@al_ghifari032", 
                "kesan": "Abangnya baik dan keren",   
                "pesan":"Semangat kuliahnya bangg sukses terus",
            },
            { 
                "nama": "Johannes Krisjon Silitonga", 
                "nim": "122450043", 
                "umur": "19", 
                "asal":"Tangerang", 
                "alamat": "Jl. Lapas", 
                "hobbi": "Ngasprak", 
                "sosmed": "@johanneskrisjon", 
                "kesan": "Kakaknya asik, baik, keren dan seru.",   
                "pesan":"Keren terus bang, sukses selalu", 
            },
            { 
                "nama": "Kemas Veriandra Ramadhan", 
                "nim": "122450016", 
                "umur": "19", 
                "asal":"Bekasi", 
                "alamat": "Kojo Golf UIN", 
                "hobbi": "Main game", 
                "sosmed": "@kemasverii", 
                "kesan": "pinter banget dan baik",   
                "pesan":"Keren terus bang", 
            },
            { 
                "nama": "Leonard Andreas Napitupulu", 
                "nim": "121450153", 
                "umur": "21", 
                "asal":"Medan", 
                "alamat": "Khobam", 
                "hobbi": "belajar", 
                "sosmed": "@lndr.", 
                "kesan": "Abangnya baik",   
                "pesan":"ssemangat dan sukses terus bang", 
            },
            { 
                "nama": "Presilia", 
                "nim": "122450081", 
                "umur": "20", 
                "asal":"Bekasi", 
                "alamat": "Kota Baru", 
                "hobbi": "Dengerin lomba sihir", 
                "sosmed": "@presiliamy", 
                "kesan": "Kakaknya cantik",   
                "pesan":"Semangat terus kak kuliahnya kereen terus", 
            },
            { 
                "nama": "Sahid Maulana", 
                "nim": "122450109", 
                "umur": "21", 
                "asal":"Depok, Jabar", 
                "alamat": "Jl. Airan Raya", 
                "hobbi": "Dengerin musik", 
                "sosmed": "@sahid_maul19", 
                "kesan": "Bang Sahid baik bangeet, soft spoken dan keren",   
                "pesan":"Kereen terus bang, terus jadi orang baik ya bang", 
            },
            {
                "nama": "M. Farhan Athaulloh",
                "nim": "121450117",
                "umur": "21",
                "asal":"Lampung",
                "alamat": "Kota Baru",
                "hobbi": "Menolong",
                "sosmed": "@mfarhan.ath",
                "kesan": "Abangnya baik dan ramah juga kereen",  
                "pesan":"Keren terus bang, sukses terus ",
            },
            {
                "nama": "Gede Moana",
                "nim": "121450014",
                "umur": "21",
                "asal":"Bekasi",
                "alamat": "Korpri Raya",
                "hobbi": "Belajar, game, baca komik",
                "sosmed": "@gedemoenaa",
                "kesan": "abangnya asik dan seru.",  
                "pesan":"Sukses terus bang",
            },
            {
                "nama": "Jaclin Alcavella",
                "nim": "122450015",
                "umur": "19",
                "asal":"Sumatera Selatan",
                "alamat": "Korpri",
                "hobbi": "Berenang",
                "sosmed": "@jaclinalcv_",
                "kesan": "kakak asik, manis dan baik banget ",  
                "pesan":"Semangat kuliahnya kak, sukses terus",
            },
            {
                "nama": "Syalaisha Andini Putriansyah",
                "nim": "122450111",
                "umur": "21",
                "asal":"Tangerang",
                "alamat": "Sukarame",
                "hobbi": "Baca",
                "sosmed": "@syalaisha.i__",
                "kesan": "kakaknya manis banget",  
                "pesan":"Semangat terus kuliahnya kak",
            }
        ]
        display_images_with_data(gambar_urls, data_list)
    Psda()

elif menu == "Departemen MEDKRAF":

    def Medkraf():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
        ]
        data_list = [
            {
                "nama": "Wahyudiyanto",
                "nim": "121450040",
                "umur": "22",
                "asal": "Makassar",
                "alamat": "Sukarame",
                "hobbi": "Nonton",
                "sosmed": "wayylaja",
                "kesan": "Abangnya keren banget",
                "pesan": "Semangat kuliahnya bang",
            },
            {
                "nama": "Elok Fiola",
                "nim": "122450051",
                "umur": "19",
                "asal": "Bandar Lampung",
                "alamat": "Bandar Lampung",
                "hobbi": "Editing",
                "sosmed": "@elokfiola",
                "kesan": "Manis bangett kakk",
                "pesan": "Semangat ya kak, tetap ramah", 
            },
            {
                "nama": "Muhammad Kaisar Firdaus ",
                "nim": " 121450135",
                "umur": "21",
                "asal": "Pesawaran",
                "alamat": "Pulau Damar",
                "hobbi": "Lagi Nyari",
                "sosmed": " @dino_kiper",
                "kesan": "Sangat menyenangkan dan bermanfaat",
                "pesan": "Semangat fotonya bang", 
            },
            {
                "nama": "Muhammad Arsal Ranjana Putra",
                "nim": "121450111",
                "umur": "21",
                "asal": "Depok",
                "alamat": "Nangka 4",
                "hobbi": "Ngoding",
                "sosmed": "@arsal.utama",
                "kesan": "terimakasih atas insightnya bang",
                "pesan": "Semangat desainnya bang", 
            },
            {
                "nama": "Cintya  Bella",
                "nim": "122450066",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Teluk",
                "hobbi": "Ngegym",
                "sosmed": "@cintyabella28",
                "kesan": "Suka banget sama outfit kakak, cocok banget di divisi media & konten",
                "pesan": "semangat kuliahnya kakk", 
            },
            {
                "nama": "Eka Fidiya Putri",
                "nim": " 122450045",
                "umur": "20",
                "asal": "Natar, Lampung Selatan",
                "alamat": "Natar, Lampung Selatan",
                "hobbi": "Menyibukkan Diri",
                "sosmed": "@ekafdyaptri",
                "kesan": "senang bisa belajar dari kakak",
                "pesan": "Sampai ketemu lagi di kampus ya,kak", 
            },
            {
                "nama": "Patricia Leondra Diajeng Putri ",
                "nim": "122450050",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Jatimulyo",
                "hobbi": "Nonton Film",
                "sosmed": "@patriciadiajeng",
                "kesan": "kakaknya cantik banget",
                "pesan": "Makasih ya kak, sudah mau berbagi ilmu", 
            },
            {
                "nama": "Rahma Neliyana",
                "nim": "122450036",
                "umur": "20",
                "asal": "Lampung",
                "alamat": "Sukarame",
                "hobbi": "Baca Coding",
                "sosmed": "@rahmanellyana",
                "kesan": "Terimakasih sharing ilmunya kak",
                "pesan": "Semangat kuliahnya kak", 
            },
            {
                "nama": "Try Yani Rizki Nur Rohmah ",
                "nim": "122450020",
                "umur": "20",
                "asal": "Lampung Barat",
                "alamat": "Korpri",
                "hobbi": "Bernyanyi dan Menonton",
                "sosmed": "@tryyaniciaaa",
                "kesan": "Terimakasih atas insightnya kak",
                "pesan": "semangat kuliahnya kak", 
            },
            {
                "nama": "Gymnastiar Al Khoarizmy",
                "nim": "122450096",
                "umur": "20",
                "asal": "Serang",
                "alamat": "Lapangan Golf UIN",
                "hobbi": "Baca Komik",
                "sosmed": "@jimnn.as",
                "kesan": "Senang bisa belajar dari abang",
                "pesan": "Semangat kuliahnya bang", 
            },
            {
                "nama": "Nasywa Nur Afifah ",
                "nim": "122450125",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Jalan Durian 1 Pemda",
                "hobbi": "Nonton Drakor",
                "sosmed": "@nsywanaf",
                "kesan": "Wawancaranya sangat menginspirasi",
                "pesan": "semangat kuliahnya kak", 
            },
            {
                "nama": "Abit Ahmad Oktarian",
                "nim": "122450042",
                "umur": "19",
                "asal": "Bandar Lampung",
                "alamat": "Rajabasa, Labuhan Dalam",
                "hobbi": "Ngoding, Gaming",
                "sosmed": "@abitahmad",
                "kesan": "Terimakasih bang, saya belajar banyak",
                "pesan": "semangat kuliahnya bang", 
            },
             {
                "nama": "Akmal Faiz Abdillah",
                "nim": "122450114",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Perumahan Griya Sukarame",
                "hobbi": "Main HP",
                "sosmed": "@_akmal.faiz",
                "kesan": "abangnya ramah banget",
                "pesan": "semangat ngaspraknya bang", 
            },
             {
                "nama": "Hermawan Manurung ",
                "nim": "122450069",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Dekat Jalan Tol (Wisma Hana Hani) ",
                "hobbi": "Bengong/Membaca Buku",
                "sosmed": "@hermawan.mnrng",
                "kesan": "Lucu banget bang",
                "pesan": "semangat kuliahnya bang", 
            },
             {
                "nama": "Khusnun Nisa",
                "nim": "122450078",
                "umur": "20",
                "asal": "Lampung Selatan",
                "alamat": "Jati Agung",
                "hobbi": "Mengerjakan Tugas",
                "sosmed": "@khusnun_nisa335",
                "kesan": "Sharing ilmunya keren banget kak",
                "pesan": "Semangat kuliahnya kak", 
            },
             {
                "nama": "Priska Silvia Ferantiana",
                "nim": "122450053",
                "umur": "20",
                "asal": "Palembang",
                "alamat": "Jalan Nangka 2",
                "hobbi": "Baca Novel yang Bikin Nangis",
                "sosmed": "@prskslv",
                "kesan": "kakaknya ramah banget",
                "pesan": "Semangat kuliahnya kak", 
            },
            {
                "nama": "Arsyiah Azahra",
                "nim": "121450035",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Tanjung Senang",
                "hobbi": "Nugas",
                "sosmed": "@arsyiah._",
                "kesan": "Senang bisa belajar dari kakak",
                "pesan": "Semangat kuliahnya kak", 
            },
             {
                "nama": "Najla Juwairia",
                "nim": "122450037",
                "umur": "19",
                "asal": "Sumatra Utara",
                "alamat": "Airan",
                "hobbi": "Menulis, Membaca, fangirling",
                "sosmed": "@nanana_minjoo",
                "kesan": "kakak keren banget",
                "pesan": "terimakasih atas sharing nya", 
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Medkraf()

elif menu == "Departemen MIKFES":

    def Mikfes():
        gambar_urls = [

            "https://drive.google.com/uc?export=view&id=1jhFExK6OkhZULi3ANrAM6fY1ImZTvE7d",
            "https://drive.google.com/uc?export=view&id=1-dtqpqKZ4P9fldHH18RGyhV6MxJJZVCQ",
            "https://drive.google.com/uc?export=view&id=1_9wEg2Rzrshyr-ooFQXCrqOkGCGuLOBO",
            "https://drive.google.com/uc?export=view&id=1-ICz3-tQM0i4Hn9AH2n6zHN29ti0IuR0",
            "https://drive.google.com/uc?export=view&id=1hstiF5mjewDvrIjpzmyNhvB1d6aMpd7j",
            "https://drive.google.com/uc?export=view&id=1YzLZi-VfJCdRCMhgV2dD3AXOXnJFqRSc",
            "https://drive.google.com/uc?export=view&id=1xK5eDMQ5dgh4q826aMSwa4GfDb6tyUUI",
            "https://drive.google.com/uc?export=view&id=1JhjfPjpi6nMzbMAcxpGiuBXAkKqqdf6c",
            "https://drive.google.com/uc?export=view&id=1McV_bo1H31D76m_xiy-D-ZBeFJzLHKBt",
            "https://drive.google.com/uc?export=view&id=181RvSwNLs0FaSc0_xYNvQKo-UYzjgenh",
            "https://drive.google.com/uc?export=view&id=1q1UmVLE2KQmntZFNes7bmoO3sXCBBxTL",
            "https://drive.google.com/uc?export=view&id=1m-d0axSNmjceeQ4qh2SyB2CX2GLjpTO-",
            "https://drive.google.com/uc?export=view&id=1Tnkr0ANk8vpD0Zosxhv27z7uCbfFouwQ",
            "https://drive.google.com/uc?export=view&id=1rmiSD1WzvnZBfHeXkUJD9958Nhu32PKw",
            "https://drive.google.com/uc?export=view&id=12_grbAWXQKHZJFs8PbtMMohMfU38Bxks",
            "https://drive.google.com/uc?export=view&id=1pW3rJg5Qi7IgidkFmZVgoHB0mnts8oIl",
            "https://drive.google.com/uc?export=view&id=1z-D-P7z3u1rVZOew-1n3ly-A3jzgY-rJ",
            "https://drive.google.com/uc?export=view&id=1XojmH1Slzx1t4hd0vzHk0yI_essiXslg",
            "https://drive.google.com/uc?export=view&id=1scTCuP1n8FhtYxWQHMShhDYvYGEaIJ0r",

        ] 
        data_list = [
            {
                "nama": "Rafi Fadhlillah",
                "nim": "121450143",
                "umur": "21 Tahun",
                "asal": "Lubuk Linggau",
                "alamat": "Jl. Nangka 4",
                "hobbi": "Olahraga",
                "sosmed": "@rafadhilillahh13",
                "kesan": "Keren banget bang, berkharisma",
                "pesan": "Semangat terus kuliahnya bang, jangan lupa makan",
            },
            {

                "nama": "Annisa Novantika",
                "nim": "121450005",
                "umur": "21 Tahun",
                "asal": "Lampung Utara",
                "alamat": "Jl. Pulau Sebesi, Sukarame",
                "hobbi": " Memasak",
                "sosmed": "@anovavona",
                "kesan": "Kakaknya ramah dan lembut banget",
                "pesan": "Semangat terus kuliahnya kak, jangan lupa tidur",
            },
            {

                "nama": " Ahmad Sahidin Akbar",
                "nim": "122450044",
                "umur": " 20",
                "asal": "Tulang Bawang",
                "alamat": " Sukarame",
                "hobbi": "Olahraga",
                "sosmed": "@sahid22__",
                "kesan": "Keren banget bang",
                "pesan": "Semangat terus kuliahnya bang, jangan lupa bahagia",
            },
            {
                "nama": "Fadhil Fitra Wijaya",
                "nim": "122450082",
                "umur": "20 Tahun",
                "asal": "Bekasi",
                "alamat": "Teluk Betung ",
                "hobbi": "Main Game",
                "sosmed": "@fadhilfwee",
                "kesan": "Asik banget abangnya",
                "pesan": "Semangat terus kuliahnya bang, jangan lupa main",
            },
            {
                "nama": "Muhammad Regi Abdi Putra Amanta",
                "nim": " 122450031",
                "umur": "19 Tahun",
                "asal": "Palembang",
                "alamat": "Jl. Permadi Sukarame  ",
                "hobbi": "Main Game",
                "sosmed": "@mregiiii_",
                "kesan": "Keren banget abang Duta Genre",
                "pesan": "Semangat terus kuliahnya bang, jangan lupa istirahat",
            },
            {
                "nama": "Syalaisha Andina Putriansyah",
                "nim": "122450121",
                "umur": "21 Tahun",
                "asal": "Tangerang",
                "alamat": "Gg Yudhistira ",
                "hobbi": "Baca Novel",
                "sosmed": "@dkselsd_31",
                "kesan": "Lucu banget kakaknya ada kembaran",
                "pesan": "Semangat terus kuliahnya kak, jangan mudah menyerah",
            },
            {
                "nama": "Natanael Oktavianus Partahan Sihombing ",
                "nim": "121450107",
                "umur": "20 Tahun",
                "asal": "Jakarta",
                "alamat": "Kemiling ",
                "hobbi": "Membuka Wisata HMSD",
                "sosmed": "@natanaeloks",
                "kesan": "Abangnya keren dan pinter",
                "pesan": "Semangat terus kuliahnya bang, jangan lupa ibadah",
            },
            {
                "nama": "Anwar Muslim",
                "nim": "122450117",
                "umur": "21 Tahun",
                "asal": "Bukittinggi",
                "alamat": "Korpri ",
                "hobbi": " ML (Machine Learning)",
                "sosmed": "@here.am.ai",
                "kesan": "Abangnya seru abis",
                "pesan": "Semangat terus kuliahnya bang, jangan lupa makan",
            },
            {
                "nama": "Deva Anjani Khayyuninafsyah",
                "nim": "122450014",
                "umur": "21 Tahun",
                "asal": " Bandar Lampung",
                "alamat": "Kemiling",
                "hobbi": "Menonton Film",
                "sosmed": "@anjaniiidev",
                "kesan": "Cantik dan ramah kakaknya",
                "pesan": "Semangat terus kuliahnya kak, jangan lupa istirahat",
            },
            {
                "nama": "Dinda Nababan",
                "nim": "122450120",
                "umur": "20 Tahun",
                "asal": "Medan",
                "alamat": "Jl. Lapas",
                "hobbi": "Main Game",
                "sosmed": "@dindanababan_",
                "kesan": "Kakaknya baik bangett",
                "pesan": "Semangat ngaspraknya kakk",
            },
            {
                "nama": "Marleta Cornelia Leander",
                "nim": "122450092",
                "umur": "20 Tahun",
                "asal": "Depok, Jawa Barat",
                "alamat": "Gg. Nangka 3",
                "hobbi": "Liatin Jurnal",
                "sosmed": "@marletacornelia",
                "kesan": "Kakaknya cantik dan manis",
                "pesan": "Semangat terus kuliahnya kak, jangan lupa main",
            },
            {
                "nama": "Rut Junita Sari Siburian",
                "nim": "122450103",
                "umur": "20 Tahun",
                "asal": "Batam, Kep.Riau",
                "alamat": "Gg. Nangka 3",
                "hobbi": "Resume Jurnal",
                "sosmed": "@junitaa_0406",
                "kesan": "Kakaknya baik bangett",
                "pesan": "Semangat terus kuliahnya kak, jangan lupa ibadah",
            },
            {
                "nama": "Syadza Puspadari Azhar",
                "nim": " 122450072",
                "umur": "20 Tahun",
                "asal": "Palembang",
                "alamat": "Belwis ",
                "hobbi": "Membaca",
                "sosmed": "@puspadrr",
                "kesan": "Cantik, baik, pengertian, penyayang",
                "pesan": "Semangat terus kuliahnya kak, tetap baik dan rendah hati",
            },
            {
                "nama": " Abdurrahman Al-atsary",
                "nim": "121450128",
                "umur": "23 Tahun",
                "asal": "Bandar Lampung",
                "alamat": "Perumnas Way Kandis",
                "hobbi": " Membaca",
                "sosmed": "@rahmn_abdr",
                "kesan": "Keren banget abangnyaa",
                "pesan": "Semangat terus kuliahnya bang, jangan mudah nyerah",
            },
            {
                "nama": "Aditya Rahman",
                "nim": "122450113",
                "umur": "20 Tahun",
                "asal": " Lampung Timur",
                "alamat": "Korpri",
                "hobbi": "Ngoding WISATA",
                "sosmed": "@rahm_adityaa",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Eggi Satria",
                "nim": "122450032",
                "umur": "20 Tahun",
                "asal": "Sukabumi",
                "alamat": "Korpri",
                "hobbi": "Ngoding dan buat konten WISATA",
                "sosmed": "@egistr ",
                "kesan": "Abangnya berkharisma",
                "pesan": "Semangat terus kuliahnya bang",
            },
            {
                "nama": "Febiya Jomy Pratiwi",
                "nim": "122450074",
                "umur": "20 Tahun",
                "asal": "Tulang Bawang",
                "alamat": "Jl Kelengkeng Raya",
                "hobbi": "Nonton K-Drama ",
                "sosmed": "@pratiwifebiya",
                "kesan": "Kakaknya asik banget",
                "pesan": "Semangat terus kuliahnya kak, jangan lupa maakan",
            },
            {
                "nama": "Happy Syahrul Ramadhan",
                "nim": "122450013",
                "umur": "20 Tahun",
                "asal": "Lampung",
                "alamat": "Karang Anyar ",
                "hobbi": " Main Game",
                "sosmed": "@sudo.syahrulramadhannn",
                "kesan": "Abangnya seru abiss",
                "pesan": "Semangat terus kuliahnya bang!!",
            },
            {
                "nama": "Randa Andriana Putra",
                "nim": "122450083",
                "umur": "21 Tahun",
                "asal": "Banten",
                "alamat": " Sukarame",
                "hobbi": " Tidur dan Berkembang",
                "sosmed": "@randaandriana_",
                "kesan": "Abangnya pinter bangett",
                "pesan": "Semangat terus kuliahnya bang, janga lupa belajar tiap hari",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Mikfes()

elif menu == "Departemen Eksternal":
    def Eksternal():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
        ]
        data_list = [
            {
                "nama": "Yogy Sea Tama",
                "nim": "121450041",
                "umur": "21",
                "asal": "Tangerang",
                "alamat": "Jatimulyo",
                "hobbi": "Ngisi Bensin",
                "sosmed": "@yogyyyyyyy",
                "kesan": "-",
                "pesan": "-", 
            },
            {
                "nama": "Ramadhita Asifa Hendri",
                "nim": "121450131",
                "umur": "21",
                "asal": "Rajabasa",
                "alamat": "Rajabasa",
                "hobbi": "Belajar",
                "sosmed": "@Ramadhitaasifa",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Nazwa Nabilla",
                "nim": "121450112",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Way Kandis",
                "hobbi": "Belajar dengan Rajin",
                "sosmed": "@nazwanbilla",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Dea Mutia Risani",
                "nim": "122450099",
                "umur": "20",
                "asal": "Sumatera Barat",
                "alamat": "Korpri",
                "hobbi": "Bikin Surat",
                "sosmed": "@deaa.rsn",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Novelia Adinda",
                "nim": "122450104",
                "umur": "21",
                "asal": "Jakarta",
                "alamat": "Belwis",
                "hobbi": "Tidur",
                "sosmed": "@nvliadinda",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Ratu Keisha Jasmin Deonova",
                "nim": "122450106",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Way Kandis",
                "hobbi": "Ngerjain ADW",
                "sosmed": "@jasminednva",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Tobias David Monogari",
                "nim": "121450081",
                "umur": "20",
                "asal": "Jakarta Barat",
                "alamat": "Pemda",
                "hobbi": "Bikin Puisi",
                "sosmed": "@tobiassiagian",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Rizki Adrian Bennovry",
                "nim": "121450073",
                "umur": "21",
                "asal": "Bekasi",
                "alamat": "TVRI",
                "hobbi": "Buat Portopolio",
                "sosmed": "@rzkdrnnn",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Arafi Ramadhan Maulana",
                "nim": "12245022",
                "umur": "20",
                "asal": "Jogja, Depok",
                "alamat": "Way Huwi",
                "hobbi": "menghafal al-quran",
                "sosmed": "@arafiramadhanmaulana",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Asa Do'a Uyi",
                "nim": "122450005",
                "umur": "20",
                "asal": "Muara",
                "alamat": "Korpri",
                "hobbi": "cuci baju",
                "sosmed": "@u_yippy",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Chalifia Wananda",
                "nim": "122450076",
                "umur": "20",
                "asal": "Padang",
                "alamat": "sukarame",
                "hobbi": "Quality Time",
                "sosmed": "@chipawww",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Irvan Alfaritzi",
                "nim": "122450093",
                "umur": "21",
                "asal": "Sumatera Barat",
                "alamat": "Jakarta",
                "hobbi": "Nonton Youtube dan main ML",
                "sosmed": "@Alfaritziirfan",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Izza Lutfia",
                "nim": "122450090",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Teluk",
                "hobbi": "main vollly",
                "sosmed": "@izzalutfiaa",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Khaalishah Zuhrah ALyaa Valefi",
                "nim": "122450034",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Rajabasa",
                "hobbi": "Nyanyi",
                "sosmed": "@alyaavalefi",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Raid Muhammad Naufal",
                "nim": "122450027",
                "umur": "20",
                "asal": "Lampung Tengah",
                "alamat": "Sukarame",
                "hobbi": "Ngeresume Seminar",
                "sosmed": "@rayHis_",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Tria Yunanni",
                "nim": "122450062",
                "umur": "20",
                "asal": "Way Kanan",
                "alamat": "Jakarta",
                "hobbi": "Baca",
                "sosmed": "@tria_y062",
                "kesan": "-",
                "pesan": "-",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Eksternal()
elif menu == "Departemen Internal":
    def Internal():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
        ]
        data_list = [
            {

                "nama": "Dimas rizky ramadhani",
                "nim": "121450027",
                "umur": "20",
                "asal": "Pamulang",
                "alamat": "Way kandis",
                "hobbi": "Manjat tower sutet",
                "sosmed": "@dimzrky",
                "kesan": "Berkharisma banget",
                "pesan": "Semangat nyusun TA nya bang dimas", 
            },
            {
                "nama": "Catherine firdhasari maulina sinaga",
                "nim": "121450072",
                "umur": "20",
                "asal": "Sumatera Utara",
                "alamat": "Airan",
                "hobbi": "Baca novel",
                "sosmed": "@chatherine.sinaga",
                "kesan": "kakanya ramah bintang 100",
                "pesan": "Semangat berproses kak",
            },    
            {
                "nama": "M. Akbar resdika",
                "nim": "121450066",
                "umur": "20",
                "asal": "Lampung Barat",
                "alamat": "Labuhan dalam",
                "hobbi": "Memelihara dino",
                "sosmed": "@akbar_resdika",
                "kesan": "Kelihatannya baik (emot senyum)",
                "pesan": "Semangat nyusun TA bang",
            },
            {
                "nama": "Rani puspita sari",
                "nim": "122450030",
                "umur": "20",
                "asal": "Metro",
                "alamat": "Rajabasa",
                "hobbi": "Mengaji",
                "sosmed": "@ranipu",

                "kesan": "Kakak baik",
                "pesan": "Selalu bermanfaat untuk orang sekitar ya kak",
            },
            {
                "nama": "Rendra eka prayoga",
                "nim": "122450112",
                "umur": "20",
                "asal": "Bekasi",
                "alamat": "Jalan lapas raya",
                "hobbi": "nulis lagu",
                "sosmed": "@rendraepr",

                "kesan": "Ramah bintang 1000",
                "pesan": "Semoga jadi pribadi yang lebih baik lagi ",
            },
            {
                "nama": "Salwa farhanatussaidah",
                "nim": "122450055",
                "umur": "20",
                "asal": "Pesawaran",
                "alamat": "Airan raya",
                "hobbi": "ngeliat cogan",
                "sosmed": "@slwfhn_694",

                "kesan": "Cantik bangett",
                "pesan": "semangat kuliahnya kak",
            },
            {
                "nama": "Ari sigit",
                "nim": "121450069",
                "umur": "23",
                "asal": "Lampung barat",
                "alamat": "Labuhan ratu",
                "hobbi": "Main futsal",
                "sosmed": "@ari_sigit17",
                "kesan": "keren banget abangnya",
                "pesan": "semangat kuliahnya bang ari",
            },
            {
                "nama": "Azizah kusumah putri",
                "nim": "122450068",
                "umur": "21",
                "asal": "Lampung Selatan",
                "alamat": "Natar",
                "hobbi": "berkebun",
                "sosmed": "@azizahksmh15",
                "kesan": "Ramah bangett",
                "pesan": "Semangkaaa semangat kakak!!!",
            },
            {
                "nama": "Meira listyaningrum",
                "nim": "122450011",
                "umur": "20",
                "asal": "Pesawaran",
                "alamat": "Airan raya",
                "hobbi": "Menghalu",
                "sosmed": "@meiraln",
                "kesan": "Baik bangett",
                "pesan": "Semangat kakk!!!",
            },
            {
                "nama": "Rendi alexander hutagalung",
                "nim": "122450057",
                "umur": "20",
                "asal": "Tangerang",
                "alamat": "Kost gunawan",
                "hobbi": "Menyanyi",
                "sosmed": "@alexanderr",
                "kesan": "Baik bangett",
                "pesan": "jangan pentang menyerah,selalu berusaha",
            },
            {
                "nama": "Renta siahaan",
                "nim": "122450070",
                "umur": "21",
                "asal": "Sumatera utara",
                "alamat": "Gerbang barat",
                "hobbi": "Memancing",
                "sosmed": "@renta.shn",
                "kesan": "Keren banget",
                "pesan": "selalu semangat kakak ",
            },
            {
                "nama": "Yosia lehare banurea",
                "nim": "121450149",
                "umur": "20",
                "asal": "Dairi, Sumatera utara",
                "alamat": "Perum griya indah",
                "hobbi": "Bawa motor pakai kaki",
                "sosmed": "@yosiabanurea",
                "kesan": "Baik bangett",
                "pesan": "semangat kakak!!!",
            },
            {
                "nama": "Josua panggabean",
                "nim": "121450061",
                "umur": "21",
                "asal": "Pematang siantar",
                "alamat": "Gya kost",
                "hobbi": "Ngawinin cupang",
                "sosmed": "@josuapanggabean16_",
                "kesan": "sangat soft spoken",
                "pesan": "semangat kuliah bang",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Internal()
elif menu == "Departemen SSD":
    def Ssd():
        gambar_urls = [
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
            "https://drive.google.com/uc?export=view&id=",
        ]
        data_list = [
            {
                "nama": "Andrian Agustinus Lumban Gaol",
                "nim": "121450090",
                "umur": "17 +",
                "asal": "Sidikalang",
                "alamat": "Lapas",
                "hobbi": "Nyari Hobi",
                "sosmed": "@andrialgaol",
                "kesan": "-",
                "pesan": "-", 
            },
            {
                "nama": "Adisty Syawaida Ariyanto",
                "nim": "121450136",
                "umur": "21",
                "asal": "Metro",
                "alamat": "Metro",
                "hobbi": "Nonton film",
                "sosmed": "@adistisa_",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Nabila Azhari",
                "nim": "121450029",
                "umur": "21",
                "asal": "Simalungun",
                "alamat": "Airan",
                "hobbi": "Menghitung",
                "sosmed": "@zhjung",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Danang Hilal Kurniawan",
                "nim": "122450085",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "TB 3 Asrama",
                "hobbi": "Belajar",
                "sosmed": "@dananghk_",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Farel Julio Akbar",
                "nim": "122450110",
                "umur": "20",
                "asal": "Bogor",
                "alamat": "Jalan Lapas",
                "hobbi": "Bebas",
                "sosmed": "@farel__julio",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Nabilah Andika Fitriani",
                "nim": "121450129",
                "umur": "21",
                "asal": "Bandar Lampung",
                "alamat": "Kedaton",
                "hobbi": "Tidur",
                "sosmed": "@nabilaafrn",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Alvia Asrinda Br.Ginting",
                "nim": "122450077",
                "umur": "20",
                "asal": "Binjai",
                "alamat": "Korpri",
                "hobbi": "Nonton Windah",
                "sosmed": "@alviaginting",
                "kesan": "-",
                "pesan": "-",
            },
            {
                "nama": "Dhafin Razaka Luthfia",
                "nim": "122450133",
                "umur": "20",
                "asal": "Bandar Lampung",
                "alamat": "Jalan nangka 1",
                "hobbi": "Olahraga",
                "sosmed": "@dhafinrzqri3",
                "kesan": "-",
                "pesan": "-",
            },
        ]
        display_images_with_data(gambar_urls, data_list)
    Ssd()

# Tambahkan menu lainnya sesuai kebutuhan